### ISSUE TITLE
Look for uses of personal information in showduggaServices.php

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10137]
We must find where/if showduggaServices uses personal information and how we can replace it.

**Comment by a19frebo** [comment]
Row 17-21 uses userid, loginname (username), lastname and firstname from $_SESSION. Is $_SESSION still going to be used?

Row 23 sets user ID to 1 if not logged in

Row 151 Here we select uid from the database, could just be removed?

Row 298 user ID is used for logging "makeLogEntry", this function only returns false, not really in use.

Row 300 user ID and username is used for logging "logUserEvent", This saves both user ID and username to the database. A solution to this could be to alter the database table for the log entries, alternatively could we skip logging for users since we should not be able to log in as a student anymore?`

Row 327 user ID is inserted in to the database table "userAnswer", this could be removed from the database table since we should not be able to log in as a student anymore so this information should be irrelevant.

Row 360 Here we select version of course from the database table user_course with the help of user ID. We should replace user ID in the database with the hash, this requires modification of the table user_course. By doing this we change the binding of the course version from the user ID to the assignment hash.

**Comment by a19kevkh** [comment]
Row 372 Same as row 360, change uid to hash instead when updating table.

Row 442 Same as row 360, should use hash instead of uid

Row 450 Should a groupdugga still exist? should be bound to one single hash?

Row 469 and 471 SELECTs uid FROM submission WHERE uid=:uid, looks like this for-loop is iterating through all participants in the dugga. Could be bound to only one hash instead of all user IDs? Might also need to alter the table submission to include hash. All the information from this query is later stored in $entry on row 531. Which is later stored in the $files array.

Row 525 SELECTs username FROM user WHERE uid=:uid. Saves the username in the array $files

Row 578 INSERTS username into userduggafeedback table, should be connected with hash instead? requires modification of the database table.

Row 616 user ID is used for logging "logServiceEvent". This inserts user ID in to the database serviceLogEntries, could be connected with the hash instead of the uid. Requires modification of the database table.
