### ISSUE TITLE
Remove login-lock and examine score variable in group-assignment.js

### ISSUE THREAD

**Issue by a19rebsa** [HGustavs/LenaSYS#10145]
In the template file group-assignment.js there is code for showing the login-lock when not logged in. This should be removed. Also the variable "score" in the saveClick() function should be examined to see if it is needed for saving the dugga, this could maybe otherwise be some type of personal information.

**Comment by HGustavs** [comment]
We need to do some proper thinking about how group hand-ins should work

**Comment by HGustavs** [comment]
Like for ER diagrams, I am thinking we should be able to share the hash and password between students, and that way more than one student can view the same assignment at the same time. But we need synchronization to support updates in the view of one student when another student changes something.

**Comment by a18osken** [comment]
Once the login functionality for individual hand-ins and the saving of file submissions are solved we will delve further into group assignments and see what we can do. Would the syncing between students be a function of the diagram core or the dugga page? We can most likely implement a group value for the hash and password so that several students can share it.
