### ISSUE TITLE
State machine only store NEW values

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10240]
~~We need to store the previous element name that the element had before the change.
An example solution is to pass the old name as a value via the changeList parameter when using the StateFactory.~~

See https://github.com/HGustavs/LenaSYS/issues/10240#issuecomment-823418912

**Comment by a19hammi** [comment]
We have two solutions actually.
Either, we move the creation of the example elements into our functions that create elements so that they are stored on load.
This way we can simply loop back through old changes and find the old name of elements.

The other way is to, as previously said, store old values next to the new values. This does mean we STORE DUBLICATE DATA which could stack up pretty bad if we're talking a theoretical hundreds of thousands diagrams stored.

**Comment by HGustavs** [comment]
Since we want to be able to scrub through the diagram history... I prefer that we only store changes compared to previous version and default elements.

And each time we draw the diagram we loop through the complete history to get the "current" diagram which is the diagram that we are drawing.

This way, scrubbing (or animating likea video) is "free" since we always go through the elements from the beginning each time we update the diagram data (not necessarily each screen redraw).

**Comment by HGustavs** [comment]
The use case that we are aiming for is viewing the complete drawing history of a student like a video to see in which step a mistake was made to judge the thinking of a student when modelling the diagram

**Comment by a19hammi** [comment]
@a19nikbo @a19karwa 
As @HGustavs mentioned we will treat the storage a little bit differently. Creating new issue out of it.
