### ISSUE TITLE
Explore setting up a local dev environment for canvas

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10289]
Probably the best way to set up a local development environment for canvas is through some kind of virtualisation. Oracle VM Virtualbox seems good. Maybe we could find a Ubuntu 20 image and set up canvas.

**Comment by a16erilj** [comment]
We have explored the possibility to have an local instance of canvas in VirtualBox by using the guide/wiki from #10054. As a result so did we find some lines in the WIKI that was faulty and needed to be rewritten. All changes that would need to be done have been committed to #10054 and a manual change of the WIKI would most likely be needed. 

Otherwise so are the exploration of setting up a local environment for canvas a success as we are able to export and import a working local version of canvas.
