### ISSUE TITLE
Create a functioning Group Assignment template

### ISSUE THREAD

**Issue by a19simma** [HGustavs/LenaSYS#10359]
Need some kind of submission in the assignment that is interactive so we can test implementations.
![image](https://user-images.githubusercontent.com/81557282/115855611-bdcfe700-a42b-11eb-80db-5cf8f86f3f43.png)

**Comment by a19simma** [comment]
Right now, elements of the dugga are not displayed even with a full copy of existing dugga.

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/116368036-39ed7480-a808-11eb-8073-4bd69d2b267a.png)
parseJSON error causing many duggor to not display correctly. @a18osken If you want to make an issue for it or keep this one open, since this is the same error affecting then "group-assignment" template.

**Comment by a18osken** [comment]
Good find, I will look for what causes the error and put up an issue for it in a few hours depending on the complexity of the error.

**Comment by a18osken** [comment]
This error is thrown because the template files try to parse an empty string and not finding anything before the JSON input ends. It stems from not having any variants of these quizzes/assignments in the database, and therefore not having a param value. The assignment literally does not exist in the database. If we knew the syntax for the different variant parameters regarding these templates we could insert them and it should, hypothetically, parse and show correctly.
