### ISSUE TITLE
Indication personal contribution in the git tree for the complete project in contribution viee

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#10383]
Once we have a git commit tree... I would like to be able to somehow indicate which commits in the commit tree that were authored by the currently selected user.

**Comment by HGustavs** [comment]
In issue #10382

We discuss showing the complete commit tree for the whole repository.

<img width="653" alt="Screenshot 2021-04-25 at 19 19 09" src="https://user-images.githubusercontent.com/6978801/116074886-9a5aa580-a692-11eb-8db2-502417fbdb0e.png">

I am thinking some kind of highlighting of the issues made by the currently selected user. 

The curernt user is the logged in user or the selected user name in a dropdown if you are a superuser

So... I am thinking we show the same display of the tree as in #10382 but with some kind of highlight of the commits made by the "current" user ... for example rectangles around those commits ... or ... distinct coloring or some other visualization.

I am not sure what it should look like so a mock-up would be a good idea.

**Comment by HGustavs** [comment]
another possible highlight could be another circle outline around the commits made by current user... so it would look like a bit like the target logotype. https://www.google.com/search?q=target

**Comment by a19danla** [comment]
Im not sure if it some problem on our end or if its intended but when we access duggaSYS/contribution.php or contributionservice.php they're just white pages. We changed the $log_db path on line 21 in contributionservice.php to point to the database you provided us. Are we overlooking something?

We would be thankful for some info to push us in the right direction.

**Comment by HGustavs** [comment]
Message me a link to the installation I can test on discord.

**Comment by a19danla** [comment]
We're running the duggaSYS locally on our computers so not sure how we can link it to you. Im currently testing on G2-2021-W17 branch as it is, except the change to line 21.

**Comment by b19wilfo** [comment]
@HGustavs Have you had any success in testing?

**Comment by a19danla** [comment]
Situation update: After removing the redirect in file contribution.php, line 9, and changing the database path in contributionserviced.php, line 21, the localhost/...../contribution.php site is just plain white. 

If I add a random combination of letters in the html-portion of the code those character will show up on the site, put no other code will (tried adding code to just show a circle). The same characters will not show up in the php-portion.

If I replace all the code with the code from access.php the "access" code will run fine.

After some conversation with Henrik we think it might be php related, since altering the code wrongly will result in error messages while inspecting the site but unsure why exactly that is.

After altering the dates and commenting out line 642 "logServiceEvent(...." I found out it after some point the contribution.php site works for @b19wilfo but not for me. After some digging around we found that hes running a earlier php version 7.2.34 (im using 7.3.27) so we tried changing the php-version on my computer to no success (tried 7.2.34 and 8.0.3).

Next in line for testing is to redownload the database file to see if that could be the problem and to write in a message on a line of code and lowering it one row for each test to see when/if it stops displaying to potentially see where the code breaks.

**Comment by a19danla** [comment]
Finally got it to work yesterday.

What needs to be done for it to work:
-Remove the re-direct in contribution.php (an if-statement at row 10)
-Change the pathway in contributionservice.php to your local database provided by Henrik
-Comment out the logServiceEvent
-Make sure your logged in as a teacher or admin (this is not a n requirement on the live version, hence why it take extra long to find the problem)

**Comment by b19wilfo** [comment]
You also need to add an "}" to line 671 to make it work.

**Comment by b19wilfo** [comment]
Was this what you were thinking @HGustavs ? As you can see its quite cluttered so we are wondering if it would be best to maybe change the shape of the commits made by the user? Maybe a square or something like that.

![CommitOutline](https://user-images.githubusercontent.com/62884368/118814434-731d7f80-b8b0-11eb-9fc6-135668dca744.png)

**Comment by b19wilfo** [comment]
Is this issue even needed since all the commits made by the user is already shown when we select a user from the dropdown? 


Co-author: @a19danla

**Comment by a20behta** [comment]
@HGustavs issue is not updated and no information about if this. 
seems like commit tree works as intended and no mock up is requested.
