### ISSUE TITLE
Diagram association end cardinality position adaptation

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#10388]
If the space is tight between association ends we want the cardinality symbol (1 or N) to move further out the line.

<img width="387" alt="Screenshot 2021-04-25 at 21 06 24" src="https://user-images.githubusercontent.com/6978801/116006345-16110f80-a60b-11eb-98aa-4cc161d4af4e.png">

**Comment by HGustavs** [comment]
So that the letter is not written on top of lines but rather moves further down the line if space is tight

**Comment by a19nikbo** [comment]
This is copied over from another issue:

"Firstly the angle is greater on the right side of the line in this case, so it should be placed to the right of the line.
If the entity symbol was placed further to the right the opposite would be true and the symbol should be on the other side.

Also we want the position to be dependent on that angle, if the angle to the next line is small we should push the symbol out further to account for this "pinching" effect.

Thirdly, as is shown in this case the cardinality symbol should be at leas the height of the letter from the connecting point.

Fortunately, Vector math is very helpful here. We can make a unit vector of the line from the connection point and multiply this unit vector with the text height and line angle."

**Comment by a19matma** [comment]
Would consider this low-prio for now. 
When two elements with a line between them gets very close to each other on the y-axis the line gets re-calculated and gets a new starting position on one of starting points on the x-axis, hence a big part of the current problem occurs on a specific axis.
This will most likely always cause one of the cardinalities to become partially obscured when two elements are extremely close in the y-axis. 
In order to accommodate for this there are in my opinion two solutions: 
The re-calculation of the line that occurs when two elements with a connected line sufficiently close to each other, will have to be refined or altered before any major changes to the cardinality.
OR:
The calculation for the cardinality position will have a lot of special cases depending on the vector angle from the lines starting position relative to vector between the line starting position and the element center on that specific element.

**Comment by a19matma** [comment]
![image](https://user-images.githubusercontent.com/81557380/117296931-e9b08b00-ae75-11eb-8d2a-c388bd8c4698.png)

**Comment by a19matma** [comment]
![image](https://user-images.githubusercontent.com/81557380/117297455-8a06af80-ae76-11eb-8438-a5cfdc657b4b.png)

This is the angle I mentioned previously. 
Depending on this angle (given that the cardinality is always located at point "p"), we could reposition the cardinality position accordingly, making sure that it's never position "inside" the element.

**Comment by a19hammi** [comment]
fixed in #10622
