### ISSUE TITLE
Dublicate line-deletions stored in state machine

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10433]
Pressing DELETE when both a line and the connected element is selected will store the change of the line being deleted TWICE making weird behavior in the state machine.

**Comment by a19aleda** [comment]
Actually it seems like the element that is being deleted is logged twice, and not the line connected to it.

**Comment by HGustavs** [comment]
This is something that we should test for.

Not the situation but the error.

The state machine should not crash if an unknown delete id or the same item is delete twice.

The easiest way is to check if the item exists and only perform the array splice in that case.  This way any unknown ids regarldess of the reason will just be skipped over.

**Comment by HGustavs** [comment]
I updated pseudocode in the documentation in issue #10304 to reflect that we must check for existence of ID before deleting... in order to keep the documentation in line with the code.

I also think we should add some example of what the data looks like when this happens in issue #10304 so we document this test case for the future.

**Comment by a19nikbo** [comment]
Fixed
