### ISSUE TITLE
Can't login to LenaSYS from canvas when in chromium browser

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#10471]
For some reason, you can't login to lenasys from canvas.webug.his.se when in a chromium based browser. You can login with firefox. This needs to be investigated.

**Comment by a19klafr** [comment]
Unsure if this is the actual problem this issue is reffering to, but this is what i can find.. errors appear when leaving the duggas view to the course view in the embedded lenaSYS on canvas. Seems to be a problem with the "uid" attribute in the databases that are being used in ths part? 
![problem1](https://user-images.githubusercontent.com/62889184/116880001-ba094500-ac21-11eb-9bcd-07a028725843.PNG)
![problem2](https://user-images.githubusercontent.com/62889184/116880006-bb3a7200-ac21-11eb-9ff3-8bf13e80f735.png)

**Comment by a19anjst** [comment]
Log in in another tab, alternatively link to another page to log in. Check so chrome doesn't autofill the entered text to something else.

**Comment by a19kimgr** [comment]
> "Log in in another tab, alternatively link to another page to log in. Check so chrome doesn't autofill the entered text to something else".

We tested without any cached login information so chrome cant autofill logins, and it made no difference.
After doing some digging we suspect it could be either a security setting in chrome or that the cookies doesnt get saved  when the page refreshes.

**Comment by a20chrjo** [comment]
@b18phika That sound good

**Comment by a19anjst** [comment]
Start with trying the webbserver, it can be localhost that is causing problems. Alternatively make it possible to log in in iframe. Suggested a little icon that opens the login window (from Henrik during customer meeting)

**Comment by a20chrjo** [comment]
@a19anjst I have now also tested with group 2 web server and like with group 1's server it works.
So I would consider this issue fixed.

So the thing to remember from here on out is that testing should be done after the web server has been updated and this should be more frequent than after the weekly merge (as needed).

**Comment by a19anjst** [comment]
I looked at it too and it seems to work. I hereby close this issue
