### ISSUE TITLE
Does the PDUGGA ajax call need an ajax call in its success function

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10504]
![image](https://user-images.githubusercontent.com/62884391/116407826-746c0700-a832-11eb-941e-72eaf1392a62.png)
Currently we have an ajax call that fetches the variant value and then in its success function sends it in the data.

Could we check if its possible to condense this into one call and solve this variant buisness serverside?

**Comment by a19arvka** [comment]
Yes, this doesn't seem to just be a lazy solution. It is necessary for the variant to be calculated first, to then be used in the next query. 
However, I have an idea to segment the functionality of the methods _getVariantValue()_ and _handleLocalStorage()_ so that "pdugga" only uses one ajax success.
