### ISSUE TITLE
Answer/Parameter not working for duggor

### ISSUE THREAD

**Issue by b12erijo** [HGustavs/LenaSYS#1051]
The format used for the parameter and answer when you create a dugga is no longer legal, e.g "danswer":"00000010 0 2". Quotation marks are no longer usable due to safety reasons so a workaround for this has to be created.

**Comment by c13andka** [comment]
This is fixed, but you know will have to save question and answear without " and :

New format will look like this 

inputbox1 = 2
Inputbox2 = 00000010 0 2

Instead of "danswer":"00000010 0 2".

**Comment by c13andka** [comment]
Syntax for dugga 2 will look like
Param: {red, röd} represent in the same order -> color, colorname
Answer: Variant

instead of 

Param: {red","colorname":"R&ouml;d"}
 Answer: Variant

**Comment by c13andka** [comment]
Syntaxs för dugga 3 kommer att se ut 

Param: {10,30,19 20 40 20 50 30 50,81 65 50}

inputbox1 = 10,30,19 20 40 20 50 30 50,81 65 50

istället för

Param: {"linje":"10,30,19 20 40 20 50 30 50,81 65 50"}

inputbox1 = "linje":"10,30,19 20 40 20 50 30 50,81 65 50"

**Comment by HGustavs** [comment]
I do not like this. 
It is pretty much a requirement that the dugga information is saved in json for the dugga to work properly.

If not, the javascript in the dugga will not work when instancing the parameters.

If we test this with a real dugga, what will happen?

I suggest an approach that replaces the quotes with something else for the json service which then restores it so that the dugga-code still works.

**Comment by HGustavs** [comment]
Have we tested this with a "real" dugga, such as the bit-räkning from the computer graphics course?

**Comment by c13andka** [comment]
That we can do, with out the " and some changes in the code, it works perfect :).  But changing " to something else might be even easier then our approach on the problem.

**Comment by c13andka** [comment]
Change " = *, will this be okay?

**Comment by a13denli** [comment]
I will just close this issue
