### ISSUE TITLE
Allow signed in teachers to access the submisions without password

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10656]
Currently so does teachers need to enter a password when accessing a submission through hash. 

Make it so a teacher does not need to enter a password.
![bild](https://user-images.githubusercontent.com/81558891/117019811-1178e500-acf6-11eb-9e1a-839502d450e5.png)

**Comment by a19gusba** [comment]
we probably found unnecessary query for reading dugga visibility in showduggaservice.php row 127. Isnt every dugga supposed to have visibility now since they are not linked to accounts anymore. This is also being used in an if statement that causes  unnecessary alert-popup for teachers when trying to visit student submission.

**Comment by a19gusba** [comment]
![image](https://user-images.githubusercontent.com/62884429/117149281-60d31a00-adb7-11eb-824d-bf9fcb0e645a.png)

**Comment by a19gusba** [comment]
![image](https://user-images.githubusercontent.com/62884429/117149315-6892be80-adb7-11eb-88c1-1bd2b535403d.png)
