### ISSUE TITLE
The text on attributes have an offset when zoomed out

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10741]
A bit difficult to see, but the text on the attributes have too much spacing to the left.
![image](https://user-images.githubusercontent.com/81541557/117301825-4febdc80-ae7b-11eb-8a87-9bae59ff2461.png)

**Comment by a19aleda** [comment]
Question is if this should even be touched? For me I can see the offset when I zoom out, but its not possible to even read the text. Seems like a none issue to me :) 

What do you other guys think?

**Comment by a19hammi** [comment]
> 
> 
> Question is if this should even be touched? For me I can see the offset when I zoom out, but its not possible to even read the text. Seems like a none issue to me :)
> 
> What do you other guys think?

Yes and no. While at an extreme zoom out it wouldn't matter but if it messes up already at a slight zoom out then it should be fixed at least on those zoom levels.

**Comment by a19steis** [comment]
We should put a cap on how far you can zoom out of the diagram. In my opinion we should cap zoom out at 0.5x , anything "higher" than that probably wont be needed since we have the panning functionality incase there is a really, really big diagram.

This would also negate the problem of the text moving to the right at 0.25x zoom out.

**Comment by a19hammi** [comment]
Discussion continued in #10876

**Comment by a19hammi** [comment]
fixed in #10966
