### ISSUE TITLE
Element overlap shouldn't be possible

### ISSUE THREAD

**Issue by a19matma** [HGustavs/LenaSYS#10747]
By using the bounding-box of each element, we could ensure that no two bounding-boxes overlap.
By also making each bounding-box slightly bigger, this could also ensure that the problem with line-recalc -> reposition gets solved somewhat. Since if the elements can't get close enough for the lines to reposition, the position of the cardinality will likely not get messed up.

**Comment by a19aleda** [comment]
Depends on how this is implemented? If the bounding box check is on while you're moving a element around this could lead to some unwanted user functionality where you have to move the element around other elements in circles to get it to the right place.

Instead if the bounding box check is done when you realse the element and it's position should be set, this would maybe be a better approach since you could then drag elements over eachother until you realse them.

Don't know if my thoughts make sense here :)

**Comment by a19matma** [comment]
I agree, I think maybe if the check is done when the element is released after having been moved would be the most optional way.
Depending on the position of the element after released, the element could be slightly pushed if it's overlapping another element.

**Comment by a19hammi** [comment]
fixed in #11016
