### ISSUE TITLE
State machine should only store absolute values.

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10755]
Right now there's both absolute and relative values stored in the machine, for example position changes are stored as a delta instead of the new position. We should move all changes into being stored as absolute changes instead.

**Comment by a19chrel** [comment]
This can make the data size will be significantly larger, if you move we say 10 elements, then the history of this movement will be something like this.

If we got the exampel data:
`{id "AAAAAA", x: 100, y: 100, kind:  "EREntity"},
{id "BBBBBB", x: 200, y: 100, kind:  "EREntity"},
{id "CCCCCC", x: 300, y: 100, kind:  "EREntity"},
{id "DDDDDD", x: 400, y: 100, kind:  "EREntity"},
{id "EEEEEE", x: 500, y: 100, kind:  "EREntity"},
{id "FFFFFF", x: 600, y: 100, kind:  "EREntity"},
{id "DDDDDD", x: 700, y: 100, kind:  "EREntity"},
{id "GGGGGG", x: 800, y: 100, kind:  "EREntity"},
{id "111111", x: 900, y: 100, kind:  "EREntity"},
{id "222222", x: 1000, y: 100, kind:  "EREntity"},`

And move the elements 10 coordinates down. The state will look something like the following.
`{
{id "AAAAAA", x: 100, y 110},
{id "BBBBBB", x: 200, y 110},
{id "CCCCCC", x: 300, y 110},
{id "DDDDDD", x: 400, y 110},
{id "EEEEEE", x: 500, y 110},
{id "FFFFFF", x: 600, y 110},
{id "DDDDDD", x: 700, y 110},
{id "GGGGGG", x: 800, y 110},
{id "111111", x: 900, y 110},
{id "222222", x: 1000, y 110},
}`

Instead of:
`{id: ["AAAAAA", "BBBBBB", "CCCCCC, "EEEEEE", "DDDDDD", "EEEEEE", "FFFFFF", "DDDDDD", "111111", "222222"]
y: 10 }`

**Comment by a19hammi** [comment]
> This can make the data size will be significantly larger, if you move we say 10 elements, then the history of this movement will be something like this.
> 
> If we got the exampel data:
> `{id "AAAAAA", x: 100, y: 100, kind: "EREntity"}, {id "BBBBBB", x: 200, y: 100, kind: "EREntity"}, {id "CCCCCC", x: 300, y: 100, kind: "EREntity"}, {id "DDDDDD", x: 400, y: 100, kind: "EREntity"}, {id "EEEEEE", x: 500, y: 100, kind: "EREntity"}, {id "FFFFFF", x: 600, y: 100, kind: "EREntity"}, {id "DDDDDD", x: 700, y: 100, kind: "EREntity"}, {id "GGGGGG", x: 800, y: 100, kind: "EREntity"}, {id "111111", x: 900, y: 100, kind: "EREntity"}, {id "222222", x: 1000, y: 100, kind: "EREntity"},`
> 
> And move the elements 10 coordinates down and 10 to right. The state will look something like the following.
> `{ {id "AAAAAA", x: 110, y: 110}, {id "BBBBBB", x: 210, y: 110}, {id "CCCCCC", y: 310}, {id "DDDDDD", x: 410, y: 110}, {id "EEEEEE", x: 510, y: 110}, {id "FFFFFF", x: 610, y: 110}, {id "DDDDDD",x 710, y: 10}, {id "GGGGGG", x: 810, y: 110}, {id "111111",x: 910, y: 110}, {id "222222",x: 1010, y: 110}, }`
> 
> Instead of:
> `{id: ["AAAAAA", "BBBBBB", "CCCCCC, "EEEEEE", "DDDDDD", "EEEEEE", "FFFFFF", "DDDDDD", "111111", "222222"], x: 10, y: 10 }`

Hmm, could @HGustavs make a decision on this one? I kind of agree with this. If we have too small of a time limit before making it a new store we would introduce a whole lot of data.

I'm kind of balling with the possibility of using the top-left value of all elements moved to get a position for all of them or use relative values on multi-element changes... of course this would defeat the purpose of _**only using absolute values**_ altogether.

**Comment by HGustavs** [comment]
I prefer per object per item so that the history is more easy to follow, and that the code is simplified significantly.

**Comment by HGustavs** [comment]
The question is how to handle all other changes e.g. handling of colors and deltas of color values

**Comment by HGustavs** [comment]
furthermore as discussed in issue #10960 storing absolutes will most likely allow simpler import/export handling since we do not need to expand delta-values when scrubbing the history for export.

**Comment by HGustavs** [comment]
The disadvantage would be the larger document size when moving multiple selected objects as stated above.

Do we have any real cases of modeling a model from beginning to end to see how much this growth would be in real terms?

**Comment by a19hammi** [comment]
fixed in #11111
