### ISSUE TITLE
Deleting items then using replay mode will "respawn" the deleted items after exiting replay mode

### ISSUE THREAD

**Issue by a19karal** [HGustavs/LenaSYS#10945]
Deleting items should stay deleted after exiting replay mode. no resurrections this time >:(
![33b7e0cf169b1bdf5d047fa9e56353ab](https://user-images.githubusercontent.com/62888356/117968261-486a7e80-b326-11eb-96e3-888b4c5e959c.gif)

**Comment by a19chrel** [comment]
This is because currently the delete state in the stateMachine seems not to work. One reason for this can be that the new `time` key has been added to keep track of time on all changes.

At the moment if only the state object contain an array of id, the `restoreState()` function will delete the array. Because this is not the case anymore it do not work.

I would suggest that we for the delete-state uses the key deleted instead of id.

**Comment by a19hammi** [comment]
fixed in #10979
