### ISSUE TITLE
Minor error is thrown, noticed when reviewed issue #10954

### ISSUE THREAD

**Issue by b19ponka** [HGustavs/LenaSYS#10986]
![Screenshot 2021-05-17 105343](https://user-images.githubusercontent.com/62886839/118461789-52152d00-b6fe-11eb-93e5-b1f48f9b9d60.png)

#10954

**Comment by HGustavs** [comment]
I can confirm that this is a bug and needs fixing, we want the running system with as few errors as possible.

Seems like an errror mesage that was channelled, do we know the origin of original error?

**Comment by a19arvka** [comment]
I found a solution, but i'm unsure why the error occured in the first place. 
Since the functionality of resulted.php have been changed recently there was an old if statement (that I created many weeks back) checking isSuperUser. This statement don't serve any purpose anymore, and i'm pretty sure we can't check _$_SESSION['uid']_ directly in _resulted.php_ because _resultedservice.php_ takes care of accessability right now. Checking accessability conditions in both _resulted.php_ and _resultedservice.php_ is likely the cause of the error.
