### ISSUE TITLE
Create a dropdown menu for pupils in mobile vers

### ISSUE THREAD

**Issue by a19anjst** [HGustavs/LenaSYS#10989]
Implement the icons that pupils use such as message of the day and feedback in the dropdown menu

**Comment by HGustavs** [comment]
Can we make a mock-up for this and some more information please?

Wich view are we talking about?

**Comment by a19samke** [comment]
@HGustavs  
I guess the issue managers aim for it to be the same design for everyone, ie regardless of whether you are logged in or not, for me it feels a bit irrelevant to see the hamburger menu when users are not logged in.

**Comment by b18phika** [comment]
@HGustavs 
About the icons in the top when viewing a course:

Students:
![image](https://user-images.githubusercontent.com/81557308/118484438-834e2700-b717-11eb-899c-68153e1623e6.png)

Teachers:
![image](https://user-images.githubusercontent.com/81557308/118484627-babcd380-b717-11eb-9944-77d1f192bf44.png)

The thought was that it might be a good idea to make it consistent, even though it might not be strictly necessary since students don't have nearly as many icons.

**Comment by a19samke** [comment]
@b18phika 
It`s maybe  better if the Icons are always visible when a student is logsin regardless of devices, instead building  hamburger menu, because there are only a few buttons there ?

Otherwise the whole nav heading is suddenly empty !

**Comment by a19anjst** [comment]
Going to ask on thursday what Henrik thinks. Either we have the message of the day button outside of the dropdown menu for teachers and equally for pupils or we have the message of the day inside the dropdown menu only for teachers and pupils has it outside (since they have no dropdown atm). Discussion about whether we shall have a dropdown menu or not for pupils will be discussed at the customer meeting
