### ISSUE TITLE
Zooming while holding an element causes problems

### ISSUE THREAD

**Issue by a19frelu** [HGustavs/LenaSYS#11058]
The element slides away from the mouse pointer when zooming.

https://user-images.githubusercontent.com/62895155/118795976-70fcf600-b89b-11eb-9c09-6dc3e127838a.mov

**Comment by a19chrel** [comment]
I guess this is because the deltaX and deltaY does not scale when the user is zooming.

**Comment by b20thelo** [comment]
Comment from pullrequest.

"Scroll will now zoom in and out and remain at the current mouse pointer coordinates. It still has some issues that occur if user moves the mouse in between zooms but it corrects itself after one zoom event. This is testable by opening any diagram and scrolling in and out, it should now remain at the same position.

What currently isn't working as intended as mentioned is alternating between move > zoom-in and move > zoom-out. However, the original issue is that when selecting a box and zooming in, the cursor moves away from the box that isn't updating it's position. Instead of updating the element position, the mouse should remain at the same place.

If any future developer solves the issue of alternating between zoom and move, it should solve the issue about the element moving away from the cursor completely. This commit should be considered a basis for a full solution."
