### ISSUE TITLE
Contribution tool commit lines of code - view of how the specific commit looks

### ISSUE THREAD

**Issue by a19anjst** [HGustavs/LenaSYS#11123]
A hover function or something similar to see what a certain commit looks like code wise. What has changed. Think like in the files changed function on github

**Comment by b20hanwa** [comment]
![MockupCommit](https://user-images.githubusercontent.com/81630271/162404951-5e8fbcea-5b33-4a3c-9466-45036516a641.png)

This is a mockup of what I think is requested. When hovering over a commit, a screen with the commits changes in code is shown. @c20adael @HGustavs

**Comment by HGustavs** [comment]
Not too nice. 

Readable list of lines owned by person. Not before / after like in the mock-up.

We are primarily inerested in the number of rows that have been updated, and what those updates are composed of.

**Comment by a20caros** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/81676918/163182312-09e761fc-932b-4880-b986-197bda92b869.png">
The solution to using an iframe is not a workable solution. The reason for this is that github does not allow you to display the web page on another page. The solution for the issue is clear if this error had not occurred.

Trying to come up with a new solution

**Comment by a20behta** [comment]
hover over implemented. mockup issue closed
