### ISSUE TITLE
Investigate what makes the contribution part load so slowly

### ISSUE THREAD

**Issue by a19anjst** [HGustavs/LenaSYS#11124]
For example if issues are shown to be the slow part, you can try to comment out certain code rows to see where it is slow and see what you can achieve. Don't commit any code to the project where you have commented out code that is being used.

**Comment by a19samke** [comment]
![Contribution_Network](https://user-images.githubusercontent.com/62887067/119468117-739d9680-bd46-11eb-85a1-119fb0e5cbfa.jpg)





Why contribution is slow to load, I can imagine because there is too much data to be loaded

**Comment by a18danli** [comment]
Shouldn't be because of the commit-tree, the contrubution was already slow before this was added. So should be because of the amount of data or how the contribution is constructed.

**Comment by a20behta** [comment]
Placed on Hold untill test data for database is avaliable. 
Waiting for Group webserver is avaliable for testing
Current information in pdf

[contributionservice issue.pdf](https://github.com/HGustavs/LenaSYS/files/8409169/contributionservice.issue.pdf)

**Comment by b20jonlu** [comment]
Update report. 
2022-04-06 i managed to get contribution.php to load by replacing the /htdocs/BGHdata_2021_05.db file and managed to test the issue and confirm it still existed. This also allowed me to confirm my suspicion of the root cause of the issue. The performance issues are caused by a high amount of database requests. contributionservice.php has about 340+ sql querries and 280 of them are caused by the for($i = 0; $i < 70; $i++) loop, and 50 by the do while($weekno < 11) loop. 
2022-04-07 i have started changing the requests to be less wasteful to try to improve the performance of contributionservice.php

**Comment by b20jonlu** [comment]
The performance issue is mainly caused by the code execution for the $count variable. Around 3/4 of the time it takes to load contributionservice.php is taken up by $count. My attempts to improve the code have lead me to confirm that the queries are responsible but i haven't found a solution that keeps the json format the same as the original which means the code didn't work with the related modules.
@a20behta 
@c20adael 
[Report contributionservice issue.pdf](https://github.com/HGustavs/LenaSYS/files/8451658/Report.contributionservice.issue.pdf)

**Comment by b20jonlu** [comment]
i just retested this with the database obtained from the usb drive and this is not a problem with that database. This means the problem was caused due to the size of the database. The code may be inefficient but still acceptable as long as the database size is resonable. To compare them the event table on the database from the usb has 3000 entries, the database i tested on had 115,000 which would explain why it was so noticable that the code was inefficient since the dataset was completley different.

**Comment by a20behta** [comment]
Not closing this issue as speed is still a issue

**Comment by a19simru** [comment]
@c20adael I would like this issue. I have some experience with the contribution files. I also believe I could make the search algorithms more efficient.

**Comment by a19simru** [comment]
Spent the last two days researching sql, php, pdo and their implementation in the code. As well as testing some code edits to improve the code. I have begun writing changes that will speed up load time on larger files dramatically. Will finish writing changes Saturday.

**Comment by a19simru** [comment]
@c20adael @a20hedta Summary of findings. 

The code uses php's PDO() function to access's the data base file BGHdata_2021_05. A well known problem with PDO is that it can't count rows in a database efficiently at all. As of the time of writing the for($i = 0; $i < 70; $i++) loop contains 4 row counting queries. Each one of these queries actually comprises 2 queries. One that is responsible for 90% of file load time and a second less noticeable one in the form of the syntax called fetchAll(). fetchAll() drains a fair bit of load time but its not the big problem. A pull request has been made to get rid of fetch all completely. However that won't solve most of the load time problem.    

Two possible solutions come to mind from here.

Maybe it could be possible to not load every users contribution at the start of program execution. But instead load only those contributions of the user who you are currently viewing. This is however a very speculative option. As I don't know if this is even possible.

A second option could be to switch from PDO() to mysqli(). This is because mysqli() is supposedly better at row counting. I don't know how much better though so it might not be worth the trouble. Additionally it would depend on what version of php the server is using. Since mysqli() has apparently been decapitated in newer versions of php.
