### ISSUE TITLE
Clicking elements in line creation mode sometimes selects connected lines instead

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#11183]
The lines should not be clickable through an element, just like in the other cursor modes

![2](https://user-images.githubusercontent.com/81541557/119516172-ce4ee680-bd76-11eb-8d07-cf74f6dabb89.gif)

**Comment by b20thelo** [comment]
![image](https://user-images.githubusercontent.com/81772705/163133513-f5202040-0882-453f-9b4a-f51da8c666ba.png)
Found possible cause of the issue. Line offset does not scale with the zoom factor. When zoomed out the lines goes into the element.

**Comment by a20jacmi** [comment]
What you say is true @b20thelo, and this makes it more likely that you will hit a line when you're suppose to click on an element. However, we've found the root cause of this issue, and then the zoom factor is irrelevant, but we're waiting with the implementation until the next merge.

**Comment by a20jacmi** [comment]
Solution to the problem is found in: "diagram.js" -> "function ddown(event)" -> "case mousemodes.EDGE_CREATION".

Earlier, if an element (that was not a line) was clicked it was selected on "mouse down". However, on "mouse up" a line could accidentally be selected instead which was not ideal. The "mouse up" behaviour in this particular situation is now disabled.
