### ISSUE TITLE
Coursesyspw.php uses plain text for passwords

### ISSUE THREAD

**Issue by a20behta** [HGustavs/LenaSYS#11239]
based on comment in issue #11218 it seems that coursesyspw.php uses plain text passwords. 

This is a security risk and should be investigated, 

How are they saved?
What is required to change it?
What is affected?

**Comment by HGustavs** [comment]
is it for database passwords? that file is not located within lenasys but one level down from the installed version of lenasys so it should not cause any problems since apache cannot read that file.

This is just a file that shows what that file should look like, not the actual passwords?

**Comment by a20novra** [comment]
jag jobbar på det här @a20behta  @c20adael

**Comment by a20behta** [comment]
@a20novra Check if this file is active, what it uses and how it affects different input/output.

**Comment by a20novra** [comment]
I checked Coursesyspw.php file and saw that password is in plaintext, but as you said this password is not connect to lenasys database. It means that no body can reach lenasys database with this password. It was better if it was saved as hashCod, but because it just on installation i don't know if it is sth. that we should focus on? 
@HGustavs @a20behta

**Comment by a20behta** [comment]
Pefect everything is checked and closing the issue
