### ISSUE TITLE
Research the use of css grid in codeviewer

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11256]
Reference to #11246. Look into this and report if the the implementation might be viable.

**Comment by a20linth** [comment]
Switching to CSS grid for the codeviewer is certainly possible considering that the codeviewer is contained in a div-box, which is necessary for implementing CSS grid. But depending on what the customer wants, there could be a need for extensive rework of both the codeviewer JavaScript and CSS files.
The resizing functionality of the codeviewer window would be one of the features that most likely needs to be reworked to work with CSS grid. The window resizing functionality modifies css dynamically, therefore if the dynamically modified css gets a rework, then presumably also will the resizing functionality need a rework. 
The methods associated with the codeviewer resizing functionality cover approximately 2500 lines of code in codeviewer.js, and there could be other functionalities that also break with CSS grid implemented.

**Comment by a20linth** [comment]
Another aspect to consider is whether the customer only wants to implement CSS grid on the codeviewer, or if they plan on making the switch to CSS grid in other parts of the system.
Because if implementation of CSS grid is only made on the codeviewer, many responsiveness issues concerning the navigation bar and its elements do not get fixed, due to the navigation bar currently being separate from the codeviewer.
