### ISSUE TITLE
Diagram module - mockup to interface with UML included

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#11286]
Create a mockup/draft that better represent existing tools and also includes UML symbols (related to issue #11248).

**Comment by a20gabpa** [comment]
Pdf-file with concept for the toolbar with some included UML symbols. 

[Issue11286-Draft.pdf](https://github.com/HGustavs/LenaSYS/files/8417265/Issue11286-Draft.pdf)

**Comment by HGustavs** [comment]
<img width="158" alt="Screenshot 2022-04-05 at 13 30 31" src="https://user-images.githubusercontent.com/6978801/161744730-76dabdc7-399b-42b2-a27c-4d895f083055.png">

Something akin to this variant.

When long-pressing the entity symbol we an uml or eer symbol and according to which is active the other symbols act accordingly.

This way we do not intoduce any new buttons, except for three icons in the "dropdown" ER/EER/UML

**Comment by HGustavs** [comment]
Liked the settings dialog for changing entity types. Lines should be able to know imho no settings for diagram types needed. Cardinalities should also "know" which symbol to draw.

<img width="473" alt="Screenshot 2022-04-05 at 13 36 44" src="https://user-images.githubusercontent.com/6978801/161745525-60e635d2-b5f4-4af9-8c6f-25b57b38c41b.png">

**Comment by a20gabpa** [comment]
Based on the given feedback, I have attempted to divide the issue into smaller steps as followed:

1:  Create an UML entity
2: Update the toolbar to include the UML entity
3: Move the entities to a togglable "dropdown" menu
4: Modify and update the options panel to support UML and diagram type for entities
5:  Update lines so that lines between UML entities use the correct UML lines.
