### ISSUE TITLE
Research why 3d dugga is not working correctly.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11345]
demo-course/ 3Ddugga
![image](https://user-images.githubusercontent.com/80856978/161719617-cc9606f9-fcb5-4eb0-8440-f2093b04ab75.png)

**Comment by a20caros** [comment]
The issue has the problem that it has a canvas designed by script. A library is used to print in the canvas. One guess is that localhost can not reach this library because it is local which the live version can do. There is no code difference between local and the live version for that reason this is considered to be the problem.

**Comment by HGustavs** [comment]
This code uses the webgl from three.js ... I would assume we need to add three.js in some folder. I do not want three.js to be included with lenasys, so that is probably the reason.

**Comment by a20behta** [comment]
@HGustavs @a20caros 
As files will not be added from production to lenasys, can this issue be closed?
