### ISSUE TITLE
Diagram: Student should be able to make changes in the received dugga and submit it to the teacher.

### ISSUE THREAD

**Issue by b19karhj** [HGustavs/LenaSYS#11365]
The student should be able to make changes to the diagram in the given dugga from the teacher.  And be able to submit it to the teacher. After submitting the student should get a receipt with the following information (see below) The layout should be the same as the last picture.

After submiting a hash code and hash password should be created. "example is shown below"

![bild](https://user-images.githubusercontent.com/81624541/162017292-e41a1e53-d0e5-420d-ac02-25fc223ccc66.png)

The student should then be able to use the link and be greeted by a popup where he/she can enter the hash password and be redirected to a page where the student can see that his/her assignment have been submited.

![bild](https://user-images.githubusercontent.com/81624541/162017653-64f6936a-0eae-4cd3-be51-ac23c6040b6b.png)

**Comment by a17nikjo** [comment]
in showDuggaservice.php  hash is aquired with $_SESSION therefor the hash is different for different user.
Seems like the hash is attempted to be used to load in duggas at some places while the hash is not a unique identifier.

For super user stei:
hash: "3ffb72e9"
hashpwd: "23512d2e"

For guest:
hash: "04174821"
hashpwd: "5d327173"

Documentation needs to be created how we can access duggas through sql querys in php.
Since currently there is no documentation of what is what and how it's done.
validateHash.php seems to attemt something similar too showDuggaservice.php.

**Comment by a17nikjo** [comment]
More information needed about how hash, hashpwd and duggas are stored in the database needs to be researched / docummented. 

Maybe a seperate issue for this?

**Comment by a16linas** [comment]
Managed to get diagram and bit dugga to display the hash and hash passwords, however only diagram dugga is able to actually store things in the database
![bild](https://user-images.githubusercontent.com/37794783/166217249-51d94b8b-eb9e-4ef7-8eb5-a3a22f244c92.png)
