### ISSUE TITLE
Implement collapsible html tags

### ISSUE THREAD

**Issue by a20linth** [HGustavs/LenaSYS#11369]
based on the research done in issue #11318.

**Comment by HGustavs** [comment]
This was implemented a few years ago, but did not work well. 

...So here is a previous precedent for this.... however it was only partially working since it is quite complicated to do this without matching the tags incorrectly for example tags inside php echo statements.

The old code may perhaps serve as a guide for this issue. Unclear how far back this was implemented, but it had to be rolled back since it interfered with the handling of php and javascript code.

**Comment by a20linth** [comment]
The problems that can occur with collapsible html tags and using html tags in php and javascript strings can be solved by using token.kind to determine if a html tag is in a string or not.

While testing with html tags in string, I found a problem with multiline strings not working correctly #11399. This issue messes with other brackets and html tags collapsibility if other brackets and html tags are inside multiline strings.

**Comment by a20linth** [comment]
Testing:
1) Go to course ”Webbprogrammering”
2) Go to example ”HTML5 Example 8”
3) It should look something like this:
![image](https://user-images.githubusercontent.com/102609651/162156936-bb516a14-168f-4fa0-be1c-becf5a468f09.png)
4) Test that both the collapsible squirrely brackets and html tags work.
