### ISSUE TITLE
Add functionality to the copy link button.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11377]
When clicking the button that give you the link for canvas iframe, it should be copied directly to your clipbard.

Todo: get the link to to the dugga into function showCanvasLinkBox in sectioned.js

**Comment by HGustavs** [comment]
Is there a mock-up of this interface?

**Comment by a17nikjo** [comment]
Starting researching how to aquire the correct link to the canvas dugga.

**Comment by HGustavs** [comment]
This is not trivial, since we are generating search terms... perhaps a warning of some kind e.g. color the icon if not possible.

If we have two assignments with the same name for example:

Section 1
Makeup Assignment

Section 2
Makeup Assignment

Then there would be no way to generate a copy paste icon since both those assignments have the same name....

if one assignment is called

Database Implementation

and another one

Database Design

Then one link would link to implementation and the other to design

or 

"Database Design" and "Database Implementation"

The Database part would in that case be superfluous.

**Comment by a20behta** [comment]
Placing issue on hold untill @HGustavs answers questions related to link generation.

**Comment by a17nikjo** [comment]
Creating a branch for this issue from branch for issue #11323 since this requires the code in that issue.

**Comment by HGustavs** [comment]
It should generate an SH linl. 

```
<p><iframe src="https://dugga.iit.his.se/sh?c=forskning&amp;a=avhandling" width="800" height="1200"></iframe></p>
```

**Comment by a17nikjo** [comment]
Link does currently not work since we need are waiting for issue #11512.

Current functionality can be merged while waiting for the correct link to be added.
