### ISSUE TITLE
Add file icon

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#11384]
Previously in older versions of file module, pressing the FAB button would directly allow us to upload a course local file, and a long press would give us the dropdown menu for example uploading url links.

<img width="279" alt="Screenshot 2022-04-06 at 14 17 47" src="https://user-images.githubusercontent.com/6978801/161972832-57ef3eaf-d721-4a04-983e-0c988ed89daa.png">

So, long press gives us the dropdown of the menu and short press (click) gives us the same as the upload course local file icon. Since we most of the time upload course local file this workflow is much faster.

Unclear when this functionality was removed.

**Comment by a20caros** [comment]
A solution to the issue has been created with some exceptions to the problem description. Instead of the user holding down the button to bring up the menu, it is enough to hover over the fab button. To upload a local file, click once on the fab button. Getting a local file and menu is still separate even though long press is not implemented. 
<img width="363" alt="image" src="https://user-images.githubusercontent.com/81676918/162902454-29f55dd6-7ed0-4c72-96d7-b84a2e372cb1.png">
The content menu is placed around the button, which is incorrect. A new issue has been created for this issue # 11529.
<img width="405" alt="image" src="https://user-images.githubusercontent.com/81676918/162902508-300c1b65-8ca6-4f31-b571-37819649448d.png">


However, a problem that remains is the link between the duggaed.php file and the fileed.js file. The connection between the files wants to be made for the buttons in the implemented menu to work. The fileed file contains a number of error messages that affect the duggaed file. The result of the error messages is that everything on the page except the fab button and lenasys menu disappears. Implementing the lines of code that belong to the menu's functionality is long and complicated, which made the connection feel like a better solution.
<img width="957" alt="image" src="https://user-images.githubusercontent.com/81676918/162905231-6857557d-702b-4121-9567-caeb17ff130b.png">
If the archived file and the duggaed file are linked, error messages follow from the fileed file and have consequences on the duggaed page
<img width="956" alt="image" src="https://user-images.githubusercontent.com/81676918/162905720-9bd36583-e7e1-484e-81eb-c9a7a85fc8f3.png">
If the connection between the files is removed, the error messages from the fileed file are not in the duggaed file, but the menu's functionality does not work because the functionality is in the fileed file.

**Comment by a20caros** [comment]
Questions to customer 
Are the menu options correct? Has implemented those who were in the picture for the issue.
When you select a menu option such as adding a link and sending it, you come to the Edit file page (fileed), is this correct or should you stay on the show test page (duggaed)? 
<img width="426" alt="image" src="https://user-images.githubusercontent.com/81676918/162908604-97de51a4-6c7b-4dc7-b677-cc10e3472bc6.png">
<img width="510" alt="image" src="https://user-images.githubusercontent.com/81676918/162908687-2fcdedd8-0890-49d5-abf4-c06e2c9573cc.png">
@c20adael @HGustavs

**Comment by a20caros** [comment]
Because the instruction in the issue was unclear, the wrong side has been working on. Starting to work on the right side

**Comment by a20behta** [comment]
merged into master
