### ISSUE TITLE
Functionality needs to be added so that the graphical column filtering can be used in resulted.php.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11381]
referring to the issue #11107

**Comment by a20kimar** [comment]
Make sure to branch this issue from #11379 when working with the functionality.

**Comment by HGustavs** [comment]
If I understand this issue right.

Resulted is hardly used any more since we do not which student submitted which assignment this view is only used if some student has lost their hash/password.

If that is what is referred to we can downprioritize issues that have to do with resulted.

**Comment by a20johba** [comment]
Added a toggle function to hide and reveal columns that are checked/unchecked in the column filter. This could possibly be done better by adding functionality directly to sortableTable.js in order to allow the same functionality for other tables. That would probably be better off as a separate issue, however.

**Comment by a20johba** [comment]
Did a quick rewrite of the filter functionality according to feedback to make it more intuitive. Rewrote the functions related to the "Select All" button to make it more flexible and understandable. Some of these changes also affect the dugga filter.

**Comment by a20behta** [comment]
functionality added in master, error exitst unreleated to issue and needs to be searched after
