### ISSUE TITLE
Diagram:  Colour issue when marking entity.

### ISSUE THREAD

**Issue by b19karhj** [HGustavs/LenaSYS#11396]
When you mark an entity that has colour in it, the colour get darker, this should not happen.
Replace the red colour with purple in both BG and Stroke
![bild](https://user-images.githubusercontent.com/81624541/161992612-67f027f3-0944-4c24-85cd-bbf3c583894f.png)

**Comment by b20matad** [comment]
Upon testing, objects need to be highlighted in more than just one way (The dashed selection box), in case muliple objects are selected. We will test making a dashed border for all objects when they are selected.

**Comment by b20matad** [comment]
On further evaluation, a dashed-stroke is not a good way to highlight selected entities, since some entities have the option to already have a dashed border. 

We decided to change the opacity of the selcted elements instead, since it doesn¨t get mixed up with different colors or borders.

**Comment by a20jacmi** [comment]
Also, me and Therese had a discussion when we tried purple as background in the elements. This made it hard to see the text inside because of such a dark color, thus the choice to go with a light blue.

**Comment by b20thelo** [comment]
Removed waiting for testing as testing of pull request has been completed and the submitted solution was merged.

**Comment by b20matad** [comment]
Since opacity isn't approved we have made some different suggestions for possible solutions. See the following pictures.

Brightness changed on each selected element.
<img width="347" alt="brightness" src="https://user-images.githubusercontent.com/102598238/163942519-67b78850-9015-405c-b75f-b6af22db61e9.png">

Dashed frame around each selected element.
<img width="387" alt="Rutor" src="https://user-images.githubusercontent.com/102598238/163942675-f427448e-733a-43b8-97e2-d60b239cbc3d.png">

Dashed frame with black dots around each selected element.
<img width="401" alt="RutorPlus" src="https://user-images.githubusercontent.com/102598238/163942898-1762811e-ddd7-490b-aad3-6befa5bf3f25.png">

All of the above on each selected element.
<img width="335" alt="Allt" src="https://user-images.githubusercontent.com/102598238/163943017-39d407bf-75ee-4836-91f7-12ba1d2dc7fb.png">

We have not made any changes on the marking of selected lines, since we don't consider it an issue at the moment but could be raised as a different one in the future.

**Comment by b20matad** [comment]
The solution we agreed upon.

<img width="324" alt="Förslag" src="https://user-images.githubusercontent.com/102598238/163954775-46f5e2fe-6877-4ff8-9f41-6ccc94ddb856.png">

**Comment by b20matad** [comment]
We have commited code for two different branches:
G1-2022-W4-#11396 - Selection box around each selected object.
G1-2022-W4-#11396b - Changing border color of selected objects. (Does not work for UML Box with the current solution. This would require a remake of the box)

**Comment by a20jacmi** [comment]
Henrik wanted a different solution so we made a third branch: G1-2022-W4-#11396c

This changes the color of the marked element and thus the same problems as the "b" branch remains, and has to be solved in a later issue.

**Comment by a20jacmi** [comment]
In our latest pull request the colors are fixed for UML entities and objects with double borders.

**Comment by b20thelo** [comment]
Closed as solution is almost fixed and a new issue were created for the feedback from the presentation.
