### ISSUE TITLE
Looking into grid layout files

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11403]
As we have made an report in #11256 (part of #11246) and also talked with the customer for further clarification regarding the css grid, we now belive we have enough information to consider it possible, and thus we continue.  

There is a possibility that simply changing the css files for a template may work, but taking the report into consideration, we do not know how this would effect the resizing. It might be worth checking it out in practice however.

The files goes by the convention of "template-x.css" where x is the file number. Try implementing css grid in at least one and see how things turn out.

**Comment by HGustavs** [comment]
We prefer simplified layout using grid over manual resizing of boxes.

Of paramount importance is that vertical and horizontal scrolling of the code boxes is not lost.

**Comment by b20sebka** [comment]
I don't know if I am just stupid but I have implemented CSS Grid and edited in template4.css to test it.
![bild](https://user-images.githubusercontent.com/102599780/162915497-fdd5bb44-b3f6-4ddd-a08a-6989527abf78.png)
No matter what I do there is always a giant white box in the middle which I suspect occurs when the boxes don't properly span the correct amount of columns. Will have to continue researching and testing around to fix this.

**Comment by a20patpe** [comment]
The main hurdle for implementing grid view is the resizeboxes function, the function stack spans from line 3811 to line 5111. Changing/removing all these functions will be extremely hard to do( since they depend on each other). 

The reason these functions do not work in a gridview is that: when you  place a box in a grid it's size being 100% means it covers the entire alotted grid.

Previously a boxs size being 100% meant that it covered the intire #div2 container. This difference means that most of the math and logic in the resize function(s) breaks when you add a gridview.

**Comment by b20sebka** [comment]
After successfully implementing resize again for the grid layout some errors occured.
The main one stopping us is a random "top" css style that is randomly added to boxes when trying to resize and it is near impossible to find where it is set.
example picture:
![bild](https://user-images.githubusercontent.com/102599780/165103117-93694051-a226-478d-9f44-78eb0c653576.png)
what happens with top:
![bild](https://user-images.githubusercontent.com/102599780/165103171-09bcf328-6953-4cbe-80e0-36fc5cfe0523.png)
without top:
