### ISSUE TITLE
Create tests on the lenasys website

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11402]
There are many functionality's which need to be tested on lenasys, but during testing we noticed that the already exisitng "dummy" examples are far from ideal, as they miss alot of things we wanted to test. We could create these manually for every time we want to test something, but it would be highly beneficial to have them already in lenasys to make it faster to test.

For example, in the issue #11300 we could not find an example anywhere where the error occurred, as there was no example of it. 

We need to create some examples to cover more areas of testing. Every Kind and Wordlist (filetype) would ideally be added. Try to structure it in a way to make it easy to see what code dugga contains what example.

**Comment by HGustavs** [comment]
Yes this would be very beneficial. This testing data is very useful for testing of lenasys. I suggest that the demo data sql and the included files / data is updated with more realistic example that allow better testing.

**Comment by a20willa** [comment]
@HGustavs Can we add an entire new course for testing specifically? Or may we edit one of the existing ones?

**Comment by a20andlj** [comment]
We (@b20fanfa and @a20andlj)  reserached this issue and found out that it needed to be split into smaller issues. Now we are going to implement code into the course "Webbutveckling - webbplatsdesign".

**Comment by b20fanfa** [comment]
After discussing with Henrik on how to solve this issue, we have realized that one of the problems may be that we are sitting on MAC computers ... The mistake is that we do not have access to edit in the files, when we give permission ALL files will be "modified" in Github Desktop".
Now we (@b20fanfa and @a20andlj ) will hand over the issue to a PC user.

What a PC user must do to solve the issue is to create a folder with all the sample files to be included and put in the LenaSYS installation folder. It is not mandatory for the What a PC user must do to solve the issue, is to create a folder with all the sample files to be included and put in the LenaSYS installation folder. It is not mandatory for those who want the files to reinstall LenaSYS, ​​instead you can after each weekly merge (or if necessary) move the folder from the installation folder to the "course" folder (in the LenaSYS folder) for the files to be displayed on their respective local LenaSYS. who want the files to reinstall LenaSYS, ​​instead you can after each weekly merge (or if necessary) move the folder from the installation folder to the "course" folder (in the LenaSYS folder) so that the files are displayed on their respective local LenaSYS.
