### ISSUE TITLE
Mock up for login to contribution

### ISSUE THREAD

**Issue by a20behta** [HGustavs/LenaSYS#11415]
When someone who is not logged in tires to acces the contribution page there should be a pop up which promts them to login to their account. 

Create a mockup which CU can accept before development begins

**Comment by a20behta** [comment]
related to #11223

**Comment by a20caros** [comment]
<img width="280" alt="image" src="https://user-images.githubusercontent.com/81676918/162195421-3cf474e2-d278-4626-b4a7-ccdf4e95a396.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/81676918/162195475-5e8b13ce-a501-4ec5-bbe8-1254320c732f.png">
This is the mockup to logging in to the page contributions for students. When the students go to the lenasys contributions page, a popup is made of a form where the student must first fill in the github username. If the student's github username is stored, a new form pops up where the student can choose a password and then get the student access to the contribution page.
<img width="386" alt="image" src="https://user-images.githubusercontent.com/81676918/162195244-5a35c05a-da36-4fba-9619-1317d6affdcf.png">
<img width="409" alt="image" src="https://user-images.githubusercontent.com/81676918/162195839-5d961d36-0ba4-4d53-8406-5b14af58a45d.png">
This is the mockup displayed on a computer

**Comment by a20behta** [comment]
* add extra position for username when checking
    - otherwise looks good.  
* part of sessing
* if not logged in pop up otherwise show directly
* utilize sessions for keeping user logged in.  
*  if user exits ask for password 
     *  else create user and check password twice to confirm password

**Comment by a20caros** [comment]
<img width="263" alt="image" src="https://user-images.githubusercontent.com/81676918/162959222-f5b012c3-342c-4f52-a9d8-0d4d6954b8e4.png">
This is the login popup form. The form allows the user to fill in their username to github and then checks with the database if the username is stored. If the username is stored, the user can log in to access the page.
<img width="254" alt="image" src="https://user-images.githubusercontent.com/81676918/162959974-f04c3753-6e56-4752-9d59-494634e101a5.png">
If the user does not have a username that is stored, creat new password is scrolled down in the same form box so that the user can create a password.
