### ISSUE TITLE
Look into material design for CodeViewer

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11449]
Currently we have both a light mode and a dark mode, but we should check that it follows material design. This is a kind of follow up to the #11314 where we started to document the colors currently present, but we should also check if they are actually correct, and update our documentation.

The documentation can be found in https://github.com/HGustavs/LenaSYS/wiki/Code-viewer-color-scheme-dark-mode.

**Comment by a20willa** [comment]
We may continue next week until actually converting current colors, as some issues which are being actively solved include dark mode.

**Comment by a20sarle** [comment]
This issue concerns to dark mode in CodeViewer and _not_ LenaSYS overall. Result is expected to be a mock-up with updated colors based on Material Designs' latest rules and documentation of the choice of colors.

**Comment by b20fanfa** [comment]
Here are the "Original CodeViewer":
<img width="1096" alt="Orginal on lenasys" src="https://user-images.githubusercontent.com/81618770/162750249-3122f2df-686d-4b2a-bfdd-994be1b5524e.png">


Here are the "mockup on Dark mode":
<img width="720" alt="mockup-darkmode" src="https://user-images.githubusercontent.com/81618770/162750302-83a6f341-3ac2-4989-8b6e-c9d4140172e1.png">

**Comment by a20sarle** [comment]
Customer says it looks good overall but that the font should be changed and that there should be more contrast between the code/file nav and the code examples. The code/file nav should not use purple but one other freely chosen color that complements the rest of the design. The fonts should be changed.

**Comment by b20fanfa** [comment]
After the customer meeting, we received some feedback on the mockup. According to Material Design, the primary colors are correctly placed and selected. But the customer wanted something else. The customer thought it was "poor contrast between the two navigation bars". The mockup would not consist of any other primary color (the color purple used around entire lenays). The font used should also be replaced.
Something that was added was the color of the text. The text now has both the color white and gray, this makes it easier to see the differences between them. As there are many users who suggest that the text should be gray instead of completely white.

Here are four new suggestions.

Mockup 1: 
Gray navigation bar, font Roboto. 
<img width="720" alt="gra boder " src="https://user-images.githubusercontent.com/81618770/163142642-06c30392-5889-4666-9823-a5f43270d84a.png">

Mockup 2:
Dark Blue-green navigation bar, font Roboto.
<img width="720" alt="dark blue border " src="https://user-images.githubusercontent.com/81618770/163144314-6467bd32-1a38-406a-8848-2b0cacd2e8e0.png">


Mockup 3:
Gray navigation bar with gray background on exemples, front “Lucida grande” 
<img width="720" alt="gra with gray background" src="https://user-images.githubusercontent.com/81618770/163142796-e5b55642-eeb8-4598-bca1-0a2d335b873f.png">

Mockup 4:
Dark Blue-green navigation bar with Blue-green background on exemples, font “Verdana”. 
<img width="720" alt="dark blue with blue background" src="https://user-images.githubusercontent.com/81618770/163142859-5ad9459f-583f-4559-a7ad-7a186a7dc257.png">

**Comment by a20sarle** [comment]
From customer: use white text, grey nav bar, code-colors on tagg ok. Box "Shadows i Material Design" is white beacuse of that it's fetched from duggaSYS, how to get this one to dark mode should be a new issue and problembly solved first.

**Comment by b20fanfa** [comment]
## This is the final product for how "Codeviewer" should look in dark mode. 
<img width="720" alt="correct" src="https://user-images.githubusercontent.com/81618770/165488769-23015435-daba-4d70-8edc-21ca66ce3245.png">

***Simple info about the colors:***

* The first nav header have primary color (purple) - # 5d4a72
* Second nav header (gray) - # 464646
* Background color (black) - # 121212
* All text (white) - #ffffff (but should have an opacity of 87%).
* All icons that are in the two headers should be white as well - #ffffff
* Source code: “Head and Style” have blue: # 90caf9 and “HTML” have red # ef9a9a.
* Background for example in description - # 1e1e1e.

*NOTE.* Why the “preview” view has a white background is because it is fetched from a different webpage (external source).
