### ISSUE TITLE
Menu description partially blocked when using diagram.php instead of showDugga.php

### ISSUE THREAD

**Issue by a20jonda** [HGustavs/LenaSYS#11461]
![image](https://user-images.githubusercontent.com/102598258/162398949-35e349d6-65a0-42ee-8da4-750c84416f59.png)

**Comment by a20jonda** [comment]
When opening diagram.php individually, the diagram window reaches to the bottom of the monitor and you cannot scroll down. The texts gets blocked by the windows taskbar

**Comment by a20edwth** [comment]
This problem is dependent on your screen resolution. When viewing diagram.php the toolbar does not scale with the screen resolution since the icons in the toolbar have a fixed size. 

Toolbar in diagram.php in 1920x1080 screen resolution:

![bf08c661fb5d58bf0656812d15e8b1e5](https://user-images.githubusercontent.com/102611046/162760196-c4723dbc-a7b7-47ef-af5c-e3182ff580e1.png)


Toolbar in diagram.php in 1280x720 screen resolution:

![b122e46e0e84f45c4075295a932a691c](https://user-images.githubusercontent.com/102611046/162760231-145ff611-0d07-4d6f-aea4-2862ea664ca4.png)


If the toolbar gets a scrollbar in the y direction, then since the tooltip is a part of the toolbar and has a visible overflow in the x direction, the visible overflow will get overwritten by the auto overflow(adds a scrollbar only if needed). This means that if a scrollbar was added, then you would have to scroll in the x direction to see tooltips. 
Source: https://www.brunildo.org/test/Overflowxy2.html

This shows what happens if overflow-x visible and overflow-y auto is added to the css for the toolbar(overflow-x visible becomes overflow-x auto):

https://user-images.githubusercontent.com/102611046/162759906-968db3e2-645e-472e-9049-5d9b1e26ec12.mp4


A solution would be to make the icons in the toolbar change dynamically with screen resolution. But when viewing diagram.php in shwoDugga.php this is not a problem since the resolution of the diagram.php will stay the same regardless of the resolution applied to showDugga.php.

showDugga.php in 1920x1080 screen resolution:

![400ebb88cfcb127e74a19e6cc8f633c1](https://user-images.githubusercontent.com/102611046/162760307-d85dfe4f-4005-47a2-a3b2-d8c52a460b7f.png)


showDugga.php in 1280x720 screen resolution:

![08f410fb66333976031da86716314b09](https://user-images.githubusercontent.com/102611046/162760334-bdf9c1e8-24e8-4b9d-a132-84a18cc1cfea.png)


Conclusion: Since diagram.php will be viewed in showDugga.php this issue is irrelevant, this issue would only become relevant if diagram.php gets viewed on its own.
