### ISSUE TITLE
Can't get back the original view once changed in codeviewer

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11488]
In the codeviewer, when the screen get's too small there's a hamburger menu which lets the user choose which window to view. However, once this is done, there is NO WAY to change back to the original view. Going in and out of the entire dugga is the only way to fix it.

![image](https://user-images.githubusercontent.com/81626616/162616362-0d126e44-7014-4e04-8b95-f34b72c8e6e8.png)

**Comment by b20idawa** [comment]
How to test the issue:

1. Choose the webprogramming course

2. Select PHP example 1
<img width="1305" alt="Skärmavbild 2022-04-12 kl  08 51 17" src="https://user-images.githubusercontent.com/81676911/162898450-4b9a7b9c-fc52-4c65-a5eb-bf61109cf6d2.png">

3. Minimize the window so that the hamburgermenu is visible

4. Press the hamburgermenu and select "Description"
<img width="694" alt="Skärmavbild 2022-04-12 kl  08 49 18" src="https://user-images.githubusercontent.com/81676911/162898257-77b7b254-4af5-425e-bad9-8fd6d9969f8a.png">

5. Then press the hamburgermenu again and select "All views"
<img width="598" alt="Skärmavbild 2022-04-12 kl  08 54 46" src="https://user-images.githubusercontent.com/81676911/162899010-28aab71f-92fd-44fc-9450-75dc43952ee8.png">


6. The result should be that both examples, ie. the both codeviews become visible again. The result should look like the picture below. 
<img width="601" alt="Skärmavbild 2022-04-12 kl  08 52 32" src="https://user-images.githubusercontent.com/81676911/162898611-5b1db8a1-de92-49bd-9a47-b62adbb70ed2.png">
