### ISSUE TITLE
Downloading markdown files gives wrong file suffix

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#11492]
When downloading a markdown file in the file editor the file is given `.txt` suffix, should be `.md`

**Comment by a20sacka** [comment]
> When downloading a markdown file in the file editor the file is given `.txt` suffix, should be `.md`

Does this concern the fileed.php file? And if it is, there is one available .md file(mdTest) im able to download but this results in a .htm file and not a .txt.

Im not able to add any other .md files to test either, is this a permission error, currently logged in as **Toddler** and im able to view fileed.php, cant view the fileed.php at all as **Teacher1**.

A bit more information for how you achieved your error would be helpful @a97marbr.

**Comment by a20sacka** [comment]
Was able to replicate issue by placing a "mdTest.md" file in global directory

**Comment by a20sacka** [comment]
Error was in **fileDownload()** in **fileed.js**, it set the download attribute to the filename, but as it defaults to a .txt if you only put the name in the download attribute you wont get the correct file type. 
This can be fixed by removing the filename from the download attribute and leaving it blank to just indicate that the anchor tag should download. By just indicating that the anchor tag should download it will default to the filename in the filesystem which has the file type preserved together with the filename.

Illustration of how the generation was fixed below:
![image](https://user-images.githubusercontent.com/102584289/162731870-48a03336-902a-4091-8fab-ab36a4ca8bfb.png)

The generated anchor tag for mdTest.md from the code above will be the following:
**Before** : <a href="../courses/global/mdTest.md" download="mdTest">mdTest.md</a>
**After** : "<a href="../courses/global/mdTest.md" download="">mdTest.md</a>"

**Comment by c20adael** [comment]
This is fixed
