### ISSUE TITLE
Codeviewer "Title" disappear sometimes in chrome browser

### ISSUE THREAD

**Issue by b20idawa** [HGustavs/LenaSYS#11513]
Codeviewer "Title" disappear sometimes in chrome browser when select any option in the hamburgermenu. This does not seem to be a problem in other browsers like firefox. 

https://user-images.githubusercontent.com/81676911/162739402-4641d6bd-9af4-4de0-80fb-9236bfd97410.mov

**Comment by a20patpe** [comment]
The reason this happens is because, the box width is always 100 when its calculated(for some reason).
In the function toggleTitleWrapper(). (found in codeviewer.js) The program decides if it should hide the titlewrapper or not,
it will always hide the titlewrapper since this:
![image](https://user-images.githubusercontent.com/102600690/163208955-50bd0758-2301-49b9-86c5-418fc6ab1831.png)
Is true. (there is one statement for each templateid)(boxW == boxWidth).

**Comment by a20patpe** [comment]
This issue is not replicable on many machines. 
The input variable boxW is sometimes wrong in the toggleTitleWrapper() function(found in codeviewer.js). I could not find the reason why it's wrong.

**Comment by a20sarle** [comment]
Solved with branch #11636. Closing issue.
