### ISSUE TITLE
Create a solution for selecting the year value for renderCommits in contribution.js

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11599]
To show the data in theCommit tree chart we need to select the right year that the data comes from. Figure out how this works

**Comment by b20jonlu** [comment]
Previously the commit tree didn't display anything the reason why is because of this code in `contribution.js` `function renderCommits(data)`
~~~
  var current = new Date();
  var currentYear = current.getFullYear();
  var weekData = data['weeks'];
~~~
This code gets the current date and gets the full year so in our case that would be 2022, the problem is that the year of the data is 2019 which means it won't display anything because of the if statement
~~~
 // for each commit ID
 // X is commit order, Y is commit nesting
  for(var i = 0; i < weekData.length;i++) {  
    for(var j= 0; j < weekData[i]['commits'].length;j++) 
    {
      var commitDate =  weekData[i]['commits'][j].thedate;
      var newDate = "";
      for(var x = 0; x < 10; x++)
      {
        newDate += commitDate[x];
      }
      var finalDate = new Date(newDate);
      
      if(finalDate.getFullYear() == currentYear){
        allCommits.push(weekData[i]['commits'][j]);
        var commit_obj = {
          index: index
        }
        index++;
        commitDict[weekData[i]['commits'][j].cid] = commit_obj;
      }
    }
~~~
The if statement checks if the commit happened the same year as the currentYear which worked when the data was from 2019 and the year was 2019. There are a few ways to go about updating this. Either we check what the year is for the first commit or we have an input to select which year we want to show the data for. Keep in mind that the input which is rendered is an interval of commits during 70 days. Since the data is in a block of 70 days it may not even be necessary to only render commits during the currentYear since we might want to render commits which are in two different years.

It might be a good idea to update the GUI to better show the weeks and dates in the interval and maybe also create an option to allow the user to select the start date of the interval instead of a static value.

**Comment by a20behta** [comment]
changes implemented into weekly merge
