### ISSUE TITLE
Dugga, changes made by student should be saved in localstorage.

### ISSUE THREAD

**Issue by b19karhj** [HGustavs/LenaSYS#11604]
When a student make changes in a dugga and managed to leave the dugga, The changes the student made should be saved in localstorage so the student can go back to the dugga with the changes remaning. There should also be a button where you can clearthe localstorage.

**Comment by a17nikjo** [comment]
Storing and loading the information is no problem, the bigger problem seems to be what to store. The best solution would be able to store any dugga. Storing the html code of the document and loading it works fine. The problem lies with restoring js and php related things.

Storing input values might be a better approach, this is however hard since all duggas are unique and avoiding a hard coded per dugga solution is preferable. Researching if we can record user input and then replay them to restore previous instance that way.
