### ISSUE TITLE
Contribution, add database information to mockup.

### ISSUE THREAD

**Issue by a20behta** [HGustavs/LenaSYS#11628]
related to #11593 

the hover functionality is added to be able to hover over a commit will start functioning. 
need to import the database information based on the commits to display when hovering occurs. 

take data from database.
filter correct changes based on where hover occurs. 
display specified lines of code.

**Comment by b20eripe** [comment]
We are creating a new array which is filled by code rows selected by the commit reference

**Comment by a20caros** [comment]
<img width="811" alt="image" src="https://user-images.githubusercontent.com/81676918/163380485-5a6a3510-e934-4edf-9927-187c91448218.png">

**Comment by b20eripe** [comment]
This query gives a rowk that is twice as large as it should be, debugging continues

**Comment by c20adael** [comment]
here is a potential debuggung function https://stackoverflow.com/questions/4323411/how-can-i-write-to-the-console-in-php

**Comment by b20eripe** [comment]
![bild](https://user-images.githubusercontent.com/102593527/164018421-db65b18c-f2ce-48e6-a790-73b8be0749ec.png)

for-loop to print out the array with the results from the query

**Comment by a20caros** [comment]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/81676918/164021194-f2064a03-8f2d-42bd-b5f7-dd8738c2ec14.png">
An onclick on the link for a commit

**Comment by b20eripe** [comment]
This can possibly be solved using an new PHP containing the SQL queries and then use ajax to access updated data from the contribution.js.

**Comment by c20adael** [comment]
We are not following the standard by doing this. What can be done is calling contributionservice.php again.

**Comment by b20jonlu** [comment]
So i tried to solve the problem by going the route of storing the data about all the commits for a github user during the 70 day interval when calling the contributionservice.php by adding this code.
~~~
//Commit changes
	$datefrom = $startweek;
	$datefrom=date('Y-m-d', $datefrom);
	$dateto=strtotime("+10 week",strtotime($datefrom));
	$dateto=date('Y-m-d', $dateto);

	$commitchanges=array();
	$query = $log_db->prepare('SELECT cid FROM commitgit WHERE author=:gituser AND thedate>:datefrom AND thedate<:dateto');
	$query->bindParam(':gituser', $gituser);
	$query->bindParam(':datefrom', $datefrom);
	$query->bindParam(':dateto', $dateto );
	if(!$query->execute()) {
		$error=$query->errorInfo();
		$debug="Error reading entries\n".$error[2];
	}
	$rows = $query->fetchAll();

	foreach($rows as $row){

		$codechanges=array();
		$query = $log_db->prepare('SELECT fileid, blameid, rowno, code FROM codeRow WHERE cid=:cid');
		$query->bindParam(':cid', $row['cid']);
		if(!$query->execute()) {
			$error=$query->errorInfo();
			$debug="Error reading entries\n".$error[2];
		}
		$innerRows = $query->fetchAll();
		foreach($innerRows as $innerRow){
			$codechange = array(
				'fileid' => $innerRow['fileid'],
				'blameid' => $innerRow['blameid'],
				'rowno' => $innerRow['rowno'],
				'code' => $innerRow['code']
			);
			array_push($codechanges, $codechange);
		}

		$commitchange=array(
			'cid' => $row['cid'],
			'codechange' => $codechanges,
		);			
		array_push($commitchanges, $commitchange);
	}
~~~
~~~
$array = array(
                'debug' => $debug,
                //.......................
                'timesheets' => $timesheets,
		'commitchange' => $commitchanges
	);
~~~

With this code i get this response from contributionservice.php
![response like this](https://user-images.githubusercontent.com/102533453/164448280-f5e2f749-4d20-4e8c-b5a5-5bde1658540d.png)


Now this response doesn't look quite right, for one thing there are commits which don't have any code changes(0 and 1). The other problem is that the response is a lot longer than it should be so i checked the database and found this problem.
![dupes in codeRow](https://user-images.githubusercontent.com/102533453/164444610-6cc094f5-cff1-4781-922d-ecb1177cc125.png)

It would appear all files are duplicated with an identical file at id+128 which also affected the codeRow table
![dupes in bfile](https://user-images.githubusercontent.com/102533453/164445359-57477d4e-e240-4e27-8035-15b14d0cb376.png)

If we compare the database to the github page there is another couple problems such as the rowno not matching, and that some code which appear as changes on github isn't counted in the database. (rowno is 186-189 in the database for this image)
![offset incorrect](https://user-images.githubusercontent.com/102533453/164446863-52dacd85-c458-49df-8655-9e235f94c595.png)

I tested the database with the default database obtained from the usb and even reinstalled it but the database still seem somewhat broken. If someone else could check their database and see if they have the same problem that would be useful in order to know if this method could work.

**Comment by b20jonlu** [comment]
@a20behta @c20adael What is it we are after when someone hovers over a commit? Are we after the lines of code, amount of changes or where the changes took place or a combination of all of those things? Because depending on the answer i don't see a way to make this function a reality. For example if we are intrested in the lines of code a user updated in a commit what happens when we have a case like this.
![all_this_on_hover_crazy](https://user-images.githubusercontent.com/102533453/164454861-96595087-3423-4ae0-aaea-a9a04102af23.png)
This being a hover function when a user changed 10 or 20 lines that is possible but when we get up to the hundreds i think it would be better to have something like the markdown in filled.php where the user clicks on an icon and gets a window
![editor_and_markdown](https://user-images.githubusercontent.com/102533453/164455817-d6fa6b5e-bb1b-443c-8f05-c815388def42.png)

**Comment by a20behta** [comment]
@b20jonlu 
the basic information exist in issue #11123 

The main information required is in this following comment
![image](https://user-images.githubusercontent.com/102468604/164461533-6aa06710-fb57-4f9f-888a-612cda90d153.png)

**Comment by a20behta** [comment]
new issues occured when testing for merge request. cannot be merged yet
details in the closed merge request. 

https://user-images.githubusercontent.com/102468604/164717890-bad3c419-1390-4d2f-9b29-5d5b468367e7.mp4

video show issue for quick reference
