### ISSUE TITLE
Diagram legend in contribution.php changes to a list after pressing the buttons in the navbar.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11663]
Here you can add the info and the pdf you made @b20jonlu

**Comment by b20jonlu** [comment]
Pdf, background to the issue.
[contribution_js_ legend.pdf](https://github.com/HGustavs/LenaSYS/files/8511381/contribution_js_.legend.pdf)
The problem is that when pressing one of the buttons at the top that invoke one of the Statview functions the elements original style.display is overwritten. This means the elements in for example barDiagramLegend goes from being display:flex to display:block which looks incorrect.

**Comment by a20behta** [comment]
weekly merge completed
