### ISSUE TITLE
Add the toggle icon for the darkmode / lightmode

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11715]
The icon should be moved to the header as we no longer require a footer (see #11696).

**Comment by a20willa** [comment]
Should the icon be on the right or left? 
![image](https://user-images.githubusercontent.com/81626616/164227913-6815f5c5-7ef5-4396-9148-07d4b422966e.png)

**Comment by HGustavs** [comment]
Compare to menu in section editor when logged in, imho I would put it to the left.

**Comment by a20willa** [comment]
Reference to #11316.

**Comment by b20fanfa** [comment]
This issue is very large and should be divided into several small parts. We have divided it into 4 parts, right now:
- [ ] The first step is to add the moon / toggle icon to the navigation bar. 
- [ ] The second step is to make sure that dark mode works on the first page (courseed.php / js). 
- [ ] The third step is to make the icon functional. When it is clicked the website should change between light / dark mode
- [ ] The fourth step is to implement dark mode on the remaining pages of lenasys.

**Comment by b20fanfa** [comment]
When I implemented the new dark mode toggle, I needed to delete the code "@media (prefers-color-scheme: light)" in both css files (blackTheme.css and whiteTheme.css). The code was removed due to the fact that depending on what the users operating system was set to before, it would collide with the code I added in my commit (Adjusted the button to switch between dark / light mode.).

Is this an okay way to do it?
@HGustavs

**Comment by b20fanfa** [comment]
Reference to #7761.

**Comment by b20fanfa** [comment]
# How to test issue. 

1. Make sure your operating system is set to dark or light mode. Depending on what you choose, Lensys will be what you set it to from the beginning.
 
2. On the home page, there is a new toggle that looks like a moon. It is located at the header on the left side. Click on it a few times and see if it changes to dark mode vs light mode.
In light mode: 
<img width="1128" alt="Skärmavbild 2022-04-26 kl  15 13 22" src="https://user-images.githubusercontent.com/81618770/165308499-9c6e15a4-25e1-4935-aec9-a8311b8739dc.png">

In dark mode:
<img width="1129" alt="Skärmavbild 2022-04-26 kl  15 13 34" src="https://user-images.githubusercontent.com/81618770/165308557-500e02bc-b74f-46a2-adc8-2e536ac70c49.png">

3. Then log in as a teacher. Go to the "Web Programming" program.
Check that page if the toggle button works there as well.


4. Then go to the example "HTML Example 5" and test the toggle button there with.

**Comment by a20willa** [comment]
The purple text has bad contrast in dugga viewer. 

Rule of theumb: 25% from white / 25% from black.
