### ISSUE TITLE
Redesign list of duggas menu

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11751]
If you hold down the right / left arrow icon, a menu will pop up which shows all duggas in front of it. The menu does currently not look very good however, and thus needs some design tweaks. 
![image](https://user-images.githubusercontent.com/81626616/164456823-3e1cc8c1-f970-435b-b362-cdded1b059de.png)

**Comment by HGustavs** [comment]
Some kind of a mock-up would be nice - we can show more information than just the names of the examples

**Comment by b20idawa** [comment]
@HGustavs What more information than just names do you want?

**Comment by b20idawa** [comment]
I have changed the formatting on the dropdown menu so that the content is more visible. I do not think it is necessary to add a title because each example contains the title at the beginning of the text. I therefore think that this issue has been resolved.

The dropdown menu looks like this now after my implementation and formatting.
<img width="770" alt="Skärmavbild 2022-04-28 kl  16 03 45" src="https://user-images.githubusercontent.com/81676911/165770336-dcf23556-6d0a-4ff2-836e-c2e9684f2a9c.png">

**Comment by b20idawa** [comment]
How to test the issue:

1. Select the web programming course 
2. Select HTML5 Example 4
3. Make a long mousepress on the forward or backward button and check the formatting of the dropdown menu
4. The result should look like the picture below
<img width="775" alt="Skärmavbild 2022-04-29 kl  14 42 18" src="https://user-images.githubusercontent.com/81676911/165946359-1978b6c7-d5e4-4da2-8e4c-7e468dbab5d4.png">

**Comment by b20sebka** [comment]
Was not closed after merge.
