### ISSUE TITLE
Github contribution hover box is incosistent. 

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11786]

**Comment by b20jonlu** [comment]
One of the problems with the `<div id="commitDiv">` element used to show commit changes when hovering over commit links is that the mouseover function stops working under certain conditions such as dragging the mouse over the link repeatedly, clicking on the webpage, and tabbing out of the browser just to name the ways i have discovered. Video example of what i mean

- When dragging the mouse over a commit link repeatedly the onmouseover functionality stops working

https://user-images.githubusercontent.com/102533453/165061115-6e0b7895-e3c4-4a33-8112-550964534a45.mp4

Another problem is that the webpage will extend when the `<div id="commitDiv">` element is shown and contract when hidden which can sometimes cause the webpage to jump when scrolling.
- When hovering on a commit link and scrolling up or down the webpage will jump.

https://user-images.githubusercontent.com/102533453/165063489-fa369461-99ca-40a4-9d3a-8e4ba9db5f83.mp4

Another problem which is a bit harder to show is that sometimes the `<div id="commitDiv">` element will take the place of another element instead of appearing above it. Somewhat related to this problem is that if the user has a screen where they can see the commit links when they are at the top of the webpage (such as a resolution of 2560x1440 when using the contribution button) the mouse over function will not display the window.

**Comment by b20jonlu** [comment]
Tried removing the hidden tag and i might have found why the webpage jumps and sometimes takes the place of other elements.
![div_over](https://user-images.githubusercontent.com/102533453/165067905-6a3afb30-03c3-4052-b084-ea3fed5f4a79.png)

The reason for the jump may be that the space the window is occupying in the image is added when the element is shown and removed when it is hidden thus extending and contracting the webpage by about 500 pixels.

**Comment by a20behta** [comment]
@b20jonlu see pull request for comments.

**Comment by a20behta** [comment]
merged into weekly branch. closing issue
