### ISSUE TITLE
Change indenting / tabs of multiple duggas 

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11835]
Currently the checkboxes only use the "ghost" icon to hide duggas, but the checkboxes could also be used for other functionality. Tabs could be added to many duggas at the same time instead of having to go do it manually.
![image](https://user-images.githubusercontent.com/81626616/165297681-08fcfaaa-1219-49ee-888d-3ec628a5b1a2.png)
A new icon should be used here and should look similar to that of the ghost icon in terms of style.

**Comment by HGustavs** [comment]
Not sure about the ghost iconography either. So ghost is hide and we want some kind of tab key icon for indenting?

**Comment by b20idawa** [comment]
I created a button with a tab icon and placed it next to the ghost icon button. When you press the new tab button, a dialog box appears where a dropdown menu is displayed.

What needs to be done further is to add functionality to the dialog box. So that the items that are marked tab in for the number of steps specified in the dropdown menu.

**Comment by HGustavs** [comment]
This seems too cumbersome, it is just as easy to click the cog wheel and select a number of tabs there. (about three clicks in total for e.g. adding one tab)

Perhaps a button for adding or removing a tab like in google docs instead.

<img width="71" alt="Screenshot 2022-04-28 at 11 34 16" src="https://user-images.githubusercontent.com/6978801/165723657-b2b81f6e-40a5-4406-a2fa-96d39054cb9f.png">
