### ISSUE TITLE
The relative deadline need some type of description.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11877]
As of now there is confusion as to what is entered in relative deadline field and what the "relative" part is. @a20kimar has created the relative deadline and could provide info about this. #11525 has some info about this. 

A solution to this could be a hover function that provides a description.

**Comment by a20kimar** [comment]
> As of now there is confusion as to what is entered in relative deadline field and what the "relative" part is. @a20kimar has created the relative deadline and could provide info about this. #11525 has some info about this.
> 
> A solution to this could be a hover function that provides a description.

The relative deadlines as they are shown in the cogwheel menu is currently not at its final stage. If you checkout branch G3-2022-W5-#11859 you'll see that my current version I'm working with handles amount of times instead of days of the week and so on. I understand the confusion as it looks and is right now.

There will be need for a future overhaul of the design. I have focused on the integration of the back-end before hand and I still have some stuff to fix such as relative deadline being kept and prioritized when creating a new course.

I think the amount - type - time model which I am using in my working branch mentioned above is the model we'll use going forward so if you know anyone interested in making a design overhaul then feel free to hand that out. That person could come in contact with me in order to establish what can be altered and changed as to not break the back-end.

**Comment by a20caros** [comment]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/81676918/165952328-b4d316a9-32cb-41a2-8072-c651b520ae83.png">
A title has been added for each dropdown menu and for the relative heading to clearly explain what each one is about
