### ISSUE TITLE
Contribution goes of screen when the links are too long.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11912]
https://user-images.githubusercontent.com/80856978/165765784-ff84a877-575b-498a-998b-b69db7be94f6.mp4

**Comment by b20jonlu** [comment]
The reason why the contribution goes off screen on certain smaller screen sizes can be attributed to the css responsible for the table. The issue in the video is caused by the "Code Contribution" column which takes up a bunch of empty space that could be used for the other columns as shown here.
![contrib is big](https://user-images.githubusercontent.com/102533453/165953022-798a54d8-d329-4a69-b054-59a17b3db993.png)

If we remove the static `width: 400px` from the contrib element the page instead looks like this which gives a lot more space for the "GitHub Contribution" column
![contrib is small](https://user-images.githubusercontent.com/102533453/165953128-9564985b-028e-4b38-956d-724be3723b1a.png)

The problem with this fix is how the columns constrict and expand when elements are hidden and shown.

Current implementation width:400px contrib:
https://user-images.githubusercontent.com/102533453/165954172-b3f0f25d-6b67-4bb9-ac51-f91d4836f943.mp4

Proposed implementation no set width contrib:
https://user-images.githubusercontent.com/102533453/165954124-d43320cf-5abd-4a36-8159-87e210d53d56.mp4

This issue is quite a lot bigger than just the contribution table being too wide, instead the problem is that the code is not adapted to different screen sizes and uses fixed size elements and percent based elements in a negative manner.
