### ISSUE TITLE
HTML files can not be opened or edited in fileed

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#11935]
![image](https://user-images.githubusercontent.com/102599327/165939502-f9981dde-fdb0-4703-b87f-a84a81e0594e.png)
![image](https://user-images.githubusercontent.com/102599327/165939598-5d109a26-fa60-4953-830a-6de2947c3408.png)

**Comment by c20adael** [comment]
![image](https://user-images.githubusercontent.com/80856978/165942365-53e0d894-2e04-41b4-a4ef-8537ad93f91c.png)
![image](https://user-images.githubusercontent.com/80856978/165942400-95849055-54f7-4ae0-af4c-56d4ab025e0e.png)
This table is being used to store the file names and load them to the fileed.php page.

**Comment by c20adael** [comment]
I found where it decides what type of function that should be used for the displaying of the file. This is in fileed.js row 357-362.

![image](https://user-images.githubusercontent.com/80856978/166218237-b560c03b-23ce-48e6-a20d-9e016c7a9546.png)

**Comment by c20adael** [comment]
If this marked part on row 360(in previous comment) is moved so that the other function is used when a html element is called the page loads. Not sure if it loads correctly. 

Here I moved the comparison to the other if statement so that it chooses the loadPreview function:
![image](https://user-images.githubusercontent.com/80856978/166225312-ea7deb0b-70b9-4e34-a13a-1df82e511341.png)

And when this is done this is the outcome:
![image](https://user-images.githubusercontent.com/80856978/166225941-f2b6f0a7-7a30-4e54-b0e1-e44063489ac7.png)
