### ISSUE TITLE
Contributions should be "closed"

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#11946]
In the contribution page, the standard should be that the different "sections" are closed when opening the page. If you have questions, ask them.

![image](https://user-images.githubusercontent.com/102599327/165943903-aba571ef-503c-42cf-93eb-888f4b6d08ad.png)

**Comment by b20eripe** [comment]
![bild](https://user-images.githubusercontent.com/102593527/166212773-5d6c5008-5d85-477f-9c78-e2ddcd6371a5.png)


At the moment the status for all div are stored in local storage to keep the settings collapsed/visible until next time. Should this functionality be removed or used in an other way to get both functionalities? Maybe add an button to collapse/expand all and otherwise get value from local storage?

**Comment by b20hanwa** [comment]
The costumer asked for a local storage that stores id of contributions. The id being stored in local storage shall result in the contribution being open/closed. The opposite to what happens when the id is stored should happen when the id is not stored in local storage (either open or closed).

**Comment by b20eripe** [comment]
![image](https://user-images.githubusercontent.com/102593527/167099511-226a7cb5-d3c3-48a1-b535-44ae7cf7e1c1.png)

This seems to already be stored? Down to the right is this status 'commit' which stores as 1 if open and 0 if closed
