### ISSUE TITLE
Codeviewer size overflows

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#11958]
The codeviewer overflows to the sides. 
Video demonstration:

https://user-images.githubusercontent.com/102599780/165952477-f47e029c-4f26-4842-99fd-1723833c28e3.mp4

**Comment by a20patpe** [comment]
The overflow occurs since a Resize bar is added to the south of the boxwrappers . There should never be any resize bar on boxes that are at the bottom of the screen. 
![image](https://user-images.githubusercontent.com/102600690/166210727-1595c087-7c7d-44c9-aba2-8e2fad23d92f.png)
The reason there currently is a scrollbar is probably because of the recent implementation of the gridview and the resize functionality being in its early stages.
However to fix the issue a line will be added to the div2 container (parent container for the boxes) that handles the contained boxes overflowing.
