### ISSUE TITLE
The zoom in and zoom out button does not work

### ISSUE THREAD

**Issue by b20idawa** [HGustavs/LenaSYS#11953]
The zoom in and zoom out button does not work in the codeviewer. Nothing happens when you press the two buttons
<img width="766" alt="Skärmavbild 2022-04-29 kl  14 56 43" src="https://user-images.githubusercontent.com/81676911/165948712-741abf40-9aec-4a1e-b3cd-b09c9bc4b67b.png">

**Comment by a20joabo** [comment]
The icons for these buttons make intended functionality unclear.

The functionality for these buttons has been previously implemented but is currently broken. 
Previous functionality maximizes and minimizes the boxes rather than the content of the boxes, evident to the `minimizeBoxes(boxid)` and `maximizeBoxes(boxid)`  functions in codeViewer.js & the tooltip of the buttons.

I believe that allowing the user to make the content of the boxes smaller and larger, rather than the boxes themselves, would be a reasonable addition to the code viewer. 

There are multiple solutions to this issue. 
- Changing the functionality to allow the user to zoom the content of the boxes.
- Fixing the previous functionality but updating the icons to avoid confusion.
- Adding a new pair of buttons for zooming content, and fixing the buttons for maximizing and minimizing the boxes. 

 **The intended functionality of the buttons is something that will have to be put forward as a question to the customer.** 

![image](https://user-images.githubusercontent.com/102584401/166211135-8a805da1-6b1b-4c5b-94f7-8e0c6d5e3826.png)
Tool-tip of the maximize-box button.

**Comment by b20sebka** [comment]
Customer wants these buttons to work like doing "ctrl +" or "ctrl -", making the text bigger. The previous functionality is to be implemented in another button.
