### ISSUE TITLE
Pressing checkmark for "moment", all files/duggas should get marked.

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#11956]
(This is in the start page for duggas)
![image](https://user-images.githubusercontent.com/102599327/165949458-d4997df6-8ae5-45b4-a7a7-5d202599e482.png)
When pressing this button/checkmark all underlying files should be marked aswell.

**Comment by a20vicad** [comment]
There is a way to determine which section an element is bellow. Under "moment" you can see which section it belongs to, this also changes when moving the elements between them. So there exists some form of variable/etc.
![image](https://user-images.githubusercontent.com/102599327/166227367-10cba355-92c7-4c6f-a940-69196cb81eef.png)

**Comment by b20jonlu** [comment]
@a20vicad Not exactly sure where you got the image from but i might have found something like it.

This seems to work for some pages and not others. For example it works with webbutveckling since it uses moments and deadlines as shown here in console.
![console_log_webbutveckling](https://user-images.githubusercontent.com/102533453/166235103-0b693618-3413-49ab-875b-f191beb160e3.png)


However it does not work for some other pages such as webbprogrammering since it uses the kind "section" and no deadlines as shown here in console.
![console_log_webbprogrammering](https://user-images.githubusercontent.com/102533453/166235086-de0be834-de0d-47e1-b54c-7a5f3589750f.png)

I already found a way to figure out which kind a checkbox belongs to such as `["header", "section", "code", "test", "moment", "link", "group", "message"]` which is committed to the branch.
