### ISSUE TITLE
When searching for duggas columns changes size

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#11951]
Before:
![image](https://user-images.githubusercontent.com/102599327/165948024-8f307432-a5af-4134-8e57-47f64558a972.png)
After:
![image](https://user-images.githubusercontent.com/102599327/165948101-11f46e43-0107-4f1a-9d02-0e6fbf00e1b8.png)

**Comment by b20jonlu** [comment]
I have had a similar problem in issue https://github.com/HGustavs/LenaSYS/issues/11912, i think this has to do with the column size being based on the size of the longest row in that column so when a row that is the longest is removed the size will shrink to the next biggest. Not sure what could be done since making everything a static size wouldn't be a good solution.

**Comment by a20johba** [comment]
I solved this by changing the row filter functionality to only hide filtered rows rather than removing them from the table. This keeps the column sizes consistent but may have a negative impact on the loading time of larger tables. 

This caused another issue however where the alternating row colors would still alternate with hidden rows, making the colors appear random and not alternating properly. I fixed this by replacing the css code with javascript code that changes the background color directly for visible rows. This might have unintended consequences for tables that use the commented css code but not the javascript code in sortableTable.js, but it appears to work fine with duggaed.php, fileed.php, and resulted.php. More testing is probably necessary.
