### ISSUE TITLE
Dragging the time table in home-page

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#11966]
It is at the moment possible to drag this "time table" at the dugga home page. It can however, not be "put" anywhere. It should either not be possible to drag it, or it should be able to be moved to a different position.
![image](https://user-images.githubusercontent.com/102599327/166193570-2643ed76-c650-4512-824a-72f61da2afcd.png)

**Comment by a20caros** [comment]
After much research, the issue was resolved that one can not drag around the table element by placing the id in another location.

To test the issue go into any course and try to move / drag the table

<img width="935" alt="image" src="https://user-images.githubusercontent.com/81676918/166237821-bf26a965-3001-4214-8217-6b27ad0ff0d9.png">
