### ISSUE TITLE
Button does not do anything

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12010]
![bild](https://user-images.githubusercontent.com/102599780/166214892-00e21eb1-cbf9-4ef2-96d5-2e290a8b3e7e.png)
This button does not have any function. Is it supposed to have any?

**Comment by b20sebka** [comment]
Button seems to appear when logged in as a designer

**Comment by b20idawa** [comment]
The button has the title = "Recent Feedback" and in the code it says "feedback from teacher" so I guess you should be able to click on it to get your latest feedback on an assignment or similar.

The button uses a function that uses username and since you can no longer log in to the page, this functionality no longer seems relevant. Since you nowadays log in via canvas, the feedback on assignments will be on canvas and not on LenaSYS

**Comment by b20sebka** [comment]
This button does not and will not have a function, it can be removed.
