### ISSUE TITLE
Only some of the buttons in the hamburger menu are "visualy pressable"

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12049]
In course homepages (when on smaller screenwidths) only some of the options in the hamburger menu give a visual response to the user that they are clickable even though they are.

![image](https://user-images.githubusercontent.com/102599327/166416428-82dc60c4-6eac-479e-94bb-4d9a38db7ed9.png)

**Comment by a20caros** [comment]
<img width="524" alt="image" src="https://user-images.githubusercontent.com/81676918/166450593-1504fb06-e4d1-4cbc-9c09-03f0b7b336db.png">
Now all parts of the hamburger menu have a hover function. The reason they did not have the hover function was because they were on tags and the rest who had the hover function before were links.


To test the issue, reduce the screen size (not in mobile view). Click on the hamburger menu on the left and hover over the menu selections.
