### ISSUE TITLE
New message

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12041]
When a new message is created it is not interactable with and can not be edited. The names also don't match where the button says "new message" and the thing created is called a "new quote"

https://user-images.githubusercontent.com/102599780/166411183-442f7340-e896-4474-96f8-5ebeb6de7ab8.mp4

**Comment by b20idawa** [comment]
Has done some research on this issue. I have changed the text "new quote" to "new message" instead to better match the item that has been created. But since it is only a message, it should not be possible to open it. Another idea from the issue manager was to open a dialog box directly that makes it possible to change the message immediately. This is not possible after some research as an ID is required to know which line to update. A lot of changes will be required in the database and this does not feel worth the work as the functionality already exists with the gear.

If this is something that should still be tried to be implemented, this request should come from the customer

**Comment by b20idawa** [comment]
How to test the issue:

1. Log in as a teacher
2. Select the web programming course
3. Press the "plus" button and select "New message"
4. Check that the alert message is "New message has been created" and that the item is "New Message"
5. The result should look like the picture below 
<img width="1370" alt="Skärmavbild 2022-05-03 kl  13 20 15" src="https://user-images.githubusercontent.com/81676911/166444184-a92dfcc0-edca-47b0-adc2-466bf970e894.png">

**Comment by b20sebka** [comment]
Was not closed after merge.
