### ISSUE TITLE
New install script

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12058]
Customer wants a new install script for the database that does not wipe the database and reinstall it from scratch. 
Research if this is possible.

**Comment by a20sarle** [comment]
Was also asked to create a wiki page and create documentation of the functions etc. this documentation can be found at https://github.com/HGustavs/LenaSYS/wiki/Installation-script-documentation.

**Comment by a20sarle** [comment]
As of now it is a bit too early to say if an individual script can be created to update the databse separately from the installation script and we're looking into how high the coupling is. We are also continueing to look into the files  `install_entry.js` and `install_defer.js`. However, the initial guess is that it should be possible since one can drop the databse and user but some of the main questions are:

1. If the username and database can be fetched directely without the need for the user to enter their student log in? (this is based on the wish from the customer during "Mittenseminariet" that it would be nice if  a user would only need to press a button to update the database (instead of running the whole script as it is today).)

2. How high the coupling is.

3. Would it be a secure solution? As dropping the databse and user might create a security issue it would be better to just be able to update the databse, but weather this is possible or not is yet to be researched.

**Comment by a20sarle** [comment]
@a20muhal Should I also write about the JS handler events "onclick" functions?

**Comment by a20sarle** [comment]
Key info needed for the additional script to fetch all new changes from database:

1. Student log in (to drop the databse)
2. Name of database (to drop the databse)
3. All the new files in the database (to install the new files)

Basically the only thing needed to be created is functionality that fetches all needed information and functionality that can detect the new changes and a script installing / updating / dropping & creating the new database.

**Comment by a20sarle** [comment]
There have been certain confusion about what the custumer actually wants and feedback is needed o continue. 

Does the costumer want:

1. That the SQL-files just fetch the newly added information?
2. That all the new files within the folder "install" shall be fetched?
3. That the developers should be able to add their own dugga examples without having to manually drag in into the LenaSYS folder after installation?
