### ISSUE TITLE
Button does not have a function

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12057]
![issuebutton](https://user-images.githubusercontent.com/102599780/166421277-b49f2e04-63de-43ad-9a2f-27cb51ba249d.png)
This button does not have any function
you can reach it by pressing this button
<img width="52" alt="Skarmavbild_2022-05-03_kl _10 00 08" src="https://user-images.githubusercontent.com/102599780/166421335-fdc81bcb-0b95-4a77-9fd2-9e63021688aa.png">

**Comment by a20joabo** [comment]
- Log in as teacher
- Press the "edit student results" button, listed above in the issue explanation. 
- Press the "?" button.

Make sure to clear cache when changing branches. 

The issue has been fixed by implementing a temporary side-menu that will be able to hold whatever text is neccessary after the requirements have been set forward by customer.

**Comment by b20sebka** [comment]
Sadly after new eu laws were implemented and how personal data is stored the page where the icon is was made redundant. Button does not have a function and will not have a function.

**Comment by b20sebka** [comment]
In fact as a small fix this button can be removed.
