### ISSUE TITLE
Resizing webpage causes issues with hamburger menu

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12099]
The issue is pretty selfexplanatory. It appears after resizing the page and opening the burger menu, then sizing it up again. It looks like this. 

![image](https://user-images.githubusercontent.com/102599327/166459662-3678f934-af83-48b1-84c8-7a856b0e0fe6.png)

**Comment by a20caros** [comment]
<img width="513" alt="image" src="https://user-images.githubusercontent.com/81676918/166700931-c625dc40-ee7e-477d-ba08-06e75b23de7f.png">
Now the result of the issue looks like this


To test this question go to any course and make the browser smaller. Open the hamburger menu and then widen your browser. If the problem is solved, the menu should not look strange
