### ISSUE TITLE
CodeViewer: Split megalong functions into smaller

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#1210]
There are some functions that are horrendously long (tokenize, rendercode in codeviewer.js) and should be divided into smaller functions, maybe even into smaller and more specified files as some files are very long (1k+ lines) to improve readability

**Comment by HGustavs** [comment]
The naming convention is as follows:
* One javascript file for each view i.e. one for code viewer and one for each other primary window.
* One html file for static interface
* One php file for database service

* One js file dugga.js for general javascript such as service code and formatting and so on.

The rationale behind this is that it should be trivial to know exactly which file each piece of code pertains to. Finding the code __within__ that file is considered easier than first searching for a file and the searching within that file.

The exception would be if it was split into view and controller i.e. one javascript for user interface stuff e.g. reading values from user input and calling service, and one second file that renders the content on screen.

 This suggestion was made some time ago and was downvoted since it was considered too difficult, as it has to be done project-wide.

we cant have codeviewer_view.js and codeviewer_controller.js if we dont have adduser_view.js and adduser_controller.js
...

**Comment by HGustavs** [comment]
Having all of the code that relates to the tokenizer in a single function is a good idea as it is a __VERY__ finicky piece of software.

However I do think that splitting the render-function into clearly named and clearly executed and commented sub-functions could be beneficial.

**Comment by HGustavs** [comment]
Kudos on the apt use of the word "horrendously".

**Comment by HGustavs** [comment]
Not relevant
