### ISSUE TITLE
Create testdata for duggasys

### ISSUE THREAD

**Issue by b13alebr** [HGustavs/LenaSYS#1218]
We should have a file with testdata for duggasys, the current testdata is not complete, the the testdata does not update activevers column in course when inserting the testdata.

**Comment by a13oscwe** [comment]
Please create a separate file for this

**Comment by HGustavs** [comment]
I say test data (as close to real data as possible) is put in init_db.sql and each merge we re-run this file in order to have a common set of data for the whole project.

**Comment by a13oscwe** [comment]
There have been a couple of issues with test data and inserts/updates in the init_db.sql file during friday merges and we were discussing if it might be a better idea to have a database creation file (init_db.sql) and then have separate files/file for test data, this will probably cause some issues as well since different groups use the same data but at least it would be somewhat more separated. Thoughts? @HGustavs

**Comment by HGustavs** [comment]
Well, my view is that the data in init_db has to be global, and working for all.....

otherwise, one group may have working code that breaks things for some other group. If both groups have the same data and the master database is reset to the contents of init_db each week, there will be no database related errors due to divergent information content.

The larger issue is how to decide what to put in the database.... well as always, work incrementally, rarely if ever removing something. Agree with other groups what information to put in the file.... and if all groups try to work incrementally, there should be a joint test dataset within a week.

The main goal is that all groups work with the same dataset.... and that every person works with the same dataset, with local additions for testing work features, and when those features are stable, merge that data into the joint dataset. The end goal is that the databases between team members and between the different subgroups differ as little as possible.

**Comment by HGustavs** [comment]
conversely, if all developers keep their own databases there is no guarantee that the code works on the machines of the other developers since they run different datasets.
