### ISSUE TITLE
Find out why this popup occurs and fix it

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12227]
Appears when trying to load certain duggas as teacher. ex biträkningsdugga2
![image](https://user-images.githubusercontent.com/102599327/167116976-f619db69-80f7-4353-81f5-4cdda182a9a4.png)

**Comment by b20jonlu** [comment]
Here is a picture which shows the difference between biträkningdugga1 which works and biträkningdugga2 which doesn't work.
![bit1_v_bit2](https://user-images.githubusercontent.com/102533453/167122302-ca47016a-2bc5-4f57-87cd-d89cdd72a026.png)

The keypoints is that no entries were retrieved from the variant and useranswer table since there was no matches for that dugga. The alert is because there was no variant so it couldn't create a link. This is kind of useless currently since the link doesn't even work since it uses hash.

The alert is overly obnoxious and could maybe be implemented in a better way. The main problem is still that the database is missing the information needed to function. Another problem is that the current code most likely loops through all entries matching the conditions saves them and then overwrites them meaning the answer displayed is the last entry which matches the condition.
![useranswer](https://user-images.githubusercontent.com/102533453/167123829-12a46f20-86a7-41bb-8e31-ff888327ebc2.png)

A potential solution for the alert is 
1. Create a default option when nothing is found  
2. Fix the database which probably requires changes to how the database is installed.
3. Pretend the problem doesn't exist and remove the alert

**Comment by b20jonlu** [comment]
Moved to this issue https://github.com/HGustavs/LenaSYS/issues/12279
