### ISSUE TITLE
Tab items

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12268]
![image](https://user-images.githubusercontent.com/102599780/167365775-d1ceeebc-69ae-4c05-9ddb-21cd2b893adc.png)
Add the function of tabbing items on every example instead of having a single button where you check the item you want to tab.

**Comment by a20andlj** [comment]
I have removed the tab button from the course header and moved it to the examples. The next step was to move the tab function from the cog wheel to the new tab button. But it was more problematic than I thought. 
Me and a20patpe tried some ways to maybe solve it, but we did not succeed.
The AJAX call that handles the UPDATE of the tabs, found in courseedservice.php on line 314 where the tab is added. However in order to run this AJAX call a lot of values have to be initialized and we are unsure how this is done.
Maybe someone can come up with another solution?
