### ISSUE TITLE
Headings returning from the dead

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12260]
After creating and subsequently removing them, these headings "magically" reappeared without any user interaction. This does not seem intentional. If not, fix this "necromancy feature".
![image](https://user-images.githubusercontent.com/102599327/167361941-c5f727ab-cf8d-4037-9934-daf2d57d504b.png)
Unsure if this can be repeated

Edit: it could, not sure exactlly how though it just sorta happened again. Even without refreshing and after waiting 60 seconds (I am aware of the undo deletion button)

**Comment by a20johba** [comment]
This issue was caused by the fact that the page refreshes when a line is deleted, meaning that any subsequent deletion after the first one gets skipped and the line will reappear when the page reloads. I solved this by adding all deletions to an array and refreshing the 60 second timer any time a line is deleted. All lines are then deleted at the same time when the timer runs out, before the page can be refreshed.

I also noticed that most of code in the function for preventing the deletion when pressing the undo button was useless since it also contained a location.reload(), which reloads the entire page anyway and thus makes it pointless to for example hide the undo button since it will be hidden when the page refreshed anyway.
