### ISSUE TITLE
Hamburger menu disappears on mobile view

### ISSUE THREAD

**Issue by a20sarle** [HGustavs/LenaSYS#12287]
In some mobile views the hamburger menu disappears.

1. Portrait mode
![Screenshot_20220509-122730_Samsung Internet](https://user-images.githubusercontent.com/81631818/167392306-cebe2451-e4b6-4e4e-a8d7-1170d1a60cc6.jpg)

2. Landscape mode
![Screenshot_20220509-122649_Samsung Internet](https://user-images.githubusercontent.com/81631818/167392309-35a079ee-6d0a-4fe2-9166-7ae84b0fcb50.jpg)

**Comment by a20patpe** [comment]
When the widht of the screen is below <800px codeviewer is considered to be in "mobile mode" 
Putting the phone in landscape mode would most likely cause the screen widht to be >800px meaning it no longer considers the page to be in mobile mode. 
As for the hamburger menu not showing up would be fixed by this merge https://github.com/HGustavs/LenaSYS/pull/12237
