### ISSUE TITLE
Deselect reset button after it has been clicked (in mobile view)

### ISSUE THREAD

**Issue by a20sarle** [HGustavs/LenaSYS#12286]
Reference to #12285. If the "reset buttons" should be kept in mobile view, make them deselected after pressed (on keyup or similar), just like the copy button. The buttons are only deselected when a new button is klicked but not otherwise.
![Screenshot_20220509-122223_Samsung Internet](https://user-images.githubusercontent.com/81631818/167391131-236686f5-4ae1-4e7f-8246-000a8db84553.jpg)

**Comment by a19xinhu** [comment]
This flash effect is the effect from mobile system. Because there is no hover effect at mobil.  Instead of that are three event listener: touch start,touchmove,touchend.  I try to add css style when click button and give a new class will change the background color when click button. No effect, No change.
