### ISSUE TITLE
blackTheme.css and whiteTheme.css should only style color

### ISSUE THREAD

**Issue by a20linth** [HGustavs/LenaSYS#12311]
The darkmode/lightmode css files include margin, padding, height, width and other attributes unrelated to color scheme. This should not be the case because blackTheme.css and whiteTheme.css should only modify colors.

Here is an example where this causes problems:
![image](https://user-images.githubusercontent.com/102609651/167411183-f82ee230-a69a-47be-8567-ff6488e52d1d.png)

How it hould be:
![image](https://user-images.githubusercontent.com/102609651/167412103-1574b757-bc2b-4ec6-9744-6295d68d8f79.png)

**Comment by a20patpe** [comment]
Since whitethem.css is being removed this issue does not change it at all.
As for blacktheme.css The code was simply copied over from style.css with the colors changed.
This means that should you want to change the size of things you would have to change it in both style.css and blacktheme.css.
This has not been the case for changes made to sizes and thus when changing to darkmode some of the older sizes are shown instead of the new ones.
Simply removing anything to do with sizes and positions from blacktheme would make it so that only style.css decides proportions.
