### ISSUE TITLE
Swedish text in otherwise English diagram.

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#12376]
Swedish text in otherwise English diagram. Double checked so it didn't have to do with language settings in the computer but that was not the case. Must be coded in Swedish somewhere. 
![image](https://user-images.githubusercontent.com/81772705/167649283-1ec5f75f-154a-419c-90a8-f333dfe0303b.png)

**Comment by a20samul** [comment]
I think this  issue is based on what language you have your browser set to rather than something that is hardcoded, as the input type is specified to file, for example:
Went to browser settings and changed the browser language to english and got (same issue we had with the alert showing automised swedish text rather than english):
<img width="163" alt="nofilechosen" src="https://user-images.githubusercontent.com/81613484/167841659-e995fa23-c929-4e34-a6d0-0f3b8dc8aae4.png">

When i changed the browser language back to swedish it showcases as the picture in the comment above.
