### ISSUE TITLE
(Mobile view?) Copy to clipboard does nothing

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12442]
![image](https://user-images.githubusercontent.com/102599780/168018941-c3198003-2d3d-4b4b-8a7d-2a9897d3d0b5.png)
When clicking "copy to clipboard" the yellow overlay comes up but nothing is copied

**Comment by a20linth** [comment]
It is the same in desktop view

**Comment by a20linth** [comment]
When the "Copy to clipboard" button is pressed on ios or android the selected text in the code viewer is deselected before copyCodeToClipboard() is executed. The function copies the empty selection followed by the deselection. This does not happen on desktop because when "Copy to clipboard" is pressed the selection is not deselected.
