### ISSUE TITLE
Massive bug when removing attributes/functions from an UML-entity.

### ISSUE THREAD

**Issue by a20chrka** [HGustavs/LenaSYS#12537]
This is what it looks like:
![image](https://user-images.githubusercontent.com/102599740/168544852-04015342-e059-4a69-8bda-0d4123cfe5f9.png)

To reach this error-state, do the following:
1. Place a new UML-entity in the diagram.
2. Remove all attributes and/or all functions in the UML-entity.
3. Click "Save" on the UML-entity
4. Move the diagram or zoom in/out. It should look like the image above.

Note that you can't stop moving the diagram afterwards.

**Comment by a20gabpa** [comment]
Tip: At the moment, the UML has two lists, one for attributes and one for functions. The problem is that the UML class is built on the values in these lists, if these are empty, neither of the other boxes are drawn / created. The updateCSSForAllElements function tries to access its child but is encounter with undefined, and thus breaking the program. One possible way to fix the problem could be to handle NULL or empty list cases correctly.
