### ISSUE TITLE
Restore deleted items

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12576]
A way to restore previously deleted items even after reloading the page would be nice to have.
Some kind of way to store deleted items that are deleted after a set amount of days and being able to open a GUI and selecting an item you wish to restore.

A mockup of this and research if deleting something after a set amount of days is needed.

**Comment by a18gusjo** [comment]
@a20linth provided me with the great idea to instead of deleteing the listentries from the database change their visibility to deleted. In that way it will be possible to retrieve deleted listentries by quering the DB for listentries with visibility 3. I have now created a ajaxservice that serves this purpose. I will create a pull-request for this later today or on monday morning. Note that the ability to restore deleted listentries will not be implemented here (GUI, buttons etc). Only the functionality that supports this.
