### ISSUE TITLE
Shorten the light script time

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12684]
Currently the light install script takes way too long to process
Is there a way to shorten the time it takes?

**Comment by a20linth** [comment]
The time it takes for the light install script to execute is reasonable considering that the whole database is recreated. The light install script uses the code from install.php so the two scripts take the same amount of time to recreate the database, which is also the more time consuming task in install.php. The inserts are slower because the tables in the database use heap indexing to optimize database entries space rather than the performance of the inserts.
