### ISSUE TITLE
Tables in duggaed and other have an "extra" row

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12708]
These rows don't fill a purpouse here.
![image](https://user-images.githubusercontent.com/102599327/169248271-f0437f23-3e31-4d20-a644-a5ca55ccfe86.png)
![image](https://user-images.githubusercontent.com/102599327/169248291-690bf100-5bab-4fe0-8380-3fb31cc659d0.png)

**Comment by a19simru** [comment]
@a20vicad Simon (a19simru) would like this issue please.

**Comment by a20johba** [comment]
For some reason the hasFooter variable is set but never used, so I readded it and added an if-statement so that only tables that explicitly want a footer has one. This works for most tables, but may in some cases require tables to be updated to use this variable. The duggaed, fileed, and resulted tables as well as the result table in contribution all appear to work as intended. I am not sure about the other tables in contribution however.
