### ISSUE TITLE
Panning the diagram to a lenght up to 1 thousand lags the process almost to a halt.

### ISSUE THREAD

**Issue by a20jonda** [HGustavs/LenaSYS#12756]
This is likely due to the ruler drawing everything to the length.

**Comment by b22jonan** [comment]
it starts lagging due to adding more and more objects without cleaning out the old ones, resulting in thousands of html elements which results in the lag. the fix for this would either to render the rulers another way without saving entities, or to clean up the elements as you pan further away. 
![image](https://github.com/HGustavs/LenaSYS/assets/61019188/76433f08-83ca-440d-b450-d5fe7285a426)

**Comment by b22jonan** [comment]
fixing this seems to be a bit wierd since the coordinate system used for the rulerbars is somewhat screwed up, currently trying to get a range where bars are visible, but that doesnt seem to work since the coordinates for bars get moved as you pan.
however this should still be possible to fix as long as i can get the range to be correctly dynamically generated.

**Comment by b22jonan** [comment]
sort of fixed now, introduced problem with 10cm bars not being drawn for some reason
