### ISSUE TITLE
Er entity with black background.

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#12975]
Er entity with black background changes colour when something else is interacted with.

before interacting with anything else:
![erwhitetext](https://user-images.githubusercontent.com/102599332/229470725-447f9136-7450-4832-a43b-b5abb041f5b9.PNG)

When line is selected the er entities change text colour to black:
![erblacktext](https://user-images.githubusercontent.com/102599332/229470735-24bef8b0-c156-49f0-b85a-87e0685ca68d.PNG)

**Comment by a21aldsa** [comment]
I couldn't solve this issue but my findings are:

It seems that only the text becomes black,  this also applies for IE and UML too. My best guess is that updateCSSForAllElements gets overwritten or simply not called, since this has checks in place for checking if the background is black or pink, and if this is the case; the font color gets set to white. 

Whenever any other tool is used, even if its just panning with the selection tool, the text becomes white again. Maybe a function for updating some graphics is called here?
