### ISSUE TITLE
Check diagram backend

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#12976]
check the status of the diagram backend code and report back any findnings.

**Comment by a21nibah** [comment]
in diagram.php:
As things stand now a connection is made to the database but there is no check on weather the connection succeeded or failed. As a result when atempts  are made to perform a request to the database you will get sql errors. You probably want to rework this so that no requests are performed if the database is not connected.
starting from line 26 the first response should be reworked. As things stand now only the latest variant version is shown to the user.
line 646 has a check if the ID variable is set. but nothing is performed in the if statement. this can probably be condensed so that the check is performed on line 650.
right now there is no error handling when querys are performed against the database. You would want to check if the query actually succeeded or failed before fetching the data and if it fails inform the user. 

 diagramservice.php
the same connection issue with the database exists here as well.
right now there is no error handling when querys are performed against the database. You would want to check if the query actually succeeded or failed before fetching the data and if it fails inform the user. 
diagram_IOHandler.php:
some notes from the file. 
    -Diagram files does not save or load on the subfolder. From testing it seems to work fine now, maybe an old issue?
    -Choosing permission does nothing to permissions.  I was not able to verify this.
    -'Upload Canvas' and 'Example canvas' options does not seem to do anything. Don't know exactly what they mean here. Clicking the option brings up the file dialog. And what file types are you supposed to upload? might be a good idea to restrict in the UI to give a clear indication what files are expected. 
the code can be refactored so that the php sektions are more unified. Right now they are all spread out in the code and there is room to restructure abit to allow for better readability and maintainability.
