### ISSUE TITLE
Model filereceive service

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#12970]
This service needs to be modelled. Related to issue #12920 

* Which parameters does the service receive?

**Comment by a21jeaha** [comment]
What is the basic idea with the model, are we suppose to to model each file as a separate class?

**Comment by a19hakja** [comment]
We need the model to resemble the project as it is at this moment, to later on be able to work on converting the monoliths to microservices

**Comment by a21jeaha** [comment]
@a21ponkr 
the file filereceive.php is completely modeled as of right now.  There are till work to be done on filereceive_dugga and filereceive_preview

filereceive_dugga: i went trough the variables, rearranged and added a couple of new ones. The methods added for this file might not be sufficient, might be a good idea to split formatTimeSheetInput() up into smaller methods. Add a description in the txt file (you can find it in the issue branch, otherwise contact me), input, output is already added.

filereceive_preview: has not been touched and so is as you left it.

NOTE: input and output includes the database accesses (insert, updates and so on..), use my text as an example of how to write it in the txt file..

**Comment by a21jeaha** [comment]
this information contradicts my previus statement regarding database accesses 

"I would argue that queries aren't anything that the service receives upon start or sends to the caller. It uses the input data described to collect data from db (external communication in the middle of the process is not what I would describe as either input or ouput data, more like manipulating data) and this data is stored in a variabel query which is then inserted into the output array."
