### ISSUE TITLE
.md or .txt .index file that we can use to control the ordering of code examples

### ISSUE THREAD

**Issue by a21rammo** [HGustavs/LenaSYS#13016]
A md or txt file to index ordering of content. A txt/md file should exist so the teacher can use to control the ordering of course items/content (code examples from github).

Should this also be the way to index the existing contents/code examples? @HGustavs 
This is a subissue #12927

**Comment by a21rammo** [comment]
**An example of a section inside of txt file:** 
![image](https://user-images.githubusercontent.com/102600501/229749949-70b08a55-66ba-452a-8e2e-bf702ac6c5e8.png)

**Comment by a21rammo** [comment]
@HGustavs I assume this issue kinda solves issue: #13018

**Comment by a21olljo** [comment]
After discussions with the customer; its been clarified that the index file should not control the order of code examples, as stated in this issue. But rather be present in the repo to specify which files or directories should be downloaded, more like a filter. Then when the code example is downloaded and generated, the newly created example should be placed in the corresponding moment to then be ordered manually through the drag and drop feature. 

@b21leowa @a21henhe This issue is now outdated and not good description for what should be done, do you want a new issue that more clearly states the issue at hand, or do we keep it here with an updated description?

**Comment by a21henhe** [comment]
@a21olljo I think a new issue would be clearer
