### ISSUE TITLE
Database code in diagram.php

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#13032]
It seems like we have back-end stuff in diagram.php this should for architectural reasons be in diagramservice.php

Document which back-end stuff ended up in diagram.php and if it can be moved to diagramservice.php

Especially since diagramservice needs to be moved to microservices.

Same thing for iohandler should this be moved to sevices or not? Is that file a second diagramservice.php or something else. This is relevant for microservice migration.

**Comment by c21adano** [comment]
diagramservice.php right now only tracks a users activity on git hub. it fetches relevant data from the database for what the user has done for the current week and then prints out a json string containing that data. I believe we could repurpose the diagramservice.php file so it contains all the database code from diagram.php and returns json objects for querys made to the database that diagram.php then can use.
Although you have to be careful and also check diagramIoHandler.php because it seems that it is sending a request to diagram.php to create a new directory, Although i am unable to track down where this gets done in diagram.php.

**Comment by c21adano** [comment]
Group 1 and 2 leaders have talked about who should move the backend code, and we agreed that group 1 can do it
