### ISSUE TITLE
Naming convention for Microservices

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#13044]
The current naming convention is:

| File  |      Function      | Comment 
|----------|:-------------:|------:|
| webpage.php | Static Form and Login Handling |    |
| webpageservice.php   |   All web service functionality |    |
| webpage.js | Any dynamic functionality for that webpage |    |

The question is what naming convention to use for the new iteration so that it is the same and any content can be easily found when working on a service you are unfamiliar with?

Perhaps _get _write _set ??

**Comment by HGustavs** [comment]
What options do we have and what functionality is common for each service?

**Comment by HGustavs** [comment]
For some reason the diagram module does not conform fully to this convention

**Comment by c21alest** [comment]
We suggest using the names in our ms documentation followed by _ms.php. Waiting for answers from other groups.

Documentation:
https://github.com/HGustavs/LenaSYS/blob/g2-2023-v6/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md

**Comment by f22linhe** [comment]
Enligt min förståelse av vad kunden önskat och vad som senare satts som standard för namngivningskonvention av tidigare grupp så uppfylls inte kundens önskemål till fullo. De verb som valts för att beskriva handlingen som funktionen utför har blandats. Exempelvis, ibland används "get.." och ibland används "retrieve..". För att hålla en konsekvent namngivningskonvention bör man bestämma vilken typ av beskrivande verb som ska användas. Antingen get, set, delete etc eller retrieve, create, update etc, inte båda samtidigt. Då implementering av microservices redan har startat så kommer namn på microservices behöva bytas ut beroende på vilken namngivningskonvention som nuvarande grupp kommer fram till. Troligtvis get, set, delete eftersom det följer kundens önskemål. Även dokumentation för "Potetial_micro_services.md" kommer behöva uppdateras.

Dokumentation för naming convention från gruppen 2023:
https://github.com/HGustavs/LenaSYS/blob/g2-2023-v6/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md

**Comment by f22linhe** [comment]
Based on my understanding of the client's desires and the naming convention standards previously set by another group, the client's requirements are not fully met. The verbs chosen to describe the actions performed by the functions are inconsistent. For instance, "get.." is used in some cases, while in others, "retrieve.." is employed. To maintain a consistent naming convention, it should be determined which type of descriptive verbs will be used: either get, set, delete, etc., or retrieve, create, update, etc., but not both sets simultaneously. Since the implementation of microservices has already begun, the names of the microservices will need to be changed depending on the naming convention that the current group decides upon. Likely, get, set, delete will be chosen to align with the client's preferences. Additionally, the documentation for "Potential_micro_services.md" will need updating.

Documentation for the naming convention from the group in 2023:
https://github.com/HGustavs/LenaSYS/blob/g2-2023-v6/backend-models/microservices/duggaSys%20services/Potential_micro_services.md

**Comment by f22linhe** [comment]
Based on my understanding of the client's desires and the naming convention standards previously set by another group, the client's requirements are not fully met? The verbs chosen to describe the actions performed by the functions are inconsistent. For instance, "get.." is used in some cases, while in others, "retrieve.." is employed. Sometimes "change.." is used and sometimes "update.." is used. To maintain a consistent naming convention, it should be determined which type of descriptive verbs will be used. Since the implementation of microservices has already begun, the names of the microservices will need to be changed depending on the naming convention that the current group decides upon. Additionally, the documentation for "Potential_micro_services.md" will need updating. 

It should be emphasized that it's possible that "get.." and "retrieve.." have been mixed because sometimes a function might be simple, and then "get" suffices, but other times it might be more complex with multiple steps, making "retrieve" more appropriate. However, for consistency, perhaps it would be best to stick to one? The group will need to make a decision on this.

Documentation for the naming convention from the group in 2023:
https://github.com/HGustavs/LenaSYS/blob/g2-2023-v6/backend-models/microservices/duggaSys%20services/Potential_micro_services.md

**Comment by f22linhe** [comment]
The 2024 group has decided to try to maintain a more consistent naming convention for microservices. Terms like get, set, delete, etc., will be replaced with more general verbs such as retrieve, update, remove, etc. This is because certain files may contain more complex methods that are executed in multiple steps and may therefore require a more general verb that describes the method used. At present, a mix of get, retrieve, update, set, create, delete, change, remove and so on is used, which feels highly confusing. The documentation for naming microservices will need to be updated, and files will have to be renamed to follow this standard.

Documentation for the naming convention from the group in 2023:
[https://github.com/HGustavs/LenaSYS/blob/g2-2023-v6/backend-models/microservices/duggaSys%20services/Potential_micro_services.md
