### ISSUE TITLE
State diagram: states shape

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13057]
The box symbolizing a state should be implemented. Preferably by reusing code from similar modelling techniques. 

The shape should be placeable on the drawing-area. 

EDIT (2023-04-14): 
The button for state entities is currently disabled so we want you to draw a state entity on the board and make it have a similar code-format to the other entites that already exists. This means that it does not have to be placeable just yet. We want the state entity that you make to be linkable to a button in a way that the other entities work.

**Comment by c21adano** [comment]
IE entities have a very similar appearance as to what state entities should have, but they should still be distinct from each other, this can be done by giving state entities rounded conners.

Like other entities state entities should only be allowed to be connected with other state entities.


![statebox](https://user-images.githubusercontent.com/102599332/230048960-359c1ce6-f13b-4be3-ba87-fa59c7bfdd42.PNG)

**Comment by b21oscpe** [comment]
This comes after adding the button.

**Comment by b21eriho** [comment]
I would like to double-check, should I in this issue handle the error-checking for drawing a line between entities of another type and the one I am implementing here. Mainly asking since that seems like a reasonable place to split this issue and I'm not certain I will have the time to implement that type of error-checking before the merge

**Comment by c21adano** [comment]
The error checking can become its own issue later on.
