### ISSUE TITLE
Research the "diagram_IOHandler" files

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13063]
Preface: 
As it is written right now we have backend code in "diagram.php", the customer does not like this because diagram.php should only work as a static php/html page. We need to figure out if it is possible for the services to migrate to another class.

What is the intended purpose of these classes and how do they work right now? Report back any findings as a comment to this issue.

**Comment by d21matbo** [comment]
## diagram_IOHandler.php
As documented in the file "*UI for creating and finding the folders to save diagrams in*”.
Currently this file only creates folders in a parent-child structure (with some identified issues) and then redirects the viewer to `diagram.php?Id=child&folder=parent`.

First time used a new folder “Save” is created under LenaSYS/DuggaSys/ in which the parent folder is created and with its child folder inside. The correctness of this approach is uncertain due to some identified issues (...)

Most of the functionality of this tool is written as generic `<div>` which are all generated as hidden by the attribute `display:none`. For example the button **New Canvas** calls the function `loadNew()` in diagram_IOHandler.js which hides the elements with `id='showStoredFolders'` and `id='showStored'` while displays the element with `id='showNew'` by setting its `style="display:block"`

### To simplify the structure for future readers the `<div>` ids are as follows;
- `showStored` - After clicking “Load Canvas” this element shows all the folders in “Save”

![image](https://user-images.githubusercontent.com/102599161/230417736-5dfc6699-e035-49cf-9437-d3b2256aae46.png)

- `showNew` - After clicking “New Canvas” this element shows a “New Folder”-button and all the folders in “Save”

![image](https://user-images.githubusercontent.com/102599161/230418263-2c824f8a-5e51-4753-9837-ce813f9f1498.png)

- `showStoredFolders` - After clicking “Test2” this element (reloads the page and) shows the subfolders of the selected folder

![image](https://user-images.githubusercontent.com/102599161/230418437-9db543af-573b-4c26-b1cf-dbaf3311f498.png)

- `newFolder` - Clicking “New Folder” in ‘showNew’ shows the form for creating a parent folder and a child (project folder) 

![image](https://user-images.githubusercontent.com/102599161/230418552-3d5acf53-c726-457d-9cb5-7e17cbc858f4.png)

- `newProject` - Clicking “Test” (any existing parent folder) in ‘showNew’ (reloads the page and) shows the form to add a project (child) to the selected folder (parent)

![image](https://user-images.githubusercontent.com/102599161/230418790-38a88f57-fb35-4667-a687-8121e0ca8dcc.png)

### Identified problems
- The `<div>` with `id='newProject'` is not hidden when `id='newFolder'` is visible so that they overlap

![image](https://user-images.githubusercontent.com/102599161/230418895-a1351f34-4747-4eb1-b60c-87048cb6ef2d.png)

- The creation of folders are not limited to the “Save” folder, by using ‘../’ it is possible to leave the parent directory

**Comment by d21matbo** [comment]
## diagram_IOHandler.js
The documentation already present in diagram_IOHandler.js claims that the file contains functions for "Save, Load and Export" for "diagram dugga". Through thorough testing (locally deleting the file) it has been identified that this is not correct, since all of the these functionalities listed above are implemented elsewhere and works for both “diagram dugga” and “diagram.php”. However it does have some current use (read below)

### Current use of diagram_IOHandler.js
`getUpload()` - Currently called when the <body> is loaded and affects the “Upload Canvas”.
`redirect(doc)` - Wrapped inside a function that is never called.
`loadNew()` and `loadStored()` - “New Canvas” and “Load Canvas” change visible elements.
`redirectas(doc, folder)` - Used in ‘showStoredFolders’ as the “onclick” for the project folders, redirects to `diagram.php?id=Test3&folder=Test2`

### For reference it is possible to
1. Load and Export diagrams from the Options menu, these buttons calls the functions `loadDiagram()`,  `exportWithHistory()` and `exportWithoutHistory()` which are currently implemented in ‘LenaSYS/duggaSys/diagram.js’
2. Save an active dugga when in ‘diagram dugga’, the save button calls the function `uploadFile()` which can currently be found in ‘LenaSYS/duggaSys/templates/diagram_dugga.js’

**Comment by d21matbo** [comment]
## Conclusion
* It appears that both of these files provide limited to no functionality for the system overall and as such the need for these files are questionable and their existence should be evaluated with the customer.
* The expected usage of diagram_IOHandler.php leaves multiple question marks, like how the tool is actually supposed to be used and its requirements. 
* The file is far from complete and thus it can be viewed as a concept rather than a file to build upon.

**Comment by c21adano** [comment]
Good work.
The files removal is sadly not a possibility right now due to the clients request, he didnt want us to remove any files from the system right now and only wanted us to mark down what they did and if they served any purpose.

diagram_IOHandler.php according to its name was suppose to handel backend kod, but that kod was placed inside diagram.php instead, it currently being moved over to diagramservice.php (see #13133 for more).

Unless we are asked by the customer to develop the file any further it will remain uncomplete and will remain as a concept on the server.
