### ISSUE TITLE
Research diagamservice.php

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13060]
Preface: 
As it is written right now we have backend code in "diagram.php", the customer does not like this because diagram.php should only work as a static php/html page. We need to figure out if it is possible for the services to migrate to another class.

Research the purpose of diagramservice.php and how it works, do you think it is suitable for our database-code?

**Comment by a21nibah** [comment]
diagramservice.php right now only tracks a users activity on git hub. it fetches relevant data from the database for what the user has done for the current week and then prints out a json string containing that data. I believe we could repurpose the diagramservice.php file so it contains all the database code from diagram.php and returns json objects for querys made to the database that diagram.php then can use.
 Although you have to be careful and also check diagramIoHandler.php because it seems that it is sending a request to diagram.php to create a new directory, Although i am unable to track down where this gets done in diagram.php.
I believe it may be best to let the group who has responsibility for micro services work on separating the code and create the relevant services.

**Comment by b21oscpe** [comment]
Good job
