### ISSUE TITLE
Add a button in the menu for placing statediagram states.

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13074]
![issue-state](https://user-images.githubusercontent.com/102578165/230064589-9f659ca6-d182-4415-bd71-4f8d2a86f174.png)

Add a button for state diagram entity

**Comment by b21eriho** [comment]
In the system, there is functionality to setup which diagram types may be used in the diagram, I am making the assumption that this is not part of this issue and my role is simply to add the button and the logic for when it should be displayed is another issue? Is this correct?

**Comment by b21eriho** [comment]
Further, should I create the icon? and if so is there a standard way to do this so that it matches the already existing icons?

**Comment by c21adano** [comment]
"should I create the icon?" - yes you should create the button, but you can reuse the IE entity image for the time being.

 "my role is simply to add the button and the logic for when it should be displayed is another issue" another person is making the state entity and all that is required right now is a button which can later be linked with state entity.

**Comment by b21oscpe** [comment]
Exactly, all that is required from this issue is a way of creating a state entity, the rest is handled in later issues

**Comment by b21eriho** [comment]
As in the button that later will add a state entity, or a button that *does* add a state entity, because the latter would require implementing a state entity in entirety in this issue

**Comment by c21adano** [comment]
the button that later will add a state entity

**Comment by b21eriho** [comment]
So, I've added the button to the toolbar, however the system has a way of dynamically hiding the appropriate buttons on the example diagram page based on the setup of that dugga. This does not work with the new button since that would require giving it an id that corresponds to the action of creating a state entity, which obviously isn't implemented yet. The result of this is that said button is displayed when it should be minimised along with a few other visual and functional bugs that depend on the supporting systems for the toolbar.

On top of this the new amount of buttons pushes another toolbar entry off the screen, this entry was simply information regarding special characters so could be relocated reasonably in theory since it isn't a tool and as such needen't be in the toolbar.

I assume I should simply describe this in my pull request because the system does not behave correctly at this point so testing will otherwise return with "there are bugs" even though the bugs need to be fixed in the "backend" of the system and as such do not belong to this issue

**Comment by c21adano** [comment]
Sounds good.

This issue is related to issue#13057 were the the entity will be added. Other issues will be dealt with later.

**Comment by b21oscpe** [comment]
"A merge should never make the system worse", send me a message on discord so we can discuss the problem
