### ISSUE TITLE
Lines between states should be possible to label

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13081]
![a5052d8a65b20721e51fef5a307b939e](https://user-images.githubusercontent.com/102578165/230072646-f5554ecb-adcc-43c6-b605-24d88350144d.png)

Currently it is possible to label IE-lines, this should also be possible for statediagrams. Try to find a way to reuse the code/functions of the IE-lines.

![af07a78db96550bcd4b415f5436fbd35](https://user-images.githubusercontent.com/102578165/230072936-0fb29343-ffe8-4a1f-b2fc-0b18ef223d73.png)

**Comment by HGustavs** [comment]
In the example from the software engineering book that we are trying to follow (page 156, 157 and 207) I think that the state change lines look similar to ER lines but with arrow heads on one end.

Also we want to add things like the very important guard conditions to the middle of the lines.

Can someone please create a mock-up (recreating a subset of the diagram on page 156,157 and 207) remember that an exact copy of the diagram may not be legal due to copy right. But we want the same general use of symbols etc.

This way we have a clear view of exactly which symbols that appear in "real" diagrams

**Comment by b21oscpe** [comment]
Note that the comment about "look similar to ER" was a mistake and he meant to say IE, we resolved this during the meeting held 2023-04-14

**Comment by a21oligu** [comment]
My findings: 
Lines are created by _addLine()_, which calls _addObjectToLines()_
Selecting a line calls the function _updateSelectedLine()_, which uses _determineLineSelect()_ to determine the selected line.
The option pane is updated by _generateContextProperties()_, which is called upon click on an edge (in updateSelectedLine)
