### ISSUE TITLE
Investigate a suitable logging standard/procedure

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13121]
What should be written to file, should .js or .php be used? 

When testing shortly I couldn't get javascript to create a textfile, however there should probably be someway.

I believe PHP has file writing support, though that may mean that dugga.js has to call a PHP-function (is it possible? is it easy?)

**Comment by b21kurar** [comment]
Been doing some log testing in the following branch:
g2-2023-v1-log_investigation

There is a console.log statement added to AJAXService in dugga.js that prints out the parameter values.

**Comment by b21kurar** [comment]
related to issue #13058

**Comment by a21jeaha** [comment]
> Been doing some log testing in the following branch: g2-2023-v1-log_investigation
> 
> There is a console.log statement added to AJAXService in dugga.js that prints out the parameter values. I will leave it up for anyone interested in testing it out

did you manage to make it print out anything at all ?

**Comment by b21hamwe** [comment]
Me (b21hamwe) and b21kurar has been discussing what would be a nice way to present log information.
b21kurar would like a separate file to present the log information instead inside of the dev. tools in the browser.

I presented a possibility, the idea would be too create a folder with separate files for the files that we want to 
test and log.

In the js files, we would use fetch functions with POST request to send the log data to the test/log files and present them with simple paragraph tags with HTML to send the data to the separate test files.
Note that we would use JSON.stringify to make the log data to strings to make them possible to POST.

I want to make i clear that i am not 100% sure that this is a possible way to go, but i don't think its impossible.
I have never personally used log.d data in this way, but i would like to test this possibility out.

**Comment by b21hamwe** [comment]
Another possibility would be, if i remember my facts right from the "databaskonstruktion" course, is that would be able to create a "view" inside the database, afterwards creating a "card" with HTML that would listen to event in js. 
When pressing the, HTML card button or href, a small window would present the log information instead of the previous idea.

The view functionality in the db would mean that only we who are "working" users on the lenansys system would be able to see this "card" and its button, and therefore, only we would be able to see the log information.

After discussing further with b21kurar, we agreed to continue and test the first idea with fetch functionality.

**Comment by a21jeaha** [comment]
right, i am conducting my own research regarding fetching and how it works, never worked in js before..

**Comment by b21kurar** [comment]
@b21hamwe has the know-how with js, we have discussed on-site a suitable solution. There should be an explanation incoming.

**Comment by b21kurar** [comment]
> > Been doing some log testing in the following branch: g2-2023-v1-log_investigation
> > There is a console.log statement added to AJAXService in dugga.js that prints out the parameter values. I will leave it up for anyone interested in testing it out
> 
> did you manage to make it print out anything at all ?

late reply, but I did get prints out on the console, should have been available in that branch before.

**Comment by a21jeaha** [comment]
might be a stupid question, but when you say "console"... where is that suppose to be?  
In the browser? because i never managed to get it to print something..

**Comment by b21hamwe** [comment]
After researching and discussing with b21kurar and c21alest, we came to the conclussion to scratch the idea of using console.log, but we keep the idea of using fetch API for retrieving test data to the future log.js/log.php file.

The idea is to have a function call in dugga.js file that uses this fetch API functionality to send data to the log file.

Instead of console.log, we will use an output with HTML to represent the data, for example tables, in the log file.
This HTML data can then later on be styled in a manner that would make the test data more readable for the developer.

And we discussed lightly of the use CSV, comma,separete,values. 
In order to save the data that we will be presenting.

**Comment by a21jeaha** [comment]
I'll continue my of on the fetch

**Comment by b21kurar** [comment]
The result of this issue should be a detailed explanation of how to implement this system. As such it should be such a thorough description so that anyone (not necessarily current assignees) should be able to implement this.

Issue #13192 will handle the actual implementation.

**Comment by b21hamwe** [comment]
Me (b21hamwe) and Jean Paul (a21jeaha) has been conducting further discussions, and our separate views of what we think is the idea to go forward since we both feel a little "lost" regarding our solutions for the future implementing for the testing.

**Comment by b21kurar** [comment]
> [Investigate a suitable logging standard_procedure issue#13121.txt](https://github.com/HGustavs/LenaSYS/files/11211047/Investigate.a.suitable.logging.standard_procedure.issue.13121.txt)
> 
> text file with the conclussion of what we come up with through our discussions.

It would be suitable to describe how the file will be created and how the data will be sent.
