### ISSUE TITLE
Changed backgroundcolor on fields in settings in course

### ISSUE THREAD

**Issue by b21sebgr** [HGustavs/LenaSYS#13146]
when editing settings the background color on the input fields are white in darkmode, this should be black, this is in "DuggaSys/sectioned.php"

![image](https://user-images.githubusercontent.com/102599253/230389630-48adfa2b-2172-4982-9191-152fe4830ad9.png)

![image](https://user-images.githubusercontent.com/102599253/230389385-4fc05d06-1393-4d04-b871-dd4101947776.png)

**Comment by b21leowa** [comment]
I found the source for this issue and the file is: LenaSYS/DuggaSys/sectioned.js. It has multiple places where backgroundColor is #fff. A solution could be to instead of #fff on each line, give it a variable like backgroundColor and it changes depending if the website is dark or light mode.

<img width="801" alt="image" src="https://user-images.githubusercontent.com/102594255/230965912-f97972e1-4e30-48e4-8332-beb1e51a48ae.png">

**Comment by b21leowa** [comment]
Saving for later: 


<img width="801" alt="image" src="https://user-images.githubusercontent.com/102594255/230966616-8e2b646f-814c-4585-9f05-1ea3842fa9da.png">
