### ISSUE TITLE
Markdown php vs js versions

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#13196]
Are we still using two different markdown versions, one in php and one in javascript?

In the case that we still have two implementations, do we have a testing case (preferably automated) to test if outputs of each are identical?

**Comment by b21geoyo** [comment]
I was under the impression that there was a file named "markdown.php" in the repository, but after searching through GitHub history, including commits and branches, as well as using Git log commands, it seems like the file doesn't exist, or at least not anymore. However, I did find another PHP file named "showdoc.php" that seems to be similar to the "markdown.js" file. I'm not entirely sure what the "showdoc.php" file is used for. I will look into it further.

**Comment by b21geoyo** [comment]
In the commit [Removed duplicate functions](https://github.com/HGustavs/LenaSYS/commit/101798f05cb4748d2b05338df8be8196c67467a0), I removed the unnecessary duplicate Markdown functions in "showdoc.php" since the file already had a script tag link to "markdown.js". I tested the file to ensure it worked as expected without the duplicate functions. As for the questions asked earlier, it appears we had two implementations of Markdown, one in PHP and one in JavaScript. However, with the removal of the duplicate functions and use of only "markdown.js", we now only have one implementation of Markdown, which eliminates the need for automated testing to verify output consistency between PHP and JS versions.

**Comment by c21sebar** [comment]
> Are we still using two different markdown versions, one in php and one in javascript?
There are some support or duplication of functions from markdown.js in showdoc.php but theese functions aren't exactly the same and seems to never be used. The new implemented GitHub style of markdown has been implemented only in markdown.js aswell.

> In the case that we still have two implementations, do we have a testing case (preferably automated) to test if outputs of each are identical?
No need for a testing case if only one of the two are used, right now it looks and seems like only markdown.js is used to display markdown files and never showdoc.php. So no need for an automated test to check if both php and javascript outputs the same.

Issue https://github.com/HGustavs/LenaSYS/issues/13326 will cleanup showdoc.php and keep only the javascript version.
