### ISSUE TITLE
Write tests for current services

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13207]
Tests for current services are needed to then ensure that the microservices fulfill the same functionality

**Comment by b21kurar** [comment]
This is connected to issue #13200 and issue #13208 as the logs and functional requirements will help and steer the relevant tests needed for each service

**Comment by a21jeaha** [comment]
There seems to be some unclarity on how the expected output for the tests are to be handled, because of that some test might already have been approved and merged in an unfinished state. I would suggest having a meting where we discus this. Preferably with the people most involved.
@d21erisu @c21alest
