### ISSUE TITLE
Dropdown for premade diagrams

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13204]
A dropdown should be made in the options menu that can hold premade diagrams. There is an export and import function already, so the dropdown should be able to hold diagram import files that can be added later on.
![dropdownforimport](https://user-images.githubusercontent.com/102599332/231421678-52a76957-0694-4ff2-a842-9b674a740b05.PNG)

**Comment by a21nibah** [comment]
currently there is no way to get the file from the server in order to be able to load the diagrams. I have been working on ajax requests to fix this. However it seems other groups seem to have a similar issue mainly group 2 I believe. do we want to consolidate and have a single function in a file somewhere that can just handle all requests? currently the way i have been implementing this is i fetch the json data from the server and then send it over to the client where a file object gets created, have not tested yet. Might be good though to consolidate how the file requests are made so that we do not get people trying to creating functions for each requests in separate files.

**Comment by b21oscpe** [comment]
We were planning on using local files to load in the diagrams. Do you think this is possible? We have made issues about this, for example #13213 . These files are later added to a directory within the project.

**Comment by c21adano** [comment]
Local files seem to work with fetch

**Comment by b21oscpe** [comment]
A later #13252 issue will adress adding these files to the dropdown, as the files did not exist at the time of this issues creation.

**Comment by a21aldsa** [comment]
As per issue #13264, I have created a function called loadMockupDiagram for fetching local JSON files and loading them up via loadDiagram

**Comment by a21nibah** [comment]
so if i am reading this right i should ignore loading files for now and just complete the dropdown so that we can add files to it later on?
i was working on a solution yesterday where you could just fetch files from the server but seems that is not needed now.

**Comment by a21nibah** [comment]
this is because load diagram requires a file object otherwise it will ask the user for a file and I thought we were storing all the files on the server which seems better to avoid any kind of tampering. you can then use a https request to fetch the json from the file and then  create a new file object where you add the json string to it.

**Comment by b21oscpe** [comment]
Would you like a new issue to store the files on the server and try this approach?

**Comment by a21nibah** [comment]
If there is a working solution already i do not see the need since my implementation does not seem to work and needs more testing. I am getting a http 500 error.

**Comment by a21aldsa** [comment]
See my pull request #13284 for a better understanding of what I implemented. If your method differs or you believe it is better; I would like to hear more about it.

**Comment by b21oscpe** [comment]
Ok, then if @a21aldsa's implementation works we will go with that and proceed

**Comment by a21nibah** [comment]
we were going for the same thing but my solution was more complecated than yourrs. Mine involves fetching the json string from the file via php, making a request from js via fetch and then load it. I did not know you could use fetch directly to get the files. 
I believe your solution  is the one we should stick with. 
should i wait for that issue to be resolved and then complete this issue?
