### ISSUE TITLE
Investigate current logging service

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13279]
There already exists a logging service, we want to know if it stores the data we require and if it works as intended.

The following comment may be a starting point:
https://github.com/HGustavs/LenaSYS/issues/13192#issuecomment-1508004848

**Comment by c21alest** [comment]
After investigation it seems like loglena db file logs same data as the other newly implemented logging solution #13058.
This loglena db file contains 6 tables, one of these is as below:
[![loglena.png](https://i.postimg.cc/GmzfWwSK/loglena.png)](https://postimg.cc/0zMZS3vK)
This contains information about services accessed by a user, data like this was not captured by #13058.

And table userHistory as shown below:
[![user-History.png](https://i.postimg.cc/g0F3Qk6C/user-History.png)](https://postimg.cc/bZgG2Pgg)
Contains almost the same as the JSON log from #13058 including all the apara array.

Conclusion is therefore that the logging solution #13058 do not need any further development after it now turned out that loglena exists. And no further development is needed for loglena as it works correctly and logs all data that we need.

**Comment by c21alest** [comment]
One potential fix could be that there is two log folders in LenaSYS. The one /log is used while /LenaSYS/log is an older folder that's not being used. This might create misunderstanding of which file to use.

**Comment by b21kurar** [comment]
> One potential fix might be that there is two log folders in LenaSYS. The one /log is used while /LenaSYS/log is an older folder that's not being used. This might create misunderstanding of which file to use.

Is it safe to remove that folder? Is there anything else that uses it?

**Comment by b21kurar** [comment]
Data we require is the data that can be used to confirm the service usage. This could be the parameters sent to it, and the values it presents. It seems to me that this log will help with identifying which services are called on which user actions, and also if intermediate services are called.

This should help with mapping out how microservices should act to replicate the service.

**Comment by b21kurar** [comment]
Before closing this issue we need to know if the logging is active and functioning, and if not how do we fix it?

**Comment by c21alest** [comment]
> > One potential fix might be that there is two log folders in LenaSYS. The one /log is used while /LenaSYS/log is an older folder that's not being used. This might create misunderstanding of which file to use.
> 
> Is it safe to remove that folder? Is there anything else that uses it?

The file in LenaSYS/log contains data from 2021 and its only a few entries. So I guess nothing is writing to this file anymore and the content inside (shown below) seems to include only some test data.
[![oldlenalog.png](https://i.postimg.cc/0Qh3G17v/oldlenalog.png)](https://postimg.cc/mzN8Rqdp)

I dont know who should decide if It safe be deleted or not. I would take a while to look trough all files and check that no file uses this data anymore.

**Comment by c21alest** [comment]
> Before closing this issue we need to know if the logging is active and functioning, and if not how do we fix it?

Yes it looks to be functioning correctly and it is active.

**Comment by c21alest** [comment]
Can this be closed now @b21kurar @a19hakja?
