### ISSUE TITLE
research how we can develop the Include button

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13323]
The include button currently lacks any functionality. The supposed purpose for the button is "To use less than, To use less than type & #60;"EX:<&#60;include>>" this seems to suggest that it was originally made write special characters. Is this a valid use of a button, is there som other derection it could be developed in?
![includebutton](https://user-images.githubusercontent.com/102599332/232465151-b9b03d03-b945-4fc6-b5ac-659f5d8ec34e.PNG)

**Comment by b21willu** [comment]
The buttons supposed function would be necessary, cause right now the input for the line labels doesnt support the characters "<" and ">" if not written in code like "&#60". Which could be needed when modelling where <<included>> relationships can happen. I would keep the button but move it to the options panel for the lines and then add a function for it that writes out <<Include>> when clicked. The function can use the codes for the special characters "&#62" for greater-than and "&#60" for less-than and send these values directly to the input label when the button is clicked, so that the user doesnt need to know the codes to write out these special characters but when using the button the user can get the <<Include>> immedietly as a label to the choosen line.

**Comment by b21oscpe** [comment]
I believe we dont have any support for modelling languages that include "<< include >>" yet so this functionality seems redundant/deprecated.

If we were to implement use case modelling your suggested solution would work fine.

Good job
