### ISSUE TITLE
Research what coverage algorithm will be the easiest to implement for test-case generation

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13339]
https://www.sciencedirect.com/science/article/pii/S1319157818311078

(Issue specifications have been discussed in voice call)

**Comment by a21nibah** [comment]
I Believe all transition pair algorithm would be the easiest one to implement because it would require less code. This is because the Round Trip Path (RTP) algorithm requires you to keep track of the sequence of transitions as well as visited nodes. The ATP algorithm only requires you to keep a counter for how many nodes have been covered by the traversals and then compare it to how many nodes there are in the diagram.
Both are straight forward though so it is a matter of which one takes the shortest amount of time to implement which I believe would be the ATP algorithm.

https://www.sciencedirect.com/science/article/pii/S1319157818311078

(Issue specifications have been discussed in voice call)

**Comment by b21oscpe** [comment]
We will go with that for our first implementation, good job
