### ISSUE TITLE
Write tests for services in contributionservice

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13394]
Go through the code, focusing on services, and write tests that traverses all paths in the code.
A step by step text file containing what actions to perform and evaluate the tests.

You should do thorough research of the logs, testing out different actions and what values are sent, if logging in or not changes behaviour. The models and functional requirements may also be applicable.

Follow the template in the README under `backend-models/service-tests/README.md`

See the process of work done in issue #13343!!!

Ignore "Retrieve Information"

**Comment by c21axepe** [comment]
I have created a branch (g2-2023-v3-issue#13394) and added a txt file with 2 tests. I tried to do this issue myself but i find it really hard to work with since there is almost no documentation about how the code works. But i have started the documentation on countributionservice-test in LenaSYS/backend-model/service-test

**Comment by a19hakja** [comment]
While I get that @b21kurar said that it was okay to remove yourself from this assignment, don't forget that you can ask anyone for help at any time (except after 17). We will distribute the workload on this one since it's not a fun file to look at on your own. But sooner or later, this is an issue that should be completed.

**Comment by d21erisu** [comment]
Did @c21axepe find anything worth passing on?

**Comment by a21ponkr** [comment]
Can't seem to find branch g2-2023-v3-issue#13394

**Comment by a21ponkr** [comment]
Found that the code says include_once "../Shared/databse.php"; which has a typo, it should be "database", there is no file called databse.php only database.php in Shared folder.

**Comment by d21erisu** [comment]
I will place JP instead. Since he is familiar with this kind of task.

**Comment by a21jeaha** [comment]
@d21erisu I am having a hard time finding ways to test this file. it seems like it is used to track users contribution on github.
The first problem comes here 
![image](https://user-images.githubusercontent.com/102600391/236389517-062df62b-42ef-4c59-95b2-521a30cc54e1.png)
From what i could gather the pdo is changed depending on what current user is logged in. I cannot finnd any pre-made gituser for testing in the LenaSYS wiki, nor can i find it in the database, the table git_user is empty. 
I tried creating a new user trough a manual insert into the table 
![image](https://user-images.githubusercontent.com/102600391/236392207-b70453a0-5b1b-4e01-a109-f8414531d0e4.png)
but i was unable to log in using that account name.  
The code does indicate that you should be able to be logged in as a super user and be able to access the methods but I am only greeted by a black page 
![image](https://user-images.githubusercontent.com/102600391/236392398-07333f12-8d62-4fd4-ada9-9566e824ea18.png)
![image](https://user-images.githubusercontent.com/102600391/236392898-143d4f12-889f-4db7-be1f-451de843fe26.png)
same applies to a student user 
![image](https://user-images.githubusercontent.com/102600391/236393086-52863917-a157-47ad-9525-e9a106049505.png)

A have a suspicion that other parts of LenaSYS are needed/used I'll conduct a bit more research on this and return with the results.

**Comment by a21jeaha** [comment]
contribution.php ends with this code 
![image](https://user-images.githubusercontent.com/102600391/236394942-f6369567-9ac0-4bbb-873d-2445446035dc.png)
which is in line with what happens if a user is not logged in as a student.
This indicates that the file contribution_loginbox.php is involved in, the function being called in contribution_loginbox.js accesses the function contribution_addEventListeners(); in the same file.
![image](https://user-images.githubusercontent.com/102600391/236395716-a366b34c-2d5f-442d-972b-7e72265810cb.png)
The contents of this function seem to indicate that a new git user could be created trough contribution_loginbox.php. 
![image](https://user-images.githubusercontent.com/102600391/236396000-7fcbf759-021b-434f-a343-e613adc151b4.png)
thou trough my test nothing happens when you click on login.

If i recall correctly, one of the other groups were working on something related to github. Could this functionality be related to that? If that is the case, that would mean that this file is in an incomplete state.
I would suggest that @d21erisu contacts the group leaders of the other groups and see if this is the case, before wasting more time on this research.

**Comment by a21jeaha** [comment]
found somethings that might be connected to this issue in the LenaSYS wiki
![image](https://user-images.githubusercontent.com/102600391/236411360-3d0455d1-85d8-4592-956b-1618d7665f70.png)

**Comment by a21jeaha** [comment]
Well, that went downhill pretty fast. 
![image](https://user-images.githubusercontent.com/102600391/236745408-604daa4b-7fbe-46e7-a697-5222c36723cd.png)
@d21erisu could you check with the other group leaders to see if anyone has access to this file?

**Comment by c21alest** [comment]
After discussion with Henrik this service is not fully functional and developed

**Comment by b21kurar** [comment]
> After discussion with Henrik this service is not fully functional and developed

Then this should be closed as not planned right?
