### ISSUE TITLE
Write tests for contribution_loginbox_service

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13395]
Go through the code, focusing on services, and write tests that traverses all paths in the code.
A step by step text file containing what actions to perform and evaluate the tests.

You should do thorough research of the logs, testing out different actions and what values are sent, if logging in or not changes behaviour. The models and functional requirements may also be applicable.

Follow the template in the README under `backend-models/service-tests/README.md`

See the process of work done in issue #13343!!!

Ignore "Retrieve Information"

**Comment by b21hamwe** [comment]
Been spending yesterday's hours and todays hours trying to understand what this file does.
When a person logs in at LenaSYS, the data that you return as a user when trying to log in gets send to the database via this file. 
But it's not responsible for the login itself, it just sends login data to the database.
And it seems like that the file also checks and sends information about the same users github information, in order to see what the person has "contributed" on github and thats why it sends data about the user information AND github user information, question is?
Is this file dead? Does it get used ? Since I can't find, for the moment at least, anywhere this data gets used and the database table is empty, there's no stored data in the database.  

Richard "I think this file is made to torture people".... And i agree....

**Comment by b21kurar** [comment]
It seems to be connected to a database that our separate development installations don't have. When looking at the table 
![image](https://user-images.githubusercontent.com/129070844/233332517-6b391100-8955-44e7-b774-388aed639b81.png)

When looking at the file its seems to store Github contributions to LenaSYS to database `BGHdata_2021_05.db` 
As for when it is called, no idea. Have you found any calls to this service on the log? Maybe check the production database if possible?

**Comment by b21hamwe** [comment]
Finally managed to open and look inside the database(BGHdata db file) thats supposed to store all the Github data that's supposed to be send, when opening the database and looking at the tables, i almost got an allergic reaction from all the dust and spider web, the database is just as empty as my ~brain cells~...... fridge.

**Comment by b21hamwe** [comment]
After discussing with our issue master, b21kurar, we descided to stop this issue since the files doesnt seem to be finished.
