### ISSUE TITLE
Transition log.php to a microservice architecture

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13434]
This is a service in the system, it should follow the same standard, but still be written in a microservice architecture.

**Comment by b21kurar** [comment]
description of current layout in table: https://github.com/HGustavs/LenaSYS/issues/13044#issue-1655120672

**Comment by a21jeaha** [comment]
should log.php be moved to DuggaSys, or should i just created the service in Shared, were it currently is ?

**Comment by a21jeaha** [comment]
as of now im copying over code from the files associated with the duggaed service. this is done to get a grasp of how the tree part separation is suppose to work.

**Comment by a21jeaha** [comment]
I'm researching where, the echoed "json_encode($array);" gets sent 
![image](https://user-images.githubusercontent.com/102600391/234209334-7af172de-3f93-4a26-b8c5-8064a294c53a.png)
![image](https://user-images.githubusercontent.com/102600391/234209381-65bfe126-6f08-4c7f-a773-3b553db0bf78.png)

**Comment by a21jeaha** [comment]
Work is progressive slowly, but there is progress non the less.

As of right now there are tree separate files. log.php, log.js and logservices.php.
The idea is that log.php will initiate the process. It will only contain a drop-down with the db tables. The code bellow establishes a connection to the file log.js and generates the drop-down. 
![image](https://user-images.githubusercontent.com/102600391/235344416-15acf55a-3d7b-4cbc-89f4-745d6b472d62.png)
the function setup(), is located in log.js.
![image](https://user-images.githubusercontent.com/102600391/235344441-ddc0c693-c290-40d8-85f0-56df3c67caa3.png)
![image](https://user-images.githubusercontent.com/102600391/235344458-5259a2f1-00ab-4006-a79c-3ee79f0e4dfd.png)

When a chose of table is made a form is sent to log.php (same file), and the variable $tableName collects the information and placing it in a hidden inputtype, that can be accessed in log.js. Note that the variable gets more information then just the table name!

to be able to access only the wanted data (table name), i had to specify that i wanted the elements value.
![image](https://user-images.githubusercontent.com/102600391/235344792-a92d1fad-81eb-462b-bb5f-848449eb3efc.png)
![image](https://user-images.githubusercontent.com/102600391/235344810-32a3268d-6ced-4557-b20b-d07b30808887.png)

The idea now, is that a request to the AJAXservice() function containing the table name should be sent from log.js, which in turn sends that information to logservice.log

A new if else statement for log was created, though im not sure if it functions as intended yet. 
![image](https://user-images.githubusercontent.com/102600391/235344911-a48cace8-c984-483b-9b06-a5d8d354b67b.png)

the log.js file should not need to include the dugga.js file (where the AJAXservice function is located), because log.php has included both these files.

![image](https://user-images.githubusercontent.com/102600391/235345140-124736cc-6787-4e56-90cb-6c4ad0e6bce3.png)

**Comment by a21jeaha** [comment]
@d21erisu 

Creating a "service" which follow the standard three-part file combination out of the displaying of log data, does not seem too be feasible. 
My understanding of how the services are constructed have after research and trying to implement said service, given me an understanding of what each file actually does.

The file sticking out in this case is the service.php file. It is suppose to make changes (such as input, delete and update) on the database conducted in the background. But no such changes are made in the presentation of the contents of the log database.
For that reasoning that file becomes meaningless, that in turn means that we only need two files, which is what we have now.

Aside from not following the naming convention, the separate files logSearch.js and log.php already follow this standard.
![image](https://user-images.githubusercontent.com/102600391/235621442-fa442f94-1709-49a7-a9c1-b17ca91235e2.png)
where logSearch.js conducts the dynamic functionality. and log.php display the information.

The issue is not wasted though, it has given an understanding of how the information is sent between the three files, which will be useful for future creation of the micro services.

**Comment by d21erisu** [comment]
@c21alest

**Comment by a21jeaha** [comment]
after a short meting we decided that the files should be left as they originally was, only the name of logSearch.js need to change name to log.js.

A documentation describing how communication is performed between the three files (.php .js and service.php) is to be created as well. this will help later when we create the smaller services.

**Comment by a21jeaha** [comment]
I have changed the name of the file so that it follows the standard. (logSearch.js is now named log.js).
And added a document placed in here.
/shared/service documentation/Communication used in the old style service files.pdf

I don't know what is to be reviewed here though.

**Comment by c21alest** [comment]
Nice work! I agree that there aren't anything special to review. Make a PR with the new naming and documentation then I can be the reviewer and approve this.

**Comment by a21jeaha** [comment]
@c21alest this issue is still open
