### ISSUE TITLE
Box-selecting preloaded diagrams does not seem to work

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13440]
![boxerror](https://user-images.githubusercontent.com/102578165/233313368-51828fdf-439c-4551-a602-b11ccb0407fb.png)

This is assumed to be caused by faulty JSON-files (Is it generation of JSON-files that caused this?)

**Comment by a21aldsa** [comment]
After doing some testing etc I have concluded that this has absolutely nothing to do with preloaded diagrams, json, etc.

This is an issue of some lines breaking when selected with the selection tool. Specifically lines of the type UML with any of these icons: 0-1, 1, 1! and 1-M. But the issue is bigger than this:

Most lines of the type UML, and even SD, cannot be marked with the selection tool. This is, in and of itself, an issue; they should work like ER, as in, become selected when the selection tool is used.

When a UML line with an aforementioned icon is selected with the selection tool, everything breaks since lineContext is undefined, it shouldn't be though. This is another issue.

I believe these are **two separate issues**, one is that all lines cannot be marked with the selecion tool,
and the other is that the UML lines that have one of the aforementioned icons that _can_ be selected break something. Note that even these lines don't seem to get selected properly but at least the site reacts in some way when the selection tool is used on them.
