### ISSUE TITLE
Lines should be selectable with box select

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13470]
Related: #13440
"Most lines of the type UML, and even SD, cannot be marked with the selection tool."
"they should work like ER, as in, become selected when the selection tool is used."

**Comment by a21aldsa** [comment]
My findings are that: 

It seems this issue is in how the box selction tool works. For example, it uses functions like intersectsBox that assumes lines have a x1, x2, y1, y2 attribute. Which is simply not the case for any UML or SD line. Marking any line with the box selection tool only works for ER.

I am not sure what the way forward is here, maybe write/rewrite functions for box select? Or add these attributes into all the lines?
