### ISSUE TITLE
Research the next diagram type

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13509]
Now when state diagram are coming along we want to find the next diagram type to focus on.

Henrik wants the next diagram to be a step between state diagrams and class diagrams. So research and find a new diagram type that can a middle step.

Report findings and why the diagram fits as a middle step.

**Comment by b21oscpe** [comment]
As far as my understanding goes it could be complimentary diagram types to state and class diagrams or diagram types that build on state and/or class. What's important is that the new diagram is somehow related to the previously mentioned diagrams.

**Comment by a21nibah** [comment]
We have 2 candidates. I personally Think the second makes sence to focus on.
An Object Diagram is a structural diagram that represents a snapshot of the objects in a system at a particular moment in time, showing the objects and their relationships. It is similar to a class diagram in that it shows the objects and their attributes and relationships, but it is more concrete and shows actual instances of objects rather than just classes.
Object diagrams can be useful for understanding complex systems by showing the relationships between objects and how they interact at a specific moment in time. They can also be used for testing and debugging by providing a visual representation of the current state of the system.
In summary, an object diagram can be seen as a bridge between the more abstract class diagram and the more dynamic state diagram, providing a more concrete view of the system than the former, but a less detailed and more static view than the latter.
A Sequence Diagram is a behavioral diagram that shows how objects in a system interact with each other over time. It shows the sequence of messages exchanged between objects and the order in which they occur.
Like an Object Diagram, a Sequence Diagram shows actual instances of objects, but it focuses on their behavior and interactions rather than their static structure. It is particularly useful for modeling complex interactions between objects in a system and for designing and testing software systems.

**Comment by c21adano** [comment]
The Sequence Diagram seems like a good choice, then we can focus on the Object diagram later if the Sequence diagram nears completion.
