### ISSUE TITLE
Create testing API

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13532]
Implement the functionality for basic testing.

https://github.com/HGustavs/LenaSYS/issues/13062#issuecomment-1520057987

I believe for our current testing needs we might only need the following functionality:

* `assert `- make sure that two values are equal, we will only test with JSON format for now. 
* `login(user, pwd)` - login as a user, is needed for pre-requisites of tests. Some functionality is only allowed by certain users
* `send(array, service)`- send values via POST to a service
* `readOutput()`- read the HTTP JSON response

**Comment by b21kurar** [comment]
To be clear, for `readOutput()` we want these values to be extracted:
![image](https://user-images.githubusercontent.com/129070844/234219955-b993ace8-4e9f-43b6-b124-b31c6cfb1275.png)

I am not sure how this works, but all services end with a `echo json_encode($array)` that are then read by the browser in the response tab, do you know if there is any way to access this?
![image](https://user-images.githubusercontent.com/129070844/234220496-22d15b3b-8fe8-48a8-8fe6-3206536c9e54.png)

Otherwise it may be better to update the logging database and passing this JSON data to it, letting `readOutput` accessing it from there instead.

**Comment by c21alest** [comment]
After some research regarding how the API will communicate the conclusion is that further actions are needed to proceed, that I can't approve of my own. My understanding is that this API is a communication between two PHP files, the service to test and the test PHP file. There are two ways of communicating between the PHP files with a REST API. The first one that doesn't require any modules are to stream context to the test PHP file and then use file_get_contents to read the response. But this is not a great way as it prints all data from the PHP test files including comments made in the code. The other way is to use php-curl, this gives the functionality of a standard HTTP request call. But php-curl is not installed on the server. So my question to you @b21kurar is, will it be possible to install php-curl?

**Comment by c21alest** [comment]
The API now works to make an assert equal test but I'm not sure what the `login(user, pwd)` should do. Am I suppose to implement a way that the test logs in to LenaSYS with account and do something, if so what? Do you know the answer for this @b21kurar?

**Comment by b21kurar** [comment]
Example:
```
// logging in
login("user", "pwd");

// prepare and send values to service
 $arrWithValues = // add an array of values
send($arrWithValues, "someservice.php");

$expectedOut = "{/*add many values*/}";
$actualOut = readOutput();

assert($expectedOut, $actualOut);

```

**Comment by c21alest** [comment]
The test API is almost finished but I have encountered a problem. The test API file can be found here:
https://github.com/HGustavs/LenaSYS/blob/g2-2023-v4-issue-%2313532/Shared/test.php
And it is built upon three different tests. The first one is simple and makes an assert test. The second one tries to login to LenaSys with the provided credentials from the file calling the test. Here is an example of someone calling the test API:
https://github.com/HGustavs/LenaSYS/blob/g2-2023-v4-issue-%2313532/Shared/example-of-test.php

The third test, that calls a service is almost working. It can gather all information that the service allows while not logged in. So the problem is that because it won't remember that it is logged in no function in a service that requires login won't work. Test 2 which is handling the login process is set to true in the third argument which means that it should set cookies so that the user can be loged in with the cookie values on checkLogin(). But this is not working and the checkLogin() uses some SESSION variables which I can't change from the test.php file.

So the workaround is to change the service file and make checkLogin() always be true. Im not fully sure how to solve this but I guess some changes is needed to the checkLogin function in session.php.

**Comment by c21alest** [comment]
Would it be okay to change checkLogin() in session.php to make this work?

**Comment by b21kurar** [comment]
That function is used in **a lot** of places. That would require that the modifications do not alter the functionality and also doesn't make it worse. 

So the answer is yes, but I would make sure many times if there aren't any other ways.

**Comment by c21alest** [comment]
Added another else if statement to session.php which shouldn't destroy or make anything worse just add functionality and allow checkLogin() test with POST, earlier only SESSION and Cookies.

Added this code:
`// Test API uses POST
      else if(failedLoginCount($_SERVER['REMOTE_ADDR']) < 100 && array_key_exists('username', $_POST) && array_key_exists('password', $_POST)) {
        return login($_POST['username'], $_POST['password'], false);
      }`

**Comment by c21alest** [comment]
After some discussion in seminar there are further implementation needed:

* The test API should have an input which tells the API what parameters in the JSON output from each service that should be displayed

**Comment by b21kurar** [comment]
An idea regarding the seminar: 
If we are to declare which labels of the JSON we are supposed to ignore, could this be a function in the API? We send an array of labels along with the response JSON, where the API can then parse and return a JSON without the labels in the "ignore" parameter?

**Comment by c21alest** [comment]
![Test API](https://user-images.githubusercontent.com/102578850/236472729-0be9cc00-8177-4740-9d79-a30715c9d687.png)

**Comment by c21alest** [comment]
![Test API](https://user-images.githubusercontent.com/102578850/236473515-79d4da2a-9bb6-472f-9ab4-c06b3f7ce621.png)
