### ISSUE TITLE
Fix rotation for triangle to align with draw-line.

### ISSUE THREAD

**Issue by b21phiro** [HGustavs/LenaSYS#13689]
![bild](https://user-images.githubusercontent.com/45258330/235898757-20d289b2-074e-4e8d-8a7c-ea5def9fc82b.png)

The rotation of the triangle for lines are not aligned correctly.

**Comment by d21matbo** [comment]
I've with some help from @b21eriho been able to figure out the mathmatics involved in solving this issue. However there exists a problem that is currently blocking the implementation of the solution.

The StateDiagram lines have an offset that places the end of the line inside element which is used to remove the gap between the end of the line and the element. This solution was implemented before the addition of "straight" lines, and as such didnt have any problems as the lines would always enter on a prefectly square angle (which lines up with the arrow). 
Currently the offset is only a problem for the "vertical" lines as can be seen in the image below, where the line should end on the tip of the arrow (just like how the "horizontal" line is placed).

Continuing on this implementation would be somewhat counterproductive as the offsets need to be resolved first. This is because how the lines connect to the elements greatly affects how the implement the solution to this issue.

![image](https://user-images.githubusercontent.com/102599161/236460369-b487cda7-287b-4343-8683-6c09625be826.png)
