### ISSUE TITLE
Toggle load button as well as dropdown

### ISSUE THREAD

**Issue by b21eriho** [HGustavs/LenaSYS#13680]
When example diagrams are to be loaded the dropdown is toggled but the "load"-button is always there, make it be toggled along with the dropdown. 
![image](https://user-images.githubusercontent.com/129077727/235888713-1cfbb9fd-bda8-43df-a8da-efbd852d16f4.png)

**Comment by b21oscpe** [comment]
The issue is fixed and I've taken some freedom in styling the button so that it follows the general design decisions made for buttons of similar kind within the options-pane. I was wondering if I am allowed to extend my issue to make the "Null" option clean the board? And perhaps also rename it from "Null"...

![964e174d1800b0d3d8f07e8053e44027](https://user-images.githubusercontent.com/102578165/235932552-c6ebd9bc-80b2-43b7-a127-da43ec148a13.png)
