### ISSUE TITLE
We should be able to rename examples in the course view at will.

### ISSUE THREAD

**Issue by a21olljo** [HGustavs/LenaSYS#13933]
From #13875 
Examples should be able to be renamed in LenaSYS without disturbing its connection to the correct repo. So if the refresh button is pressed the system fetches the correct files.

**Comment by a21henhe** [comment]
RIght now, the github metadata-database uses the name of the downloaded files as primary keys when storing their data, meaning that there could be a conflict when eventually changing the name in LenaSys. One solution would be to create a column called id and use that as primary key in order to free up the ability to change the filename. Another solution, if it's decided to keep fileName as primary key, would be to add another column called for example "lenasysFileName" which could be changed without problem and could be the name that is actually showcased in LenaSys. @a21olljo

**Comment by a21olljo** [comment]
The solution that interferes the least with the legacy system is the best, so changing the function of the filename (the first solution) would cause issues with the already existing tables in LenaSYS that misses id:s. So if the second one could be done without disturbing the existing system, that would be best.

**Comment by b21leowa** [comment]
We need to create 2 new issues. 
One issue is to change the backend of files and add like LenaSysName or add githubFileName which will refer to the files from github. GithubFileName will be PK and  not affect the legacy system because the legacy system will still use the old naming. 

Second issue is to add an input field on LenaSys frontend so the user can change the name of the file.
