### ISSUE TITLE
Redesign of refresh button

### ISSUE THREAD

**Issue by a21olljo** [HGustavs/LenaSYS#13959]
After asking some other groups, if the refresh button where descriptive in its design. It was concluded that it wasn't. 
A redesign that more clearly shows what the button does, would be helpful. The new design should more clearly show what the button does from the users point of view, which is to download updates from GitHub.

**Comment by c21rebja** [comment]
Made a few examples for what the new refresh-button could look like. Asked around a little and the consensus seems to be that 7 or 8 (or a combination of both) is the way to go. It is both because it's more generic (if repos on for example gitlab that will be used on lenasys in the future) and in case the github octocat is protected by copyright.

![github icon examples](https://github.com/HGustavs/LenaSYS/assets/102578746/732ec61a-1d86-40a9-88ed-a8190c60a186)

**Comment by c21rebja** [comment]
Here are a few more versions of number 8.
![image](https://github.com/HGustavs/LenaSYS/assets/102578746/1162a190-864f-4222-a7ee-1b9c2650273a)

**Comment by c21rebja** [comment]
Here are a few more versions of number 8.
![icon_ex_2](https://github.com/HGustavs/LenaSYS/assets/102578746/c260e3b9-e4d7-40bc-8ff4-6334c5d5fd26)

**Comment by c21rebja** [comment]
Do you have any opinions on which would be best? @HGustavs 
Not just the versions of number 8, but out of all of them. :)

They are for the button in the navbar that is currently a refresh. 
![image](https://github.com/HGustavs/LenaSYS/assets/102578746/a3325758-a0c7-4581-a2a3-20ab9714fb1d)

**Comment by HGustavs** [comment]
Perhaps something generic such as 8a or 8d is the best if we for example also allow support for e.g. gitlab also.

**Comment by c21rebja** [comment]
Based on the feedback, here are mockups for how it would look on LenaSYS with these icons implemented. 
Icon 8:
![8](https://github.com/HGustavs/LenaSYS/assets/102578746/f5d9df2b-bc32-4058-a4ed-32426ad1a808)

Icon 8a:
![8a](https://github.com/HGustavs/LenaSYS/assets/102578746/71cf1d08-35cc-4657-b9ef-abb5da656703)

Icon 8d:
![8d](https://github.com/HGustavs/LenaSYS/assets/102578746/25ebb17c-798d-42d7-8a76-5f7e9e1c9198)
