### ISSUE TITLE
Research: Find out why save button does not work

### ISSUE THREAD

**Issue by b21phiro** [HGustavs/LenaSYS#14003]
## Description
From previous issue: https://github.com/HGustavs/LenaSYS/issues/13975

The save button shown in figure 1 does not work and throws an error. It should be able to save assignments but currently is not.

Figure 1.
![bild](https://github.com/HGustavs/LenaSYS/assets/45258330/b33e59aa-516b-4588-8f20-9a2daa12251d)

**Comment by b21eriho** [comment]
The task is to figure out what if any back-end functionality is behind the button and why it is disabled

**Comment by d21matbo** [comment]
The button is created in `showDugga.php` with the id `saveDuggaButton`. The button is created with the class `btn-disable` which is why it is disabled.

Looking at different duggas and their buttons are also disabled, however once you press on anything the buttons are enabled. It appears that this is managed by the function `canSaveController()` which exists in multiple places. Generally it exists in `dugga.js`, but for this issue it is overridden in `diagram_dugga.js`. 

The last piece of the puzzle is the function `setup()` which is implemented in every dugga file, but it is commented out in `diagram_dugga.js` This function binds the `canSaveController()` to an event listener, so the missing `setup()` function is the reason as to why the save button can not be used.

Note that:
1. This function was commented out to “solve” an issue and by uncommenting it, this issue will return.
2. This does not solve the error which occurs when the the diagram is saved, this occurs somewhere after the call to `uploadFile()` in `diagram_dugga.js`

**Comment by d21matbo** [comment]
The error mentioned above happens when the save button is pressed (after it has been enabled), and it seems to happen because of the structure of the filesystem running on the server. When the error occurs the diagram is already saved in submissions and the error is related to the generation of the link used to retrieve the saved diagram/”upload to canvas”.

The current structure uses `SERVER/LenaSYS/sh/` etc however the save button uses a structure like `SERVER/sh/` which then throws the error because this filepath does not exist, and thus the file is not found.

**Comment by d21matbo** [comment]
Additionally enabling the save button (by uncommenting the setup function) the instructions and the general information changes from the hardcoded text to the contetns found in the file `HTML_Ex1.txt`. 
![image](https://github.com/HGustavs/LenaSYS/assets/102599161/e6ada0dd-4cad-4991-9be7-d2411ef37c84)
This connection is found in the `param` column from table `variant` in the mysql database.

**Comment by b22jonan** [comment]
`showDugga.php` no longer uses `diagram_dugga.js`, resulting in the save button trying to call a function `uploadFile()` which  doesnt exist in `diagram.js`. 
reAdding `diagram_dugga.js` makes it worse, if viewing e.g. 3D Dugga, and filling in the infobox and clicking "Lägg till" causes an error 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'contentWindow')
    at canSaveController (diagram_dugga.js:168:23)
    at duggaChange (dugga.js:937:2)
    at Object.onClick (dugga.js:2596:3)
    at newVertex (3d-dugga.js:420:16)
    at HTMLButtonElement.onclick (showDugga.php?did=13&courseid=1894&coursename=Demo-Course&coursevers=52432&moment=3002&segment=3001&highscoremode=1&comment=null&deadline=2020-06-30%2000:00:00&cid=1894:308:136)
```
and clicking save causes error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'contentWindow')
    at getDiagramData (diagram_dugga.js:42:19)
    at uploadFile (diagram_dugga.js:59:24)
    at HTMLInputElement.onclick (showDugga.php?did=13&courseid=1894&coursename=Demo-Course&coursevers=52432&moment=3002&segment=3001&highscoremode=1&comment=null&deadline=2020-06-30%2000:00:00&cid=1894:383:228)
```
So the Save button doesnt work at the moment simply because the button doesnt use the correct function for saving a dugga. It should either get a new function to save or adapt to use another existing function

**Comment by b22jonan** [comment]
> Additionally enabling the save button (by uncommenting the setup function) the instructions and the general information changes from the hardcoded text to the contetns found in the file `HTML_Ex1.txt`. ![image](https://private-user-images.githubusercontent.com/102599161/238917136-e6ada0dd-4cad-4991-9be7-d2411ef37c84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjYwNTcsIm5iZiI6MTcxMjA2NTc1NywicGF0aCI6Ii8xMDI1OTkxNjEvMjM4OTE3MTM2LWU2YWRhMGRkLTRjYWQtNDk5MS05YmU3LWQyNDExZWYzN2M4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQxMzQ5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGE5YTllYWJkYTUxOTEyN2IxMzUxNmMwNGYwZmE5YjQ3MDNiZDhkZjUyMzUxMDY5MmIxOGI3MWI3MGM4MjFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gik-4P3IrtJuCVKXwnb3WJCDVqCs-_XzVyL-mX1l5Fs) This connection is found in the `param` column from table `variant` in the mysql database.


this seems to no longer happen from what i've tested. Looking a little closer at how `showDugga.php` tries to save it, the problem probably has something to do with how filerecieve.php handles saving the file. the location where the file is saved should be moved to `/LenaSYS/` instead of just `/`. just editing on line 169:
`$submissionpath.="/".$hash;` to `$submissionpath.="/LenaSYS/".$hash;` did not fix it as it still created a folder under `/` but it didnt save the file there. infact it wasnt saved anywhere. more research needed to find out if specifying the save location is possible somehow.

**Comment by b22jonan** [comment]
in `filereceive_dugga.php` on line 119-120
```
		$currcvd=getcwd();
		$submissionpath=$currcvd."/../../submissions";
```
the $submissionpath is made incorrectly, it shouldnt back out twice since getcwd is `htdocs\LenaSYS\DuggaSys`, it backs out twice and ends up in root.

**Comment by b22jonan** [comment]
looking at file history i found that `setup()` was commented out to fix issue [13080 ](https://github.com/HGustavs/LenaSYS/issues/13080)
not sure if uncommenting will bring it back, if so another fix for that issue is needed.
