### ISSUE TITLE
Unable to group-select sequence objects

### ISSUE THREAD

**Issue by b21phiro** [HGustavs/LenaSYS#14026]
## Description
Right now the user can't group selecect sequence element types. 

Figure 1.
![bild](https://github.com/HGustavs/LenaSYS/assets/45258330/3abf7b8a-870d-44a7-963a-1a3331c97736)

## Job
Try to solve this issue, so you are able to group select these elements.

**Comment by b21matfi** [comment]
I have found that you can select the sequence objects, but when you change the size of the object that's when it is not possible to group select them 
![image](https://github.com/HGustavs/LenaSYS/assets/102650424/59b62e49-a742-4466-8c66-830b01ec4ce5)

**Comment by b21matfi** [comment]
it is only vertically aswell

**Comment by b21matfi** [comment]
![image](https://github.com/HGustavs/LenaSYS/assets/102650424/9832df34-5bbb-4cf4-b84c-9cb4fa73f2d7)

the half circle is life line

**Comment by b21matfi** [comment]
This issue is much bigger then just group selecting, this is about resizing all together, i found out that you are able to group select all the elements does not matter if it is sequence or any other element. The first issue is that resizing vertically resizes both up and down for height, does not matter if you pull the lower node or upper node. Second issue is that this is not visuall so you can not see if the height changed uppwards or downwards (depending on the node pulled) you can still select the elements but you have to start from a much heigher distance because the start of the elements is much higer or lower. Third issue i came accross when using (snap to grid) that it snaps wrong which can be something with the ghost behind it. This problem is only with resizing vertically not height.

**Comment by b21matfi** [comment]
This issue should also be renamed because you are able to group the sequence objects but not correctly because they are offset like all the elements
