### ISSUE TITLE
Allow multiple saves in localstorage

### ISSUE THREAD

**Issue by b21phiro** [HGustavs/LenaSYS#14042]
## Description
Right now we save JSON in localstorage using the key ``CurrentlyActiveDiagram``. However only one save can be done each time.

## Job
Make so (for example an array) of JSON-object that we can save.

## Suggestion
Maybe also make a limit of how many saves can be done, so we don't store too much,

**Comment by a21nibah** [comment]
do we only want to save diagrams to local storage that is currently being worked on or so we rather make it more flexible so that any diagram can be saved? this is important to know because there are diferent aproaches depending on when diagrams should be saved. If we want multiple diagrams to be saved, if we only want to save the diagram that a user is currently working on and allowing multiple of those saves I would suggest we use an aproach where we modify the keys so that each key is unique with a date and timestamp. But if the goal here is to allow saves at any time using any key i can make it so the function accepts parameters, that would also not break the rest of the code. But the user would then have to make sure the keys are unique.

**Comment by a21nibah** [comment]
do we only want to save diagrams to local storage that is currently being worked on or so we rather make it more flexible so that any diagram can be saved? this is important to know because there are diferent aproaches depending on when diagrams should be saved. If we want multiple diagrams to be saved, if we only want to save the diagram that a user is currently working on and allowing multiple of those saves I would suggest we use an aproach where we modify the keys so that each key is unique with a date and timestamp. But if the goal here is to allow saves at any time using any key i can make it so the function accepts parameters, that would also not break the rest of the code. But the user would then have to make sure the keys are unique.
