### ISSUE TITLE
Find cause of error

### ISSUE THREAD

**Issue by b21phiro** [HGustavs/LenaSYS#14069]
## Description
If you go to console you will find an error being print out stating that the ``window.parent.paramArray`` is empty not set. 

## Job
Find out why the window.parent.paramArray is empty, and see if you can fix it.

**Comment by a21nibah** [comment]
It appears that the goal is to set preview values, specifically data that is supposed to be loaded in to the parent window array when the window first loads. it is supposed to be a diagram type that has to be loaded but i am not sure what type it is expecting. The function is also wrapped in a try and catch statement. I could modify the function to either not throw that error by taking in to account that the array is empty or has length0or i could just remove it since it appears to not have a function. Although I believe it is fine leaving it as it is.

**Comment by b21eriho** [comment]
Rather modify it to not throw the error than remove it entirely.

**Comment by a21nibah** [comment]
I will modify the function so that no error is thrown if the array is of length0. Also if someone can figure out what values this is supposed to have we could add a fallback value later on. There just is not enough info on what values are expected where the function  is being used.
From what i can gather though it seems the preview values are not being used at all though.

**Comment by b21eriho** [comment]
That seems wise, do so and add a comment about why it was commented out
