### ISSUE TITLE
Add input field to change file name

### ISSUE THREAD

**Issue by b21leowa** [HGustavs/LenaSYS#14079]
Add an input field to change the name for the code example file name.

#14078 is blocking this issue atm.

Read #13933 as it refers to this issue.

**Comment by a21henhe** [comment]
After further work we have realized that there has been a misunderstanding by our side when interpreting the related issues to this matter. We interpreted the original issue #13933 that there currently was no way of being able to rename the files in lenasys, which actually is the case. Because of this, we previously missed testing if changing the names affected the connection to a github repo.

After testing, we have come to the conclusion that the requested feature in the above mentioned issue is already in place in the system and works without interrupting the connection to a github-repo. Because of this, we will close this issue and revert the changes merged in issue #14078 @a21olljo
