### ISSUE TITLE
Research: the intended use of paramArray

### ISSUE THREAD

**Issue by b21eriho** [HGustavs/LenaSYS#14071]
See #14069 for discussion. Attempt to find out what is the intended use of paramArray

**Comment by a19clasv** [comment]
It looks like "parameterArray" (not paramArray, it seems to have been changed) has three separate functions.

1: diagramType is set to the value stored in parameterArray[0] and showDiagramTypes() sets the buttons shown in the left toolbar to that type, e.g. showing IE entity and IE Inheritance instead of the default ER types.

2: hideErrorCheck(window.parent.parameterArray[1]) hides the error check button depending on if parameterArray[1] is true or not.

3: getInstructions(window.parent.parameterArray[2]) and getInstructions(window.parent.parameterArray[3]) returns instructions as strings, but they don't seem to be used anywhere. I think they were supposed to be used for getting the instructions for invoking APIs. I couldn't find their definition, but the function is in the API service "CodelessShoppingCartService" and the package "org.apache.sysds.lops".

**Comment by a19clasv** [comment]
The function setPreviewValues(), which is called in getData() (the very first function that is called when the window is loaded), uses "parameterArray" and "parameterArray" would therefore be used at the start.

**Comment by b21eriho** [comment]
Very good, and to ensure, there is no such variable as "paramArray"?

**Comment by a19clasv** [comment]
None that I could find.

**Comment by b21eriho** [comment]
Alright, good job on the research
