### ISSUE TITLE
Override save-name issue

### ISSUE THREAD

**Issue by b21phiro** [HGustavs/LenaSYS#14117]
## Job/Description
When creating a save, you can write a name for the save. However, right now you can accidentally override a save-file because you are allowed to have duplicate save-names.

If, there's a name that allready exist, the user should get notified that there's allready a save-file with that name, and if the user want to proceed, and should be warned that the previous file will be overwritten.

**Comment by a21nibah** [comment]
I don't really understand the point of having diferent file names and so on for local storage. Why are we expanding functionality of local storage anyway? it is a bad way to save diagrams. Is the point not to have diagrams on the server from what i have seen from another issue? if so local storage only needs to save the currently active diagram if even that. I really do not get why we are expanding functionality of something that does not need to be there if we are going to save everything to the server. If the user switches browser or device well those diagrams will be lost anyway.
@b21phiro @b21eriho 
I believe this needs to be reassessed before making any further changes. Also the naming function is plane broken right now. It is getting the name and then it overrides that name no matter what. so the name is not even getting used. What happened during the review?
I also wrote in another issue when working with this that we needed to have unique keys but what seems to happen here now is that a name is getting treated as a key which is debatable if it should. Personally I think a name and a key should be 2 diferent things where a key is a unique timestamp so that we can allow for duplicate names if the user wants.

**Comment by b21eriho** [comment]
That is a reasonable point to make. On the other hand however this functionality will hardly be harmful and the server-side saving is still under consideration and research. Conclusively this is functionality we have decided to implement in the meanwhile.

**Comment by a21nibah** [comment]
I believe this issue should be reassigned to someone else to fix the front end. I have now made it so you can save and load files with diferent names from local storage and i have added the backend to check for diagram overrides. but someone eneds to complete this issue by adding a modal for the front end and then use my backend to tie in. I believe it is better if someone else makes the front end so we get it right from the beginning.

**Comment by b21eriho** [comment]
Noted, someone else will be assigned as well as you when there is a vacancy so that you can collaborate on the finishing touches
