### ISSUE TITLE
Create microservice createNewListentrie

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14155]
Related to: https://github.com/HGustavs/LenaSYS/issues/14143

Read more about the MS [here](https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#createNewListentrie)

File: createNewListentrie_ms.php
Folder: shared_microservices

**Comment by c22cargo** [comment]
A new file "createNewListentrie_ms.php" needs to be created in the "shared_microservices" folder.

The microservice will be implemented by reusing and modifying code from the monolithic.

Explanation from "potential_micro_services.md":
-----------------------------------------------------
createNewListentrie
USED BY

* createListentrie
* createGithubCodeexample

Uses the services insertIntoTableListentries to insert into the table listentries.

* cid
* vers
* entryname
* link
* kind
* pos
* visibility
* creator
* comment
* gradesys
* highscoremode
* groupKind
-----------------------------------------------------

**Comment by c22cargo** [comment]
It seems that the current functionality is located inside the "sectionedservice.php" file under the "NEW" opt. Not everything from the "NEW" opt is relevant though.

I am unsure how the implementation will be tested since I assume the whole "NEW" opt will be divided in several microservices. Perhaps testing will have to wait until the other relevant microservices are implemented.

**Comment by a22iliru** [comment]
waiting for tester.
