### ISSUE TITLE
Create microservice createNewVersionOfCourse

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14156]
Related to: https://github.com/HGustavs/LenaSYS/issues/14143

Read more about the MS [here](https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#createNewVersionOfCourse)

File: createNewVersionOfCourse_ms.php
Folder: shared_microservices

**Comment by b21isabe** [comment]
I have investigated earlier branches all the way back to 2020 to see if there was a time when it was possible to create new versions  but I haven't found any branch when it has worked. My next step will be to create a new branch and see if I can find what the issue is before I start working on the microservice.

**Comment by b21isabe** [comment]
After doing some testing it appears that the original implementation actually does work as intended as long as you choose to create a completely new version from scratch. If you don't press the button to copy the contents from an earlier version the new version is created without any problems. The issue seems to be with the code starting on line 186 in the file "courseedservice.php".

**Comment by b21isabe** [comment]
I have fixed the microservice the students from last year started and implemented it with the repo. From my own testing it seems to be working as long as you do not choose to copy content from a previous version. I decided to not attempt to fix that issue since it is not part of the "NEWVRS" opt but "CPYVRS"  that has its own issue  #14198
