### ISSUE TITLE
Create microservice retrieveCourseedService

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14159]
Related to: https://github.com/HGustavs/LenaSYS/issues/14143

File: retrieveCourseedService_ms.php
Folder: courseedService

**Comment by a21oscgu** [comment]
File: retri**e**veCourseedService_ms.php

**Comment by c21alest** [comment]
Haha sorry for my typo

**Comment by c21alest** [comment]
<img width="797" alt="Skarmavbild_2023-05-22_kl _15 59 37" src="https://github.com/HGustavs/LenaSYS/assets/102578850/0f1801f3-9407-4f21-a696-9053a66a530f">

This is all output data

**Comment by c21alest** [comment]
Solves this before continuing with this issue: https://github.com/HGustavs/LenaSYS/issues/14184

**Comment by b21kurar** [comment]
As of now, to make it work as normal there are a few parameters added that are expected to be updated **before** calling the microservice. This assumes that there is something that modifies these values before the function is called.

The file that does this right now is `courseedservice.php`, however since this is supposed to be dissassembled to different microservices, this might not be the proper solution for the future. There should be some way to let `retrieveCourseedService()` do this independently.

```php
function retrieveCourseedService($pdo, $ha, $debug, $writeAccess, $LastCourseCreated)
```
