### ISSUE TITLE
Create microservice getCourseGroupsAndMembers

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14208]
Related to: https://github.com/HGustavs/LenaSYS/issues/14143

Read more about the MS [here](https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#getCourseGroupsAndMembers)

File: **getCourseGroupsAndMembers_ms.php**
Folder: **sectionedservice**

**Comment by c21alest** [comment]
selectFromTableScore needs to be done before this issue

**Comment by a22marca** [comment]
The microservice is now implemented in `DuggaSys/microservices/sectionedservice/getCourseGroupsAndMembers.php`. I will test that it works by changing the path in `Dugga.js` to use the MS instead. Using the test data already provided and the interface on the website, it is not very clear when the returned data from the MS is used. Will have to make sure that correct values are returned and used correctly before creating a pull request. I will also have a look at the [test api documentation](https://github.com/HGustavs/LenaSYS/blob/6874b5277f63c2ca2e0a60429d0c22dc1878c3fb/Shared/Documentation/Test%20API/Guide%20on%20how%20to%20use%20Test%20API.md)

**Comment by a22marca** [comment]
I've found issues related to the existing code that executes the query to the database. It does not look complete and chunks of the code is commented out.

In the current state it does not handle the returned rows from the database correctly, so no values seems to be stored from it. To correct this issue I would need to know what columns that should be returned to e.g. `Dugga.js,` when this MS receives a request. I can't find any documentation on what part of the website this data will be used, so I believe the columns in the query for the [database service](https://github.com/HGustavs/LenaSYS/blob/g2-2023-v7/backend-models/microservices/duggaSys%20services/Database_related_micro_services.md#selectfromtableusercourse---used-only-by-getcoursegroupsandmembers--) should be used.

`SELECT user.uid,user.username,user.email,user_course.groups FROM user,user_course WHERE user.uid=user_course.uid AND cid=:cid AND vers=:vers`

**Comment by a22marca** [comment]
Data returned is now structured like so:
```{"debug":"NONE!","grplst":[["coursegroup","firstname","lastname","email@his.se"]]}```

**Comment by a22marca** [comment]
The returned json from the microservice has been provided with the data that is used by the function `returnedGroups` in `sectioned.js.`
We should consider changing this to be returned using a `retrieveSectionedService_ms` instead, so that all microservices returns a json with the same structure, but since that is not implemented yet this will work for now.

Additionally, some code that was used before this functionality was moved to a microservice has been removed. The code did not have a clear purpose or was incomplete.

The testing API is not working currently so I had to test via a browser.

To see the returned values from the microservices in a browser, navigate to a course that has related groups in the tables user_course. Create a new group activity. Open inspect->network->search for "getCourseGroupsAndMembers"->check the response after clicking the newly created group activity.
