### ISSUE TITLE
Note prints out style-error when using lines.

### ISSUE THREAD

**Issue by b21phiro** [HGustavs/LenaSYS#14223]
## Description
Note element throws error in console when drawn onto an element. See why and fix it
![Uploading image.png…]()

**Comment by c21adano** [comment]
From what ive found, the error only occurs for note right now due to note fulling the "if (stroke != context[i].stroke && !varyingStrokes)" but the error would occur for any element that fullfiled the if statment due to the contents of it not existing in the current system.

the code inside the if statment tries to change the "colorMenuButton2" but this button is never mention outside of this one if statment. 

The best course of action may be to just comment out/remove the if statment causing the problem for now.
