### ISSUE TITLE
[Documentation] Sequence Diagram

### ISSUE THREAD

**Issue by b21phiro** [HGustavs/LenaSYS#14243]
## Description
Make a quick report in MD (mark down), known bugs and issues with our sequence diagram. Write it knowing that this is going to help future students. Also write short how it's implemented. Code snippets are welcome.

![bild](https://github.com/HGustavs/LenaSYS/assets/45258330/964b51fb-71e3-4242-866a-e817cfa0be96)

**Comment by a21aldsa** [comment]
# Sequence diagram elements
Sequence diagrams are created just like any other diagram, the only real differences is the resizing working a little differently on actor/object since the lifeline on actor/object was the only thing that was supposed to get resized upon resizing vertically, hence the height is actually just based on the width and so the whole actor/object gets scaled when horizontally resizing.

## Actor/object
Actor and object are combined into the same element which is toggled with the context panel, this is to save space in the left side menu. Same goes for alt/loop (sequence condition)

##  Alt/loop
A future issue regarding the alt/loop or Sequence Condition as theyre also called is that the user might want to have differnet sized alternatives. If the last alternative is just like an else that returns nothing, that does not need to be, say, 1/3 of the size of the element. 

Future developers should also implement a proper way to stack diagrams ontop of eachother so that one can actually make a sequence activation element ontop of a sequence condition element without having to create it next to it and then drag it on.

# Important note
Also, very important: remove actorFontColor from diagram.js and replace it entirely with nonFilledElementPartStrokeColor. I cant believe its still in there, they do the same thing, nonFilledElementPartStrokeColor is just a better name for it.
