### ISSUE TITLE
Explore if it is possible to link a github repo with a course

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14289]
**Does adding a github repository to a course work?**

Explore if it is currently possible to link a github repository to a course in LenaSYS.

Try to create a small and concise report of your findings in the comments below, what works, what doesn't etc.

[sqlite diagram](https://github.com/HGustavs/LenaSYS/wiki/Github-Integration#sqlite-1)

**Comment by a22danwe** [comment]
There is code implemented to link a GitHub repo to a course, when testing we found issues with the linking of GitHub repos and the courses. We have not yet found the specified issue in the code.

**Comment by b22chran** [comment]
Tried to create a new course with linked gitHub-repo to see if the problem was the same as adding it to a already existing course and ran into a few more problems.

Problem 1:
When created a new course we get errors for the file navheader.php on line 236, 237 and 239 for the parameters $year and $term and a message "trying to acces an array offset on value of bool". This should be generated by an explode-function from line 116 in the the navheader.php that uses the version name from created course. 
(The problem appeared for two people with macOS and not for one with Windows. Not certain if it has anything to do with that though.)
<img width="540" alt="error_new_course" src="https://github.com/HGustavs/LenaSYS/assets/129262828/27a53f48-39b7-43c3-8087-8d41e7d93663">

Problem 2:
While on “sectioned.php” the site regularly tries to update the code examples. According to comments this is supposed to happen every 10 minutes but instead happens every 10 seconds. Related code start on line 3138 in “sectioned.js”.

The update itself also seems to be a bit scuffed, and on some courses it prints up to 30 AJAX calls that all return the same object, which is the course. Location of this AJAX call is unknown.
