### ISSUE TITLE
[Research] Inconsistent centering with "Reset View"

### ISSUE THREAD

**Issue by a22solmi** [HGustavs/LenaSYS#14297]
## Description 
Different types of diagram will be centered in different ways when selecting "Reset View" from the toolbar.
Templates found in Options > Example Diagrams
ER
![issue-v1-3](https://github.com/HGustavs/LenaSYS/assets/129150661/e6dd9ca6-14e8-4de7-b155-abd5a11bd3b2)
IE
![issue-v1-4](https://github.com/HGustavs/LenaSYS/assets/129150661/a5be782a-9e54-40b2-97c5-2f3cce91c301)
UML
![issue-v1-5](https://github.com/HGustavs/LenaSYS/assets/129150661/8fb48551-82c2-473c-b14e-a299a63e6196)

## Job
Find out what causes the centering to be inconsistent. Give details such as what functions / files the issues arise in.

**Comment by b22davbe** [comment]
The problem with the ER-example is that there's a small dot to the right of the diagram that makes the centering seem of. The centerCamera function (row 12865) itself is working correct but the fact that the zoom is restricted to just a few different values make the "jump" between zooms to big. That's why the UML-example becomes so small. Optimizing determineZoomfact() and  zoomin() with more flexible code would solve the issue while also making the program work and feel more flexible.
![Skärmbild 2024-04-03 134049](https://github.com/HGustavs/LenaSYS/assets/129262690/7b711c0a-dabc-4317-b9c6-8f96dc935da5)

**Comment by a22solmi** [comment]
Adding more zoom steps could make the centering behave in a more consistent way.
