### ISSUE TITLE
Can't place Sequence Activation direcly over Sequence Lifeline

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#14309]
## Description
When trying to place an Activation direcly over a Lifeline it just highlights the lifeline instead of placing the Activation.

![bild](https://github.com/HGustavs/LenaSYS/assets/129258593/234f5a60-84ff-4d08-b0b0-471c03d1e04c)

## Job
Fix so that activations can be placed directly over lifelines

**Comment by a22vioja** [comment]
It is possible to place activation correctly if first activation is placed outside the sequence actor rectangle. 

function entityIsOverlapping line 3592
this functions seems to work correctly, because when trying to place an activation, it does not give error message as it gives for other elements. But it does not let place activation either - need to check why.

It could be that CSS positioning of the activation box in the HTML structure is preventing placement of the object.

Event handler “ddown” on line 1798 could be the reason that prevents from placing on the lifeline.

One more guess - overlapping is disabled on purple rectangle around the entities. If so, it needs to be enabled but only for sequenceActorAndObject , not other entities. 

Still working on it.

**Comment by a22jacka** [comment]
Nice findings. Could also maybe have a check for if the mouse has a lifeline or other entity selected and change the behaviour based on that.

Small note on this however:
>  it needs to be enabled but only for sequenceActorAndObject , not other entities.
Would be nice to have a more general solution to this since other elements, like the super state, would benefit to also be able to place elements directly on it

**Comment by a22vioja** [comment]
I think that the problem could be on lines 1727 -1790 , function mdown(), because it handles mouse actions and updates states considering if the mouse button is clicked. On line 1727 code suppose to handle actions if mouse is clicked on selection box. The logic is to prevent placement of objects over existing elements by checking the initial position of the object, but instead of placing or preventing from placing the object over - it takes the element which is under the cursor and starts to interact with it. 

I also think that the implementation on mouseModes is missing (starts at line 1829) but  I was not able to find a solution for this.

**Comment by a22jacka** [comment]
Solved by other issue
