### ISSUE TITLE
Change references to services from absolute to relative paths in 2 files

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14330]
From a22albjo: When i try to run the tests i notice that an other test
http://localhost/LenaSYS/DuggaSys/tests/duggaedservice-tests.php
seem to be full of errors and warnings.

The service links to a wierd adress: https://cms.webug.se/root/G2/students/c21axepe/LenaSYS/DuggaSys/duggaedservice-tests.php
the url don´t seem to work, i guess it it some kind of server the school has set up.

I think that a issue is needed to change the references to services from absolute to relative paths to make duggaedservice-tests.php work.

I find that the same thing is true for filedservice.php.

Example row 8 in filedservice.php:
'service' => 'https://cms.webug.se/root/G2/students/b21kurar/LenaSYS/DuggaSys/fileedservice.php',
should be changed to:
'service' => 'fileedservice.php',

**Comment by a22marca** [comment]
Comment from the recent pull request:

This does not seem to address the issue that is described. From my knowledge of another issue regarding `test.php`, the mentioned code from in lines 162 to 167  in`test.php` creates a url to the files hosted on cms.webug.se if the service name does not contain a "/". So e.g. a test in `sectionedservice_Test.php` having the service entry "sectionservice.php" will be built into a `cms.webug.se/.../sectionedservice.php` url. 

We should probably use the file name as entry under "service" in a test, but retrieve the local path to it.
The code in test.php 162 to 167 should probably changed to use the function `dir(__FILE__)` to get the local path to e.g. `sectionedservice.php`. My opinion is that we should wait for the issue regarding test.php to be merged into master and then we can continue work on this issue on a new branch.

This is a rather involved issue, since it is related to the issue fixing test.php. Here is the issue regarding [test.php](https://github.com/HGustavs/LenaSYS/issues/14336).

**Comment by a22marca** [comment]
I've replaced the code at line 160 in test.php with the code below. This code builds a absolute path on the local system instead of using the cms.webug.se.
```
        if (!(strpos($testData['service'], "/"))) {
            // Build a absolute path to the service file
            $dirname = dirname(dirname(__FILE__));
            $serviceURL = $dirname . "/" . $testData['service'];
            echo $serviceURL;
        }
        else{
            $serviceURL = $testData['service'];
        }
```

Unfortunately this can't be properly this tested as of now, since we need to merge the fixed version of test.php before determining how well this solution works. So the next step after the weekly merge is to test that using the built absolute path works. Curl is used in the function `callServiceTest`. We also have to make sure that curl is able to use the absolute path to the local file.

**Comment by a22marca** [comment]
Fixes in `test.php` has been merged and I've been able to test the code in the comment above. The path to the local machine is built created and used, but curl does not seem to work with a local path on the machine.

**Comment by a22marca** [comment]
I've tried to find a solution on how to make a curl request to a file using the absolute path to the file on the server machine. However as mentioned above it does not work. There are two possible ways to deal with problem as of now:
1. Change the code to make a POST request using a method that may use file paths, e.g. the built-in PHP function `file_get_contents()`.
3. Requiring the use of a `localhost/LenaSYS` url, and if the developer is using another PORT than the usual, they will have to provide it themselves in the `service` entry of the tests.

I will discuss with the team about the best way to go about this. Most developers will use the default port (80). Because of this the first (1) solution might not be necessary.

**Comment by a22albjo** [comment]
This is a solution that seem to work, however you need to evaluate if this is a good solution, this code should replace line 161 - 169 in test.php:
```
        if (!(strpos($testData['service'], "/"))) {
            $current_url = $_SERVER['HTTP_REFERER'];
            $serviceURL = str_replace("tests/",$testData['service'],$current_url);
        }
        else{
            $serviceURL = $testData['service'];
        }
```
with this code it is possible to write the name of the service file in the tests ex in DuggaSys/tests/sectionedservice_Test.php change line 32 to:        
'service' => 'sectionedservice.php',

**Comment by a22marca** [comment]
` Warning: Undefined array key "HTTP_REFERER" in /var/www/html/LenaSYS/Shared/test.php on line 162`

I'm receiving this error when using the code in the previous comment. When researching it I found out that this is something that _may_ be included in the header. It is not certain that it is included, for privacy reasons. Seems like my firefox browser does not send it in the header in this case.

**Comment by a22albjo** [comment]
> Because of this I'd advice against using the code in the comment.

Thanks for testing, good job. I agree!

**Comment by a22marca** [comment]
Me and @a22albjo have agreed to use localhost url in the entry `service`, since this will work for most users. 

I will proceed to remove the selection that builds the url, so the `$serviceURL` will always be set to whatever the `service` entry contains in the specific test.
