### ISSUE TITLE
Fix errors that prevents copying of older course versions

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14349]
Context:
From my own testing it seems to be working as long as you do not choose to copy content from a previous version. I decided to not attempt to fix that issue since it is not part of the "NEWVRS" opt but "CPYVRS" that has its own issue https://github.com/HGustavs/LenaSYS/issues/14198 

Related to: https://github.com/HGustavs/LenaSYS/issues/14198

File: copyCourseVersion_ms.php

**Comment by b21isabe** [comment]
The problem is that it is currently impossible to create a new version of a course and copy the contents of an already existing course.

![Skärmbild 2024-04-02 145158](https://github.com/HGustavs/LenaSYS/assets/129263151/f31fd608-177d-4b9b-9137-03d4c9c3e4ff)
Enter a course as a superuser, press the + button to create a new version.

![Skärmbild 2024-04-02 145345](https://github.com/HGustavs/LenaSYS/assets/129263151/a06849c4-7da5-4d44-acb6-8184f4fa5f78)
enter the information and choose a version to copy.

![Skärmbild 2024-04-02 145542](https://github.com/HGustavs/LenaSYS/assets/129263151/e39d2fea-69a4-46ad-b207-08b49a201686)
When you return to the course, no new version has been created.

No troubleshooting to find the cause of the issue has been done but the problem most likely lies in the DuggaSys/courseedService.php file between line 186 and 461.
