### ISSUE TITLE
Github moment selection does not work

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14351]
When opening a moment trying to add a github moment, even though there is a github repo selected for the course, the dropdown does not show any of the folders in that repo.

![bild](https://github.com/HGustavs/LenaSYS/assets/129264968/edd9b57e-71a6-4cc3-ae56-c4d1cd995c4c)

At the moment, the code for saving a github to a course does not work. This will be fixed by this [PR](https://github.com/HGustavs/LenaSYS/pull/14346). So I suggest that you try out their dev branch before writing any code. When the pull request has been merged, you can create your own branch.

**Comment by a22maxra** [comment]
When adding dummy data to a folder in `"../courses/$cid/Github/*` the available repositories get displayed in the drop down menu.

![image](https://github.com/HGustavs/LenaSYS/assets/98206230/8bb82e56-fdd1-43dc-9fe6-507997c9267f)

The problem seems to be that a Github folder does not get saved to `"../courses/$cid/`  despite specifying a Github repository.
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/d8b9322f-0ec5-4b7d-82e8-d0f598f84de3)
