### ISSUE TITLE
error on fields stay red even if correct when creating new Test

### ISSUE THREAD

**Issue by a22karja** [HGustavs/LenaSYS#14368]
While editing a new test after creating it, if the field becomse red it will stay red even if the information is valid.
  
![red markings stay after being fixed](https://github.com/HGustavs/LenaSYS/assets/129260794/09cf99c9-b4f4-4933-a276-878a9f500b34)

**Comment by a22chrfa** [comment]
Fixed validation for name and date
For the name:
Validation color for name was based on a variable that was defined in a function that turned out to be unused. Therefore, undefined. Unsure if the function has any other functions and if the variable might be used in other place.

For this validation I created a new variable "inputColorTheme". A function was added to initialize the variable by checking localStorage for which color theme is being used. in "validatesSectName()" the function is always run to reinitialize the variable, since the theme can be changed before or after entering the page. The function then uses the new variable insted of the old one to color the element.

For the date:
The date validation was based on the same variable, which is now changed, so the color will work (confirmed with testing). But that's only one of two issues. The remaining issue is that the date checks if the absolute deadline is set between the start and end date of the object (the test), but the when the object is created it is created with incorrect start and end dates (2020).

So the validation and coloring is fixed, but the creation of a new object is a new issue that I suggested being a separate issue on github.

**Comment by a22chrfa** [comment]
Notes and testing:
Neither the checkbox nor the date-element is triggering the function that validates the date. So the function wont be found by inspecting those elements. The function being used is validateDate2() and it's being triggered by mouseover from the "editSection" ID. This is found in the code but not when inspecting the element in the browser for some reason. Looking through the callstack will reveal.
