### ISSUE TITLE
unsaved deadlines on tests

### ISSUE THREAD

**Issue by a22karja** [HGustavs/LenaSYS#14371]
When creating a test in Datorns grunder IT500G HT15, the deadlines aren't saved

![red markings stay after being fixed](https://github.com/HGustavs/LenaSYS/assets/129260794/7cea641f-e50f-4e72-9184-2179138e8361)

Press save

![unsaved absolut deadline](https://github.com/HGustavs/LenaSYS/assets/129260794/906c42e8-810a-44d4-8157-7eec644bf994)

This might be because no absolute deadline can be after 08/03-2015 and that date have already past. I cant test this because the field must have a date between 29/12-2014 and 08/03-2015 in it

**Comment by a22moamy** [comment]
### Issues surrounding test deadlines

1. When changing a deadline for a user created test in “Webbutveckling - Datorgrafik”, all deadlines for all tests recently created by the user are changed, IF they have the same link value. This is due to a query in sectionedservice.php (line 384 to 387), where the id is set to link, therefore, all tests with the same link value will be updated to the edited deadline. This code can be seen below:

```
					$deadlinequery = $pdo->prepare("UPDATE quiz SET deadline=:deadline,   
                                         relativedeadline=:relativedeadline WHERE id=:id;");
					$deadlinequery->bindParam(':deadline',$deadline);
					$deadlinequery->bindParam(':relativedeadline',$relativedeadline);
					$deadlinequery->bindParam(':id',$$id);
```

2. There are courses in the system who have database entries and those who do not. “Demo-course” and “Webbutveckling - Datorgrafik” have database entries, all other courses do not. When creating a test in all public courses except for those with database entries, no default deadline is shown. 

3. When a test is created in a course without database entries, no links are available as options, which should correlate to the created dugga. 

4. When creating a new test in courses without database entries, if the user clicks on the dugga, it does not display an actual test (like in “Webbutveckling - Datorgrafik”). It only displays the following error message: 
![Skärmavbild 2024-04-09 kl  11 34 36](https://github.com/HGustavs/LenaSYS/assets/129263915/841267a7-024b-45a6-91b8-f389509bca49)

5. Even when creating a new test in a course with database entries, like “Webbutveckling - Datorgrafik“, the following error message alert is displayed: 
![Skärmavbild 2024-04-09 kl  09 42 47](https://github.com/HGustavs/LenaSYS/assets/129263915/e35e8026-0419-48a4-8dca-0fe0f78b67ea)

When closing the alert, you still get taken to a dugga nonetheless (so it still works). This is what the default dugga will look like: 
![Skärmavbild 2024-04-09 kl  09 43 00](https://github.com/HGustavs/LenaSYS/assets/129263915/d9f992d1-60dc-4c43-94ba-b386fae6a8b8)

The issue might lie in that “Webbutveckling - Datorgrafik” has database entries, while “Datorns Grunder” does not. This means the errors might be resolved only if a database is connected or if the script is changed to work differently. 

Besides courses like “Datorns Grunder”, which do not have database entries, the JavaScript / PHP logic works well enough to save a deadline and fetch it, besides the fact that editing a test will change all deadlines created by the user with the same link type (this might be an issue of the previous provided query). Doing console logs of the deadline variables will fetch a real date value, except for in the courses with no database entries.

**Comment by a22natth** [comment]
Another issue that we encountered was that deleted tests reappear when creating a new one. When the user removes their own tests on LenaSYS and then adds a new one, all the previously deleted tests will reappear again. This will only happen if the user does not refresh the page, although, if the page is refreshed then this bug will not be present.
