### ISSUE TITLE
Research how code examples are entered into the code viewer

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14428]
Research how a code example can be added to the website. Answer the following questions:
- Is it currently possible to add a new code example manually.
- How is the mapping made via a code example and its files. (Is there a table with code examples and their files?)
- Can any file path be "mounted" as a file example, can sub directories be used in the `courses` directory?

When you are done, give step by step instructions of how a code example was added, if it was possible. And attempt to answer the above questions.

**Comment by a22maxra** [comment]
**Is it currently possible to add a new code example manually?**
By pressing "+" and pressing "code" a new code example gets created. This is how a code example gets created manually.
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/48fb6fa6-265f-4e06-82b9-2f02b77f3583)
När denna "Code" knappen som ligger i klickas körs
`onclick="createFABItem("2","New Code","TOP");"`
rad 195 i `sectioned.php`

**Comment by a22maxra** [comment]
`createFABItem` resides in `sectioned.js` row 751 and takes the arguments 
	`async function createFABItem(kind, itemtitle, comment)` 
It calls the function `newItem` with the _itemtitle_ argument which is "New Code" in this case
	`async function newItem(itemtitle) {`
	
and the newItem function in turn calls `AJAXService` 
`await AJAXService("NEW", prepareItem(), "SECTION");`

which resides in _dugga.js_ located in the Shared directory line 958 
`function AJAXService(opt,apara,kind)`

As we can see AJAXService takes "SECTION" as its "kind" argument.

```
	}else if(kind=="SECTION"){		
		$.ajax({
		url: "sectionedservice.php",
		type: "POST",
		data: "courseid="+querystring['courseid']+"&coursename="+querystring['courseid']+"&coursevers="+querystring['coursevers']+"&comment="+querystring['comments']+"&opt="+opt+para+"&hash="+hash,
		dataType: "json",
		success: returnedSection
		});
```

Further down
```
	// Create JS Object with all data
	const loggingData = new Object();
	loggingData.opt = opt;
	loggingData.apara = allApara;
	loggingData.kind = kind;
	loggingData.apara_type = typeof(apara[0]);
	loggingData.dateTime = dateTime

	const logginDataJSON = JSON.stringify(loggingData);

	// Sends log data as JSON to logging.php
	fetch('../Shared/logging.php', {
		method: 'POST',
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
		},
		body: logginDataJSON
	})

	localStorage.setItem("loggingData", logginDataJSON);

**Comment by a22maxra** [comment]
The imporant section is the `else if (kind == "SECTION")` which is responsible for adding a code example.

**Comment by a22maxra** [comment]
As we can see data is sent to `sectionedservice.php` with the POST method which means something is being added to the database, _querystring_ has been populated with values form the URL. 

_$opt_ = "NEW" which we can see from the initial function call arguments and parameters, take this into account when we head in to **_sectionedservice.php_** soon.

_sectioned.js_ line 1095
`await AJAXService("NEW", prepareItem(), "SECTION");`

_dugga.js_  line 958 
`function AJAXService(opt,apara,kind)`
#### _sectionedservice.php_
An else if statement will be entered at line 221 since _$opt_ = "NEW". The highest exampleid is retrieved from the SQL database and 1 is added to it to create a unique exampleid. This is were a new code example is created in the SQL database and linked to the course id (_cid_).
Line 221
```
else if(strcmp($opt,"NEW")===0) {
	// Insert a new code example and update variables accordingly.
	if($link==-1) {
		$queryz2 = $pdo->prepare("SELECT * FROM codeexample ORDER BY exampleid DESC LIMIT 1");
		if(!$queryz2->execute()) {
			$error=$queryz2->errorInfo();
			$debug="Error reading entries".$error[2];
		}
		foreach($queryz2->fetchAll() as $row) {
			$sname=$row['exampleid'] + 1;
		}
			$sname = $sectname . $sname;
			$query2 = $pdo->prepare("INSERT INTO codeexample(cid,examplename,sectionname,uid,cversion) values (:cid,:ename,:sname,1,:cversion);");
	
			$query2->bindParam(':cid', $courseid);
			$query2->bindParam(':cversion', $coursevers);
			$query2->bindParam(':ename', $sectname);
			$query2->bindParam(':sname', $sname);
```

**Comment by a22maxra** [comment]
I added all the information up and finished the questions in this responds:

## Is it currently possible to add a new code example manually?
By pressing "+" and pressing "code" a new code example gets created. This is how a code example gets created manually.
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/301094ba-5903-46de-86cb-adcc06fb0a5a)

When the "Code" button is clicked
`onclick="createFABItem("2","New Code","TOP");"`
rad 195 i `sectioned.php`

`createFABItem` resides in `sectioned.js` row 751 and takes the arguments 
	`async function createFABItem(kind, itemtitle, comment)` 
It calls the function `newItem` with the _itemtitle_ argument which is "New Code" in this case
	`async function newItem(itemtitle) {`
	
and the newItem function in turn calls `AJAXService` 
`await AJAXService("NEW", prepareItem(), "SECTION");`

which resides in _dugga.js_ located in the Shared directory line 958 
`function AJAXService(opt,apara,kind)`

As we can see AJAXService takes "SECTION" as its "kind" argument.

```
	}else if(kind=="SECTION"){		
		$.ajax({
		url: "sectionedservice.php",
		type: "POST",
		data: "courseid="+querystring['courseid']+"&coursename="+querystring['courseid']+"&coursevers="+querystring['coursevers']+"&comment="+querystring['comments']+"&opt="+opt+para+"&hash="+hash,
		dataType: "json",
		success: returnedSection
		});
```

As we can see data is sent to `sectionedservice.php` with the POST method which means something is being added to the database, _querystring_ has been populated with values form the URL. 

_$opt_ = "NEW" which we can see from the initial function call arguments and parameters, take this into account when we head in to **_sectionedservice.php_** soon.

_sectioned.js_ line 1095
`await AJAXService("NEW", prepareItem(), "SECTION");`

_dugga.js_  line 958 
`function AJAXService(opt,apara,kind)`
#### _sectionedservice.php_
An else if statement will be entered at line 221 since _$opt_ = "NEW". The highest exampleid is retrieved from the SQL database and 1 is added to it to create a unique exampleid. This is were a new code example is created in the SQL database and linked to the course id (_cid_).
Line 221
```
else if(strcmp($opt,"NEW")===0) {
	// Insert a new code example and update variables accordingly.
	if($link==-1) {
		$queryz2 = $pdo->prepare("SELECT * FROM codeexample ORDER BY exampleid DESC LIMIT 1");
		if(!$queryz2->execute()) {
			$error=$queryz2->errorInfo();
			$debug="Error reading entries".$error[2];
		}
		foreach($queryz2->fetchAll() as $row) {
			$sname=$row['exampleid'] + 1;
		}
			$sname = $sectname . $sname;
			$query2 = $pdo->prepare("INSERT INTO codeexample(cid,examplename,sectionname,uid,cversion) values (:cid,:ename,:sname,1,:cversion);");
	
			$query2->bindParam(':cid', $courseid);
			$query2->bindParam(':cversion', $coursevers);
			$query2->bindParam(':ename', $sectname);
			$query2->bindParam(':sname', $sname);
```

## How is the mapping made via a code example and the entry on the website. (Is there a table with file location and its equivalent on the website?)
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/775e22a6-adfe-428b-b3d3-957e3d045750)

Code examples are mapped through template, fileLink and box tables.
When creating a code example and you are choosing a template and code examples, the `updateTemplate();` function line 2524 in `codeviewer.js` gets called
```
AJAXService("SETTEMPL", {
	courseid: courseid,
	exampleid: exampleid,
	cvers: cvers,
	templateno: templateno,
	content: content
}, "CODEVIEW");
```

`function AJAXService(opt,apara,kind)`
Which means this else if gets triggered from `dugga.js` line 1167 which sends data to `codeviewerService.php` 
```
}else if(kind=="CODEVIEW"){
		$.ajax({
			url: "codeviewerService.php",
			type: "POST",
			data: "opt="+opt+para,
			dataType: "json",
			success: returned,
			error: returnedError
		});
```

`codeviewerService.php` 
Since _$opt_ = "SETTEMP" this if statement will be entered on line 96 and a template is set
```
if(strcmp('SETTEMPL',$opt)===0){
	// Parse content array
	$content = getOP('content');
	$cArray = explode(',', $content);
	$multiArray = array_chunk($cArray, 3);

	$query = $pdo->prepare( "UPDATE codeexample SET templateid = :templateno WHERE exampleid = :exampleid AND cid = :cid AND cversion = :cvers;");
	$query->bindParam(':templateno', $templateNumber);
	$query->bindParam(':exampleid', $exampleId);
	$query->bindParam(':cid', $courseId);
	$query->bindParam(':cvers', $courseVersion);
```

Boxes are created with the chosen files under this if statement

```
// There are at least two boxes, create two boxes to start with
if($templateNumber==10) $boxCount=1;
if($templateNumber==1||$templateNumber==2) $boxCount=2;
if($templateNumber==3||$templateNumber==4 ||$templateNumber==8) $boxCount=3;
if($templateNumber==5||$templateNumber==6 ||$templateNumber==7) $boxCount=4;
if($templateNumber==9) $boxCount=5;

// Create appropriate number of boxes
for($i=1;$i<$boxCount+1;$i++){
	$kind = $multiArray[$i-1][0];
	$file = $multiArray[$i-1][1];
	$wordlist = $multiArray[$i-1][2];

	$query = $pdo->prepare("SELECT * FROM box WHERE boxid = :i AND exampleid = :exampleid;");

	$query->bindParam(':i', $i);
	$query->bindParam(':exampleid', $exampleId);
	$query->execute();

	if($query->fetch(PDO::FETCH_ASSOC)){
		// Update box, if it already exist
		$query = $pdo->prepare("UPDATE box SET boxcontent = :boxcontent, filename = :filename, wordlistid = :wordlistid WHERE boxid = :i AND exampleid = :exampleid;");
	} else if (!$query->fetch(PDO::FETCH_ASSOC)){
		// Create box, if it does not exist
		$query = $pdo->prepare("INSERT INTO box(boxid,exampleid,boxtitle,boxcontent,settings,filename,wordlistid,fontsize) VALUES (:i,:exampleid, :boxtitle, :boxcontent, :settings, :filename, :wordlistid, :fontsize);");
		$query->bindValue(':boxtitle', 'Title');
		$query->bindValue(':settings', '[viktig=1]'); //TODO: Check what viktig is and what it's for
		$query->bindValue(':fontsize', '9');
	} 
```

The interesting part is how files which make up a codeexample/template is linked and how they are at the right place, like for example there could be an Example1.js on the top and Example.js on the bottom. These files should stay in the code example when the page is refreshed and in the same spot.

A **Course** has **code examples**. Code examples has a single **template**. Templates has one or more **boxes**. Boxes has a single **file**.

There are templates which have 1-5 boxes. Where a file displayed is in the template is dependant on which boxid it has from the _box_ table.
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/2b043054-bdbb-4d22-95e5-54aa5dd991e9)

in the _box_ table, there is also a _exampleid_ which specifies which code example the box is for, and _filename_ which is what file is supposed to go in that box.

In the picture above the files are mapped to the correct placement in the template with its _boxid_ and the box is mapped to the correct code example with _exampleid_ and the code example is mapped to the correct course by its _cid_.

Files are stored in /courses/_cid_   (cid = courseid). Files are mapped in the _fileLink_ table with its _filename_ and _cid_. Code examples also has _cid_ so code examples are stored for specific courses.

This is a **course**
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/ce2b3248-d332-48d2-adc9-9710b739ee95)

These are **code examples**
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/42f52c5c-dfe6-4381-b32e-8c2a84fe8d11)

These are **Template**, **Box** and **File**
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/4c2faa00-53c7-4c89-83cc-f5df6c9e41de)

## Can any file path be "mounted" as a file example, can sub directories be used in the _courses_ directory?
A code example can use files for that specific course. These files are stores in /courses/cid. However, there is also a /courses/global directory, which hosts public files which seems to be available for all code examples, regardless of course.

Files are always stores in sub directories in /courses, either in /courses/cid or /courses/global.
