### ISSUE TITLE
Research and create microservice updateQuizDeadline

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14421]
file: sectionedservice.php

Se: https://github.com/search?q=updateQuizDeadline&type=code

**Comment by c20juler** [comment]
A folder for the monolithic file sectionedservice does not yet exist and has to be created (where the code will be split into microservice files).
A file "updateQuizDeadline_ms.php" has to be created and put in the to be created sectionedService directory.

**Comment by c20juler** [comment]
Convert issue-related code from monolith file: sectionedservice.php into microservice according to guide:  https://github.com/HGustavs/LenaSYS/blob/master/DuggaSys/microservices/monolithic-to-microservices.md 

The service accesses database table "quiz" to change columns "deadline" and "relativedeadline". 

Changing absolute and relative deadline on a dugga currently works, so any issues arising after converting to microservice should be due to recent changes during the conversion process.

**Comment by c20juler** [comment]
Microservice is now implemented and works as expected. Only getuid needs to be implemented further on (goes for all microservices) which does not currently work.
