### ISSUE TITLE
Research and create microservice updateListentriesTabs 

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14422]
file: sectionedservice.php

Se: https://github.com/search?q=updateListentriesTabs+&type=code

**Comment by a22marca** [comment]
This code should use database service updateTableListentries to change to contents of the column gradesystem in listentries.

It will be using this query 
```
UPDATE listentries SET gradesystem=:tabs WHERE lid=:lid;
```
This is related to the `opt` "UPDATETABS" in sectionedservice.php at line 392.

**Comment by a22marca** [comment]
I'm trying to change the gradesystem of a dugga via the website, but this functionality doesn't seem to work. The opts that are sent to sectionedservice are "UPDATE" and "UPDATEDEADLINE". Deadline, since this can be edit in the same window. No requests contains the opt with "UPDATETABS" in any of the requests sent.

This code is part of the opt UPDATE in sectionedservice
```
					if ($kind == 4) {
						$query->bindParam(':gradesys', $gradesys);
					} else {
						$query->bindParam(':gradesys', $tabs);
					}

```
Looks like the update opt should also be able to update the gradesystem of a listentry. I will look through sectioned.js and see if i can find the parts that are calling sectionedservice with the opt UPDATETABS.

**Comment by a22marca** [comment]
The functionality of updating the gradesystem on a listed entry in a course isn't working properly right now. We should address this problem before. It's also not possible to update a entry's moment or visibility.

**Comment by a22marca** [comment]
I implemented the microservice and it is possible to update the gradesystem of a listentry. It is not possible to integrate it until the issue mentioned in the previous comment is resolved. I tested by using the following command.

Pick a "lid" from any of the list entries in your database, and add it to the command. I used 1. The command will make a request to the microservice to update the gradesystem of lid 1 to gradesystem 2.

```
curl -X POST -d "opt=UPDATETABS&lid=1&tabs=2" http://localhost/LenaSYS/DuggaSys/microservices/sectionedService/updateListentriesTabs_ms.php
```
