### ISSUE TITLE
Research and create microservice getDeletedListentries

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14435]
file: sectionedservice.php

See: https://github.com/search?q=repo%3AHGustavs%2FLenaSYS+getDeletedListentries&type=code

**Comment by a22marca** [comment]
Related code for this microservice seems to be located in `sectionedservice.php` line 1370
```
					//This will enable fetching every listentry with visibility DELETED and will enable restoring deleted items
				if(strcmp($opt,"DISPLAYDELETED")===0) {
					$resultArray = array();
					$query = $pdo->prepare("SELECT * FROM listentries WHERE visible = '3'");

```

**Comment by a22marca** [comment]
Should use database service selectFromTableListentries.

```
SELECT * FROM listentries WHERE visible = '3'
```

**Comment by a22marca** [comment]
The microservice has been implemented and can be tested by opening `http://localhost/LenaSYS/DuggaSys/microservices/sectionedService/getDeletedListentries_ms.php`. One issue with testing is that there doesn't seem to exist a part of the website that sets a listentry's visiblity to 3 (hidden). So you have to update the DB manually, to have a few rows with the correct visibility for this case. 

I used this query during testing:
```
update listentries set visible=3 where lid>5009;
```

**Comment by a22marca** [comment]
Originally this functionality can be executed by calling the function `getDeletedEntries()` in sectionedservice.php. 
The call for this function is executed from sectioned.js:
```
function getDeletedListEntries() {
  var deletedEntries = document.write('<?php echo getDeletedEntries("DISPLAYDELETED"); ');
}
```
This functionality is not integrated in the same manner as the other `opt`s handled in sectionedservice.js. The microservices should not be called in this manner. The microservice should be called using a GET request.

I will look in to a proper integration of the microservice, so that it can easily be integrated when it is time.

**Comment by a22marca** [comment]
This modified version of the function makes a GET-request to the microservice from `sectioned.js` and the data can be handled inside the success function of the request. I will comment this code out and leave the original code since the microservice should not be integrated at this point. This code can be used to test the microservice.
```
function getDeletedListEntries() {
  $.ajax({
    url: "../DuggaSys/microservices/sectionesdService/getDeletedListentries_ms.php",
    dataType: "json",
    type: "GET",
    success: function (response) {
      deletedEntries = response;
      console.log(deletedEntries);
      //handle the deleted entries here
    },
    error: function(xhr, status, error) {
      console.error("Error retrieving deleted entries: ", error);
    }
  });
}
```

The function `getDeletedListEntries()` exists at line 987 in sectioned.js.
