### ISSUE TITLE
Delete all branches from 2022 and below (Not 2023 and above)

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14456]
All branches not 2023 and 2024 should be deleted (all thousands of them).
Google how to automate this so it does it instantly.

**Comment by b21isabe** [comment]
I have made a fork of the lenasys repo to test on before we do it on the live version.
https://github.com/b21isabe/LenaSYS

I have started researching making a git bash script that will delete all branches before 2023.

**Comment by b21isabe** [comment]
first we can navigate to the forked repo in git bash and run:
```git for-each-ref --format='%(refname:short) %(committerdate:short)' refs/heads/ refs/remotes/```
to list all branches with the dates of their last commit

**Comment by b21isabe** [comment]
this script will show all branches from before 2023 with their name and date of last commit, this just shows the branches without deleting them and can be used to check that the correct branches have been selected.
```
git for-each-ref --format='%(refname:short) %(committerdate:short)' refs/remotes/origin/ | 
while read branch date; do
    if [[ "$date" < "2023-01-01" ]]; then
        echo "$branch $date"
    fi
done
```

I have run into a problem, I am able to delete a branch manually like this:
```
git push origin --delete "$branch"
```
But when i try to automate it (as seen below) I am getting the error "remote ref does not exist"
```
git for-each-ref --format='%(refname:short) %(committerdate:short)'  refs/remotes/origin/ |
while read branch date; do
    if [[ "$date" < "2023-01-01" ]]; then
        git push origin --delete "$branch"
    fi
done
```

I will continue troubleshooting this issue

**Comment by b21isabe** [comment]
The problem seems to have been that the $branch variable contained the full address to the branch and not just the name. I have corrected this and made a new script.

```
git for-each-ref --format='%(refname:lstrip=3) %(committerdate:short)' refs/remotes/origin/ | 
while read branch date; do
    if [[ "$date" < "2023-01-01" ]]; then
        git push origin --delete "$branch"
    fi
done
```
this new script seems to be working but is very slow deleting 1 branch at around every 2 seconds, so it should take about 1 hour to run through all 1800 branches. I will let this run through once on the fork to see if it managed to delete all the branches from before 2023. And while it runs I will look for a better way to bulk delete branches.

**Comment by b21isabe** [comment]
I have tested the script and it seems to work but 560 branches remains of the original 1880. The reason why there are so many left is because the script only deletes from refs/remotes/origin/ which is the only location branches are stored on the original lenasys repo. In the created fork many branches were stored in refs/remotes/upstream and these werent deleted. this shouldnt be a problem when the script is run on the main lenasys repo.

**Comment by b21isabe** [comment]
I have created a new script that should be faster, I have made a new fork to test it.

**Comment by c22cargo** [comment]
I could not get the newest and fastest script to work. It seems quite unreliable and I suggest we use the slower script that deletes branches one by one. That script can be seen below:
```
git for-each-ref --format='%(refname:lstrip=3) %(committerdate:short)' refs/remotes/origin/ | 
while read branch date; do
    if [[ "$date" < "2023-01-01" ]]; then
        git push origin --delete "$branch"
    fi
done
```

**Comment by b21isabe** [comment]
The slower script has now been used to delete all branches last updated before 2023. The process went smoothly, 578 branches now remain of the previous ~2000.
