### ISSUE TITLE
Fix initial date for deadline

### ISSUE THREAD

**Issue by b22marah** [HGustavs/LenaSYS#14466]
When creating a new test via the fab-icon on sectioned.php the new object created is created with wrong start and end dates as can be seen in the following image:
![image](https://github.com/HGustavs/LenaSYS/assets/129395645/2dad71aa-12fb-4efa-9c80-c11416c0e545)

This needs to be fixed, so that the course object is created with relevant dates, and therefor will work as intended with the validation

**Comment by a22chrfa** [comment]
It turns out this was an issue with the predefined courses from the test environment.

The test object itself has no date attached to it other than the deadline, confirmed with database entries. The function "validateform2()" also didn't base it's validation on any hardcoded values. The dates are extracted from the "retdata" object which is an object containing information (including dates) for the actual course object.

When creating a course you have to choose start and end dates for the entire course. The predefined examples in the database of the test environment were all obsolete. Therefore, assuming new courses will be created with relevant dates, it's related objects (in this case the tests) will be validated with correct dates. This was confirmed by changing the courses start and end dates, which made the validation of the deadline date behave as intended.

The colors are based on an undefined variable, but will show correct colors with the complementary fix from issue: https://github.com/HGustavs/LenaSYS/issues/14368
