### ISSUE TITLE
[Research] bugged entities when too many are created

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#14520]
## Description
In #14445 it was found that creating a lot of elements could eventually create a bugged entity

## Job
Find out why this happens

**Comment by b22jonan** [comment]
this bug is not actually something that happens due to lag or large quantities of elements, to replicate it, put down an er entity, click it, and putdown a new box and drag it into the highlighted box and then release
video:

https://github.com/HGustavs/LenaSYS/assets/61019188/7b0bb582-6914-4d60-83a6-91003f420433

i still have no idea why this happens but its gonna be a bit easier to understand now that i know its not due to just there being hundreds of objects

**Comment by b22jonan** [comment]
if you create one of these, then click somewhere else a few times, the bugged entity appears, its just a ghost element that isnt handled correctly and is placed into the data array even though it shouldnt. it doesnt register that its overlapping with another element since you clicked down somewhere else and moved it, normally this doesnt work but somehow does when the entity youre moving into is highlighted. then its not turned into an EREntity but stays as an ERAttr ghost, which for some reason becomes an edge. this entity which is created has skipped a bunch of checks resulting in a ghost element being present in data which completely breaks the entire program

**Comment by b22jonan** [comment]
just had a look at [14298](https://github.com/HGustavs/LenaSYS/issues/14298) and its the same issue with that a ghost entity is created when it shouldnt. the reasoning for why it happens is better explained there.

**Comment by b22jonan** [comment]
trying a few different console logs through out the code, the entity is let through the mouseMode_onMouseUp(event) function, 
it gets to the part
```
if (event.target.id == "container") {
                    if (ghostElement && event.button == 0) {
                        addObjectToData(ghostElement, false);

                        // Check if the element to create would overlap others, returns if true
                        if (entityIsOverlapping(ghostElement.id, ghostElement.x, ghostElement.y)) {
                            displayMessage(messageTypes.ERROR, "Error: You can't create elements that overlap eachother.");
                            console.error("Failed to create an element as it overlaps other element(s)")

                            // Remove added element from data as it should remain
                            data.splice(data.length - 1, 1)

                            makeGhost();
                            showdata();
                            return;
                        }

                        //If not overlapping
                        stateMachine.save(StateChangeFactory.ElementCreated(ghostElement), StateChange.ChangeTypes.ELEMENT_CREATED);
                        makeGhost();
                        showdata();
                    }
                    break;
                }
```
and is let through there, so it saves an entity which looks like this:
```
{
    "name": "Ghost",
    "kind": "ERAttr",
    "fill": "#ffffff",
    "stroke": [
        "#383737"
    ],
    "width": 5,
    "height": 5,
    "type": "ER",
    "x": 264.5,
    "y": 257.5,
    "id": "A8111E",
    "left": [],
    "right": [],
    "top": [],
    "bottom": [],
    "x1": 365,
    "y1": 331.5,
    "x2": 368,
    "y2": 334.5,
    "cx": 367.5,
    "cy": 334
}
```
which means that it was let through the first two if statements, which means it realises youre putting the object inside of another object but doesnt notice that its overlapping with the other object. which then means it gets saved. the fix for this would be to redo this check:
```
// Check if the element to create would overlap others, returns if true
                        if (entityIsOverlapping(ghostElement.id, ghostElement.x, ghostElement.y))
```

now i dont know exactly what is wrong with the check. but fixing this should fix the issue with ghost objects being saved.
