### ISSUE TITLE
Look through the installer

### ISSUE THREAD

**Issue by b22marah** [HGustavs/LenaSYS#14530]
## Task
The task is to look through the installer to find flaws/bugs within the process, start by looking through the UI step-by-step, and if any issue is found try to find about where this occours in the code.

Also look through the installer to find potential flaws with the user experience, to find things we could improve to enhance the overall user experience for the installer. This includes accessability, feedback, error messages and general look of the page.

## Documentation
Write down every bug / issue / improvement you see we could implement to fix these things you've recognized, and for any bugs, try to provide a decent description for the issue and it's potential fixes.

**Comment by a18chrkr** [comment]
### Explored the installer
**Co-comment with @b22chran**

From what we have explored, there is not many flaws in the installer per se, except the errors you get when actually installing. Still, the installer look very outdated and could do with a total makeover.

Beneath is two general problems that we've found:

1. "install.php" sometimes gives "Warning: Trying to access array offset on value of type bool in C:\xampp\htdocs\LenaSYS\install\install.php on line 81"

2. Create better "start-dialog" pop-up and/or create a better position for it's button. Alternatively embed this pop-up cleanly into the installer window to make it always visible due to it's importance.
