### ISSUE TITLE
Create mockup for new installer

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14534]
Due to the old installer not working very well, we have decided that a new installer should be created. In this issue you are tasked with creating a mockup of a new installer, that is more userfriendly and visually appealing. The mockup must include all the features of the old installer. 

In general, come up with a new and improved design of the old installer. 
You could potentially collaborate with the people working on issue #14530.

Maybe figma could be used for the mockups?

Generate a style guide with color theme, fonts etc, that can be used in future development.

**Comment by a18chrkr** [comment]
### LenaSYS mockup
**Co-comment with @b22chran:**

Have started creating mockup for the new installer in Figmam, including a new process flow and updated UI. Attaching a preview of the start page.

![installer](https://github.com/HGustavs/LenaSYS/assets/102579106/072b70bd-a083-4ad5-85bb-599001967fe0)

**Comment by b22chran** [comment]
Co-comment with: @a18chrkr.
We continued with the rest of the pages for the mockup. We also created other variants of the pages to see how the layout for the elements to best fit the page and follow the LenaSYS standard as it is today. A screenshot of one of the page below.

<img width="630" alt="Skärmavbild 2024-04-16 kl  15 34 00" src="https://github.com/HGustavs/LenaSYS/assets/129262828/329d21fb-a414-4367-9adb-8b54598127d7">

**Comment by a18chrkr** [comment]
### Final steps of mockup

**Co-commit with @b22chran**

Today we finalized the last steps of the mockup representing an updated variant of LenaSYS. Only minor touches remain and those are quick fixes that will be covered moving forward. A small documentation of fonts and colors will also be included as part of the next installment.

![lenasys_installer_figma](https://github.com/HGustavs/LenaSYS/assets/102579106/131028d6-9712-440b-b124-e93e68e06aa3)

**Comment by b22chran** [comment]
**Co-comment with: @a18chrkr** 

For the new installation of LenaSYS a minor change in the flow is suggested. Instead of choosing to _overwrite_ user and/or database and if the user wants to choose database-initializing as an transaction is in a separate step late in the installation, it is integrated where the user and database is created. There is also an option to choose different OS for the installation due to different permission-granting is needed for Mac and Linux. 
For a future implementation the information that is wanted to present for the user shall be evaluated. The texts in the mock-up are only examples.

Here is a style-sheet with the components of the mockup of the new installation. 
[lenaSYS_Design_Guide_Installer (1).pdf](https://github.com/HGustavs/LenaSYS/files/15039648/lenaSYS_Design_Guide_Installer.1.pdf)

A video of the flow of the installation process. 

https://github.com/HGustavs/LenaSYS/assets/129262828/63aa0f20-e827-45cd-a43b-94dfde23af94

**Comment by a22willi** [comment]
Looks great, what do you think @b22marah?

**Comment by b22marah** [comment]
Looks awesome!
