### ISSUE TITLE
label <<includes>> shows wrong text

### ISSUE THREAD

**Issue by a22solmi** [HGustavs/LenaSYS#14548]
## Description 
When selecting a line there is a option to create a label and a button that should fill it with "<<includes>>".
Before deselecting the line the text displays text other than "<<includes>>".
![Screenshot from 2024-04-15 08-44-11](https://github.com/HGustavs/LenaSYS/assets/129150661/105677f1-622d-4fe1-9047-d9d9fca1c19f)

## Job 
Find a way to make the text display in the right way

**Comment by b22samer** [comment]
We have noticed a problem in our code where we are trying to display "<<Include>>" both in a text box and on the actual diagram. We have managed to adjust the text box to correctly display the value "<<Include>>" by changing a value in the code, but when we try to display the same value on the actual diagram, there seems to be an issue. Instead of showing "<<Include>>", only the "<" part is displayed for some reason.
