### ISSUE TITLE
Fix the issue with the inspector messing up the grid (#14327) 

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#14549]
## Description
The issue seems to be caused by the grid not realizing that the size of the window has been changed

## Job
Find a fix so that the grid always take up the whole screen

**Comment by a21liltr** [comment]
The issue seems to appear when a user loads the diagram page with a minimized/smaller window or with inspection tool open, after which, maximizing or closing the inspection window (essentially making the inner window bigger than when initially loading the page) causes the grid to break.

1. Loading in page in Firefox.
![image](https://github.com/HGustavs/LenaSYS/assets/129370135/3e6325a5-0b10-4786-8b79-370ef9fa4011)


2. Expanding/maximizing page to a bigger window than initially (doesn't have to maximize, as long as the window after expansion is bigger than when first loading in).
![image](https://github.com/HGustavs/LenaSYS/assets/129370135/61594048-8f79-42b0-9577-4435b595855a)
