### ISSUE TITLE
Fix bugs in showDuggaService.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14587]
When trying to save a dugga a error as recieved as response from showDuggaService.php.

Request:
`courseid=2
did=2
coursevers=97732
moment=2003
segment=2001
hash=UNK
password=UNK
opt=SAVDU
answer=2%2097732%202003%2000000001%200%200%201408%20880%20777%20748
log_uuid=mn11hhYj2brFXjG
variant=undefined`

Response:
`Fatal error: Uncaught Error: Class "ZipArchive" not found in /var/www/html/LenaSYS/DuggaSys/showDuggaservice.php:170 Stack trace: #0 /var/www/html/LenaSYS/DuggaSys/showDuggaservice.php(378): processDuggaFiles() #1 {main} thrown in /var/www/html/LenaSYS/DuggaSys/showDuggaservice.php on line 170`

**Comment by b21isabe** [comment]
I have started investigating this.
notes for showDuggaService:
line 170 - a new zipArchive object is made
line 129 - ProcessDuggaFiles() function
line 378 - processDuggaFiles() is called, and the error is thrown

**Comment by b21isabe** [comment]
I have replicated the error by opening Biträkningsdugga 2 in the course Webbutveckling - datorgrafik and when trying to save it, got the error: "Unable to save dugga!"

I will look into lines 278-328 in showDuggaService to see if there is anything there that is causing the issues.

**Comment by b21isabe** [comment]
I have done some more testing and discovered that the error only seems to show up when signed in as a superuser, when signed in as either a guest or student saving works fine.

**Comment by b21isabe** [comment]
The initial error reported was most likely because the person who found the error was using linux and had not configured zip-archive or had some other local issues with zip-archive. This can be read about here: [install guide](https://github.com/HGustavs/LenaSYS/blob/60fa0a4f5d03b176fc48452ed0b53346defc3cbc/README.md#to-get-zip-archive-to-workused-in-download-zip-function)

I have not been able to replicate the error message in the issue description but I have found some other problems that keep users from saving/viewing a saved dugga. The first one is that when a dugga is saved the generated link links to the wrong folder for example: 
http://localhost/sh/?s=21f0f62c
 when it is supposed to be 
http://localhost/Lenasys/sh/?s=21f0f62c
The other problem I have encountered is that when you enter a hash and hash password at the corrected address, you are again sent to an address without the Lenasys prefix. When the address is manually fixed, saving works as it should. I will try to find a way to fix this with relative filepaths and also see if I can update the alert received when trying to save as a superuser, to make it more clear that teachers are not allowed to save duggas.

**Comment by b21isabe** [comment]
I have fixed the links and alert message and saving is working as it should right now, at least on my device.

I did encounter a very strange bug though, on line 286 in showDuggaService.php I made en echo to print out a link for testing purposes, I later forgot about the echo and continued troubleshooting. When I later decided to delete the echo it made everything stop working, so I left it in the code. I will see if I can find the root cause of the issue, and if I don't find anything I will just leave it in.
