### ISSUE TITLE
Merge Potential_microservices.md and Database_related_micro_services.md into 1 file

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14599]
Merge into potential_microservices.md

**Comment by f22linhe** [comment]
Previously, there were two documentation files, Potential_microservices.md and Database_related_micro_services.md. Since these two files essentially contain the same information, the 2024 group has decided to merge them into one file to avoid confusion. The majority of the microservices to be implemented are database-related. The portion of microservices that are not database-related is small, and therefore, maintaining two separate documents is considered unnecessary.

Documentation for potential microservices and database-related microservices from the 2023 group:

https://github.com/HGustavs/LenaSYS/blob/master/backend-models/microservices/duggaSys%20services/Potential_micro_services.md

https://github.com/HGustavs/LenaSYS/blob/master/backend-models/microservices/duggaSys%20services/Database_related_micro_services.md

Related to issue #14467.

**Comment by f22linhe** [comment]
The merging of the two documents is ongoing. The majority of the microservices have now been implemented, and therefore, we are more than halfway through resolving this issue.

New link for the microservice documentation (updated the filename for the documentation) :
https://github.com/HGustavs/LenaSYS/blob/master/backend-models/microservices/duggaSys%20services/Microservices.md

**Comment by f22linhe** [comment]
Since this issue has become a part of the issue Document information about all microservices #15515, this issue should be closed.
