### ISSUE TITLE
Vertical resize faster on IE/UML/SD

### ISSUE THREAD

**Issue by a22solmi** [HGustavs/LenaSYS#14624]
## Description
When dragging the node of an entity up or down the resizing is faster than on IE/UML/SD than on ER. The mouse pointer should always be on top of the node being dragged like on ER.

## Job
Fix this issue so that all entities change size at the same speed. Most likely an issue with entities having multiple boxes and all boxes having their height changed.

**Comment by a22vioja** [comment]
“case pointerStates.CLICKED_NODE” resizes elements based on mouse movements. 
Pointer position should be adjusted to the mouse movements and it works fine on the right and left sides, but not when dragging up and down.

I tried to change the calculation for “deltaY” and “deltaX” and “widthChange”, but it looks like it has been calculated correctly.
I tried to update mouse position (“updatepos(deltaX,deltaY”) every time the resizing node was triggered. 
I also tried to modify the “mouseMode_onMouseMove(event)” function which manages mouse movement behaviour for different mouse modes, but as I understand this function should not cause the problems since pointer is working as expected on other edges(nodes) or when moving the element.

Neither of this worked so I need to do further research on this issue..
