### ISSUE TITLE
Move and Resize jump

### ISSUE THREAD

**Issue by a22solmi** [HGustavs/LenaSYS#14623]
## Description
Resizing an entity by dragging the "left" or "up" node will cause it to jump a few pixels. This only happens once when you move the mouse when dragging the node. The moving and resizing itself works as expected.

## Job
Find out why the entity is moved and implement a solution.
Most likely caused by "StateChangeFactory.ElementMovedAndResized" or "screenToDiagramCoordinates"

**Comment by a22hanfa** [comment]
Okay, I'm pretty sure I've figured out what is causing the jump.

This line in the`screenToDiagramCoordinates`-function. But I'm kind of stuck on how to redo this function.
```
return new Point(
        Math.round((mouseX / zoomfact - scrollx) + zoomX * scrollx + 2 + zoomOrigo.x), // the 2 makes mouse hover over container
        Math.round((mouseY / zoomfact - scrolly) + zoomX * scrolly + zoomOrigo.y)
    );
```

**Comment by a22hanfa** [comment]
# Overview of the issue
I think I have found the where the issue stems from. The function ``screenToDiagramsCoordinates`` is intended to convert screen coordinates to diagram coordinates. This function uses a lot of different variables like zoom, scroll, and an origin adjustment. However, I believe the function's implementation has led to significant and unexpected movements of elements, as evidenced by various tests and adjustments tried.

***All test** where done on the Y-coordinate but it should apply the same for the X-coordinates, since it's outputting the same behavior.*

# Where does the errors occur?
I'm pretty sure that the error occurs in the ``case pointerStates.CLICKED_NODE`` in `mmoving`-function. It's hard to know what causes what because there are so many variables in this.

My research has concluded that the error happens here:

    tmp = elementData.y;
    elementData.y = screenToDiagramCoordinates(0, (startY - deltaY + 14)).y;

    // Deduct the new position, giving us the total change
    const yChange = -(tmp - elementData.y);

I also believe that the code here is the reason for all the errors:
This return statement in thescreenToDiagramCoordinates-function. 
```
return new Point(
    Math.round((mouseX / zoomfact - scrollx) + zoomX * scrollx + 2 + zoomOrigo.x), // the 2 makes mouse hover over container
    Math.round((mouseY / zoomfact - scrolly) + zoomX * scrolly + zoomOrigo.y)
    );
```
I've found that the elementData.y is different before vs after the `screenToDiagramCoordinates`-function. Here is an example of what happened once:
> The post-screen to diagram coordinate computation results in an elementData.y of 423 from an initial 343, a jump of 80 units, despite deltaY being 0. This suggests that the transformations or their application to elementData.y are not in sync with intended coordinate system or object movement logic.

Here is the related console log and all the variables I've used for testing:
```
Starting pos, X, Y: 570 409 diagram.js:2667 ¨

Start Drag: elementData.y: 343, startY: 409, Initial Mouse Y: 409, zoomOrigo.y: 0 diagram.js:2668 

elementData.y, Pre screentoDiagram: 343 startY: 409 deltaY: 0 diagram.js:3460 

Last Mouse Position: 570 409 diagram.js:3461 

zoomX: 0, zoomfact: 1, scrollx: 100, scrolly: 100 diagram.js:3462 

Computed X: -98 diagram.js:3463 

Computed Y: 323 diagram.js:3464 

MouseX: 0 MouseY: 423 ZoomFact: 1 ScrollX: 100 ScrollY: 100 ZoomX: 0 ZoomOrigioX: 0 ZoomOrigioY: 0 diagram.js:3466 

Raw Computed X: 0, Raw Computed Y: 423 diagram.js:3467 

Adjusted Computed X: -100, Adjusted Computed Y: 323 diagram.js:3468 

Final Computed X: -98, Final Computed Y: 323 diagram.js:2670 

elementData.y, Post screentoDiagram: 423 diagram.js:2673 

yChange, Post screentoDiagram: 80 diagram.js:2691 

Initial elementData.y: 423, startY: 409, Initial Mouse Y: 409 diagram.js:2692 

Used: else if (startNodeUp && (startHeight + (deltaY / zoomfact)) > minHeight)
```

# Explanation of logs
## Starting Position and Drag Initialization
- Starting pos, X, Y: 570 409: Indicates the initial mouse position when the drag started.
- Start Drag: elementData.y: 343, startY: 409, Initial Mouse Y: 409, zoomOrigo.y: 0: This shows various initial values at the start of the drag:
  - elementData.y: 343 - The Y-coordinate of the element being dragged at the start.
  - startY: 409 - The Y-coordinate of the starting position, likely where the mouse was clicked.
  - Initial Mouse Y: 409 - Confirming the mouse's Y-coordinate at the start.
  - zoomOrigo.y: 0 - Indicates the Y-origin offset for zoom operations is zero, implying no vertical offset due to zoom.
## Transformation Calculations
- Last Mouse Position: 570 409: Confirms the mouse position hasn't changed from the initial position.
- zoomX: 0, zoomfact: 1, scrollx: 100, scrolly: 100: Parameters for the transformation calculation:
    - zoomX: 0 - No additional X scaling factor is applied.
    - zoomfact: 1 - Zoom factor of 1 means no zoom scaling.
    - scrollx: 100, scrolly: 100 - Indicates the amount of scroll offset applied to the position calculations.
- Computed X: -98, Computed Y: 323: The outputs from the transformation function for X and Y coordinates, which will be used to position the diagram element.
## Detailed Computation Steps
- MouseX: 0 MouseY: 423 ZoomFact: 1 ScrollX: 100 ScrollY: 100 ZoomX: 0 ZoomOrigioX: 0 ZoomOrigioY: 0: Detailed inputs and settings used in the computation. 
- Raw Computed X: 0, Raw Computed Y: 423: Initial results from a direct computation without adjustments.
- Adjusted Computed X: -100, Adjusted Computed Y: 323: Shows adjustments made for scroll and possibly other factors.
- Final Computed X: -98, Final Computed Y: 323: Final coordinates after all adjustments.
## Post-Transformation Application and Result
- elementData.y, Post screentoDiagram: 423: The Y-coordinate of the element after screentoDiagram, which has changed significantly from the initial 343.
- yChange, Post screentoDiagram: 80: The change in the Y-coordinate resulting from the drag, showing a significant jump.
- Initial elementData.y: 423, startY: 409, Initial Mouse Y: 409: Reaffirms the new position and starting mouse Y-coordinate after processing the transformation.
- Used: else if (startNodeUp && (startHeight + (deltaY / zoomfact)) > minHeight): From where the functions are called. Branch executed based on the drag operation, suggesting it was evaluating whether the drag had moved beyond a minimum height requirement, adjusted for zoom.
