### ISSUE TITLE
Create microservice settingCodeexampleTemplate

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14637]
Updates the template for the code boxes in LenaSYS.

Uses service __updateTableCodeexample__ to set templateid recived from input, that value is also placed in the variable __templateNumber__. 
The number of boxes created depends on on the value of _templateNumber_. 
The contents of all boxes are gatherd with the service __selectFromTableBox__.
Depending on if a box with the set id exists or not an insert into the table __box__, using service __insertIntoTableBox__, or an update, using __updateTableBox__, is performed. 

`Note that the description may be wrong or missing steps, do as u think is right.`

**Comment by a22eriwi** [comment]
This ms will use the opt "SETTTEMPL". It is supposed to update the template for a certain code example. This can be found if you click on a code example and then click on one of the buttons in the top menu which looks like this 
![image](https://github.com/HGustavs/LenaSYS/assets/129263553/480d6419-ec31-4d2d-b8ec-d146dd409d55)
.

Then if you choose to change the template it will update it and this is what our microservice is supposed to do.
![image](https://github.com/HGustavs/LenaSYS/assets/129263553/5ae7e49b-e681-40e8-88b4-57b6506b6dd4)

**Comment by c22emigr** [comment]
This microservice seems to be a bit more complicated then we first thought. When applying a template to a new code example the code somehow retrieves a CSS file with the selected template from dugga.js. Continuing work on this issue.
![image](https://github.com/HGustavs/LenaSYS/assets/129170158/f9b96b3c-9e10-4244-a792-3b7c2d0491b4)

**Comment by c22emigr** [comment]
After some researching it seems like our microservice now works and sends the correct data. However in order to display the new template that is chosen you need to refresh the page and that is because there is still some code in codeviewerService.php between the lines 341 -> 624 that needs to be made into a microservice that can be used by our ms.

**Comment by a22eriwi** [comment]
This issue is a bit complex since there are many files involved. Our ms is working but you have to manually refresh the page to see the changes. This is because in codeviewer.js on line 2524
![image](https://github.com/HGustavs/LenaSYS/assets/129263553/622a0038-07e7-4f48-95f3-14dff323ed85)
there is an AJAXService that is linked to dugga.js and codeviewerService.php. 
In dugga.js there is this condition 
![image](https://github.com/HGustavs/LenaSYS/assets/129263553/a8705557-e5f3-4c97-bcf0-250db40801ca)
Which retrieves the new template and other things to show the codeexample layout etc.
There is this file 
![image](https://github.com/HGustavs/LenaSYS/assets/129263553/d25fa9df-fd80-4bf2-b59d-b8eec49d012c)
which changes depending on the template you have selected and that is active. In order for our ms to be properly implemented there has to be work done with other files or other ms files have to be created for this to work properly.

**Comment by a22eriwi** [comment]
If you add this code to codeviewer.js on line 2525 you can test our ms:
		var flattenedContent = content.flatMap(innerArray => innerArray).join(',');
        // AJAX request
        $.ajax({
            url: "microservices/codeviewerService/updateCodeExampleTemplate_ms.php",
            type: "POST",
            data: {
                opt: "SETTEMPL",
                courseid: courseid,
                exampleid: exampleid,
                cvers: cvers,
                templateno: templateno,
                content: flattenedContent // Send the flattened string
            },
        });
![image](https://github.com/HGustavs/LenaSYS/assets/129263553/98607b46-bc40-48a3-b296-7c6bdf5ff13a)
