### ISSUE TITLE
Create reusable "loader-button"

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14648]
Create a button, that can replace some of the existing buttons, that incorporates a loader that makes it clear the website is still working and has not crashed. 

Requirements:
- When clicked the button should become disabled, and the loader should appear inside it. (innterHtml)
- The button should preferably be class based, maybe using [builder pattern](https://www.geeksforgeeks.org/builder-design-pattern/) so that when used, appropriate settings can be made to accomodate the specific functionality that is needed.
- There should be a function to make it stop loading that can be called when something has completed.

**Comment by a22maxra** [comment]
The loading button can be implemented in several places such as when saving and getting data from github. A good way could be creating a JS class that can be reused.

**Comment by a22maxra** [comment]
We are trying to find a button with DOMContentLoaded and then attach an eventlistener, which we did, but the code that is supposed to run when the attached eventlistener is triggered is not running...

**Comment by a22maxra** [comment]
We will try a different approach tommorow

**Comment by a22danwe** [comment]
It seems like the code doesn't run on the "demo course" and courses we create ourselfs but works on the already existing courses

**Comment by a22maxra** [comment]
Will do it a different way then we tried, instead of adding a class that adds functionality to buttons/inputs, we will try to replace the buttons with added functionality

**Comment by a22maxra** [comment]
I have been trying to create a class that functions with the requirements but it is hard!!!! ! !!!

**Comment by a22maxra** [comment]
A button container is now created instead of the old button
``` 
<div id="buttonContainerSaveRepo"></div> 
```

And the arguments are added as an action in the ´loadingButton.js´ file
```
const actions = {
  saveRepo: {
    action: validateForm, // Function
    argument: "githubPopupWindow", // Argument to pass to the function
    buttonLabel: "Save Repo", // Button label
    containerId: "buttonContainerSaveRepo" // Container ID
  },
```

Which generates a button with loading functionality 
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/bcd24479-d7ce-4ba7-996b-b74b95e38a0e)

This button stops loading when an action is completed, some functions reload the page after completion as well so it won't show, but when pressing a button without an argument the loader will show for 0.25 seconds.

There is a problem with this code which i have not been able to resolve, newly created courses for some reason do not work with the code, the onclick functions seem to now activate even though the button is generated.

**Comment by a22maxra** [comment]
OnClick still doesn't work for some reason on new courses, issue handler wanted me to try making a php solution so i created a new branch for the new week `g3-2024-v4-#14648` and will try.

**Comment by a22maxra** [comment]
OnClick works when course information is filled in and the course gets a version so solution should be ok.

**Comment by a22maxra** [comment]
Check https://github.com/HGustavs/LenaSYS/pull/14900 on how to use the loaderButton, there is now added styling if needed. Wiki will be updated soon.
