### ISSUE TITLE
Test the current version of LenaSYS with old data

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14653]
The version the school is currently running of LenaSYS is several years old. We suspect that the data from the old system will not work "out of the box" with newer versions of LenaSYS. Test LenaSYS using the old data and document what does not work. Preferably the specific tables that have changed over time and are no longer compatible. 

Due to privacy concerns this data will not in its present state be shared GitHub. Ask me or @b22marah for a flash drive with the data on it.

**Comment by a22oscja** [comment]
upon running the sql file the following is shown after telling the database to simply ignore errors:

![Screenshot 2024-04-17 115437](https://github.com/HGustavs/LenaSYS/assets/129263158/e1d566e4-ffef-4e56-b9eb-76f055c376b5)

Below is an attempt to summarize the errors given, the full error log is further down.

**cannot drop tables:** _“table” - “has issue with” - “table with foreign key”:_
-   box - improw_ibfk_2 - improw
-   class - programcourse_ibfk_2 - programcourse
-   codeexample - box_ibfk_1 - box
-   course - course_req_ibfk_1 - course_req
-   groups - user_group_ibfk_1 - user_group
-   listentries - useranswer_ibfk_3 - useranswer
-   quiz - variant_ibfk_1 - variant
-   template - codeexample_ibfk_3 - codeexample
-   user - course_ibfk_1 - course
-   wordlist - fk_word_joins_wordlist - word


**Incorrect columns in some way:** _“table” - “column” (if known) - “reason” (if known):_
-   codeexample - cversion - incorrect integer value
-   course - - wrong column count
-   groups - groupKind - data too long?
-   listentries - - wrong column count
-   listentries - partname - wrong type on foreign key
-   listentries - class - wrong type on foreign key
-   quiz - - wrong column count


**tries to reference thing that does not exist:** _“table” - “references”:_
-   box - codeexample(exampleid)
-   filelink - course(cid)
-   improw - box(boxid,exampleid)
-   impwordlist - codeexample(exampleid)
-   variant - quiz(id)
-   variant - quiz(id)
-   vers - course(cid)
-   word - wordlist(wordlistid)


**table does not exist:**
- partresult
- programcourse

it also appears to try to alter a database called “imperiouz”, this may be something we simply do not have locally, this appears to be the name of the database itself looking at the query inside the file (it tries to set which character standards to use), but there should still be a better query to fetch the name of it.

I also tested this by running it on an empty version of our database instead, which did not significantly reduce the amount of errors given.

I will also add that some of the listed errors may not explicitly need fixing, especially when it comes to foreign keys not existing, as this could be caused by other errors and no longer be an issue when said other errors are fixed.

full error log:
[error log.txt](https://github.com/HGustavs/LenaSYS/files/15011539/error.log.txt)
