### ISSUE TITLE
`ESC` to go back

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14663]
When navigating the website there is usually a back button, as seen in the image:
![image](https://github.com/HGustavs/LenaSYS/assets/129264968/75e43c4b-a9fc-41ca-bd05-e4c651f78108)
Implement a keybind `ESC` that when pressed brings you back to wherever this back button takes you. Ensure that the implementation does not override the exising functionlity connected to the `ESC` key, such as closing modals/popups.

**Comment by a22natth** [comment]
When trying to combat this issue, the different approaches still did not solve the main issue. Although, pressing the escape key made it possible to go back to the previous page, it unfortunately caused problems in regards to the modals and popups. This resulted in the escape button closing the modal AND going back to the previous page simultaneously. To possibly solve this issue, one might use "window.removeEventListener()" in sectioned.js (this file contains the event handler for closing the modals with the escape button) to specify that when closing a modal, the listener for the back button is not active. During the work process, files such as navheader.php was modified in which the event listener was implemented and fulfilled the functionality of the back button, since the specific links correlating to the click of the button is within this php-file. Perhaps, because of the code being in different files and not "communicating" correctly by my implementation, might have been a reason to why it did not operate correctly.

These were the two main files that were modified as an attempt to complete the issue but hopefully, the previous information might act as a clue to how it might achieve full functionality.
