### ISSUE TITLE
Create wiki page for input validation

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14673]
Create a wiki page detailing how the input validation should work, where its files are stored, how it can be used, and what the standard is.

**Comment by a20jonda** [comment]
A wiki page named "Popup Form standards" is currenlty up and under constuction and will contain rulers of a popup form should be like and how it should interact with the user and deal with bad input.

**Comment by a20jonda** [comment]
Draft 1 is essentially completed, would need a peer reviewer and suggestions for a completer draft 2

The wiki currently goes under the name ["Popup form conventions"](https://github.com/HGustavs/LenaSYS/wiki/Popup-form-conventions)

**Comment by a22danwe** [comment]
Good explanation of the error handling, very informative and easy to understand. 

It might be good to add information surrounding which files the code examples are located. Minor spelling error here on the text marked blue.

<img width="922" alt="image" src="https://github.com/HGustavs/LenaSYS/assets/129262677/a19c8e80-e59d-4579-8441-28d384e30ef0">

**Comment by a20jonda** [comment]
I think I also should add a table to keep track of the known forms on the site. Some of them are currently broken. I did fake some of the example images but will add the original forms locations on the hover text.

**Comment by a22moamy** [comment]
# Changes requested
The text is very good, but please run through the text in a grammar checking program. Small grammar errors such as "an function" and "specific input field it is referring [to]" make the text harder to read. Also, try to explain what variables do, like "regex" for example, before using it in the text. 

The wikis pictures should also be updated once issue #14940 is done since the current look of the forms are faulty.

**Comment by a22moamy** [comment]
Looks good now!
