### ISSUE TITLE
After saving a github repo the user is still prompted for one 

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14671]
After adding a github repo to a course using the following menu: 
![image](https://github.com/HGustavs/LenaSYS/assets/129264968/5f2c7265-ad31-4762-ada7-bb99ee6e50c4)
This window still pops up when trying to fetch the repo. This window should only show up if there is no github repo saved already. 
![image](https://github.com/HGustavs/LenaSYS/assets/129264968/447cd5ba-d5f0-460d-82c0-6ab7f7deb404)

This functionality has been previously developed and discussed in: #14339, #14352 and #14533

**Comment by a20jonda** [comment]
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/932f1391-3e5b-48eb-af94-b9caaa2b9e74)
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/71ecaa3c-b35c-421c-9a28-a1a5cf48d3a1)

The "No Repo" message caused the "Add one" message, currently cannot reproduce steps to get it to not work

**Comment by a20jonda** [comment]
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/af76cf57-c1a1-440a-b1d0-584c0e450770)

Currently updateGithubRepo() fails due to the cid entry not existing. No error appears.
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/9598dced-fce4-4c9c-abe6-dd9a4b40fdb2)

Current suggestion would be for `clearGitFiles()` to replace instead of clearing which would ensure that a row with CID would exist
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/9e1162ae-48d4-44f2-94e8-dae3e3011c6d)

**Comment by a20jonda** [comment]
The `directInsert` part from #14647 appear to have solved this issue
