### ISSUE TITLE
Investigate why loading of old SQL data failed

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14688]
In issue #14653 it was determined that loading data from the current LenaSYS system (the one the school is currently running live) did not work, investigate the first error, and fix it, so that the script can create the data successfully. 

> **cannot drop tables:** _“table” - “has issue with” - “table with foreign key”:_
> 
>     - box - improw_ibfk_2 - improw
> 
>     - class - programcourse_ibfk_2 - programcourse
> 
>     - codeexample - box_ibfk_1 - box
> 
>     - course - course_req_ibfk_1 - course_req
> 
>     - groups - user_group_ibfk_1 - user_group
> 
>     - listentries - useranswer_ibfk_3 - useranswer
> 
>     - quiz - variant_ibfk_1 - variant
> 
>     - template - codeexample_ibfk_3 - codeexample
> 
>     - user - course_ibfk_1 - course
> 
>     - wordlist - fk_word_joins_wordlist - word

**Comment by a22oscja** [comment]
The issue, as mentioned, appears to lie in tables from the current database being unable to be dropped due to foreign keys in different tables referencing their values. To this end a working order was determined, it is the following:

1. improw
2. box
3. programcourse
4. class
5. impwordlist
6. codeexample
7. course_req
8. user_course
9. useranswer
10. variant
11. timesheet
12. quiz
13. vers
14. filelink
15. partresult
16. subparts
17. announcement
18. userduggafeedback
19. shregister
20. user_participant
21. opponents
22. listentries
23. course
24. user_group
25. groups
26. template
27. word
28. wordlist
29. user_push_registration
30. user
 
This order is not completely set in stone, to make it I simply went through the errors given when trying to drop tables in the order the original file attempts to. Then i would simply drop whatever it complained about first and repeat until everything dropped correctly.

At this point the simplest solution seemed to be to drop all of these in the beginning of the script, which is exactly what has been done.

The next part of the issue was the fact that the order the tables are created had to be changed to accommodate for the tables being dropped so early. This is obviously fine to do anyway, since a problem with referencing to data that hadnt been written yet would occur later on anyway.
To do this a similar process to before was used, simply go from top to bottom in the document and check for tables with foreign keys, then make sure that the table it references lies above it in the creation order, then repeat until it fully works. Here is the order used:

1. user
2. course
3. template
4. codeexample
5. box
6. class
7. course_req
8. eventlog
9. filelink
10. groups
11. improw
12. impwordlist
13. list
14. listentries
15. subparts
16. partresult
17. playereditor_playbacks
18. programcourse
19. quiz
20. sequence
21. settings
22. studentresultat
23. submission
24. userAnswer
25. user_course
26. variant
27. vers
28. wordlist
29. word

Upon doing this the only remaining errors were about tables attempting to reference entries that did not exist. As i'm not a machine I cannot go through the massive amounts of data to find where specifically the problem lies, although a good guess would be that something tries to take from a table that has been wiped due to security reasons.
Either way, to circumvent this I disabled the database caring about foreign keys for the duration of the script, since otherwise it still would not write any data. This should most likely be remembered, as it is quite bad practice and should be removed before attempting to actually migrate the data for real.

The last thing that was done before data would be fully added was to increase the varchar limit of sectionname in codeexample and entryname in listentries to 128 instead of 64. Again, due to one or more entries exceeding the limit, data would not be written at all.

With that all done, I believe all data is written correctly. And no, the site itself does not just work instantly with the new data. Also I left the error about the database "imperiouz" in there, but again, it is simply trying to alter the standard for characters in the database, and is done at the end of the file, so this should cause no issues.


**Notes for future issues**
The following tables are currently dropped but never recreated by the script:

- timesheet
- announcement
- shregister
- user_participant
- opponents
- user_group
- user_push_registration

I also went through the current tables (that are effected by the script) and noted down differences with the tables it creates, take note that I may have missed some, but they will likely come up as this is further worked through:
(apparently i forgot to check the user table, oops. Also when i say x is a new field, i mean it was added to the one we have since the backup file was made.)

- course - courseGitURL is a new field 
- filelink - path, filesiz, vers are new fields
- listentries - comments has shifted positions in column order (probably irrelevant). grouptype is no longer a field. groupID, githubDir has been added
- partresult - grade is no longer a primary key
- quiz - relativedeadline is a new field
- submission - order of fields has changed (probably also irrelevant)
- useranswer - uid is no longer a key field. gradeLastExported, seen_status, last_Time_techer_visited are new fields. Also the code appears to name this table with a capital A, still appears to work fine though.
- user_course - vers and vershistory have switched places. teacher, passed, failed, pending are new fields.
- vers - updated, motd are new fields.

Lastly i'll that the tables mentioned in previous issue not existing do exist now that the script runs correctly, I did not however look into if they are supposed to be a part of our current system or not.
