### ISSUE TITLE
github fetch cooldown should not be visible if there is no repo 

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14694]
In issue #14352 a tooltip was added that shows the last fetch and cooldown for fetching a github repo. This cooldown does not appear if there is no github repo set for a course. It however reappears after clicking the fetch button once. Make sure that the cooldown part of the tooltip stays hidden if there is no github repo set for the course. 
![image](https://github.com/HGustavs/LenaSYS/assets/129264968/5d7b645c-17c5-45c7-a1cf-60bd2dd78735)

**Comment by a22chrfa** [comment]
The button, when clicked, make the following calls:

- resetGitFetchTimer(), defined in "navheader.php".
- isSuperUser(), defined in "sessions.php".
- gitcommitService.php(), defined in "gitcommitService.php"

The functions are called from the button in "navheader.php". In order to ensure that the cooldown only appears if a github-repo is set, the calls need to instead be made form the button in "sectioned.php". However, this is a general button that handles other cases, therefore our specific case of github is handled in an if-statement inside it's related javascript-file "sectioned.js".  It is here the calls need to be made from. So we need access to the php-variables inside this file. Accessing php-files inside a js file is static, but that shouldn't matter (I think) since it only has to call the functions.

I'm also not entirely sure how navheader.php has access to the functions inside "gitcommitservice.php". Will have to keep digging.

**Comment by a22chrfa** [comment]
log:
![image](https://github.com/HGustavs/LenaSYS/assets/128893264/0f8e6f28-7425-4f52-b32f-9203092e85d6)

**Comment by a22chrfa** [comment]
Log:

The original call for the function looks like this:
$onclick = 'onclick=\'refreshGithubRepo(' . $_SESSION['courseid'] . ',' . isSuperUser($_SESSION['uid']) . ');resetGitFetchTimer(' . isSuperUser($_SESSION['uid']) . ')\'';

Since the session variable can't be loaded in a dynamic manner into a js-file, one solution might be to trigger a call from the js-file to an intermediary function, that does have realtime access to the variable. However, when looking at the session keys used, the user ID will remain static during a session and the course ID will only change when entering a new course, which loads the sectioned.js anew. Therefore, it shouldn't matter if the loaded php-variable is static in the js-file. Will test this out, otherwise there is a plan B that might work.

**Comment by a22chrfa** [comment]
Log:
After some tinkering, the solution from the previous comment seems to work. The php variables need to be stored as variables in javascript. The saved variables being static doesn't seem to matter. The sectioned.js and sectioned.php gets reloaded whenever entering a course, which is all that is needed.

What baffled me at first was that they can't seem to be stored inside the javascript file. They need to be stored in a script tag within the php file. This is fine, since we need to initiate js-variables before the script file is loaded anyway.

Ran into some other issues with the save button and the box not disappearing. Don't know why right now, will figure out in later comment. But the solution seems promising.

**Comment by a22chrfa** [comment]
The save button does run all the intended functions but it doesn't close the windows. Turns out it wasn't the new code that did this, it wasn't working in the original branch code. Will commit the fix and register a new issue for this.

**Comment by a22chrfa** [comment]
Back from a broken test environment. It seems the save button is behaving a bit differently now, maybe some other issue fixed it. Will implement my changes once again and confirm. And finally, commit.

**Comment by a22chrfa** [comment]
It seems some code surrounding this has been changed, so the solution is no longer working.

**Comment by a22chrfa** [comment]
As mentioned, the fix no longer works as there seems to be code around this that has been changed. First off, the save button that appears if a course doesnt have a github link is no longer attached to anything. Why?
Secondly, when clicking the github button, nothing happens on the first click. Only when a second click is done something happens. This seems to be related to the fact that the async call is set to "async: false". Can't confirm 100% yet.

Also, sometimes the fetch seems to fail with the default error message, why does it fail sometimes.

As these things are making my fix with the cooldown a bit harder, I asked if I should take a look at these things first. Which I was told I should. If the error seems to complex, it will be handled in a different issue instead.

**Comment by a22chrfa** [comment]
Log:
Whenever the button is clicked for the first time when entering a page, server responds with 403 (forbidden). Might be missing som auth.

**Comment by a22chrfa** [comment]
Log:
Every second click seems to work, getting a 200 response. And every first click responds with 403.

After looking at the code I couldn't see anything obvious as to why there should be a difference between the first and the second time the button is clicked. But I knew that for some reason, we didnt have permission during the first request.

I tried looking in the server logs but they didn't tell me anything about WHY it was declined or what information was sent. I tried looking into more specific logs in the docker environment but for some reason this seems harder than solving world peace. I could not get a look at a single log and it's likely that they wouldn't show me any more details any way. 

I tried looking at the request and response headers and I could see that for the first request (which returns a 403) the server is trying to set a cookie on the client side. On the second click (which returns a 200) that cookie seems to be used to establish the connection.

Could it be possible that there is a sequence or timing issue here? Maybe the server rejects the connection for not having legit auth (via cookie) before it tries to send the client the cookie. And that's why it works the second time, because then the client has the cookie.

**Comment by a22chrfa** [comment]
Log:
Did some more digging today. Oddly enough, today everything seemed to work "better". I still got the error sometimes though. I wanted to understand how the authorization works, since I didn't know anythin about it. All I know is that the request is made to gitCommitService.php and sometimes we get 403 "forbidden". I also wanted to understand why it seems to work better today.

First off, the authorization to the server seems to be purely session based. When comparing 403 and 200 response headers, I could see that in both cases the session ID's were the same. So that's probably not the issue. I found the logs related to this file and it showed the 403 responses, with a nudge to tokens. I started looking for the tokens and found them in gitfetchService.php. Here I could also se the code for "set-cookie" that I discorvered in the http headers. I found here that this is where the request to github is made. I was beginning to think that maybe the rate limits for github was being reached yesterday, and that since today is a holiday, it might be less requests being made.  I looked up some github information about their API and it turns out that when the rate limit is exceeded, github will respond with 403. So maybe github is responding with 403 due to rate limit, which is then cascaded and presented in the headers.

Nope, that wasn't it. And this is where I found a new issue with the github call. I started specifically logging the respone body from github and I could now see that we were getting 403 responses from github, where they specified the rate limit. However, apache responds with 200 and the text that says everything has been updated. This is clearly wrong. So back to square one, github isnt the issue. when it isn't working it is in fact Apache that sends the 403. And on top of this, a new issue appeared. Our application is giving the user wrong information.

**Comment by a22chrfa** [comment]
![image](https://github.com/HGustavs/LenaSYS/assets/128893264/f4151f62-24dd-47a2-89f2-ffc0d4523e47)
![image](https://github.com/HGustavs/LenaSYS/assets/128893264/366b8a78-e748-4229-8fb1-02bbace5dadb)

Here is a 403 response from github, with a 200 response from our web server, which our feedback seems to be based on.
This incorrectly tells the user that even that our files have been updated, even though we can't have done so since we don't have access to them on github.

Furthermore, this seems to incorrectly update the metadata as the "last fetch" is updated. This suggests that the metadata is being updated when it shouldn't. If we get a 403 from github, and can't update our local files, then the metadata shouldn't be updated to say that our unsuccesful attempt was our last actual update.

**Comment by a22chrfa** [comment]
Log:
It seems there is no handling of the status codes received from github in the bfs-function inside gitfetchService.php. Since there is no handling, it seems the response from bfs is being defaulted to a 200-response. The logic that handles this response, is then incorrectly making assumptions about the entire call. For example, assuming a 200 response means everything went OK.
