### ISSUE TITLE
Write new tests for showDuggaService

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14703]
One for each functionality that the  microservices will provide: 
https://github.com/HGustavs/LenaSYS/blob/6874b5277f63c2ca2e0a60429d0c22dc1878c3fb/backend-models/microservices/duggaSys%20services/Potential_micro_services.md#-------------------------------------showduggaservice------------------------------

Each test can be its own issue.
e.g. showDuggaService-test-updateActiveUsers
etc..

Identify what opt/parameters is needed to execute that functionality, and what the expected-output will be

**Comment by a22marca** [comment]
There are several tests implemented for this file, but some of them are unclear. I have been trying to find what each tests that is implemented actually is trying to test. I will create new issues for the tests that are unclear or need to be remade in showDuggaservice_test.php (if they do not already have a issue).  I will post a written summary of the tests once I've collected all information.

**Comment by a22marca** [comment]
This is what i've gathered so far about some of the tests
#### Get active users
- Inserts into table groupdugga before test. 
- Deletes inserted rows after the test
- Tests code related to`opt`= "UPDATEAU"

Problems with the test:
$AUtoken is not sent as a parameter in the current test. If the hash exists in the table, this AUToken is used together with the variable $active to create a new token.

#### Create active users

- No query before the test
- Sends a request with the opt and a hash
- Deletes inserted rows after the test
- Tests code related to`opt`= "UPDATEAU"
- the code performed when the opt is UPDATEAU and there are NO rows in the table groupdugga with the requested hash

**update active users**
- unclear, the current tests the same thing as get active users

**get data from userAnswer (student)**
- inserts a new course to course table
- inserts a new list entry in listentries, related to the above course
- retrieves the listentrie with the high lid
- inserts a user answer into userAnswer, related to the above course
- Deletes the inserted entries after the test
- opt `SAVDU`
- sends hash parameter 
- uses a student account

The code executed:

- retrieves the row from userAnswer with the hash sent as parameter 
- checks if the dugga to be saved is already graded, if it is nothing is done
- if it is not graded, timessubmitted is updated if hash and hashpwd is correct
    - if the hash is set but the password is invalid, no query is performed.
    - otherwise the userAnswer will be inserted as a new entry
- retrieves dugga variant for the specific useranswer

**get data from userAnswer (teacher)**
- inserts a new course to course table
- inserts a new list entry in listentries, related to the above course
- retrieves the listentrie with the high lid
- inserts a user answer into userAnswer, related to the above course
- Deletes the inserted entries after the test
code:
- same as get data from userAnswer (student)
- but also executes code after the opt has been handled, since the teacher is a superuser in this case
- retrieves dugga variant for the specific hash(userAnswer) or the course moment if the hash is unknown

**update submitted dugga**
- inserts a new course to course table
- inserts a new list entry in listentries, related to the above course
- retrieves the listentrie with the highest lid
- inserts a user answer into userAnswer, related to the above course
- Deletes the inserted entries after the tests

code:
- uses opt `SAVDU` but for a dugga that already exists and updates it

**submit dugga**
- inserts a new course to course table
- inserts a new list entry in listentries, related to the above course
- retrieves the listentrie with the high lid
- inserts a user answer into userAnswer, related to the above course
- Deletes the inserted entries after the tests

code:
- uses opt `SAVDU` for a dugga and inserts it

**Comment by a22marca** [comment]
These are the microservices that are currently written down for showDuggaService. I think new test should be created for showDuggaService according to the functionality of each of the microservices.

**updateActiveUsers**
Microservice implemented: [YES](https://github.com/HGustavs/LenaSYS/issues/14552)
Functionality according to [Microservice description](https://github.com/HGustavs/LenaSYS/blob/6874b5277f63c2ca2e0a60429d0c22dc1878c3fb/backend-models/microservices/duggaSys%20services/Potential_micro_services.md#updateactiveusers)

**processDuggaFile**
Microservice implemented: [NO](https://github.com/HGustavs/LenaSYS/issues/14553)
Functionality according to [Microservice description](https://github.com/HGustavs/LenaSYS/blob/6874b5277f63c2ca2e0a60429d0c22dc1878c3fb/backend-models/microservices/duggaSys%20services/Potential_micro_services.md#processduggafile)

**submitDugga**
Microservice implemented: [NO](https://github.com/HGustavs/LenaSYS/issues/14554)
Functionality according to [Microservice description](https://github.com/HGustavs/LenaSYS/blob/6874b5277f63c2ca2e0a60429d0c22dc1878c3fb/backend-models/microservices/duggaSys%20services/Potential_micro_services.md#submitdugga)

**loadDugga**
Microservice implemented: [YES](https://github.com/HGustavs/LenaSYS/issues/14555)
Functionality according to [Microservice description](https://github.com/HGustavs/LenaSYS/blob/6874b5277f63c2ca2e0a60429d0c22dc1878c3fb/backend-models/microservices/duggaSys%20services/Potential_micro_services.md#loaddugga)

A implemented test should be able to be performed on either showDuggaService.php or the specific microservice, by changing the link to the service. Check sectionedservice_Test.php for reference, some the tests are created like this there. Each test is named after the microservice and it is possible to change the url form sectionedservice.php to the microservice to test that instead.
