### ISSUE TITLE
Make a working test for removeListentries in sectionedservice_Test.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14716]
make sure a correct expected output and filters are used
    currently this does not pass the assert test
    Be aware that some tests needs a fresh database to pass

File: sectionedservice_Test.php

**Comment by b21isabe** [comment]
There seems to already be a test for this but it doesnt seem very good / doesn't seem to work at all. It uses way too many data points in the filtered expected output, the only data we are really interested in comparing is the listentries. The second thing is that the test first creates a list entry and then deletes it which means that the database/output will look the same before and after the test is run.

It would be better to pair this test with the createListEntry test like what was done in the duggaedservice-tests.php where one test first created something then another updated it and then the last one deleted it, this way you can see how the output is changed every step of the way.

**Comment by b21isabe** [comment]
There appears to be 2 separate opts with very similar names but that do different things. There is removeListentries and deleteListentries. removeListentries sets a listentries visible attribute to 3 and the deleteListentries service deletes the listeEntry entirely. Since I have the remove one and not the delete one making a test should be pretty easy. I will first create a new listEntry before the test, then call the opt to change its visibility then get the output and compare it and then after the test delete it.

**Comment by b21isabe** [comment]
There is a slight problem with making a test for this opt. At the moment no entries will show up as output, the reason for this is that there is an if statement that blocks entries from being stored. The if statement checks for many different things so I will have to investigate what it does, if its necessary and if there is another way to pass the entries to the output array.

**Comment by b21isabe** [comment]
Fixed it by copying a working test and remaking it. Don’t know why it wasn’t working earlier.
