### ISSUE TITLE
Filter output for reorderListentries test in sectionedservice_Test.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14718]
make sure a correct expected output and filters are used
    currently this does not pass the assert test
    Be aware that some tests needs a fresh database to pass

File: sectionedservice_Test.php

**Comment by a22albjo** [comment]
The test seem to be working fine for me, im having a discussion with @a22melst on how to move forward.

The problem seem to be that its only working if testing course is included during install.

This issue is resolved, i will create a issue to make it more clear that the checkbox needs to be checked for servicetests to work.

**Comment by a22albjo** [comment]
We have decided to filter the output on the tests in sectioned service to make them more readable.
