### ISSUE TITLE
Fix getCourseGroupsAndMembers microservice

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14825]
Like the monolit, it should also return:
grpmembershp
Also check what showgrp is used for, since its included in the code in sectionedservice.php but not in the microservice.

**Comment by a22marca** [comment]
Things that should be part of the microservice:
- `showgrp` parameter. This specifies what specific group to retrieve members from
- call to `retrieveSectionedService()` to package the returned group members like the rest of the microservices in sectionedservice

Question is if this microservice should only return groups specified by `showgrp`, the description of the microservice:  "Gets groups and there members for a specific course".

The original code is a little unclear what they where trying to do, since it's not working properly and a lot of the code is commented out since before this year.

For now I will assume that only the specified group's members should be returned, since this is a parameter in the request for the opt "GRP".

**Comment by a22marca** [comment]
When testing, dont forget to change the url to the microservice in dugga.js

**Comment by a22marca** [comment]
Before making a pull request I need to make sure that only group members specified by `showgrp` is retrieved.

**Comment by a22marca** [comment]
The problem is solved now. The microservice only collects group members that pertain to the group specified in `$showgrp` now. 

```
	// just need two first letters for comparison
	$grpletters = $grpmembershp[0] . $grpmembershp[1];
	// Collect members part of the group specified in $showgrp
	if (strpos($showgrp, $grpletters)!==false){
```

A users groupmembership could be e.g. "No_2" and the $showgrp is "No_UNK". Because of this the code currently only checks if the first two characters in the users groupmembership to the $showgrp.
