### ISSUE TITLE
Fix grpmembershp is "UNK"

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14873]
This is another issue with the code related to the "GRP" opt in sectionedservice.php. It works in the getCourseGroupsAndMembers microservice, so we need to make sure they are working the same way

**Comment by a22marca** [comment]
I have made it so that sectionedservice.php works in the same manner as the getCourseGroupsAndMembers. The `grplst` variable will be filled with members that are specified by the parameter `showgrp`.

It seems the `grpmembershp` is set based on what group the logged in user is part of.  So when logged in as the teacher user "brom" the grpmembershp is returned as "UNK", which is fine since that user is not part of a group . Setting a student login as part of a group, and logging in, the returned valueof `grpmembershp` is the correct group.
