### ISSUE TITLE
Fix retrieveUsername microservice

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14911]
Add pdo as parameter, dont create a new one with pdoconnect
Remove as many includes as possible
Remove session_start()
The reason for this: This things are already done by the calling microservice

IF IT DOESNT NEED PDO ( DOES NOT EXECUTE QUERIES) , JUST MARK ISSUE AS COMPLETE)

**Comment by a22marca** [comment]
I've removed all includes except `getUid_ms.php`, since that is needed to get the userid. PDO now needs to be passed as a parameter to use this function. I also removed the `session_start()` and `pdoConnect()` function calls, since these are already made by a calling service.

I tested this on the website by changing the code in "courseedService/updateCourse_ms.php" that retrieves the username, to this new function instead. And then it immediately `echo`'s the username, which can be read by looking at the response after e.g. changing the name of a course.

updateCourse_ms.php (roughly line 25, dont forget to remove the code that currently retrieves the username):
```
include_once "../sharedMicroservices/retrieveUsername_ms.php";
$username = retrieveUsername($pdo);
echo $username;
```
integrate, dugga.js (line 1018):
```
	if (kind === "COURSE") {
		let service_url = "courseedservice.php";
		if (opt=="UPDATE"){
			service_url = "../DuggaSys/microservices/courseedService/updateCourse_ms.php";
		}
		$.ajax({
			url: service_url,
			type: "POST",
			data: "opt=" + opt + para,
			dataType: "json",
			success: returnedCourse
		});

```
