### ISSUE TITLE
Fix alignment of course settings modals

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14940]
When editing group activities/code examples/tests etc, the input boxes are not properly aligned. Fix this.
![image](https://github.com/HGustavs/LenaSYS/assets/129264968/b5af7a70-45b0-43af-89a5-4d9babe68935)

Create item:
1. Navigate to a course.
2. Hover over the floating plus button in the bottom right.
3. Select an item
4. Click the settings icon for the newly created item.

**Comment by a22chrfa** [comment]
In this case. The name has a set pixel width of 440, unlike the other elements. This is probably a bandaid for some previous fix. Most likely not a good solution as the consistency with other elements might be compromised, as in this case.

For the last element. The select element has a margin of 10 px, which is inherited by all select elements in except for the last one. Where there is a higher priority (ID) styling attached, which sets the margin to 0. This is likely also a bandaid fix.

Fixing these issues will not take much time, however. Removing these might lead to new issues with alignments as these bandaid fixes (although not a good solution) might have fixed something somewhere else.

**Comment by a22chrfa** [comment]
Removed the specific pixel width for the inputwrapper-name ID. Removed the specific higher priority style for the last element.

This cause new issues to arise, as I feared. There were two new input fields that was now shifted. After some digging I found that these elements now inherited the correct styles, but as they probably had issues before this. It seems the span element covering those elements had a wrapping margin for those elements. Which has probably been a quick fix to solve the alignment for those elements, instead of fixing the source of the problem.
