### ISSUE TITLE
Create microservice refreshCheck_ms.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14958]
https://github.com/HGustavs/LenaSYS/blob/g2-2024-v4/DuggaSys/gitcommitService.php

folder: microservices/gitcommitService

**Comment by a22marca** [comment]
I will move this function into a microservice, and integrate the newUpdateTime microservice into this one. This is because `refreshCheck()` uses the `newUpdateTime()` function. Furthermore I will  also integrate this microservice with `refreshGithubRepo` because that is the microservice that needs the `refreshCheck()` function.

**Comment by a22marca** [comment]
This microservice is included in refreshGithubRepo_ms.php. refreshGithubRepo is implemented to be interfaced via POST requests. This makes the microservice a bit more complicated to integrate and test with the rest of the system.

**Comment by a22marca** [comment]
Apparently there are some issues with the github fetching service at the moment. So these microservices can't be properly tested as of now. Group 3 are working on the [issue](https://github.com/HGustavs/LenaSYS/issues/15129).

I suggest that we merge the microservice in this issue and create a new issue, to test the integration of the three microservices together (refreshGithubRepo, refreshCheck and newUpdateTime).  And we should also make sure that the paths to the githubMetadata/metadata2.db is correctly set for the sqlite db in refreshGithubRepo.
