### ISSUE TITLE
Research which sectionedservice_Test.php tests work and which do not

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14955]

**Comment by a22marca** [comment]
A fix that I was involved  for the test getCourseGroupsAndMembers just got merged with PR#14904, so I will considered that one working.

**Comment by a22marca** [comment]
This query is not really necessary for the test `deleteListentries`:
```
        'query-after-test-1' => "DELETE FROM listentries WHERE lid > 5009;",
```
The service tested in this test performs the delete itself. I guess this is good to have as a fallback, if the service fails. It should be changed so that it removes the specific listentry that was inserted before, e.g.
```
        'query-before-test-1' => "INSERT INTO listentries (lid, cid, vers, entryname, link, kind, pos, visible, creator, comments, gradesystem, highscoremode, groupKind)   
                                  VALUES(5020,1,45656,'New Group',9021,6,5,0,22,'TOP', 0, 0, null);",
        'query-after-test-1' => "DELETE FROM listentries WHERE lid=5020;",

``` 

Furthermore, the only needed filter is "entries".

1. So we need to change the query-after-test-1
2. Expected-output only needs "entries"
3. Change filters to only include "entries"

**Comment by a22marca** [comment]
**Test** `removeListentries`:
Looks good!

**Comment by a22marca** [comment]
Test `createListentries`:
Overall this test looks good. One thing we could do is to implement a way to retrieve variables after the test, like we can do before a test:
```
   'variables-query-before-test-4' => "moment",

```
This would mean that we could pick exactly the listentry and codeexample to be removed, instead of the current solution:
```
        'query-after-test-1' => "DELETE FROM listentries WHERE lid > 5009;",
        'query-after-test-2' => "DELETE FROM codeexample WHERE exampleid > 9009;",

```

**Comment by a22marca** [comment]
test `reorderListentries` works and it doesn't seem to need any changes..

**Comment by a22marca** [comment]
The test `updateQuizDeadline` is not working. I suggest we start by creating a new expected-output in a separate issue.

**Comment by a22marca** [comment]
The test `updateCourseVersion_sectioned` is not implemented fully. It is missing a expected-output and is currently not filtering anything. We need to make a separate issue for this test and create a new expected-output and use only the needed filters. After this has been done we can see if the test is working.

**Comment by a22marca** [comment]
The test `changeActiveCourseVersion_sectioned` has the same issue as the one above
Needs 
- a expected-output
- correct filters

**Comment by a22marca** [comment]
The test `setVisibleListentrieHIDDEN` is failing because it is missing the "groups" entry. When adding the "groups" to the filter list, there is a difference in the values for this entry. I believe we should try to create a new expected-output and filters for this test as well.

**Comment by a22marca** [comment]
The test `setVisibleListentriePUBLIC` seems to be working and are using a good amount of filters.

**Comment by f22linhe** [comment]
Group 2024 has decided to focus on working tests for the microservices instead of the service files. Therefore, this issue, along with other research issues regarding the functionality of tests for the service files, will be postponed until the next group takes over. It will then be up to them to decide whether these issues are still relevant or not.

**Comment by f22linhe** [comment]
Might be related to: Research tests for monorepos #15139
