### ISSUE TITLE
Create microservice fetchOldToken_ms.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14963]
https://github.com/HGustavs/LenaSYS/blob/g2-2024-v4/DuggaSys/gitcommitService.php

folder: microservices/gitcommitService

**Comment by a22marca** [comment]
The function `fetchOldToken()` is a function in gitcommitService. Currently it is only called by `insertIntoSQLite()`, which has been made into a microservice in another issue. Because of this i believe it is ok to leave this implemented as a function but in a separate file (microservices/gitCommitSystem/fetchOldToken_ms.php). The insertIntoSQLite_ms microservice can then include this file and run the function.

Furthermore, since `fetchOldToken()` is only used by other functions and not individually because of a call to gitcommitService it would be better to pass a pdo in the function call. Currently e.g. insertIntoSQLite() initializes a sqlite pdo, and then calls fetchOldToken(), which also initializes it's own pdo. This seems a little unnecessary, since they could both use the same pdo.

**Comment by a22marca** [comment]
The microservice is now implemented. This function is used by insertIntoSQLite(). To test this new microservice, I had to modify that function a little bit:
```
	function insertIntoSQLite($url, $cid, $token) { 
		$pdolite = new PDO('sqlite:../../githubMetadata/metadata2.db');
		if(strlen($token)<1)
		{
			include_once "../DuggaSys/microservices/gitCommitService/fetchOldToken_ms.php";
			$token=fetchOldToken($pdolite, $cid);
		}
```

A pdo needs to be passed with the `fetchOldToken()` function call.

When testing don't forget to comment out `function fetchOldToken()` in gitcommitService.php.
If you want to verify that the function is being executed when called add a `echo` in microservices/gitCommitService/fetchOldToken_ms.php and check the response of the last response from gitcommitService.php.
