### ISSUE TITLE
Create microservice updateGithubRepo_ms.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14966]
https://github.com/HGustavs/LenaSYS/blob/g2-2024-v4/DuggaSys/gitcommitService.php

folder: microservices/gitcommitService

**Comment by a22marca** [comment]
I've copied the function from gitcommitService.php to DuggaSys/microservices/gitCommitService/updateGithubRepo_ms.php. To test that the microservice works, comment the function out in gitcommitService.php (line 268) and add this code where the function is called (line 33):
```
		else if($_POST['action'] == 'updateGithubRepo') 
		{
			include_once("./microservices/gitCommitService/updateGithubRepo_ms.php");
			updateGithubRepo($_POST['githubURL'], $_POST['cid']);
		}

```
The functionality can be tested by changing the github link of a course.

I'm not completely convinced it is necessary to split gitcommitService into different microservices, but this will work and no large changes need to be done to the service in general.

**Comment by a22marca** [comment]
Checking if this issue is possible to complete now.

**Comment by a22marca** [comment]
I've tried to implement this like a microservice that receives a POST request. One issue i've encountered is that the bfs method that is included from gitfetchservice uses a path to the sqlitedb that is not working from the the path where updateGithubRepo_ms.php is performed.  The microservice does not perform its functionality without failing because of this.

All paths used for the location of e.g. the sqlite db is hardcoded according to where the functions in the file first where supposted to be called from in gitfetchservice. This probably needs to be fixed in a separate issue.

**Comment by a22marca** [comment]
There are still issues with the gitfetching service. I can no longer add a github repo url, even if im using a token.
