### ISSUE TITLE
When starting a dugga it automaticaly change the stopligth to "Handed in"

### ISSUE THREAD

**Issue by c13chrjo** [HGustavs/LenaSYS#1500]
This happens even if you have not handed it in

**Comment by b12erijo** [comment]
Unsure how this should be solved. As it is now an entry is created in the userAnswer table when the dugga is loaded. This is very reasonable and should not be changed. After the dugga has been started the stoplight should not be white since white light implies that the dugga has never been started.

A possible solution would be to implement a new stoplight for when the dugga is started but a result has not yet been submitted. Maybe a timer showing how much time is left to submit it as well? This would be good in case of a crash while the user is doing the dugga. This will possibly require being able to save the state of the dugga as well so the user doesn't have to fill every answer again in case of a crash.

Opinions?

**Comment by b12erijo** [comment]
Continued in #1534
