### ISSUE TITLE
Create microservice getCourseID

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#15027]
https://github.com/HGustavs/LenaSYS/blob/g2-2024-v4/DuggaSys/gitcommitService.php

folder: microservices/gitcommitService

**Comment by a22marca** [comment]
I will be adding the function into microservices/gitCommitService/getCourseID_ms.php.

We have to decide later if this microservice should be called with a POST request or as a function call.
For now I will leave it as a function.

**Comment by a22marca** [comment]
This microservice will be using `insertIntoSQLite()`, which will also be made into a separate microservice. Since this is currently not implemented yet we need to make sure this is included when it is finished [#14962](https://github.com/HGustavs/LenaSYS/issues/14962)

**Comment by a22marca** [comment]
The microservice is now implemented and can be used by commenting the original function in gitcommitService.php.
You then need to include the function, which can be done at line 25:
```
		if($_POST['action'] == 'getCourseID') 
		{
			//getCourseID($_POST['githubURL']);
			include_once "../DuggaSys/microservices/gitCommitService/getCourseID_ms.php";
			getCourseID($_POST['githubURL']);
		}

```

**Comment by a22marca** [comment]
When creating a new course version, the `validateForm()` function receives "newCourseVersion" as a formid. If all information is filled in correctly by the user the function `createVersion()` is called. This function retrieves all the inputted parameter, and it checks if the user wants to copy a currently existing course version or make a new one. It then makes a AJAX call to courseedservice.php, containing "CPYVRS" if a course version should be copied, or "NEWVRS" if it should be a completely new version.

In both of these cases (copying or creating a new), the request is not able to be performed:
![image](https://github.com/HGustavs/LenaSYS/assets/128985931/7876885b-f677-45b7-8c79-d75b2a09c743)

The request itself is aborted with the message NS_BINDING_ABORTED. I believe this might be because the page is being redirected before courseedservice.php is able to execute.
