### ISSUE TITLE
Warnings in courseed.php

### ISSUE THREAD

**Issue by a13denli** [HGustavs/LenaSYS#1512]
![image](https://cloud.githubusercontent.com/assets/11715616/7699683/e549de76-fe19-11e4-9c5d-e802d567465f.png)

After downloading the weekly branch, and unpacking it to my web-server, I get this error.

**Comment by HGustavs** [comment]
Should courseed really open files? 

I thought that file was strictly database oriented?

**Comment by a13karsi** [comment]
This only happens if you forget to move the .git folder to your own server directory, the file it wants to load is /.git/refs/heads/master, I added this code to the courseed page so we could load the master hash easily to identify "versions" of LenaSys.

In windows the .git folder is commonly hidden. So you have to go into folder options, enable to see hidden files and folders, and make sure you move the .git folder to your server as well.

My pull request: #1454 
Original issue: #826

**Comment by a13denli** [comment]
Ah okey

**Comment by c13chrjo** [comment]
sorta fixed in #1553
