### ISSUE TITLE
Automatic scroll bug fix

### ISSUE THREAD

**Issue by d22mikwe** [HGustavs/LenaSYS#15157]
- #15143
- #14942

In above issue and pr it was noticed that sometimes when creating a new item in the entry list at the bottom the automatic scroll function doesnt scroll all they way down. 
Look into if you can recreate this problem and try and fix it.
@SleepyBearIV was tester ask him for details about recreating the problem.

Edit: Also include fix for instant scrolling in edge and chrome

**Comment by a20jonda** [comment]
Also currently the scroll animation is instant both for chrome and edge when testing.

**Comment by a20jonda** [comment]
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/fe49f41e-11da-4580-b55b-773116990d44)
both chrome and edge uses system settings to check if smooth scrolling should be possible. Unchecking "turn of unnecessary animations" solves the problem. So it was not a bug.

**Comment by a20jonda** [comment]
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/00e6d7b8-dc41-415f-b5c6-209be8759b4e)
The problem is connected to a race condition. If the time is too low, both the scroll clips and the highlight might not show. Was working on a sync solution but unforseen problems occured. Adding an extra 100 ms stopped the problem on my end. 

Also
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/eb6fa483-87bf-4a52-9f6d-61003399b234)
Adding a new section too fast or within 3 seconds between another would make the new toast disappear once the first toasts 3 seconds where complete.
