### ISSUE TITLE
Research contribution_loginbox_service.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15246]
We need to know if this service is used and what it is used for. If it is used we can create microservices for the service. If not, can we delete the file?

https://github.com/HGustavs/LenaSYS/blob/g2-2024-v5/DuggaSys/contribution_loginbox_service.php

**Comment by a22melst** [comment]
Contribution is a type of dugga which is completely empty when opened.

**Comment by a22melst** [comment]
The database file BGHdata_2021_05.db is empty.

**Comment by a22melst** [comment]
There exists a functional requirements document regarding this file [here](backend-models/functional-requirements/FRD_contribution_loginbox_service.mdl). There is mention of a "contribution page", which I suppose is a contribution dugga. It is unclear exactly what this page is supposed to be, but the page is related to GitHub connectivity, which leads me to believe it is supposed to be a page showing the different commits contributed by students to a project.

**Comment by a22melst** [comment]
Since this service does not work at the moment, I and I do not know clearly know the intention of its creators, I do not think it should be turned into microservices as of now. However, it is clear that a lot of time and thought has been put into this and the other files regarding the contribution page, so I do not think it should be deleted. Since these files are related to the use of GitHub  for students on the LenaSys website, maybe it is something that Group 3 should look into.

**Comment by a22melst** [comment]
Since this service does not work at the moment, I and I do not clearly know the intention of its creators, I do not think it should be turned into microservices as of now. However, it is clear that a lot of time and thought has been put into this and the other files regarding the contribution page, so I do not think it should be deleted. Since these files are related to the use of GitHub  for students on the LenaSys website, maybe it is something that Group 3 should look into.

**Comment by a22melst** [comment]
I just noticed that that the tool called "självskattningsverktyg" mentioned [here](https://dugga.iit.his.se/DuggaSys/showDugga.php?did=1679&courseid=17&coursename=undefined&coursevers=927622&moment=11794&segment=11780&highscoremode=0&comment=null&deadline=2021-05-28%2017:00:00&cid=17) is contribution.php. However, when clicked the file is not found.
