### ISSUE TITLE
Create a retrieveCodeviewerService microservice

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15251]
Some of the microservices originating from the servicefile has no output, while some, such as _updateActiveUsers_ms.php_ from the _showDuggaService.php_, have a very short output. Create the microservice _retrieveCodeviewerService_ms.php_, similar to the ones made for _sectionedservice.php (retrieveSectionedService_ms.php)_ and _courseedservice.php (retrieveCourseedService_ms.php)_. This microservice should then be called at the end of each microservice in the codeviewerService folder.

**Comment by b21isabe** [comment]
I have created a first draft for a microservice but I am having some problems testing it. I have tested it on editCodeExample_ms.php, and it looks like it's working. It did however not work on deleteCodeExample_ms.php probably because it tries to look up an exampleID after it has been deleted. The function probably has to be run before the operation, or something else has to be changed.
