### ISSUE TITLE
Create a retrieveAccessedService microservice 

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15250]
Some of the microservices originating from the servicefile has no output, while some, such as _updateActiveUsers_ms.php_ from the _showDuggaService.php_, have a very short output. Create the microservice _retrieveAccessedService_ms.php_, similar to the ones made for _sectionedservice.php (retrieveSectionedService_ms.php)_ and _courseedservice.php (retrieveCourseedService_ms.php)_. This microservice should then be called at the end of each in the accessedService folder.

**Comment by a22marca** [comment]
I have reused the part from accessedservice.php after the "Retrieve information" comment and moved it into a function inside retrieveAccessedService_ms.php. Some parameters has to be passed with the function call, since some query are med in this function.

**Comment by a22marca** [comment]
It is not possible to test any of the microservices properly on the website currently since the functionality of accessed.php is not finished. Because of this the only way of testing retrieveAccessedService_ms.php is to manually make a POST-request to one of the microservices, who will then use `retrieveAccessedSerivce()` and return the retrieved information.
I will investigate how to perform this testing.
