### ISSUE TITLE
Create a retrieveGitCommitService microservice

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15261]
Some of the microservices originating from the servicefile has no output, while some, such as _updateActiveUsers_ms.php_ from the _showDuggaService.php_, have a very short output. Create the microservice _retrieveGitCommitService_ms.php_, similar to the ones made for _sectionedservice.php (retrieveSectionedService_ms.php)_ and _courseedservice.php (retrieveCourseedService_ms.php)_. __This microservice should then be implemented and called at the end of each microservice in the gitCommitService folder.__

**Comment by a22iliru** [comment]
I will see how I can retrieve some of the functions from gitcommitservice

**Comment by a22albjo** [comment]
I think we should close this issue or put it on hold instead of high priority. This servicefile(monorepo) don't need to have a retrieve microservice. It does atleast not seem to have a uniform response to requests. 

It seems that we are waiting for group 3 to finish their work as well before moving on with this according to the documentation in backend-models/microservices/duggaSys services/Microservices.md.
