### ISSUE TITLE
Create a retrieveGitFetchService microservice

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15264]
Some of the microservices originating from the servicefile has no output, while some, such as _updateActiveUsers_ms.php_ from the _showDuggaService.php_, has a very short output. Create the microservice _retrieveGitFetchService_ms.php, similar to the ones made for _sectionedservice.php (retrieveSectionedService_ms.php)_ and _courseedservice.php (retrieveCourseedService_ms.php)_. __This microservice should then be implemented and called at the end of each microservice in the gitFetchService folder.__

**Comment by a22marca** [comment]
Each function in the file is a function used internally (not called from javascript) to retrieve/handle data regarding github repo's that are linked. No general data is returned each time gitfetchService.php is performed, Each function performs a different task and returns a different type of data.

**Comment by a22marca** [comment]
Another alternative is to create the retrieve service and it simply, returns a array with different entries over all of the different types of returns that the functions in gitfetchService may return.
E.g. some functions return a `translateURL`, so the array may include a translateURL entry .
I do think this feels a little unnecessary though, because these functions will only be used by other services (from e.g. gitcommitService.php).

**Comment by a22marca** [comment]
We decided that the retrieve service for gitfetchService is not necessary, closing this issue.
