### ISSUE TITLE
Datorgrafik "frågedugga 1" does not work

### ISSUE THREAD

**Issue by a22moamy** [HGustavs/LenaSYS#15277]
# The needed fix
Currently, there is no way to progress in "frågedugga 1" from Datorgrafik. You can choose an option to a question, but there is no way to move forward in the dugga. Therefore we request that you implement two buttons:
1. One button to proceed to the next question labeled "Continue". 
2. One button to go back to the previous question labeled "Previous question".

The two buttons should be positioned right below the quiz container, right above the "Save"- and "Reset"-buttons:
![Skärmavbild 2024-05-02 kl  13 21 48](https://github.com/HGustavs/LenaSYS/assets/129263915/613e7845-61a0-4a16-a6f2-02c6d9d7c6b6)

The buttons should also be responsive and work with varying screen sizes. 

## "Continue"-button requirements
The user should have to pick/check an option before being able to press the "Continue"-button, otherwise it should be disabled. The button should only be visible when there is another question coming up. In other words, if the current question is the last one, the button should not be displayed. 

## "Previous question"-button requirements
The second button, "Previous question", should only be visible when there is a previous question before the current one. In other words, it should only be visible from question 2 and onwards. 

## What you DON'T need to do
You do **not** have to add a way to submit the dugga, that will be handled in another issue if it proves to be difficult.

**Comment by a22chrfa** [comment]
Log:
When looking at this I first noted that information about duggas are stored in the database. Each dugga has an ID and each of these has an attribute called "quizFile" that points to one specific file in the application folder. I'm not sure how this is intended to work, and from what I could see in the production environment of LenaSYS, the quiz-item doesn't seem to be used anywhere.
Typically on prod, if a dugga involveras more than one step, it is simply separated into different files and then listed as such in the UI.

I would like to know if there is a live example of a quiz or if there is some form of plan for this, as there currently seems to exist fundamental limits as to how this can be solved. Currently, it seems there are three primary options for implementing this.

1. Since the database stores only one file per dugga ID. Multiple question quizzes can be expected to be stored with one question in each dugga file. This way a button in the UI can simply load the next file. This would require the files to be named according to some sort of standard. This doesn't seem like a good solution and might make saving a dugga very hard.

2. The quiz files themselves could be made with boilerplate code that implements a button in order to display separate divs. This would shift the issue into creating such a boilerplate and instruct it to be used for quizzes. This will likely make saving a dugga much easier.

3. The quizzes could be expected to have a specific structure. For example, have div1 and div2 and so on for question. We could then parse the data from a given file and make the buttons show the correct div at the correct step. This would also likely make the saving of duggas easier. Essentially the difference in this alternativ, compared to alternative 2, would be that the "boilerplate" would be removed from the quiz-files and instead implemented in the application.

**Comment by a22moamy** [comment]
Your third option sounds good! Go with that one :)

**Comment by a22moamy** [comment]
Henrik proposed the idea that maybe the quiz only has one question and that it MAYBE does actually work. Regardless he does not want us to mess with the database structure for just one dugga, so this issue will be closed.
