### ISSUE TITLE
Not possible to fetch github repo in newly created course

### ISSUE THREAD

**Issue by d22mikwe** [HGustavs/LenaSYS#15342]
- #15091 
See issue above.

When creating a new course it is not possible to link/fetch a github repository to that course. 

Look into what's causing it and solve it.
If the problem seems too big for one issue make sure to notify so we can split it into multiple issues

**Comment by a22moamy** [comment]
Seems to be already fixed, according to developer

**Comment by a22moamy** [comment]
Nvm does not work for me

**Comment by a20jonda** [comment]
Log.
1. Appear to be solved in the revert reverts.
2. Got half solved in the reverts reverts.
3. Will be solved in a currently pending pull.

I'm not gonna jump the gun and try solve this myself yet because of the ongoing revert reverts and only investigate what's still lost and what functionality will return. The fetch feature is currently broken.

**Comment by a20jonda** [comment]
<img width="346" alt="image" src="https://github.com/HGustavs/LenaSYS/assets/102598258/d359c79c-1fba-4cf8-8809-6e889333aa1f">
Currently, the fetch feature has completely lost the ability to create folders for courses

**Comment by a20jonda** [comment]
There appears to exist microservices which do not match the services they have copied, I'm somewhat concerned

**Comment by a20jonda** [comment]
Update.
<img width="308" alt="image" src="https://github.com/HGustavs/LenaSYS/assets/102598258/c782cb19-a165-4e3a-aadf-ac6f4a870b5b">

Folders now successfully gets added.

<img width="401" alt="image" src="https://github.com/HGustavs/LenaSYS/assets/102598258/51ba80ab-ae7a-4837-bf85-232f1305504d">

Fetch now successful
