### ISSUE TITLE
Code Viewer: Resizing templates doesn't work in Firefox

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#1549]
It doesn't work to resize the templates when you using firefox as a web browser

**Comment by a12jiyba** [comment]
its working in:
http://webblabb.iki.his.se:8080/codesys/cv21/CodeViewer/EditorV50.php?exampleid=1&courseid=1&cvers=2013

**Comment by c13caral** [comment]
You have to download the lastest week branch (cv21)

**Comment by a12jiyba** [comment]
that is our main branch for cv21

**Comment by b12alela** [comment]
This is due to the recent dragndrop update, which also includes the jQuery and jQuery ui frameworks. Which makes some for some crazy behaviour with the jQuery ui functions, because it says sometimes that it doesn't recognize the function resizable from the jQuery ui framework. This is due to the second redundant loading of jQuery ui.

**Comment by a13jorla** [comment]
After this wekly merge this issue has been resolved by deleting redundant loading of some files so now i'm closing this issue.
