### ISSUE TITLE
Fix login form CSS

### ISSUE THREAD

**Issue by a22moamy** [HGustavs/LenaSYS#15607]
# The issue
Currently, the login form looks like this for wider screens:
![Skärmavbild 2024-05-13 kl  08 55 32](https://github.com/HGustavs/LenaSYS/assets/129263915/82b9a0aa-025b-4a57-b0ad-98420899f45f)

**Fix it so that it looks something like this again:**
![Skärmavbild 2024-05-13 kl  09 00 12](https://github.com/HGustavs/LenaSYS/assets/129263915/a34866de-9df5-4c07-b8e6-40761aa34a2b)

Make sure that that it stays looking the same for different screen sizes (so that the inputs don't float weirdly). 
## How to test (for the tester and developer)
Make sure that that the login form looks good in different screen sizes
**Also, test that other forms have not been broken by this fix.** Other forms should still look the same, in different screen sizes as well.

**Comment by b22chran** [comment]
Changed the css for the class loginbox to have a max-width to fit-content. Here is som example where it's changed the size. It doesn't hide any functions but the windows may look a little small. This is a decision to take if it is good enough or not.
<img width="1173" alt="Skärmavbild 2024-05-13 kl  11 17 42" src="https://github.com/HGustavs/LenaSYS/assets/129262828/2f2c137f-bc61-441c-bbe4-2d86195d746b">
<img width="1173" alt="Skärmavbild 2024-05-13 kl  11 17 15" src="https://github.com/HGustavs/LenaSYS/assets/129262828/04e5a612-fe70-485f-b3a1-0ae72f4593d6">
<img width="1173" alt="Skärmavbild 2024-05-13 kl  11 08 21" src="https://github.com/HGustavs/LenaSYS/assets/129262828/8e68e030-205b-4c31-98b4-bda6ea6cb4ea">
<img width="1173" alt="Skärmavbild 2024-05-13 kl  11 08 12" src="https://github.com/HGustavs/LenaSYS/assets/129262828/23609f67-94eb-4938-8486-cdadf1deb65d">
<img width="1173" alt="Skärmavbild 2024-05-13 kl  11 07 23" src="https://github.com/HGustavs/LenaSYS/assets/129262828/9d62f7ff-5900-415f-a781-6638b2ceac57">
<img width="1173" alt="Skärmavbild 2024-05-13 kl  11 07 13" src="https://github.com/HGustavs/LenaSYS/assets/129262828/0181f16a-b538-47a8-8c58-bbbc5a2ba938">
<img width="1173" alt="Skärmavbild 2024-05-13 kl  11 06 29" src="https://github.com/HGustavs/LenaSYS/assets/129262828/8186cffb-b31e-415b-8cb9-3d6d406afebf">
<img width="1173" alt="Skärmavbild 2024-05-13 kl  11 06 19" src="https://github.com/HGustavs/LenaSYS/assets/129262828/d7c6aa66-2d9c-446d-9a75-666f26e83a93">
<img width="1173" alt="Skärmavbild 2024-05-13 kl  10 56 35" src="https://github.com/HGustavs/LenaSYS/assets/129262828/c0cbcc85-c99d-49a8-a813-6498b8a99c2b">
<img width="1173" alt="Skärmavbild 2024-05-13 kl  10 56 26" src="https://github.com/HGustavs/LenaSYS/assets/129262828/299f2e46-259a-4972-986c-68ad90e02b76">
<img width="1173" alt="Skärmavbild 2024-05-13 kl  09 55 16" src="https://github.com/HGustavs/LenaSYS/assets/129262828/65a4c925-8801-4a8a-946c-c07c4f381139">
Here is the "Sign in" present because it calls the logintable from. It can be removed if tis string is not needed in the login-box.
