### ISSUE TITLE
Fix tooltip for "Edit section" form

### ISSUE THREAD

**Issue by a22moamy** [HGustavs/LenaSYS#15645]
Fix alignment of the "Name"-input tooltip to be less devious:
![Skärmavbild 2024-05-13 kl  13 39 35](https://github.com/HGustavs/LenaSYS/assets/129263915/2d8e7a2a-c444-4231-9665-65ebee9c9ed6)

To find the issue:
1. Go into a course
2. Try to edit a section/moment (Press on its cog wheel)
3. Enter an illegal character in the "Name"-input, like # for example.

Do _NOT_ change CSS for all tooltips by using class selectors. Only change CSS specific to this tooltip, _dialog10_ (ID).

**Comment by a20jonda** [comment]
Since I worked on this before.
The ´left: -100px;´ originally caused this dialog misalignment. There should also be an extra misalignment due to a 10px shift in margin from another issue.
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/baf329b9-9ae4-4847-9696-114e90479f4e)
The 100px shift comes from the `Choose Template` from in the same php file. 
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/07bbff0a-300c-42b1-a810-b66344a3bf71)
I would recommend removing the  ´left: -100px;´  and moving the change to its original `Choose Template` form.

**Comment by a20jonda** [comment]
This issue was reverted in the merge and needs to be done again.

**Comment by a20jonda** [comment]
Nevermind, this issue will conflict with [#15664](https://github.com/HGustavs/LenaSYS/issues/15664) and will need to be considered there.
