### ISSUE TITLE
Create new test for the microservice setVisibleListentries_ms.php

### ISSUE THREAD

**Issue by a22marca** [HGustavs/LenaSYS#15696]
See parent issue: [Create new tests for the microservices created from sectionedService.php](https://github.com/HGustavs/LenaSYS/issues/15681)

**Comment by b21isabe** [comment]
There was no output from the service but this was fixed by removing changing some echos to debug. There is a new issue with the $entries array showing up as empty in the output. This array is needed to see listentries and their visibility, and seems to work in tests for other microservices, so I will investigate what is different with the other tests/microservices and then see if I can fix it.
