### ISSUE TITLE
Deleting list entries produce weird effect and produces unreliable results

### ISSUE THREAD

**Issue by a22moamy** [HGustavs/LenaSYS#15712]
See attached video:
https://github.com/HGustavs/LenaSYS/assets/129263915/b7afd244-88e8-4d15-8fc9-5f49c00d8fec

**Comment by a18chrkr** [comment]
I've put a lot of time into this issue but has of yet not found the source to the weird visual bug that happens when you delete duggas. The deletion itself of one and multiple duggas work however. The only way I've managed to get rid of the visual bug is by commenting out the AJAX call on line 985-987, but then the actual deletion  _do not_ work and the duggas will be back when the page is reloaded.

**Comment by a22moamy** [comment]
Developers give up. Previous developers gave up too.
