### ISSUE TITLE
The play(button) link should disappear if the play link is empty

### ISSUE THREAD

**Issue by e12johka** [HGustavs/LenaSYS#162]
When typing an invalid link the play button is hidden and the only way show it again is to update the page.
the invalid link is being replaced whit the last valid link, but the play button is not shown

**Comment by HGustavs** [comment]
Fixing "bug" issues does sound like a priority to me, has this been fixed?

**Comment by a13jorla** [comment]
When logged in you allways have the play button pressent at this stage of development. So i do not know if this issue is relevant any longer?

**Comment by c13caral** [comment]
The play button is always pressent. Regardless if you are logged in or not.
But we maybe can fix that if the link for the play button is invalid, instead of getting the not found message maybe it can show an alert message or something that the play button link is invalid. 
But this feels like a really low priority issue

**Comment by HGustavs** [comment]
Im thinking that if the play link is empty i.e. there is nothing to run, the play link should disappear through hiding it with css.

**Comment by a13jorla** [comment]
Linking to issue #1326
