### ISSUE TITLE
Character in regular expression is unsafe

### ISSUE THREAD

**Issue by a13karsi** [HGustavs/LenaSYS#1633]
The character "-" was added to the regular expression in dugga.js at some early point. The "-" character is a pretty basic character to try when performing SQL injections, especially seing if "--" as input works and is interpreted as a comment, in which case SQL code could be injected. Is this a character that we want to or can allow without any other precautions?

**Comment by a13karsi** [comment]
We can change the regular expression to allow only one instance of the - character in sequence, would that be a good workaround for now?

**Comment by a20behta** [comment]
Is this still active?

**Comment by a20sacka** [comment]
Researched dugga.sys, couldn't find the aforementioned regex but found and created an issue #11349

**Comment by a20vicad** [comment]
This issue seems to have been solved a long time ago. No SQL injection seems to be possible (Granted, my experience is very limited). On top of that, in the cases I can find. SQL queries use parameters (prepared) to controll which protect from injections. 
![image](https://user-images.githubusercontent.com/102599327/164649463-51e289c4-7ed4-4162-a573-52f3f6ccc431.png)
/filereceive.php line(at time of writing): 358 - ...
