### ISSUE TITLE
Fixed issue with high score to show right

### ISSUE THREAD

**Issue by c13andka** [HGustavs/LenaSYS#1648]
It did not show right dugga moment when you press highscore. fix this

**Comment by b14kriwe** [comment]
Looking at the results, a part of this is that the NULL results are showed as the highest score. This needs to be changed as they should not been displayed. Only scores that are eligible should be displayed.

**Comment by b14kriwe** [comment]
This issue seems to be changed. As you no longer need to press for the high-score, I suspect this issue might have been resolved in the process of doing something else on the site. However there is now a column added called "Mark" which is either "Passed" or "Not passed yet", as an extra indicator of rank. When someone's dugga is either pending or failed, they will show up on the leaderboard (if less than 10 passed) but not have any rank. So it may be confusing why people are there without a rank but with a score. Therefor I think this addition was good. See screenshow below for how it now looks.

Regarding the null values, those are for the fill-out users that have just been "Passed" for the reason of seeing whether the system accounts for passed students correctly or not (+ fill with extra results).

![screenshot from 2016-04-20 10-41-09](https://cloud.githubusercontent.com/assets/18162859/14668483/d31a1b10-06e4-11e6-85dc-da78be50508b.png)
