### ISSUE TITLE
Dugga1 bug

### ISSUE THREAD

**Issue by c13andka** [HGustavs/LenaSYS#1737]
Dugga 1 seems to load last result of saved dugga if you save it. But the saved dugga is still the one that you get result for. so if you refresh page you will see your last saved dugga.

**Comment by a14vicni** [comment]
We should redo this and make a dynamic system that can handle all the duggor where the teacher can create by drag and drop these things. Because right now everything is just a big mess

**Comment by a14vicni** [comment]
I don't really see the problem here. But if I follow these problems I get the result of a working save function.
Ex. If I save a Dugga A i get the answer:
32 20 39 37 37 33 32 20 32 30 33 32 20 31 31 31 30 30 31 30 30 20 30 20 30 20 31 39 32 30 20 31 30 38 30 20 31 39 32 30 20 39 34 37 23 23 21 21 23 23 31 32 35 23 23 21 21 23 23 34 23 23 21 21 23 23 31 32 35

If i then refresh and Save a new Dugga B i get the answer: 
32 20 39 37 37 33 32 20 32 30 33 32 20 30 30 30 30 30 30 30 30 20 30 20 30 20 31 39 32 30 20 31 30 38 30 20 31 39 32 30 20 39 34 37 23 23 21 21 23 23 31 23 23 21 21 23 23 30 23 23 21 21 23 23 31

Which isnt the last saved dugga.

**Comment by a16konka** [comment]
Is this relevant in 2018?

**Comment by a16konka** [comment]
This issue cant be recreated therefore this issue is solved
