### ISSUE TITLE
A split screen view with panes would be nice

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1763]
I codeViewer, when having multiple source code files it would be nice if we could have a way och showing only a few of the files and minimize the others. Readability becomes hard when splitting up in to too many pages.

**Comment by a17fellu** [comment]
This is not really an issue anymore since you can change the size of the windows. I instead have added a maximize button to the boxmenu (menu above the file). This lets you more easily and faster choose what window you want to have maximized. Right now if you want to maximize one window you have to drag the corners of all the other windows that you want to minimize. So these buttons will make it way faster.

**Comment by a17fellu** [comment]
working on this over at branch: #gruppC2019W20_1763

**Comment by a17poner** [comment]
Maximise and reset maximise functionality have been merged with  #7034 closing this!
