### ISSUE TITLE
switch statements and ? operator

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1769]
There is a section in the code standard about switch statements.
They should be avoided as much as possible since the code is generally larger and harder to read with switch statements.
Same goes for use of the ? operator which also makes code hard to read.

**Comment by b14davbo** [comment]
I think it's a bad idea to avoid switch statements, they make the code easier to read than having a long if, else if, else statement. These are generally very good, and it's easier to read in my opinion. We actually already converted ajaxservice to switch statements from if, else if, else before seeing this issue.

I do agree with you about the ternary operator (? operator) since it makes the code hard to read, even if it's a one-liner.

**Comment by HGustavs** [comment]
I can see some merit to switch statements in some cases when there is an extreme amount of cases, but for few cases, if-else is easier to read.

I can support augmenting the code standard with a statement like 

When there are more than X cases in an if-else-statement, it can be replaced with a switch statement.

However, where do we draw the line? I would say around 10 or so. Definitely considerably over 4-5....
