### ISSUE TITLE
Code viewer popup documentation

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1789]
One feature that has been asked for is the ability to launch a pop-over (iframe?) documentation window for important words or some class of syntax highlighted words.

For instance in a php example by using some gesture e.g. click or double click a link to the corresponing page on php.org is shown as a pop-over or pop-under, allowing drill-down viewing of that specific keyword.

**Comment by a17poner** [comment]
Seems a bit hard to get it to show the correct page, i.e we need to know if it s a php function or say a constant like __LINE__  thats a different url to php.net/manual. 
would something like having a small popup/popover iframe that leads to https://www.google.com/search?q=[important word] be sufficient?

**Comment by a17poner** [comment]
We're leaving/dropping this issue for this year, either this functionality won't be necessary to implement as the hover on important words have since the creating of this issue been changed to include and give hover effect on the important words in documentation. This could be used to have the documentation there instead of a popout which would require a lot of fixing and some close to ai level of work to get the correct url for php.net/manual vs some js manual etc and all the different languages and functions that could become important words. Unless the important words themselves were changed to include a documentation area. Most simple solution seems to be to to just use the existing functionality and write the documentation and or link to man pages in the documentation on in a different box since it also gets the hover effect. 
![image](https://user-images.githubusercontent.com/49194938/57925182-9e2afe00-78a7-11e9-9bf9-27d50c252547.png)
Like this as it is used currently on the live version of dugga (in 2019 for databaskonstruktion) to achieve an effect which provides information of the same value.
