### ISSUE TITLE
Code viewer

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1811]
More informed labelling or popovers would be very helpful. Something like the work of bret victor.
http://worrydream.com/LearnableProgramming/

**Comment by a14jimso** [comment]
@HGustavs So i understand this correctly. You want a user to be able to hover over, say an RGB element in fill, to see what this value is for and what changing it will accomplish?

**Comment by b14antfr** [comment]
This seems to be a quite big issue if you think about it, adding descriptions to every single thing in the code, every possible tag, so on and so forth. That is if I've understood it correctly, at the moment we've created a way to get popovers on all tags that start with < and end with >.

Is there something more specific that you would like to get popovers on @HGustavs ? Otherwise I think it'd be wiser to split this issue into several smaller issues.

**Comment by b14antfr** [comment]
Also, would you like the tags to have custom made description or would you be satisfied with the tag definitions from the html tag reference library from w3s @HGustavs ?

**Comment by HGustavs** [comment]
Yes I would leave this at the very bottom of he priority queue like a "wishlist" it has partially been solved by better previews (see Shader Programming with previews for example Tangent Space 5 in shader programming)

**Comment by b14antfr** [comment]
Ok, we'll commit the tools we've made to work with this later but we'll move on to something else for now then, thanks for the quick response.

**Comment by HGustavs** [comment]
Have not thought this issue through any further... it was a year ago after all, but making this type of thing generic is nearly impossible, if done like in shader programming we get nearly there without resorting to too much magic.

**Comment by a17poner** [comment]
Looking at the 3 year old comment above I think we can safely close this.
