### ISSUE TITLE
Link lists are not populated correctly

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1814]
The item lists for the preview function in the code viewer does not show web links (which should be the most common use).

Furthermore the list has items from other courses also, not just the local course.

**Comment by a16vikva** [comment]
What exactly do you mean by this issue. Is this the list you're referring to? 

![image](https://user-images.githubusercontent.com/62876505/78257738-8a59ac00-74fa-11ea-9761-11e00fe333d2.png)

This is the only table that we can find that is somewhat close to this issue, however links are already visible here, and it's possible to filter to show only local files, so we assume that it's not here that the problem is.

**Comment by a16vikva** [comment]
Is this the function you want for the preview function? 
![image](https://user-images.githubusercontent.com/62876505/78261809-fee31980-74ff-11ea-8c36-c1d9ac86e120.png)
If so, this is already working.
Also, what exactly do you mean by "Furthermore the list has items from other courses also, not just the local course." since the lists holds whatever the publisher puts there? Or what "list" are you referring to here?

**Comment by a16vikva** [comment]
Is this the function you want for the preview function?
image
![image](https://user-images.githubusercontent.com/62876505/78262322-ad875a00-7500-11ea-8c1c-865ee1323f9b.png)

If so, this is already working.
Also, what exactly do you mean by "Furthermore the list has items from other courses also, not just the local course." since the lists holds whatever the publisher puts there? Or what "list" are you referring to here?

**Comment by HGustavs** [comment]
I would say that it works... but since that issue is 5 years old I am not 100% sure that is what i refer to...

could also be the dialog used to create the view? either way both seem to work.
