### ISSUE TITLE
The "new item" button should be fixed to the lower right corner

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1844]
The "new item" button should be fixed to the lower right corner and could be changed into a plus sign? It should also be elevated according to the principles found in Material design

**Comment by HGustavs** [comment]
A round circle with a plus inside it?

We are talking section edtor, or are there also other applicable views?

To reduce unnecessary mouse movements I would like the current button to remain at the top in addition to the fixed location at the bottom.

Also, a move to top would be nice in the section editor. For a course moving an element to the top is very tedious due to scrolling....

**Comment by a97marbr** [comment]
* move to top of course
* move to top of section
* move to top of heading

**Comment by a14gabon** [comment]
added a new "new item" button
