### ISSUE TITLE
Copy old material / course layout when creating a new version is not working

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1847]
Copy old material / course layout when creating a new version is not working.
This is a critical feature. Must have.

**Comment by a13arnhe** [comment]
Copying of a course listentries has been incorporated (on branch grp1w17-issue-1847) and that seems to work very well. The only table that needs to be copied from and that depends on the version of the course is the listentries table.

The problem is. If a student was in a former version of the course and has taken duggas, the student won't see his pass or fail on the stoplights as he has no tries for this current version. 
![screen shot 2016-04-22 at 15 30 00](https://cloud.githubusercontent.com/assets/18159848/14742959/30f3b3e8-089f-11e6-83ac-3d8897ae6971.png)

The teacher however can see old version grades on the result page. Is this something that should be kept like it is or do we want the students to be able to see their old tries?
![screen shot 2016-04-22 at 15 30 19](https://cloud.githubusercontent.com/assets/18159848/14742964/35060fbc-089f-11e6-8a5d-838f52da89fc.png)
