### ISSUE TITLE
Stop light logic is not correct for moment that has duggas

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1860]
This is for moments that has sub-moments (duggas). In the code they are identified as type '4'.
We want:
**No light** if no duggas have been started
**Yellow light** if any dugga has been started, date should be from the latest submission
**Red light** if dugga has been marked a fail, date from time marked
**green light** if dugga has been marked a pass, date from time passed

**Comment by d11karjo** [comment]
So the way I understand it, the light for the moment is going to be yellow if any dugga has been started, red if the moment overall is marked as a fail (possibly if only one sub-moment is marked as a fail, because that means you've failed the whole moment?), and green is all sub-moments are marked as passed?
