### ISSUE TITLE
Postgres migration

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1871]
There is now a test-branch for migrating to Postgres.

The hope is that it would be possible to use a configuration switch between postgres and MySQL and that the rest of the application (queries) would remain the same except for some minor parts (such as login) that would be different for postgres and MySQL.

**Comment by a97marbr** [comment]
I would argue that during this process an overview is done with respect to key words used as table names. For example:
* user
* password
Are used as tables. This is not recommended.

**Comment by HGustavs** [comment]
Are you saying for technical reasons or for general security reasons?

Secret table names only work for non-open-source projects e.g. if we want to know the structure of the database we view the source code....
However some databases use a table called user, and our table may clash with that.

If this is a very local change, I assume it is a worthwhile process but if we end up changing code in more than one or two places I think this is too great of an effort for little benefit.

**Comment by a97marbr** [comment]
It is for technical reasons. 

We have to make changes in the code regardless of if we change from **user** to for example **lenasysuser**. If we keep **user** all occurrences of 'user' in any SQL queries would have to be quoted like this in order to work in postgres: 
~~~
select * from "user"; 
~~~

**Comment by HGustavs** [comment]
Those quotes are evil.

I second changing user to lenasysuser

I really like systems that are agnostic when it comes to which database they use, and I think that supporting postgres is the first step towards widening the database support in lenasys.

**Comment by a97marbr** [comment]
:+1:

**Comment by a14jimso** [comment]
@a97marbr 
As we talked about last week, we will skip actually migrating to Postgres this term, but instead start with making all the queries database neutral (that way we can choose whichever database we want later on, and not just postgres). Like finding a different method for auto-increment that works for all databases, instead of mysqls proprietary method that only works for mysql.

**Comment by a14jimso** [comment]
@HGustavs 
Currently when you are adding a new student to LenaSYS, do you do this manually through something like phpmyadmin? We believe we have a solution to make a function that is similar to auto_increment, but should work for all databases. But without actually being able to add users through the site, we can't actually test our proposed solution, unless we save the actual command somewhere, which you then can copy-paste when adding a new user.

**Comment by HGustavs** [comment]
We do this by pasting a student list into access-editor window. This is the "Official" way to add new students. If the student already exists it is only connected to the course.

So in short, it can be tested by pasting a list of students into the access editor.

**Comment by a17robhe** [comment]
Migration seem unreasonable for one year of students to achive, closing this for now since it hasn't been discussed since 2016.
