### ISSUE TITLE
Play link do not appear to be grayed out?

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1878]
The play link should only be visible if there is something to play.

Also, I think that for the play button the links should be from a file list dropdown, not a text field (like code examples and so on).

**Comment by a97marbr** [comment]
I second this

**Comment by A15cecal** [comment]
@HGustavs @a97marbr It seems like there's a fix for this in codeviewer.js, in the function returned(data), but this one is not used anywhere. Is this correct?

**Comment by A15cecal** [comment]
We will ignore the first part of this issue for now. It might besolved already, and either way, there's no good way of testing this untill another issue related to this has been solved.

Fokusing on part two: 
Creating a dropdown list in playlink instead of a text field. This will be done with the same code as for the dropdown in code examples where you choose a file.

**Comment by a15elibr** [comment]
@A15cecal Since part two seems to have been resolved, is part one of this issue do-able?

**Comment by A15cecal** [comment]
@a15elibr It seems like @a15oscwe solved this as he was assigned an issue similar to this one.

**Comment by a15elibr** [comment]
OK, closing issue then.
