### ISSUE TITLE
There is one cog too many in the codeviewer menu

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1884]
There is one cog too many in the codeviewer menu. The second one should be removed?

**Comment by HGustavs** [comment]
Are we talking cogs or cog wheels?

**Comment by HGustavs** [comment]
I see only one cog wheel for the top menu and one for each display pane......

**Comment by a97marbr** [comment]
I see 2 ...
![cog-wheel-bug](https://cloud.githubusercontent.com/assets/4948661/13299573/02884efa-db3c-11e5-93bf-58b57101972e.png)

**Comment by HGustavs** [comment]
This is clearly a bug....

**Comment by b14antfr** [comment]
Could you specify how you came across this issue? What steps did you take etc

**Comment by HGustavs** [comment]
I am thinking that this issue happens when you are logged in as a superuser?

Furthermore, the chose layout button (third one) should not be visible if you are not a superuser or administrator. Currently students can see that button even though it does not work for them as it would change the layout for the example for all students if it did work.

Also, the play button should only be visible if there is a play link pasted, if there is no code in the play link no button should be shown (this was reported as a separate issue?)

**Comment by h14marma** [comment]
This issue does not seem to exist anymore. Perhaps it has been solved in a duplicated issue?

**Comment by b14antfr** [comment]
We're looking to solve the issue regarding the play button at the moment but I'm curious if you have an example somewhere where the play button is actually used, been browsing around and haven't found anything yet.

**Comment by HGustavs** [comment]
Since we got better previews this is less of an issue. But....

@a97marbr  has a good example of what it can be used for:
We have a mobile web page that makes use of screen orientation or screen size we dont want to run this only as a preview we want to run it in full-screen by linking to the preview but in full screen.

So I view it as a ful-screen variation of the preview.

Also the shader course, if I press the play button I get a link out of lena and into the preview pane page in full screen.

for example this link could be in a play button link and we would get to http://wwwlab.iit.his.se/gush/Shaderprogrammering/Tool_fbm.html

**Comment by b14antfr** [comment]
We haven't encountered anywhere that there are two cogs so we're going to be moving on from this issue for now.
It seems that the template problem was another issue so we're just been wasting out time with that since someone else has been working on the actual issue.
The play issue has been resolved aswell and was a different issue as you said.
