### ISSUE TITLE
Sorting duggas when marking

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1889]
Right now the order of students listed is based on UID. I want to sort based on the cloumns.
I suggest using the jQuery plugin tablesorter (http://tablesorter.com/docs/)
We should be able to sort on all duggas in order from oldest submitted to newest. A click in a particular column should yield a sorted result table with the oldest submitted dugga on the top row.

**Comment by b14kriwe** [comment]
So for each column (all of them), when you click on it all the results should be older->newer, meaning that we would have to sort on the time-stamp in the database, correct?

**Comment by b14kriwe** [comment]
@HGustavs Do you have any input on this?
Currently it seems that the Tablesorter sorts on the content of the TH or TD. The TD's are currently containing their own tables with tbody's that also contains div's, images and TR's. So there is no real value to sort on, since it's images. An idea that I have here is to eventually add an attribute (or two) to the "TD's" that should be sorted with a timestamp. BUT we would have to modify (I think) the tablesorter, or make us a script using that fitting our needs where it browses for attributes.

This _**may**_ end up in lot of work, if the script seems to not be easy to implement. Is this a viable solution you think? Also another issue is that there may currently be up to 5 dugga's per column (that should be sorted). We may face an issue here if the different dugga's are submitted at different times. Should it then use the newest submitted dugga as the one to sort on?

**Comment by HGustavs** [comment]
I would do the sorting in the database.

Much less headache it seems.

**Comment by b14kriwe** [comment]
Personally I'm good with sorting from the database, however that would have to reload the page right? Instead of Javascript just sorting it locally, the server will have to deal with yet another request, most likely hurting performance comparing compared to letting JS do the job? But the amount of work required for the database solution is far less then trying to fiddle with getting a solution ready for the "JS version".

**Comment by b14kriwe** [comment]
This issue will be resolved in #2136
