### ISSUE TITLE
All public content is not visable when logged in

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1898]
All public content is not visable when logged in.

If we log in to LenaSYS we should see:
**as user**
* all public content
* all private content that we have access to

**as super-user**
* all content (public, private, hidden)

**Comment by HGustavs** [comment]
I am not sure what it is that we are missing.

Screenshot?

**Comment by a97marbr** [comment]
When accessing as guest:
![not_logged_in](https://cloud.githubusercontent.com/assets/4948661/13509200/8f19cebc-e18a-11e5-9798-69ac42423b71.png)
When logged in, but not part of the actual course:
![noaccess](https://cloud.githubusercontent.com/assets/4948661/13509233/be5c1194-e18a-11e5-9c7c-c0bad8777686.png)

**Comment by HGustavs** [comment]
There seems to be some problem with public and private settings.

Conversely, we need to make sure that private content is not visible to guests or to non-members of the course.

**Comment by d11karjo** [comment]
Temporary fix implemented

**Comment by a97marbr** [comment]
Where? It would be great if there was a link to the code or merge request.

**Comment by d11karjo** [comment]
Niklas implemented a fix where guests are not able to access courses, though they can still see all listed public courses, by changing sectionedservice.php so guests are assigned a uid of "0", rather than "guest". The latter seemed to break the access system and automatically gave all guests read access to all public courses.
