### ISSUE TITLE
Section editor dugga deadline

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1909]
I would really like the deadlines for each of the dugga-s to be printed in the section editor (if a deadline has been given if there is none nothing should be written). Preferrably to the right of the entry as in the given mockup.

![mockup22](https://cloud.githubusercontent.com/assets/6978801/13649673/08408f5c-e63f-11e5-85a6-45564cad4f93.png)

**Comment by HGustavs** [comment]
And I do want it to use tables for the layout.

**Comment by b14kriwe** [comment]
This is already implemented in the code. The GitHub code already has this activated and it also fetching values from the database. If you add a "test", you set the deadline in there, then accessing the dugga's from the course, where you can modify them, adding a new one then choosing your test as "link" will give you your set deadline.

This issue is probably closed.

**Comment by HGustavs** [comment]
I agree. We jumped the gun here and implemented this one as it was so useful that we could not do without.

There is a bug though.

In that when there is a very narrow window like on a phone, the deadlines will overflow properly but the assignment text will not, breaking the tab lines.

![screenshot 2016-04-01 11 20 25](https://cloud.githubusercontent.com/assets/6978801/14203030/d0c767ca-f7fb-11e5-89d1-6494fe27cef6.png)

Im thinking it lacks  white-space: nowrap; in addition to clipped overflow.

**Comment by b14kriwe** [comment]
This is how it looks on my phone. In addition to the tab breaking, the overflow of some words are seeming to exceed their cell. This can be fixed by adding "word-wrap: break-word;" in the CSS for the link. As I assume this is something that should be fixed too?
![capture1](https://cloud.githubusercontent.com/assets/18162859/14204028/b64eff2e-f801-11e5-96cd-48d6ce812c7d.PNG)

**Comment by b14kriwe** [comment]
This issue has now been resolved. Instead of having the marking on the <a> link, the <a> margin was removed and a <div> was added wrapping the <a> element. The margin 15px was set to the new div. This will make the whole <a> element to wrap, instead of only the beginning of the string.

![capture2](https://cloud.githubusercontent.com/assets/18162859/14206336/b1ae5ab2-f812-11e5-9b09-be2d2d22ee97.PNG)
