### ISSUE TITLE
Developer documentation should be in GitHub Wiki

### ISSUE THREAD

**Issue by b14davbo** [HGustavs/LenaSYS#1941]
All documentation of LenaSYS should be be kept inside the GitHub Wiki, not in the actual source code. Doing this will with great probability make the project structure more clear.

Some files that I think should be migrated to the wiki:
- [/CodeViewer/Color scheme HEX.jpg](https://github.com/HGustavs/LenaSYS/blob/master/CodeViewer/Color%20scheme%20HEX.jpg)
- [/branch_merge_strategy.md](https://github.com/HGustavs/LenaSYS/blob/master/branch_merge_strategy.md)
- [/code_standard.md](https://github.com/HGustavs/LenaSYS/blob/master/code_standard.md)
- [/Markdown suggestion.md](https://github.com/HGustavs/LenaSYS/blob/master/Markdown%20suggestion.md)

**Comment by HGustavs** [comment]
Kind of.

We need some kind of a live help / documentation  system inside lenasys.

I think some combination of both wiki and markdown and inside-lenasys is optimal.

* Documentation for ourselves e.g. how to use markdown is fine in the repository main folder as we can simply check how to do markdown or code standards offline by looking in the code folder (as well as wiki?)
* If we have normal users (non-technical teachers) "look in the wiki" is not the optimal way of doing it. In that casewe need an organized form of help icons or help texts inside lenasys in some way, albeit unobtrusive in order to not incite regular users. 
* Things that fall in-between those two extremes... well...

**Comment by HGustavs** [comment]
In short, offline-capable developer documentation is one thing and online-built-into lenasys is another.

**Comment by b14davbo** [comment]
Absolutely. What I want to do is to move the documentation for the developers from the source code to the wiki.

**Comment by a97marbr** [comment]
I agree that using the GitHub Wiki for development documentation is a good place (as I said when I talked to you guys). I also see the point that @HGustavs is bringing up -- the offline developer, for those an actual file is crucial.

As a second comment: **you should not commit anything into the master branch directly - this is done at merge days, i.e., Thursdays during this course**

**Comment by b14davbo** [comment]
@a97marbr My bad, removed from wrong branch.

**Comment by a97marbr** [comment]
:+1:
