### ISSUE TITLE
SQL code does not follow Code Standard.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1963]
A lot of the SQL code (in all parts of the project) does not follow the code standard i.e. capitals on SQL code.

so code should read
~~~
SELECT filename FROM submissions WHERE type=2 AND length=2;
~~~

and not 
~~~
SELECT filename from submissions where type=2 and length=2;
~~~
...

furthermore we should avoid star in selects and list columns instead

It is much less error prone to write
~~~
SELECT filename FROM submissions;
~~~

than

~~~
SELECT * FROM submissions;
~~~

Also. all inserts should read 

~~~
INSERT INTO submissions(ColA,ColB,ColC ) VALUES(1,2,3)
~~~

and not...

~~~
INSERT INTO submissions VALUES(1,2,3)
~~~

even if that line does not produce errors.

And all sql code should end with ;

**Comment by HGustavs** [comment]
Updating the code standard accordingly if some of this is missing...

Any other suggestions for code standard for SQL?

**Comment by HGustavs** [comment]
I added this issue since I tripped up mystelf in the sql code....

I need to be really close to the screen to differentiate and vs. amd but I can see the difference between AMD vs AND very clearly.

**Comment by a14didda** [comment]
In the cases where a select (or whatever query) will take all values from a table, do we still need to include every column instead of the star? Is it necessary to change this?

**Comment by a97marbr** [comment]
Yes. Due to the fact that a table might get more columns in the future. Being specific is a very good approach, albeit cumbersome at times ;)

**Comment by HGustavs** [comment]
It is more self-documenting that way, the star does not say anything about what we are using it for

~~~
SELECT * FROM person;
~~~

compared to

~~~
SELECT firstname,lastname FROM person
~~~

**Comment by a14didda** [comment]
Okay! We will take care of that. However I need to ask: where is this benchmark table? I´m unable to find it in the database, but it is used in the parseagents.php file.

**Comment by HGustavs** [comment]
It may have been removed. I am not sure that all that code works as intended.

**Comment by a14didda** [comment]
Then I´ll just leave it there for now and if it´s needed, it will be taken care of in #1926.

**Comment by a14didda** [comment]
After changing everything, the following lines produce errors if we do not use the stars there: 	

`$query=$pdo->prepare("SELECT COUNT(*) AS unmarked FROM userAnswer WHERE cid=:cid AND grade = 1 AND submitted > marked;");`

`$query=$pdo->prepare("SELECT COUNT(*) AS unmarked FROM userAnswer WHERE cid=:cid AND submitted IS NOT NULL AND useranswer IS NOT NULL AND grade IS NULL;");`


We need to have the stars here at this time because if we add every column instead, it cannot read all the columns - it seems that variables are not fetched and thus results in errors. Chances are the table is too large and thus needs to be normalized. We will keep the stars as is until that has been done if needed.

**Comment by HGustavs** [comment]
Imho Count(*) and * are not the same.

I am fine with count(*) as it gives a single defined column.... even better that it has a name unmarked. No complaint there.

What I am against is generic 

SELECT * FROM whatever

**Comment by a14didda** [comment]
Then there are no problems. Issue is solved then.

**Comment by a14jimso** [comment]
This has been fixed for everything except those mentioned.
