### ISSUE TITLE
Copy documentation from Wiki to source

### ISSUE THREAD

**Issue by b14vikgu** [HGustavs/LenaSYS#1994]
The documentation should exist in the source for offline reading.
Create md files in the source for each wiki page and copy the contents.
This could be done in a subfolder at the source tree root. perhaps Documentation.

**Comment by b14vikgu** [comment]
An idea could be to create a [gh-pages](https://pages.github.com/) branch for documentation. That way it would be readable both online at hgustavs.github.io/lenasys, and offline in the gh-pages branch of the repository.

The documentation could then be made more as a static website (in pure HTML), with navigation and such.

What do you think @HGustavs?

**Comment by HGustavs** [comment]
Im thinking markdown format for all documentation regardless of purpose, easier to edit than html without errors or risk of exploits. Question is whether we want new markdown functionality for documentation.

* programmer documentation in the repository so that programmers can view documentation in the repository when offline e.g. code standard. 
* Documentation in the sense of how-to for lenasys users e.g. how to create users or add a new courses is best stored as forum posts like faq-style. e.g. if we have a help icon for the create user page we end up in a forum post, this allows users to seamlessly ask for clarification on documentation content.

**Comment by b14davbo** [comment]
@b14vikgu I suggest using [](https://readthedocs.org/) or something similar, this is used in many big projects such as CodeIgniter. See their user guide [here](https://codeigniter.com/user_guide/). They also provide a local copy of the documentation in their Git repository.

**Comment by HGustavs** [comment]
Im thinking markdown format for all documentation regardless of purpose, easier to edit than html without errors or risk of exploits. Question is whether we want new markdown functionality for documentation.

* programmer documentation in the repository so that programmers can view documentation in the repository when offline e.g. code standard. 
* Documentation in the sense of how-to for lenasys users e.g. how to create users or add a new courses is best stored as forum posts like faq-style. e.g. if we have a help icon for the create user page we end up in a forum post, this allows users to seamlessly ask for clarification on documentation content.

**Comment by b14vikgu** [comment]
The dev-documentation has been added to the Documentation folder in the source tree and the how-tos will be added to the forums later. Closing this issue
