### ISSUE TITLE
Redesign suggestion: ResultEd

### ISSUE THREAD

**Issue by Skabunkel** [HGustavs/LenaSYS#2136]
The current page used to grade duggas and tests is big heavy and not very pretty.
so i suggest that we redesign it to look like the image below.
![result](https://cloud.githubusercontent.com/assets/9131566/14520942/41804a4c-0227-11e6-855a-ad91f1aadf55.png)

Let me take you throught the layout.

Total students lists the current amount of students who can get anysort of mark.

The next colum is notice it will count the students who have returned something that hasnt been marked.

The next is colums are passed grades per moment, simlar to the system that is implemented in our test version.

After that is Student entrys, every entry has to components a head that is always visibal and a body that is loaded via Ajax when the head is clicked.

This would reduce load time since the current system loads every student and there exams at the same time. Using some back of the envelope calculations we can say that the current system provided that it loads 5 moments with one entry and 5 with 4 sub entries we get 25 fields per student, this for 39 students is 975 database fields that needs to be processed via JS, increase it to 128 students and we have 3200 fields that needs to be printed out.

In this new system we would have 6 field per user and for 128 students that's 768 fields for the system to print out and update.

**Comment by HGustavs** [comment]
No this does not quite do what we need.

Do we have any performance data to support that the javascript is the reason that the view is slow?
* I am thinking that it is a database issue.... since the processor in the browsing computer should be able to process millions of data items relatively fast.
* If javascript is the problem this can be solved by not updating the view on every change, but on refresh.

We need two things...
* to get an overview of all students, who has submitted at all, and who has not submitted anything, kind of a "where are we" view.
* to get an overview of specific students for specific assignments to do marking.

I am thinking that we can do both, with filters.

There should be a line limiter e.g. the sql should be:
~~~
select * from blabla limit 25
~~~
i.e. we only collect information for 25 students at a time unless we explicitly say: get all students...

so I suggest a dropdown students with options for 0-25, 25-49, 50-75, etc etc and ALL as the last option, with 0-25 being the default.

This way we see only 25 students at a time except for when we are viewing all students for making result lists on paper or to get an overview of all students.

If we combine this with a filter for each assignment that we can click..... to limit the queries to for instance only showing dugga1 ... or dugga1 and dugga2 ...

By doing this we are limiting the database to a small subset without missing any information.

I however DO like the way that we are sorting the stuff with the moments first and each dugga afterwards.... much better than the current layout.

**Comment by HGustavs** [comment]
Also from a usability standpoint I want to limit the number of clicks as much as possible....

If I have to do one additional click for each student this makes thousands of clicks and scrolls for each marking of an assignment, which is unsuitable from a work-flow-standpoint.

We want a workflow that is: click-mark-click-mark-click-mark without additional clicks or scroll actions.

But with the solution I suggested I get very few clicks.

One click to limit marking to only assignment 1 or for example two clicks for assignment 1 and assignment 2. (checkbox or modal button for each assignment)

Then I can immediately mark the first 25 entries for assignment 1.... then I can move on to the next 25 with one click.

The load on the database access requirements should be much smaller if we only do 25 students times a few columns at a time (ideally one at a time).

**Comment by HGustavs** [comment]
In short, I vote for

* Make the layout in the mockup with separate moments and assignments, which is much clearer than the current

| Moment A                                | Assignment 1 | Assignment 2 | Momment B | Assignment 3 |
|-----------------------------------------|--------------|--------------|-----------|--------------|
|                                         |              |              |           |              |
|                                         |              |              |           |              |

* Add filtering, to filter out only the assignment(s) that we are marking at the moment.
* Limit view to 25 students at a time but with an option to "all students" with confirmation (are you sure?) alert to get a full course overview of all students.
* @a97marbr suggested that if possible we add an option for sorting the student list on oldest unmarked assignment or newest unmarked assignment in addition to the current name-based sorting.

**Comment by a14nikau** [comment]
Would something Work?
![mokup_resulted](https://cloud.githubusercontent.com/assets/9131566/14530673/490134ba-025a-11e6-9766-224f1f09f9b9.png)

**Comment by HGustavs** [comment]
Can you take me through the arrows and what they mean. Is the arrows the sorting order?

I am thinking along these lines - Show 25-50, assignment 1-3 and moment A are shown, we sort on newest unmarked in assignment 3. The rest of the moments and assignments are hidden.

![foo copy](https://cloud.githubusercontent.com/assets/6978801/14537598/f03ad4e4-0277-11e6-87ed-7408a84049df.png)


Any combination of assignments or moments could be chosen. Perhaps it would be a good idead to have a button somewhere to show all assignments.

Somehow the marking icon is lost in your mockup, so I added it back.

**Comment by HGustavs** [comment]
Thinking about this overnight....

I came up with this suggestion.

Not all information is required to be read every refresh, only the results change rapidly, but student enrollment and moments change more rarely.

So I suggest reading the information **twice**.

one service call "READSTATIC" which is called once per page refresh to collect the student list and the moment list and then store this information in in-memory javascript arrays.

and one service call that is used to read the results and render the list e.g. "READRESULTS".

For rendering the table we read from memory, rather than from the JSON data most of the time for the student list, moment list and so on.

This can reduce the database load even further, this way when a mark is set, or when we read the assignment or results of a student we only read that information and refresh the list, we do not read the full database.

Also the application will be sligtly more separeted on the service level.

**Comment by HGustavs** [comment]
Im thinking that issue #505 is probably also possible to merge into this issue, and that we can retire that old issue.

**Comment by a14nikau** [comment]
After gathering some data related to the execution time of part of the current Resulted.php the following can be said
![exetime](https://cloud.githubusercontent.com/assets/9131566/14598760/13753f60-0554-11e6-93c9-9b1fef98d5da.png)
"Total php time" measures how long it takes for the entire resulted service.php file from top to bottom. 
"Javascript returnedResults time" is the time it takes for the function returned Results in resulted.js to finish execution. the above test was done with 40 students and repeated about 10 times with similar results.

**Comment by c14emian** [comment]
Could we get an update on this? As far as I understand a lot of changes have been made since the issue started and I'm not sure what still requires fixing.

**Comment by a15freed** [comment]
bump :) @HGustavs

**Comment by a17pongo** [comment]
@HGustavs bump ;) 
This issue seems to be fixed? 
or should I create a new issue about performance problems?

**Comment by HGustavs** [comment]
I am pretty sure this has been resolved.
