### ISSUE TITLE
Specific grade doesn't show up when hovering a corrected dugga

### ISSUE THREAD

**Issue by b14davbo** [HGustavs/LenaSYS#2155]
If a student pass a dugga, he cant see what grade he actually gets. If you hover on the green circle you can only see "Pass" and the date the submission was corrected. You should be able to see the specific grade G / VG and 3 / 4 / 5.

**Comment by b14kriwe** [comment]
![screenshot from 2016-04-19 09-14-27](https://cloud.githubusercontent.com/assets/18162859/14630944/18f2afdc-0611-11e6-8ca2-bbe5a92e6e96.png)

This now displays the grade G or VG. It's not possible in the current system to give a student the grade 3-5. Färgdugga 2 is supposed to have the grading system U-5, but as you can see, you can only give the student U. So this issue is resolved with the current system that is in use.

How it looks now? Instead of the current "Status: Pass" You have "Grade: G" or "Grade: VG".

@a97marbr What is your input on this?
