### ISSUE TITLE
Hovering over highscore problem

### ISSUE THREAD

**Issue by g13johbj** [HGustavs/LenaSYS#2296]
When hovering over the highscore symbol, sometimes when you go over it fast or something like that, the popout window does not disappear when the mouse isn't hovering over the symbol anymore.
![highscorebug](https://cloud.githubusercontent.com/assets/9322288/14951057/98ab799e-1056-11e6-9404-e2dc10ea49c4.png)

**Comment by d11karjo** [comment]
After some research it seems that this is due to a limitation in the programming language, rather than anything in the code itself. It is possible to create a workaround, but that will increase the performance requirements, seeing as it essentially requires a loop that constantly checks whether or not the pointer is within the Top 10-icon.

**Comment by a16konka** [comment]
This issue has been handled in a different way, propably through a different issue. Therefore this issue is no longer relevant.
