### ISSUE TITLE
Should items related to a moment be removed with the moment?

### ISSUE THREAD

**Issue by k14marst** [HGustavs/LenaSYS#2347]
Right now, if you remove a moment, the items in that moment (duggas, links, etc) are still there. Should the items also be removed or should it stay like it is now?

**Comment by HGustavs** [comment]
I would leave it as it is.

Perhaps one wants to change something, moving one element from one moment to another.

**Comment by k14marst** [comment]
Well, you can still do that can't you? If you add deleting elements of the moments deleted you could still move elements before deletion. Or it would be possible to add a pop-up menu where you could choose to, for example, either delete the elements, move them or leave them as is.

**Comment by HGustavs** [comment]
Im thinking that by design, the different sub-parts should not be connected at all. 

It is more common that one moves one piece of content from one part of the course to another and very rarely one needs to delete a complete section of a course.

I would treat *any* deletion as a unicorn, and deletions of all sub-sections of a course are liike decacorns or hectocorns... e.g. so rare that we dont need special code for it.

**Comment by k14marst** [comment]
Yeah alright. That makes sense. I'll close this issue then.
