### ISSUE TITLE
Login timeout

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2417]
The login timeout is probably the most grievence-causing issue so far.

A student may be working for a long time on an exam or a teacher may likewise be working on reading a document for a long time, if the system times out during this time, no change is visible on screen.

* Make the timeout visible on screen (either by polling every minute/30 seconds etc) or some other means
* When one logs back in, the redirect should return to the same page, not to the main page.
* Currently one has to click the login button twice, once to log out once to log in again. Even though the user already has been logged out through the timeout.....

**Comment by a15tobli** [comment]
Hello! We have been working on a timeout-message which will display an alert shortly before the 5-hour sessions ends, issue #2486. This will help to prevent users from getting timed out by prompting them to stay active by adding a button to reset the session timer. 
At the moment we are not working on any code regarding what happens when the session has timed out.

**Comment by a15tobli** [comment]
Two alerts have been added, one displays 30 minutes before the session ends, and another when it has expired. Our current work progress is to add a button which allows a session reset on the first alert, #3200 and updating the user icon from green to red when the user has been logged out, issue #3199.

**Comment by a15ponja** [comment]
Closed due to issue cleanup, was done.
