### ISSUE TITLE
Using a direct link to a page that requires login is shown to guest

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#2436]
There does not seem to be a proper credentials check for showdoc.

Using a direct link to a page that requires login is served by showdoc to guest

**Comment by d16linja** [comment]
On what example dugga can i see if the changes work or not?

**Comment by d16linja** [comment]
Already solved

**Comment by d16linja** [comment]
Realized what the problem was, reopened the issue

**Comment by c16matan** [comment]
The implemented change was not good from a continuous development perspective, so that merge got reverted. @HGustavs I did not find any other data in $_COOKIE other than the PHPSESSID variable, any other idea of how to solve this? As you mentioned we can do a proper course credentials check, but currently i don't know how this could be implemented to also check for each moment without the actual moment identifier.

**Comment by c16matan** [comment]
Approved verbally from @HGustavs. Closing.
