### ISSUE TITLE
Dugga template - Seminar dugga

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#2462]
I would like to have a dugga template(s) that provide a good way to represent
* registering to a seminar 
* provide an automatic (or at least a semi-automatic) presentation scheme with 
* optional number of opponents 

I believe that inspiration can be found in the feedback dugga and that we should divide this into a register for seminar dugga and a presentation scheme dugga

**Comment by a15alica** [comment]
@a97marbr What things do you want to be a part of registering to a seminar? Students just letting the teachers know they want to be in a seminar or more things? Date preferences? PDF, links text or something like that?

An automatic presentation scheme - what would that include? Which parts could be automated and which parts should you do yourself?

**Comment by HGustavs** [comment]
File upload that is goup only e.g. if we want specific articles for specific groups in specific seminars, we can do that.... so at the very least a way to attach a file link (markdown or pdf) for each group seminar.

**Comment by HGustavs** [comment]
Do we have  mock-up for what this thing may look like? Kind of hard to visualize what we are discussing...

**Comment by a17maxsj** [comment]
Is this issue still relevant? @HGustavs  @a97marbr

**Comment by a17joaap** [comment]
Beautiful mock-up:
![seminarmockup](https://user-images.githubusercontent.com/37792198/57520466-044ed880-731e-11e9-964e-ce33fe2ca5f9.png)

Still unclear exactly what you want in this dugga.

But I'm thinking you have to add variants in this format: {'group': 'A', 'link': 'the_article.pdf'}
This way we can check when the student enters the dugga which group they belong to and load the correct file. I'm also thinking we need a new database table for seminars, so when one person in the group clicks register to seminar, the whole group is registered. Or do you want it so that every person in the group has to register?

Feedback needed @HGustavs @a97marbr

**Comment by c20adael** [comment]
I'm pretty sure this is fixed and a review is needed so see if it exists.

**Comment by a20johba** [comment]
Added template files seminar_dugga.html and seminar_dugga.js as well as new entries to the quiz and listentries tables in demoCourseData.sql, making the Seminar Dugga visible in the Demo Course after installation. The seminar page has been modeled after the mock-up and appears correct. Further development will be necessary however, since deeper functionality such as adding registered users to the database, saving uploaded files, and automatic loading of group data is still missing. More checks to ensure correct username input may also be necessary.

**Comment by a20behta** [comment]
merges in during weekly merge
