### ISSUE TITLE
Display notification before session ends

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2486]
A user's session ends after being inactive for 5 hours which results in the user being automatically logged out. Add notifications that displays on the site soon before the session ends. This would help to prevent student from being logged out and having the risk of loosing any work made on the site. 
Related issues:
#2627 - Add styling for this message
#2690 - Add icon for this message

**Comment by HGustavs** [comment]
Not a bad idea...  if we are revising the login-system anyhow....

how could this be implemented? 

Suggestions?

**Comment by a15tobli** [comment]
A suggestion is to check the timer of the session declared in the loginlogout.php. By using a selection you can check when the timer drops below a set number, e.g. 5 minutes. When the statement is correct an alert would display which asks if you want to renew your session. If a confirmation is sent, a reset on the session timer would occur which set the session timer back to 18000, giving 5 more hours.

**Comment by HGustavs** [comment]
Lets try it out and see if it works... it seems like a promising solution to that problem.

**Comment by a15tobli** [comment]
Great! We will begin implementing this feature.

**Comment by b14larek** [comment]
This turned out to be harder to implement than I first realized, since I'm trying to solve this client-side with javascript. However, I created a function with a cookie that at least seem to persist in all subdomains, the issue I'm currently tackling is how to solve the issue with the cookie being reset evertime a page is refreshed. Thus invalidating the timeout function since it's constantly being restarted. I think I can find a solution by using local storage though to circumvent the problem with page reloads.

**Comment by HGustavs** [comment]
I would store a time variable when the page reloads and compare with that variable once every second and see if it is over 5 hours....

Should only be a few lines of code?

**Comment by b14larek** [comment]
That seems lika a viable solution. Another one I figured I can try is to split the original script into two functions, one that sets the cookie and one that destroys it after a certain time and returns the aforementioned alert. I just need to find a place in dugga.js where the set cookie function is only called once,  so the cookie won't be overwritten, since that's the critical component. The other function isn't adversely affected by page refresh.
