### ISSUE TITLE
When a file is uploaded to a dugga, no feedback is given to the user what so ever

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#2532]
For instance when uploading a file here: 

http://webblabb.iit.his.se:8080/grupp2/b15matol/LenaSYS/DuggaSys/showDugga.php?cid=2&coursevers=97732&did=19&moment=2042&segment=2039&highscoremode=0

Where the * did the file go?

**Comment by HGustavs** [comment]
Is the user logged in?

If the user is not logged in, nothing should happen.

Check the javascript console for any errors in the json data.

**Comment by a15tobli** [comment]
Hi! I tried uploading a pdf-file in the correct submission, I had no problems with this. When adding non-supported files the page displayed feedback that the file format was not supported for uploading. (e.g. .jpeg file in the undefined submission) 
I assume you were logged in when trying this, since the submission field won't show up otherwise. Which file format was used when this was discovered? Could it be that there is an issue with a certain file type?

**Comment by b15matol** [comment]
Hello, 

This issue can be closed. The problem was related to a specific template for duggas and not a general problem as this issue insinuates.
