### ISSUE TITLE
Courses gets duplicated in the list

### ISSUE THREAD

**Issue by A15cecal** [HGustavs/LenaSYS#2535]
Some courses in the list gets duplicated (ex. "datorns grunder" shows up twice in the list).

**Comment by HGustavs** [comment]
May be a problem with the test data in the installation script?

**Comment by a15freku** [comment]
Yes i think this has to do with the testdata file because in the database there are two "datorns grunder" with different course code (DA121G and IT115G) but still unique id. Maybe there was an old "datorns grunder"-course. 

So i think this is normal but we could remove the old course from the testdata.sql file if it's misleading.

**Comment by a15elibr** [comment]
Closing issue.
