### ISSUE TITLE
Add table in dugga editor

### ISSUE THREAD

**Issue by a15osmla** [HGustavs/LenaSYS#2548]
Add a table to show submission ways in a list and you should be able to delete rows in the table.

Related to #2547, #2545, #2544, #2546

**Comment by HGustavs** [comment]
Dont quite understand this. More details please.

**Comment by HGustavs** [comment]
Are we saying that a table should be created that contains the names of each of the submission types e.g. PDF, ZIP, LINK etc? 

That sounds like a good idea, if we want to add more submission types a first step would be to insert a row into that table....

I suggest 

Storing an ID, a short name, a long name and a description

...

We can show the name in the dropdown but also have a description as a tool-tip.

**Comment by b15matol** [comment]
Hello HGustavs,

This and the referenced issues together make up a larger issue. We had some problems interpreting the JSON-dugga problem. Yesterday we realized that when editing a dugga, JSON is used as a "variant" and edited through a popup window. 

So the person editing must write the variant as JSON manually which is a painstaking task. Instead of writing it manually like that, we created these issues to come up with a solution to dynamically create the JSON through a form, or table, of input elements. Some javascript function can then create a JSON string out of the inputted data. 

Something like this, the old solution is at the top and a draft of the proposed new the bottom of the picture: 

![capture](https://cloud.githubusercontent.com/assets/26713381/24543073/69b8f964-15fe-11e7-81e5-3998165fb36f.PNG)

Hopefully this will result in the fact that the editor does not need to edit the JSON string manually, but that is created through the form instead. 

BR b15matol

**Comment by HGustavs** [comment]
![screenshot 2017-03-29 20 01 27](https://cloud.githubusercontent.com/assets/6978801/24550013/76c7c78e-161c-11e7-8357-d9e8b4baf923.png)

Something along these lines from the image above, dont remember which issue I posted that image in...

**Comment by a15tobli** [comment]
Merged in #2601, closing issue.
