### ISSUE TITLE
Send form data to table in dugga editor

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2621]
By using the form added in #2547, implement a way to send this set data into the HTML table implemented in #2548.

**Comment by a15alica** [comment]
This issue is no longer working in the same way since the design has changed. Instead of using data from a form and putting it into a HTML table we add new form fields and use the data directly from them to create a JSON string.

Because of that this issue has changed a bit. The box needs styling so that the added form fields fit. A delete-button is also needed for each part of the form since you might want to change or remove submissions.

**Comment by a15tobli** [comment]
Closing issue, we will work with the new changes in #2773.
