### ISSUE TITLE
handle tables in markdown.js

### ISSUE THREAD

**Issue by d15johro** [HGustavs/LenaSYS#2636]
markdown.js is currently not handling tables. This should be implemented in function parseLineByLine(). Possible create new function for handling this issue and invoking it in parseLineByLine()

**Comment by HGustavs** [comment]
It is more important to handle "easy" tables rather than the "messy" tables used by the still renders nicely example.... as that first type of tables is much more readable by users.  So I would concentrate efforts on the "normal" tables and not implement the "messy" style tables.

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

**Comment by a15ramha** [comment]
This issue is a duplicate to #1781 and therefore it will be closed.
