### ISSUE TITLE
Add form to change password on user page

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2638]
Extend the user setting page with a form that allows change of password for the user.

**Comment by HGustavs** [comment]
Good idea.

**Comment by HGustavs** [comment]
Is there a way to only allow this on https?

**Comment by c14caran** [comment]
Make sure to limit new password lengths to 72 characters. Give an error if the new password is longer than that. This limit is from bcrypt, the password hashing function that the system might change to by implementing issue #1964 . As 72 characters is already very big it should be fine to limit to this even before that issue is fixed and implemented.

**Comment by a15tobli** [comment]
The forms and max password length have been added in #2958 and #3070. Functionality to change password needs to be added to the form.
