### ISSUE TITLE
Attribute Dropdown Option - Composite Attribute

### ISSUE THREAD

**Issue by a14davlo** [HGustavs/LenaSYS#2748]
Create a menuoption inside the double-click dropdown menu where you can turn an attribute into a composite attribute. A composite attribute does not look different in appearance from a regular attribute, the functionality is different. A composite attribute can have attributes be connected to it while a regular attribute cannot have attributes be directly connected to it.

#2576 root issue

**Comment by a15gunfu** [comment]
This issue should be re-defined and more clearly described since it can be easily misunderstood. 

After discussing this issue with the group leader and two other colleagues we reached this conclusion - it is now possible to connect all types of attribute to each other. What needs to be done is to make it possible to re-define an attribute to make it composite and only make it possible for this option to connect it to other attributes.

**Comment by c16jonha** [comment]
This issue will be solved through Issue #4601

**Comment by c16jonha** [comment]
This issue is no longer relevant and will now be closed.
