### ISSUE TITLE
The security challenge answer is case sensitive

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2828]
When answering the challenge question in any form where it's included, the answer can easily be misstyped if you a user do not know if they had lower- or uppercase letters. This could create a problem in issue #2822, where a barrier stops you from making too many attempts. By entering the wrong input because of a letter not being in the right case, these attempts could quickly add up and temporarily lock out a user from resetting password. 
The challenge answer is NOT a password, and that's why this could be implemented without problems consisting of compromising security.

**Comment by a15ponja** [comment]
It is worth to note that whoever implements a way for the user to add a security question and answer for said question will have to save the answer as lowercase or the user will not be able to ever answer it, since when the user enters the answer in the forgot password screen it's treated as if it were lowercase.

**Comment by e14johho** [comment]
This is solved, regarding the comment @a15ponja did above this has been forwarded to the developer that is responsible for that area in the system. Closing.
