### ISSUE TITLE
When logging out you are redirected to first page, not the current page.

### ISSUE THREAD

**Issue by a15eriho** [HGustavs/LenaSYS#2946]
When pressing the logout icon, the user is directed to the first page.

The redirect should reload the current view in a logged out state. Not clear on where to redirect when the view is not accessible for a guest.

**Comment by a15tobli** [comment]
Hello! Found that this issue is relevant to one of the fixes for #2417, where the same functionality is desired when a user gets a timeout of their session. Group 2 suggested to fix this issue from a timeout perspective at a later stage, thereby I wonder if this is something your group intended to implement? 
I assume the code can be implemented in a way that it's working the same, no matter if you log out manually or because of a dropped session. If that's the case, we can refrain from fixing that part as the solution to this issue should solve ours as well.

**Comment by HGustavs** [comment]
This is an annoying issue for sure. Logging in works as expected but logging out does not...

**Comment by a15elibr** [comment]
@a15tobli Any status on this? Have your group implemented this? If not, my group can look into this

**Comment by a15tobli** [comment]
@a15elibr This is not something that we have been begun implementing yet. Your group can fix this issue, hopefully your solution will fix so that it works with a timeout aswell. If not, that is something we can create a seperate issue for at a later stage.

**Comment by a15elibr** [comment]
Roger that!
