### ISSUE TITLE
Icons in LenaSYS should be checked

### ISSUE THREAD

**Issue by a15freed** [HGustavs/LenaSYS#3038]
Icons under /Shared/icons should be checked if they are in use in LenaSYS.

If they are in use they all should get the "ALT" and "TITLE" attribute if a user for some reason cannot view it. 

Icons should also be checked using for example https://images.google.com/ to see if they come from a webpage or are made by us. If they come from a webpage (ex creative commons)  they should not be used in LenaSYS but not removed from the icons folder. Instead we should create our own icons.

ex these smileys need to be checked if they come from a webpage:

![image](https://cloud.githubusercontent.com/assets/26706932/24959398/f3651538-1f92-11e7-8593-652041988813.png)

**Comment by A15cecal** [comment]
Checked the images in use and I don't think the alt/title-tag is necessary. Where it's needed it's already in use and the rest of them don't need one.
I will refer to this guide for further explanation:
https://www.w3.org/WAI/tutorials/images/decision-tree/

Could not find anything on the web on the images being used, so I think they are OK to keep.

I think we can close this issue since there's nothing to do here.

**Comment by a15elibr** [comment]
I agree with OP, all icons should have an ALT and a TITLE, regardless of use. They are often used as navigation and need to have an ALt-text if the icon doesnt load. The guide you linked also says that everything used as navigation or other similiar uses should have an ALT-tag. So I think you should check all icons in use and add tags if they are missing.

**Comment by A15cecal** [comment]
@a15elibr They do, they have an title tag. This can be closed

**Comment by A15cecal** [comment]
Checked the folder and could not find anything that was out of order. Might have missed something, but if so this issue can be opened again when someone finds something. Closing issue.
