### ISSUE TITLE
Add functionality to security question box on the profile page

### ISSUE THREAD

**Issue by a15timbe** [HGustavs/LenaSYS#3142]
You need to actually be able to change your security question by submiting the form on the profile page. You will need to load and save to the database to enable this functionality.

**Comment by a15ponja** [comment]
Since we changed from allowing the user to input their own security question to a selection of predetermined questions, which was the plan from the start. We should maybe consider to revamp how we save the question in the database, since we will save a lot of duplicate data if the system stays as it is now. I would say that we start saving questions as a relation between possible security questions to a user instead, i would like to hear your thoughts on this tough @HGustavs

**Comment by a15ponja** [comment]
I talked with Henrik about my last comment and we are to keep it the way we have it now, since its more flexible.

**Comment by a15timbe** [comment]
Solved in #3544
