### ISSUE TITLE
Prepare to make every cell a button in grouped.php

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#3337]
Need to adjust the file grouped.js, to add the cid of the course and the lid of the listentry to be able to identify the cell. This should be placed in the id of each table cell, in the format `<cid>-<lid>`, for instance `#2-2013`. This should in theory make each id unique, which is desirable. 

Also add a function in grouped.js that handles the onclick event of each cell. This function should for now only `console.log` the id and lid of the cell, in some "interpreted" format like "Cid of the cell is <cid>, lid of the cell is <lid>". 

This is a preparation to enable to toggle group assignment directly in the group editor view. The cells that should be enabled as buttons are the ones under each moment. In the below screenshot, this is the three last columns: 

![skarmavbild 2017-04-26 kl 10 53 53](https://cloud.githubusercontent.com/assets/26713381/25426244/c874a2c6-2a6e-11e7-9ae5-17dbf9232451.png)

As usual, related to the larger issue #2441.

**Comment by HGustavs** [comment]
To me this list may not be organized logically...

If I have a class of students and I want to assign groups to each student... how do I do that in this view?

**Comment by HGustavs** [comment]
To me it seems like this view is from the view of the group and not the students or the teachers?

If the first column contains the name of the student we could then proceed by assigning groups by clicking a dropdown on each assignment (e.g. 1-5) ...

If we want to se all members of a group we sort on that column, all 1-s are in first group and so on, and any un-assigned student comes last.

We can set participation in a seminar by clickin a sopligt-button, and mark a group assignment by clicking some other icon. 

if someone wants to change group we just click the dropdown and select for example group 2 instead of group 5.

The data in the database then becomes student 1234 connected to assignment 4 with group number 2.

...

**Comment by b15matol** [comment]
Hello, this is very much a work in progress. The page is intended for the teachers, and it is for assigning students to groups as well as assigning groups to assignments. 

What is displayed in the picture is how the page looks right now. This issue is meant to improve that, and the idea here is that there should be stoplight buttons to assign groups to each assignment. That is what this issue is trying to fix. 

The data in the database is precisely as you said, and we also had an idea to use dropdown lists to add students to the groups. But that is for the future as of now. 

Thanks for the comments!

**Comment by b15matol** [comment]
A small update, at first we decided to have all the students belonging to a group in one cell. But the comment above from HGustavs seems to request a single cell for each student, so this issue will fix that as well.

**Comment by HGustavs** [comment]
I think having the group as a dropdown makes it easy to see which students that have not been assigned groups... also I would like standardized group identifiers int that list e.g. 

1,2,3,4,5
A,B,C,D,E
Sven,Greger,Egon,Örjan

...Well, maybe not that last one...

**Comment by a15timbe** [comment]
This was solved in pull request #3397
