### ISSUE TITLE
Change the option buttons to improve the user experience

### ISSUE THREAD

**Issue by b15matki** [HGustavs/LenaSYS#3361]
The current state of the buttons on the diagram page needs to be redone to follow the style of the site.

![knappar](https://cloud.githubusercontent.com/assets/26705132/25473796/1799cc2e-2b31-11e7-9f12-802fabfe852b.png)

Above you can see what the goal of the button structure is supposed to be. The lines dividing the buttons indicate the different sections of the button types and therefor also needs to be implemented.

1. The following buttons are:
- A drop of the following options.
      - Delete all.
      - A placeholder icon of a "save-floppydrive".

2. The following buttons are: 
- Create entity.
- Create line.
- Create class.
- Create relation.

3. The following buttons are:
-  Square figure.
-  Draw free figure.

4. The following buttons are:
- Zoom in button.
- Zoom out button.
- Move button.

At the moment you don't need to fix the debug, delete object, change apperance, removed hashed diagram and also the save state option since the functions is going to be revised. They can be moved to the side or put somewhere where it won't affect the new buttons.

**Comment by a14davlo** [comment]
Here's the design. The svg files been uploaded on G4's G-drive folder.

I'll add them into my code on Friday.

![projekt i software engineering paint](https://cloud.githubusercontent.com/assets/26733328/25486531/c714feaa-2b61-11e7-9e90-c62528bf64db.png)

**Comment by a14davlo** [comment]
@a15perbl 
@b15matki 
@HGustavs 
Here's the progress I've made during 2nd May Tuesday. They're on my grupp04 a14davlo server inside the shared/icons/ folder and their names all start with "diagram_" to make it easier to find.

Right now if you open up the php I've momentarily placed them there in a small size. They're in that location for the time being and will become the buttons you press on in the editor. 

However, I may need some advise on how to best go about making them into buttons that replace the current ones.

Here's a link for you to see yourself!
http://webblabb.iit.his.se:8080/grupp4/a14davlo/LenaSYS/DuggaSys/diagram.php

![github photo svg icons](https://cloud.githubusercontent.com/assets/26733328/25616029/c6d93cee-2f3a-11e7-8bf4-b643c3897800.png)

**Comment by b15matki** [comment]
Looks good so far, all you need to do is to include the image tag within the button tag then the image will be displayed within the button!

There is however another issue regarding the current images. Since the background of the button will change color depending on whether or not the user has selected the specific button there also needs to be another set of images to indicate that the button is selected. For example:

![examplebutt](https://cloud.githubusercontent.com/assets/26705132/25617850/8d2ebed8-2f44-11e7-9db8-6f93fa0e0a72.png)

As seen above the buttons need two different versions in order to indicate to a user which button has been selected. There is however a "smarter" and more easier way to solve this problem. That would be to remove the current blue background and instead only keep the existing icon. Then we only need to change the background-color of the button in order to indicate the selected button. And if we/someone in the future wishes to change the color of the buttons we/they only need to edit the CSS instead of creating a new image and etc.

**Comment by a14davlo** [comment]
@b15matki 
@a15perbl 
@HGustavs 

Here's what I did 3rd May Wednesday.

Made a second iteration where I colored the figure blue and made everything else transparent. Then I uploaded it to my grupp4/a14davlo and tested it out, looked good. 

In the second iteration I also created diagram_create_class which is designed as the UML class which three rectangles put together. I also redesigned diagram_create_line and changed its angle 45 degrees to make it less horizontal and more easily distinguished from other figures.

I also went back to the diagram_move_arrows design and increased the size of the arrows, when in minature size it looked very similar to the diagram_plus figure and this made them more distinguishable.

Made a third iteration where I changed the color to C0C0C0 which is a silver-grey color so that the figure can be seen even when the background switches colors between blue & orange.

Today I'll make sure to add the silver-gray figures into my grupp4/a14davlo and place them inside the buttons, however will not be finished then, there's still some work to be done regarding the positioning, size and coloring of the buttons inside the Diagram.php file.

This is written for documentation but also because this would otherwise not easily fit into the issues, code, pull request work format, I've been doing aesthetics & designing using adobe illustrator and here's my way to report that I've been working. It's a big issue.

**Comment by a14davlo** [comment]
Here's what I did 4th May Thursday before the Merge.

The silver-gray icons are now put in place, the test files have been removed and I've added a blue background color that's located in Style.css under the name .diagram_option_button .

My work is not going to be merged this week, it's still in progress.

Here are the next steps.
1. When selected, the color switches to orange.
2. Reduce the size of them, remove the text and just make the svg-file itself into the button.
3. Add a text so that when you hold your mouse over the buttons, the name appears.

http://webblabb.iit.his.se:8080/grupp4/a14davlo/LenaSYS/DuggaSys/diagram.php#[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]

![projekt i software engineering paint 3](https://cloud.githubusercontent.com/assets/26733328/25698842/e67efa3e-30c0-11e7-9a24-26e2eaf746c2.png)

**Comment by a14davlo** [comment]
During 5th and 8th May I continued my work on creating hoovering effects for the buttons and I also moved the text in the buttons to only be shown when hoovering your mouse over the button.

http://webblabb.iit.his.se:8080/grupp4/a14davlo/LenaSYS/DuggaSys/diagram.php#[object


![github photo buttons](https://cloud.githubusercontent.com/assets/26733328/25817193/e39bf510-3426-11e7-836f-9e7fcc6dbf8c.png)

**Comment by a14davlo** [comment]
@HGustavs 
Today been working on buttons able to switch color between blue & orange by selecting them, I'm almost done but encountered some challenges which I do not know how to solve. I'm done with about 90% of this issue and I'm stuck trying to figure out how to make the color to switch from blue to orange on the create line, class, attribute etc buttons.

I need some assistance with trying to figure out how to solve the color switch in the diagram.js file I have and I want to be able to meet with you before the weekly merge so that this can be added in that merge.

**Comment by a15chrau** [comment]
Be very cautious when reviewing the coming pull-request form this issue, as it will most likely result in code disappearing from #3743

**Comment by b15matgu** [comment]
How about using the purple color that's already used in LenaSYS for the buttons?
![1](https://cloud.githubusercontent.com/assets/26705189/26236855/c21886ac-3c72-11e7-9b0a-f6978a354de2.JPG)

**Comment by HGustavs** [comment]
In another issue (#2458) I talked about using the dashed box and "handles" for showing selection. The orange secondary color is fine, but I would combine it with some kind of boxes and/or handles also.

**Comment by a15chrau** [comment]
I suggest making the buttons slightly thinner, or the menu wider, so you can fit two buttons in one row. This is refering to @a14davlo's branch.
![image](https://cloud.githubusercontent.com/assets/26707347/26265403/4ac03c98-3ce1-11e7-96f8-8db0d2ab0b52.png)

**Comment by a15perbl** [comment]
Issue resolved
