### ISSUE TITLE
Add a function that can remove figures.

### ISSUE THREAD

**Issue by b15matki** [HGustavs/LenaSYS#3400]
At this moment the delete object function does not work on figures. The function needs to be revised so that it is possible to delete selected figures.

**Comment by HGustavs** [comment]
I say, a generic delete function.

* If we have selected an object we delete the current selected object (figure or symbol)
* If more than one figure or symbol is selected we delete all of them
* If points in figures are selected, we delete only the selected points.

**Comment by a15oskst** [comment]
I fixed this in issue #3032. But this has stopped working lately. Probably something else that destroys the code?

**Comment by a15oskst** [comment]
I think that I might actually fix this issue when I fix issue #3321. As there is something wrong when selecting the figures, and as I said before I have already fixed this issue once before and if this selection bug gets fixed it should also fix this issue.

So put this issue on ice until we know what the problem is!

**Comment by a15perbl** [comment]
Issue resolved.
