### ISSUE TITLE
Internet Explorer wrong alignment

### ISSUE THREAD

**Issue by a15emibo** [HGustavs/LenaSYS#3575]
Things are misplaced in internet explorer, specifically the "show/hide all" (duggor) and create dugga button.

![ieright](https://cloud.githubusercontent.com/assets/26706727/25737877/5c7a2c72-317a-11e7-8e4e-b73626b41ae7.png)
![ieleft](https://cloud.githubusercontent.com/assets/26706727/25737883/600c6ee0-317a-11e7-8d8f-9c5546af8d97.png)

**Comment by HGustavs** [comment]
It is not important what happens in internet explorer, if it looks ok in edge we are fine, if it looks messy but works in internet explorer we are fine.

**Comment by a15matab** [comment]
This happens in Firefox too.

**Comment by c16matan** [comment]
Seems to be working in firefox, chrome and microsoft edge. Internet explorer couldn't load the page at all. Maybe this has been fixed this in the recent year by either a pull request or better support from the browsers. And since you said that internet explorer is not important i will close this issue. If theres something i'm missing please explain the issue further.
