### ISSUE TITLE
Add odd even colors to table and decrease height of rows

### ISSUE THREAD

**Issue by a15freku** [HGustavs/LenaSYS#3624]
![oddeven](https://cloud.githubusercontent.com/assets/26705670/25797873/4f9bc15c-33df-11e7-82d3-08f1d58376f6.png)

**Comment by a15freku** [comment]
Should look similar to files view

**Comment by a15wilhe** [comment]
The height of each row has been reduced and fixed with pull request which is approved. 

I have tried to add odd and even styleing but there are "hidden" tablerows in an unspecific amount so somethingg like "tr:nth-child(3n+2)" won't fix it. I will continue trying to fix it with jQuery after the AJAX renderer.

**Comment by a15wilhe** [comment]
For fixing the odd even background coloring i tried first in jQuery :
`$('#testTable tr:visible .fumo').not('variantInfo').filter(':odd').css({'background-color': 'red'});'red'});
$('#testTable tr:visible .fumo').not('variantInfo').filter(':even').css({'background-color': 'yellow'});`

Then in css:
`.list#testTable tr.fumo:not(.variantInfo):nth-of-type(odd) {background-color:LightGray;}
.list#testTable tr.fumo:not([style="display:none"] ):nth-of-type(even) {background-color:WhiteSmoke;}`

Nothing works the way I want, there are "hidden" rows and innertables that makes it tough.
