### ISSUE TITLE
Diagram editor animation support

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#3744]
We want to see the full history of a diagram as an animation.

e.g. we click a diagram and we se an empty diagram area, and then click a "play" button, at which point we see all of the actions to arrive at the final diagrma as a sequence of animation frames.

**Comment by b18phibe** [comment]
Is not worth to begin making this feature before #8823 are done

**Comment by a18antsv** [comment]
I am thinking to have some kind of timeline just under the diagram. Then for every action that has been made to that diagram, there will be one part on the timeline. The timeline will be divided into the number of actions. It will be possible to click a play button to go through the actions on the timeline automatically like an animation. It will also be posible to click on the different parts on the timeline to go to a specific state of the diagram. There can also be buttons to step one state to the right or left.

**Comment by a18antsv** [comment]
I could possibly even try to animate movements for when something was moved. The stored information just says what points something was at before and after movement but it could be possible to use the difference here to make a smooth animation between the positions to make it look nice.

**Comment by a18antsv** [comment]
I wonder if the intention is to also animate every single undo and redo that has been made. Or if these should be omitted to only show the progress. The latter would be the easier option. I am right now working with undo and redo to work with the new storage functionality of only saving changes for each state and then building the diagram from the changes. I have to make a decision for how the undo and redo should be working. The problem comes when doing some action that is not undo/redo after undoing. The idea then, that most programs I have seen use, is to invalidate all changes that exists after current state, when not in latest state. If the number of changes that will be invalidated exceed a certain number, a warning should popup making the user have to accept this to not lose work. If the number of changes to be invalidated is below 5 or some other good number, the warning is not necessary.

**Comment by b18phibe** [comment]
The animation of movement is a nice to have but i do not see it as a must so leave it if it is too time consuming. Regarding the undo and redo are my opinion that it should not be included because even if some teachers may like to see how the student progresses. so will the majority of them be super bored the 5th time the student starts allover.

**Comment by a18antsv** [comment]
Yes, I will fix the timeline with auto playback and manual navigation to begin with. Then I can fix the smooth movement if there is enough time.

**Comment by a18antsv** [comment]
This is how I implemented the timeline. I think it looks great. It is possible to see what states will be added and which states will be removed on the timeline when hovering on one part of the timeline.
![c1284af1c4a04b4e6c9b612dc6d44518](https://user-images.githubusercontent.com/49121839/82751445-999cfd80-9db7-11ea-9126-277ed1455ad3.gif)

**Comment by a18antsv** [comment]
The play button also works and will animate by changing the state to the next one every 1 second. So this issue is solved and extra functionality has been added. I am thinking to create a new issue to implement some kind of slider or dropdown making it possible to change the speed of the animation.

**Comment by a18antsv** [comment]
Maybe the backwards/forwards buttons could be omitted since it is possible to do the same functionality by undoing/redoing or easier by clicking on exact part that should be loaded. Then make a reset button and a slider to control animation speed. To prevent the slider from taking up too much space it could possible be represented by a normal button and when this button is clicked, it could be shown.
