### ISSUE TITLE
Diagram export to svg button / Export to JSON button

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#3748]
We need a button to download the document as svg or download the current json as a file.

**Comment by a15admsa** [comment]
@HGustavs Does it have to be SVG? If yes; why didn't we make the diagram in SVG instead of Canvas from the first place? All I can find on the internet are different libraries and how to export canvas to svg with them. I have made it possible to export in .jpg. If I want to make it work with svg, I have to use a extended library.

**Comment by a15admsa** [comment]
@HGustavs I asked the question on Stackoverflow and got these answers;
[http://stackoverflow.com/questions/44020028/export-canvas-to-svg-without-library]

**Comment by a15admsa** [comment]
This issue is not yet fixed!

**Comment by a15admsa** [comment]
This issue will have to be fixed at a later date. @HGustavs have made a new issue with some exemple code on how to fix this one. That exemple code is in issue #4033

**Comment by c16jonha** [comment]
This issue will be fully solved through Issue #4033
