### ISSUE TITLE
Diagram layers

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#3750]
Much like the layers in adobe illustratior I would like layer support (but simpler than illustrator that sometimes does not work).

* Each diagram object should have a layer (which is a number) ... eg Layer 1, 2, 3, 4, ...
* Current drawing operation always is in a specific layer
* Each layer has a spcific default coloring e.g. if an er entity is created in layter 2 it is green by default, if it moves ot layer 3, it should keep its color, but if we draw another entity in layer 3 it hould be for instance orange.
* It should be possible to restrict the diagram display to display only some layers or all layers

**Comment by o18marka** [comment]
Tried to develop a suitable solution, but failed to make anything stable enough to use. I'll have to leave this to a more knowledgeable developer.

**Comment by a18antsv** [comment]
Maybe it would be good to create a new class called Layer. An instance of this class can have an array of objects for all objects in the array and also store properties that should be applied to objects added to that layer. A minimum of one layer is required. Then the diagram array could be an array of layers instead of an array of objects directly. The layers then store the objects.

**Comment by a18antsv** [comment]
In the toolbar it should be possible to hide a layer, add a new layer and move a layer up or down for the order the objects should be drawn. Then default properties for each layer should be possible to set from the global appearance menu. Here a collapsible element, introduced recently could be used for "Layers" then another collapsible for each layer could appear after opening the layer collapsible.

**Comment by a18petha** [comment]
some interesting proposal, although I don't think this would be a good implementation "Then the diagram array could be an array of layers instead of an array of objects directly" issue here is that some functions requires the objects to be at cretin diagram index values to work. Changing this would require some adaptive work for system to be compatible.

**Comment by a18petha** [comment]
to achieve so objects are place in orders compare to layers all that is needed is a forloop that write's the diagram in accordance to layers. Only negative to this is obviously the decrees in performance from running a forloop on the main drawing function.
