### ISSUE TITLE
Change the look for zoom selection

### ISSUE THREAD

**Issue by a15perbl** [HGustavs/LenaSYS#3815]
The zoom selection looks pretty basic at the moment. Styling it up would be a good change, do you have any suggestions on how to change them? @HGustavs 

![bild](https://cloud.githubusercontent.com/assets/26705103/25943178/5236ad84-363f-11e7-9e5c-584c98a1b23d.png)

**Comment by b15matki** [comment]
**Feedback from @HGustavs :** 

The zoom button should lie within the canvas itself to enable the canvas to get as much space as possible. The coordinates should also be placed within the canvas itself rather than having a reserved space beneath the canvas.

**General feedback:** 
It would probably be cool if some basic css would be implemented, such as round corners, a colored "semi-button" where the arrow-down is displayed.

**Comment by a15perbl** [comment]
Issue resolved
