### ISSUE TITLE
Redesign [Edit version] and [New version] buttons

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#3889]
Related to #2951. The dropdown list for choosing version has been moved from the navigation bar. The two buttons mentioned should also be moved as they are not navigation links and take up a lot of extra space. Maybe a settings icon and a plus icon could be used at the dropdown list to make editing versions more smooth.

**Comment by a15tobli** [comment]
Suggested mockup.
![3889_mockup](https://cloud.githubusercontent.com/assets/26705097/26060993/f79ecf64-3986-11e7-9f73-a5c44b8821c4.png)

**Comment by a15tobli** [comment]
Also considering that these options may be moved to the header as there is alot of unused space there at the moment. This mockup adds some more use of icons instead of all the text in the buttons, which was requested. Also makes the site more mobile friendly with the navigation menu.

**Comment by a15eriho** [comment]
Suggestion. The version box could reside in the same place it was from the beginning (next to the new version and edit version buttons, since this button bar will always be visible in some form even when buttons has been collapsed to a hamburger menu. Thus this space can with good measure be used to hold things like this version box.

As it is now it is not really fitting in on the header bar (looks somewhat misplaced), and it also overlaps, and gets hidden by, the yellow New Version (+) button to the right of the header bar when collapsed.

**Comment by c14emian** [comment]
@a97marbr @HGustavs Any preferences? There's currently several suggestions and I would like to know what you would prefer before I begin making changes.

**Comment by a15tobli** [comment]
The dropdown was moved in the first place because @HGustavs did not want to have it in the same place as the buttons. The variants desired would either be to have it in the header or next to the course name (left side specifically, but it did not look good). I do see the problem when it is collapsed and will try to move it to the header as there is more space in that location.

**Comment by a15ponja** [comment]
Fixed in #4102.
