### ISSUE TITLE
Different animations on Hide/Show all

### ISSUE THREAD

**Issue by a14phili** [HGustavs/LenaSYS#4030]
Different animation on "Hide/Show all". If you press the text(Show/Hide all) you get one animation and if you press the arrow you get another one. The right animation happens when you press the text(Hide/Show all). Change the animation when you click on the arrow to the one you get when you click on the text.

**Comment by a15eriho** [comment]
Had to redesign the functions which handles this a bit since there were several functions that did almost the same thing, just triggered with different class-types.

As of now they are more generic for what type of sections/moments that are collapsed, and will collapse until the next section OR moment, whichever appears first. It will be fairly easy to add new collapsible section-types too if that is desired. The animation type now only has to be altered in one place when someone wants to redesign how they work.
