### ISSUE TITLE
missleading text in code viewer dialog

### ISSUE THREAD

**Issue by d15johro** [HGustavs/LenaSYS#4060]
**In the picture below, should it really say "delete" and not "cancel"?**
![asd](https://cloud.githubusercontent.com/assets/26705142/26297324/af293390-3ed2-11e7-8255-24ef22cf6806.png)

**Comment by A15cecal** [comment]
@d15johro I'm thinking that this is correct, but the question is if not a cancel-button should be added too? Or if we move the delete-option out of this dialog and put it next to the cogwheel as an "X", and replace the button with cancel.
@HGustavs What do you think about this?

**Comment by d15johro** [comment]
i agree with you @A15cecal. We should replace the delete-button with a cancel-button and move the delete-button next to the cogwheel, and most importantly add some sort of warning before calling the deleteItem()-function. For instance, the following code "confirm("Are you sure you want to to this dugga delete?");" could be added ti the deleteItem()-function or click event.

**Comment by A15cecal** [comment]
@d15johro Yes, I think this change would be very good. Let's wait and see if the teacher agrees, create a mockup for this maybe? I could do that right away.

**Comment by A15cecal** [comment]
@HGustavs Here's a mockup of the dialog-box and a new delete button. 
Made one with the trashcan-icon and one with just a red cross (we might want it grey instead of red if this is the used alternative) just so we have something to choose from.

![ny knapp](https://cloud.githubusercontent.com/assets/26705134/26363983/1a9c066e-3fe3-11e7-9b19-39e67aaaf60e.JPG)

![papperskorg](https://cloud.githubusercontent.com/assets/26705134/26363998/211374a0-3fe3-11e7-8c76-8ac583ede30b.jpg)

![med kryss](https://cloud.githubusercontent.com/assets/26705134/26364007/26f029ae-3fe3-11e7-93e6-9dd626fbfb9c.jpg)

**Comment by d15johro** [comment]
solved by #4122
