### ISSUE TITLE
Control+Click to change incorrect mark - part 1.1, ctrl + click

### ISSUE THREAD

**Issue by a16seplu** [HGustavs/LenaSYS#4226]
make grade editable with the ctrl+click functionality

**Comment by HGustavs** [comment]
This is a prioritized feature.

A php-level adjustable time limit is important also (30 minutes or 10 hours for example, in minutes?)  so that we cannot change grades one week later when the student has already seen the mark but we can fix something immediately if mis-pressing a button (which does happen)

**Comment by HGustavs** [comment]
Related to #4220 #4219 I guess?

**Comment by HGustavs** [comment]
Sortabletable has editing built in, perhaps the built-in editing functionality can help us with this?

Sortabletable may need to be updated slightly to support this but I think it is a worthwhile endevour.

https://github.com/HGustavs/SortableTableLibrary/blob/master/sortableTableDemo_edit.html

**Comment by d16linja** [comment]
Solvec, you can now use both ctrl or cmd for mac users
