### ISSUE TITLE
Mini mode (blue mushroom mode) - part five

### ISSUE THREAD

**Issue by a16seplu** [HGustavs/LenaSYS#4231]
Sorting of columns should happen normally.

**Comment by HGustavs** [comment]
currently there is no sorting (database-exact order) until a sort column is chosen. 

I believe this is a reasonable behavior.

**Comment by HGustavs** [comment]
In the sortable table sorting demo 

https://github.com/HGustavs/SortableTableLibrary/blob/master/sortableTableDemo_sortsimple.html

It is possible to see how to with very little code implement sorting using sortabletable.

Unsure if the mini-mode will allow us to set the background of cell without tricks or if sortabletable has to be modified so that it also passes a string for inline styling of the td.

**Comment by b16nilpe** [comment]
Sorting in minimode was given for free with sortable table and the implementation of sorting in issue #4332 and it seems to behave like the sorting in normal mode
closing this issue for now.
