### ISSUE TITLE
Test deadline either normal date like currently or a json string - part two

### ISSUE THREAD

**Issue by a16seplu** [HGustavs/LenaSYS#4241]
Add json option for deadlines format: {["2010-11-01","You have past first deadline","2010-11-02","You have past the second examination deadline","2010-12-01","Your submission was handed in after last deadline, let the teacher know that you have handed in by sending an email"]}

**We need to also change the datatype of the deadline field in the database from datetime to string to allow us to either store a single deadline date or a json string containing multiple deadlines and error messages for passing each deadline.**

**Comment by HGustavs** [comment]
Customized deadline messages is a prioritized feature for some teachers.

Please do not forget adding reasonable test data for this so we have a few example of different approaches.

We should perhaps not change the datatype but rather adding a deadline as string in a separate column, otherwise we break the "no changes in database" cardinal rule.

**Comment by d16linja** [comment]
The new deadline is added for the database part, still needs to be implemented for reading
