### ISSUE TITLE
Migration functionallities to update and alter database

### ISSUE THREAD

**Issue by a16filol** [HGustavs/LenaSYS#4259]
To make the process easier when making new tables and updating existing. Should a migration feature be interesting?

Make migrations, update migrations and rollback old migrations.

**Comment by HGustavs** [comment]
The big problem is updating the database and keeping the changes known.

I think some kind of a php file that can be run (and then removed) to update the database non-destructively to a certain version.

It is a big problem currently since the running system does not have the same tables as the github version.

Such a feature would be very welcome.

* Forward-migrate only (no removing of things) - should not be an issue as all changes should be incremental anyhow
* Data-based system e.g. xml or json data but IN a php file (external data files tend to be forgotten in systems and could give informatino to hackers)
* steps for versions e.g. move to a certain version ID - but not migrate to things in the "future" of specific version
* Three things /columns need to be displayed in a nice (sortable) table
   * Migration of tables one by one (so we can get feedback if errors occur) (alter table or create table)
   * Feedback with short description of the change (e.g. "Added column for study program")
   * Test data to verify that the change works as advertised (e.g. Inserts also, not only alter table/create table)

**Comment by a16filol** [comment]
Ive made a module for migrations during the weekend. Please checkout https://github.com/a16filol/LenaMIG . The current functionallity of the module migrates new tables. But i could easy implement Alter / Insert.

**Comment by HGustavs** [comment]
Looked over the code.

It seems to require separate files for the versions / files etc.

Dont like that, as it requires synching/uploading more than one file.

I say that the data is written inside the php, so the only thing we need to copy from dev machine to living system is migrate.php and it needs to use the login system so that it cannot be run without being logged into lenasys and being a superuser.

Other than that I am mostly on board.

**Comment by d15marwi** [comment]
This was just a question, closing this issue because there is no need for it anymore
