### ISSUE TITLE
New test data is needed for LenaSYS during development

### ISSUE THREAD

**Issue by b16linra** [HGustavs/LenaSYS#4282]
New test data, for example teachers, students and courses, are needed to be able to recreate problems and to test solutions for different issues.

This issue might need to be broken up into smaller issues for different areas.

This issue is related to #2974

**Comment by HGustavs** [comment]
Most pressing I find is adding tests (dugga-s, with file submission and other kinds) and students so that the marking view can be tested with a realistic amount of students/tests.

Im thinking a course with 25+ students and 10-15 tests.

We can also add test-submissions and test-feedback so that those parts can be tested properly.

Not sure if this pertains to more than one group or if it is shared... very important either way.

**Comment by d15marwi** [comment]
There is now testsdata for Tests and for SectionEditor. Group has no testdata because of its dynamic nature. But you can just connect students and moments at any time.

**Comment by c16matan** [comment]
The only necessary test data for group 1 is test submissions and answers in the resulted page, and this was added in issue 5246 (referenced above). So this can be closed assuming that everyone else is done.
