### ISSUE TITLE
Refactorizing Diagram code

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4325]
We have made a list of suggestions that we think would improve the readability of the code and the codes structure in general.

- Remove redundant code
- Merge together files such as Diagram_figure and Diagram_symbol into one file. The same for the files in the forms folder.
- Renaming or documenting variable names so that they become easier to understand.

If possible we would like to see the original code for the diagram files to get a better understanding of the codes origin. 

Any feedback @HGustavs ?

**Comment by HGustavs** [comment]
I found the seed code by going to the start of last years project in the releases tab. This should be the earliest available.

https://github.com/HGustavs/LenaSYS/tree/382dc230b14463b55a0a4775c78f64ecd9dcc5a5/DuggaSys

**Comment by HGustavs** [comment]
They did a very big suggested renaming of variables which in some cases made the code more difficult to read and process.
 
This "refactoring" was done and documented in two text files...

~~~
-----------------------------------------------------------------
                ##List of changed variable names##
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

#
# This was done to follow the javascript code
# standard
#

Old Name                        New Name
-----------------------------------------------------------------
private_lines                   privateLines
dist                            distance
ind                             index
xk                              xCoordinate
yk                              yCoordinate
dx                              deltaX
dy                              deltaY
dd                              hypotenuseElevatedBy2
selval                          isSelected
ctx                             canvasContext
sx                              startX
sy                              startY
ex                              endX
ey                              endY
x1                              topLeftX
y1                              topLeftY
x2                              bottomRightX
y2                              bottomRightY
px                              width
py                              height
len                             boxHypotenuseElevatedBy2
centerpoint                     centerPoint
connected_objects               
private_points                  privatePoints
selobj                          lastSelectedObject
ev                              event
private_objects                 privateObjects
object_points                   objectPoints
current_hash                    currentHash
diagram_names                   diagramNames
lastDiagramedit                 lastDiagramEdit
timediffrence                   timeDiffrence
last_edit                       lastEdit
line_width                      lineWidth
cx                              currentMouseCoordinateX
cy                              currentMouseCoordinateY
sx                              startMouseCoordinateX
sy                              startMouseCoordinateY
mox                             oldMouseCoordinateX
moy oldMouseCoordinateY-----------------------------------------------------------------
                ##List of changed variable names##
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

#
# This was done to follow the javascript code
# standard
#

Old Name                        New Name
-----------------------------------------------------------------
private_lines                   privateLines
dist                            distance
ind                             index
xk                              xCoordinate
yk                              yCoordinate
dx                              deltaX
dy                              deltaY
dd                              hypotenuseElevatedBy2
selval                          isSelected
ctx                             canvasContext
sx                              startX
sy                              startY
ex                              endX
ey                              endY
x1                              topLeftX
y1                              topLeftY
x2                              bottomRightX
y2                              bottomRightY
px                              width
py                              height
len                             boxHypotenuseElevatedBy2
centerpoint                     centerPoint
connected_objects               
private_points                  privatePoints
selobj                          lastSelectedObject
ev                              event
private_objects                 privateObjects
object_points                   objectPoints
current_hash                    currentHash
diagram_names                   diagramNames
lastDiagramedit                 lastDiagramEdit
timediffrence                   timeDiffrence
last_edit                       lastEdit
line_width                      lineWidth
cx                              currentMouseCoordinateX
cy                              currentMouseCoordinateY
sx                              startMouseCoordinateX
sy                              startMouseCoordinateY
mox                             oldMouseCoordinateX
moy oldMouseCoordinateY
~~~

cx,cy,sx,sy,x1,y1,x2,y2 are standard variable names which allows copy-pasting of complicated graphics code without having to change variable names across programs.

Also those two .txt files in the dugga folder is github-littering...

I would not mind to get my variable names back.

The important thing is that the variable names in the saved JSON dat are as short as possible...

if we store 

~~~
{xk:200,yk:200}
~~~

instead of 

~~~
{xCoordinate:200,yCoordinate:200}
~~~

**Comment by b16petma** [comment]
Changed canvasContext to ctx in all diagramfiles. Changes is in pull request #4347

**Comment by c16carbe** [comment]
Refactorized a few functions and optimized some code. All changes is in pull request #4348

**Comment by b16ponpe** [comment]
Changed variable names, startX and startY to sx and sy in diagram.js and diagram_mouse.js. Changes is in pull request #4349

**Comment by b16petma** [comment]
Made a pull request #4359 That removes code that is used for creating figures (Freedraw and Square).

**Comment by c16carbe** [comment]
Refactorized a few functions but mostly focused on optimizing the functions and making them more readable. All changes is in pull request #4348

**Comment by c16carbe** [comment]
Pullrequest #4372 added. Same changes as pullrequest #4368 but with the functionality of the help menu added back.

**Comment by b16ponpe** [comment]
Changed variable names back to original from endX to ex and endY to ey. Changes is in pull request #4357

**Comment by b16ponpe** [comment]
Changed variable names, deltaX and deltaY to dx and dy. Changes is in pull request #4402

**Comment by c16carbe** [comment]
Small optimizations of the code in diagram_symbol.js, began splitting the draw() function into smaller pieces and also re-writing those functions to be easier to read.
Pullrequest #4415

**Comment by c16jonha** [comment]
This issue is mostly solved now. Our goal with this issue was to make the code easier to understand and more optimized and effective. It's not 100% solved and the code is not perfect right now either, but we feel like we've reached our goal. If more refactorization will be needed in the future, we will create smaller, more specific issues dedicated to the refactorization of single files.
