### ISSUE TITLE
Barriers for logging in

### ISSUE THREAD

**Issue by a16seplu** [HGustavs/LenaSYS#4436]
Add maximum number of tries any user has before receiveing a "timeout"

**Comment by b16filor** [comment]
@HGustavs Is a popup (like in the first image) or text in loginbox (like the other images) preferred? Currently the popup version is used but we feel like it might be worth looking into changing this because related functions such as password reset uses the other version. 

![gammal](https://user-images.githubusercontent.com/36665559/38678138-79dc7ed4-3e60-11e8-9fa9-ef467b534fb4.JPG)
![ny1](https://user-images.githubusercontent.com/36665559/38678145-8063a8f4-3e60-11e8-9466-ba0a882fed5f.png)
![ny2](https://user-images.githubusercontent.com/36665559/38678150-85d014ee-3e60-11e8-8406-02c42e583415.png)
