### ISSUE TITLE
Group-Functionality: Forensics, what is left in SectionEd?

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4541]
After deleting the grouped.php and grouped.js (as per request fro the customer) a lot of functionality was "lost". However a lot of group-realted functionality is still requested in other parts of the system.
It would be good to have an overview of the code and see if there are any traces of group-related features left in the code, and if this code is usable?
-Check: sectioned.php & sectioned.js
-Are there variables?
-Are there functions?

**Comment by a16linas** [comment]
I managed to only find one variable in sectioned.js called "groupitems" on line 801. The difficulty with this issue is that there is no way to know exactly which functions and/or variables that were called when the grouped files existed. Coupled with the troublesome variable-naming led to me only finding one variable.
