### ISSUE TITLE
Selecting an object doesn't work when clicking on its middle point

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4570]
EDIT--Read the comment below for more accurate information about the problem--EDIT
If you try to select an object by clicking on its middle point, the click won't register. This does not happen after you resize the text, only with the standard text. It seems that the text is not contained inside the object. This needs to be fixed.

**Comment by c16jonha** [comment]
It's actually the objects middle point and not the text.

**Comment by c16carbe** [comment]
This doesn't seem to be possible within any reasonable timeframe since it would essentially require large re-writes of the codebase. The simplest solution that I could find at the moment was to remove the middlepoint and make two middlepoints that are at the top and on the bottom of the drawn object instead. This does however break a large portion of the rest of the code that uses these points as a reference when working on the object.

**Comment by c16jonha** [comment]
Any thought on this @HGustavs ?

**Comment by c16jonha** [comment]
A newer issue will solve this one. Issue #4776
