### ISSUE TITLE
updateGraphics() in Diagram.js casues problems

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4619]
The function seems to be called every time the mouse moves in the canvas, causing some minor visual bugs and and makes the performance worse. The function should only run when something is being drawn or some object is being moved. Now this function is running at unnecessary times.

**Comment by HGustavs** [comment]
This may be due to highlighting on hover and drawing while moving.

* Ideally it should be possible to for example hover an entity or relation for example.
* Not sure if hovering is supported currently but this is the rationale behind auto-updating.
* Also the gfx should auto-update when resizing and when drawing partial lines.

**Comment by c16carbe** [comment]
@HGustavs Yes. It should be possible to hover, and it is. But I don't see how that's relevant since the current solution draws a new frame every single time your mouse moves over the canvas, regardless if you actually hovered over anything or not. It is using up unnecessary amounts of cpu cycles and should be rectified to minimize lag and maximize responsiveness.
