### ISSUE TITLE
Add comparability for the old navheader in showdoc

### ISSUE THREAD

**Issue by d16linja** [HGustavs/LenaSYS#4679]
Related to #2436

If the new showdoc gets implemented to the live version and the navheader does not, the old showdoc should still work at least as good as before with the credentials

**Comment by c16matan** [comment]
We found another way of solving this issue. Instead of using the session variable we could use the filename from the $_GET variable and check if the user has permission to view any moment that uses that file. If the user has enough with permissions the file can be shown to the user, otherwise access will be denied.
