### ISSUE TITLE
showdoc special case with a direct link

### ISSUE THREAD

**Issue by c16matan** [HGustavs/LenaSYS#4798]
Main issue #2436 

When trying to access a dugga through showDugga.php which requires login when logged out will present the "Bummer" message. If the user log in on that page, the course id session variable will never be set, that will in turn make showdoc not work because it cannot do a proper credentials check. However, i want to point out that showdoc does work if the user has taken the proper route from the course page to the dugga page.

**Comment by HGustavs** [comment]
So if I paraphrase.

The issue is that if we are not logged in we get the same error message as if the file did not exist.

I do not consider this a bug, since this behavior makes it difficult to perform link fishing (guessing file names to figure out which files that exist). If the behavior between not found and requires login an attacker gains no additional information about our system or the courses.

Or am I mis-understanding something?

**Comment by c16matan** [comment]
As you said, logged out users should not be able to see duggas that requires a user to be logged in and have read permission. But if the user logged in on the showdugga.php page the session variable 'courseid' never got set, and that resulted in that showdoc.php could not do a proper credentials check for logged in users. So if a user logged in on that page and a image was loaded through showdoc, that image would not show, and this issue is a fix for that.

**Comment by c16matan** [comment]
Solved.
