### ISSUE TITLE
Functionality of greyed out text and checkbox

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#4895]
Check what functionality the text and checkbox in the picture below has.

![checkbox](https://user-images.githubusercontent.com/37793947/39360384-597f34be-4a1e-11e8-8dbc-3db852b48a51.PNG)

**Comment by a16lovka** [comment]
The MOTD textbox is used to create a message of the day at the bottom of the page. This works and is only displayed on the courseed-page.

The Read only checkbox is supposed to enable a read only-mode to LenaSYS (uploads/submits can't be made), useful for backup-servers. The checkbox can't be clicked because it is disabled in the code. Should this be enabled so the functionality can be used? @HGustavs

**Comment by a18antsv** [comment]
The checkbox can be clicked right now. But the value it supplies the function called when submitting the form is useless. The checkbox will always give the value "no". A check for if the value is "yes" is made in updateSettings(). The value will never be "yes", even if the checkbox is checked. For the current code to work, code must be added that changes the value of the checkbox that switches the value between yes and no on click. 

A better way would be to remove the value of the checkbox and check if it is checked with the .checked property to get a true or false returned.

**Comment by a97marbr** [comment]
The whole idea behind the **read-only** option is so that we could have a hot-standby server. In case of downtime for the main server we could redirect students to the hot-standby and dugga descriptions and previous student submissions would be present (for example 1 day old) ...

But by disabling student submissions (hence **read-only**) we could maintain consistency regarding student submissions.

**Comment by a18kaswi** [comment]
Greyed out box not there anymore, other related stuff in new issue. CLOSING

**Comment by a18antsv** [comment]
#8218 was created instead when functionality was known.
