### ISSUE TITLE
Resulted view deadline indicator - part three

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#4960]
Part of #4164 

the ability to set a grace period (swe: respittid) on the dugga deadline. This should default to the closest following workingday. A dugga submitted during this time __should not__ be indicated as handed in too late

**Comment by a17anter** [comment]
Grace time period is implemented and is not possible to set via Lenasys. The reason why it's hardcoded is because if you would like to be able to set the grace time yourself you might aswell only have a deadline that you set correctly from the beginning. Grace time will always default to the next workday as explained in more detail below.

The code implemented now works like this:
A "workday" is between 8-17 so if a dugga has deadline at 17:00 or later on monday --> thursday it will set the grace time period to the following day 8:00:00. If the dugga is submitted after this grace time adjustment it will be marked as "late". If the dugga has a deadline set to friday 17:00 or somewhere during the weekend the grace period will be until the following monday 8:00:00.
If the deadline is set somewhere before 17:00:00 there will be no grace time period at all.

**Comment by a17adasy** [comment]
It is now tested. Follows code standard and it works.

**Comment by a17anter** [comment]
Note!
Code doesn't take account for holidays monday-friday. (röda dagar)
