### ISSUE TITLE
Duggasys magic headings

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#504]
If large tables are used in duggasys, headings are not visible.since they scroll out of view. Headings that are fixed when they move out of view would resolve this.

Furtheore, any solution that relies on a fixed unmoving header and scrolling table body is seen as too difficult to use.

We are asking for fully free-moving headers both horizontally and vertically.

**Comment by c13chrjo** [comment]
Issue is not present

**Comment by a13chrju** [comment]
I don't understand which tables we're talking about? YOu mean under the file "sectioned.php"?

**Comment by a13oscwe** [comment]
Having a sticky or "fixed" table heading(thead tr essentially) is very tricky to do when the table exceeds the current screen width since setting the css property to position: fixed sets an absolute width for the table heading row on both the X and Y axis. I tried using JS to set the width's of the TH's to the data TD's but the browser overrides the width because the fixed element cannot overflow on the x axis. This is possible to fix using third-party libraries (https://github.com/sxalexander/jquery-scrollspy) but as i understand, is not allowed.

Given i understand the issue correctly that you want the tables on resulted.php and duggaed.php to have a fixed header.

If somebody else want's to give it a shot feel free.

**Comment by HGustavs** [comment]
There is no easy "automatic way" to do this. The trick is to have two table headings, one that is "locked in place" and one that is free-floating. If you on scroll updates the width of the second table heading to match the width of each of the column in the first table the sizes match up.

This is done with about 25 lines of javascript.

**Comment by a13oscwe** [comment]
@b13alebr has solved this and it looks pretty good. Pull request #1591
