### ISSUE TITLE
Lines are attached automatically to objects

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#5057]
As it is now, the lines attach automatically to the objects depending on how they are placed in relation to each other. It would be nice to be able to manually change where the lines should be attached after the line has been drawn, if needed.

this could possibly solve issue #5037

**Comment by a17jonro** [comment]
This issue requires a change in how points are created for diagramObjects since they do not technically exist. Attributes (oval's) will need a new implementation of how their points are placed since they start at the origin of the shape as of now. We deem this issue to much effort for what it provides. Therefore we put it on low priority.

**Comment by a18kaswi** [comment]
Possible connected:
#5057
#6491
#7491
#7673

**Comment by o18marka** [comment]
Please see my comment on issue #8553 .
