### ISSUE TITLE
Appearance menu styling

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#5087]
For now, the appearance menu have the same styling as the loginbox and dialog popups. It would be better suited if it had a similar styling to the toolbox. The darker overlay isn't necessary, since it distorts the preview of the changes that are made to an object and because we don't want to "hide" the object that we are changing.

<img width="1063" alt="skarmavbild 2018-05-07 kl 09 10 30" src="https://user-images.githubusercontent.com/37794632/39689284-85674606-51d6-11e8-8982-c404586fcf37.png">

**Comment by c16linst** [comment]
Like this? Doesn't it look a bit strange that two of the diagram "boxes" look almost completely different?

![skarmavbild 2018-05-07 kl 17 15 26](https://user-images.githubusercontent.com/37794714/39709492-4b987dde-521a-11e8-9dc0-f12d37a863a6.png)

**Comment by a16adala** [comment]
I have made some minimal changes to the appearance menu, please let me know if the changes are desirable or not. 
![image](https://user-images.githubusercontent.com/37834994/39743581-9c9d8dbe-52a1-11e8-928c-64b358c60ac2.png)

![image](https://user-images.githubusercontent.com/37834994/39743599-af109f68-52a1-11e8-81ab-71c955a23fda.png)

**Comment by c16linst** [comment]
@HGustavs 
We were thinking about changing the functionality for the appearance menu, so that there is no underlay and the object you are currently editing is highlighted (with the orange "selected borders", so you clearly can see which object is currently being edited), and when you select another object in the diagram the appearance menu changes content according to the newly selected object. This removes the "problem" with having the appearance menu break the process. You will not have to close the appearance menu to edit another object then.

If we implement this functionality, is it okay if the appearance menu and toolbar look a bit more similar so that the user can see that they belong to the diagrams internal functionality?
