### ISSUE TITLE
Styling for markdown preview window

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#5210]
For now, the styling isn't what the costumer wants. if it could emulate the picture below with fieldsets instead of windows in the editors, it would be more consistent with the rest of LenaSYS. The styling for the buttons should also follow the example. 

![32375958_10209676186140691_3049710432685129728_n](https://user-images.githubusercontent.com/37794632/39985721-cdc82d00-575f-11e8-9162-a0c5d0ef75ce.png)

**Comment by b16nicbr** [comment]
Where is a good spot to set the shortcut buttons?, on the legend line (instruction file) or edit variant or as buttons or if you have another suggestion of where to set the shortcuts @HGustavs

**Comment by HGustavs** [comment]
Not an easy question to answer. I would put the buttons somewhere near the top.

It does not have to emulate this specific dialog, but I do believe that there are not many side-by-side dialogs in Lena.

Does not have to use fieldsets exactly, but something that looks similar to this so that we are using a style that is somewhat recognizable across the various views.

I would prefer emulating some other dialog rather than inventing yet another styling option.
