### ISSUE TITLE
Contribution - Horizontal range line fix

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5211]
The horizontal lines marking the different ranges is the same colour as one of the background colours in the diagram.
![cont](https://user-images.githubusercontent.com/37793947/39986641-9156fcae-5762-11e8-9cad-f62c5e610606.PNG)

**Comment by b16filor** [comment]
@HGustavs

**Comment by a16chrsa** [comment]
The color the horizontal line was changed in #5587.

And the numbers are rounded in #5589.

**Comment by a17fellu** [comment]
Looks like this issue has been solved. Or is it still some problem with it? @HGustavs

**Comment by HGustavs** [comment]
Do we have a screenshot for how it looks right now?

**Comment by a17fellu** [comment]
![Capture](https://user-images.githubusercontent.com/49202955/55544416-52434180-56cb-11e9-8bc9-a614968ba95e.PNG)

* Color of the horizontal lines have been changed to a darker shade of gray so it doesnt clash with the background

Cant see any numbers but it is reported to also have been fixed in a post above.

**Comment by a17maxsj** [comment]
Has the numbers been implemented? Will close issue if this is the case.

**Comment by a17maxsj** [comment]
bump

**Comment by a17fellu** [comment]
I was totally wrong. You cant view contribution.php at all.

**Comment by a17maxsj** [comment]
This is working. Closing...
