### ISSUE TITLE
Counter column for sortabletable

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#5256]
For now, the fileLink table has a counter column. This need to be implemented for the sortabletable so all user that wants to have this functionality easily can add it. 

<img width="146" alt="skarmavbild 2018-05-15 kl 10 51 05" src="https://user-images.githubusercontent.com/37794632/40046703-e7507f38-582d-11e8-805e-b27fb2aea939.png">

**Comment by HGustavs** [comment]
I have jotted down a few requirements for the counter column

* We want the couter column to call the rendercell function normally, so that we can add custom styling to the coutner value. 
* However no filters, so we should not be able to remove the counter through filtering
* No sorting, the counter column should not be sorted in any other order than 1..x top to bottom.

**Comment by b16andka** [comment]
The solution to the first point will be solved by adding a class to each "counter"-td (<tableid>_counter). 
This makes it possible to style the counter column for each table. 
The other points works as intended.
