### ISSUE TITLE
AccessEd - Sorting icon in navheader

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5258]
In access editor view:

Sorting is already possible by clicking on the column headers in the table itself. We need to implement the feature of sorting the table from the sorting icon in the navheader. (The icon to the right)
![navheader](https://user-images.githubusercontent.com/37793947/40047060-ba170784-582e-11e8-926d-bdd49dd8473a.PNG)

Note that the radio- and checkboxes in the popup might be outdated since they were lasts used before sortableTable was implemented.
![access](https://user-images.githubusercontent.com/37793947/40047084-cbf9291e-582e-11e8-9812-971f8fed51d3.PNG)

**Comment by a16chrsa** [comment]
We discussed how to implement this. It's between making a solution which changes dynamically with future updates to the database(for example if new column is added) or to have a static(hard-coded) solution.

Before updates to Shared/SortableTableLibrary/sortableTable.js were made the sorting was done statically. This was removed in fa7ee71 and now there are no sorting-options to choose when hovering over the icon.

I made a commit(aa7f940) with only an example checkbox. This checkbox currently filters a column instead of sorting. Not sure if there is a function for sorting which could be called on the onclick inside the tag. 

Some advice is needed on how to continue with this.

**Comment by a16chrsa** [comment]
Made sorting possible in the navigation menu in #5585.

The solution is static as defined in the comment above. It would have been more ideal with a dynamically changing menu. However this was beyond my capabilities. I did not understand how to accomplish it. But this is a working solution to the problem.

**Comment by a17joaap** [comment]
Issue fixed?

**Comment by a17maxsj** [comment]
Seems to be fixed, if otherwise will reopen
