### ISSUE TITLE
Edit course not possible on Toddlers epic course.

### ISSUE THREAD

**Issue by a13erisc** [HGustavs/LenaSYS#529]
The cogwheel icon does not give a menu to edit the course Toddlers epic course.

**Comment by c13chrjo** [comment]
syntaxError: unterminated string literal is the error message

**Comment by b13johfr** [comment]
I don't think this is an isolated issue here. I believe the issue is that the name of the course contains the character " ' " which causes the final generated site to parse the string incorrectly and makes a bad query to the database. 

To test whether my hypothesis was correct I created another course that contained the faulty " ' " letter. It exhibits the same faulty behaviour. I will create a new issue that addresses this problem and close this issue.

**Comment by c13chrjo** [comment]
A new issue was made for this  #747
