### ISSUE TITLE
Title attribute for sortable tables

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5626]
A requested feature for all sortable tables is to introduce title / alt attributes for the table headings so that it is possible to view the headings when hovering etc.

**Comment by HGustavs** [comment]
For example the result view headings that tend to be long...

![Screenshot 2019-03-25 10 29 32](https://user-images.githubusercontent.com/6978801/54908802-fa495580-4ee8-11e9-890c-92d3fa494d3c.png)

... and if we only see last part of heading can be very un-informative.

**Comment by b17timjo** [comment]
There are a great number of potential changes, what is the preferred behaviour?

Ex. 1) Removing "rtl" shows start instead of end 
![remove_rtl](https://user-images.githubusercontent.com/38911528/55705235-a3f70f00-59de-11e9-83ea-e521c0a005ea.png)

Ex. 2) Removing hard width limit of 150 px:
![remove_width_limit](https://user-images.githubusercontent.com/38911528/55705239-a78a9600-59de-11e9-8fc5-906f53b57c32.png)

Ex. 3) Removing nowrap on header (but keeping width limit):
![remove_nowrap_on_th](https://user-images.githubusercontent.com/38911528/55705243-aa858680-59de-11e9-82be-515c72294100.png)

**Comment by b17timjo** [comment]
@HGustavs as you will be the primary user, do you have any preferences?
