### ISSUE TITLE
SQL code is ambiguous, few comments / no documentation

### ISSUE THREAD

**Issue by a13karsi** [HGustavs/LenaSYS#564]
The SQL code is undercommented and there don't seem to exist any documents specifying requirements, design and other concerns regarding the database.

**Comment by HGustavs** [comment]
One or two rows of text comments for the code and some separate text documentation would be nice.

Perhaps creating a documentation folder?

**Comment by a13karsi** [comment]
Good idea, I'll start with trying to add some sensible comments to the sql file

**Comment by HGustavs** [comment]
The overarching goal of the project is readability.
The sql file should be understandable just by reading the file, but at the same time we do not want too much documentation in the code, so that the code becomes unreadable if it has more comments than code....

Even though... you can never have too much documentation... I suggest .html files in a documentation folder for the really detailed stuff, when the amount of documentation is starting to approach the amount of code.

**Comment by a13karsi** [comment]
I agree, but I thought the database was kind of hard to intuitively approach. For the time being I've just added a few comments at the top of each table to try to make it easier next time I look at it. I'll see whether I can find more application for your documentation ideas as I keep working!

**Comment by a13karsi** [comment]
Oh, I seem to have made a mistake when I made the pull request, the changes were actually merged into the master branch and not our weekly when the pull request was reviewed and accepted. I'll make sure to not let this happen again.

**Comment by c13chrjo** [comment]
It´s equally my fault for not checking this before I merged it.
