### ISSUE TITLE
Profile page is missing

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#5646]
Clicking on the user name in the navbar leads to DuggaSys/profile.php, which throws a "File not found" error.

Is this intentional @HGustavs ?

**Comment by HGustavs** [comment]
The profile should be there... in DuggaSys/profile.php

it was/is there in the main repo

However it should say:

Profile settings can only be changed on a secure HTTPS connection.

if you are not using https

**Comment by a17joaap** [comment]
On the live version of LenaSys, regular users are met with the 'File not found' message.

![filenotfound](https://user-images.githubusercontent.com/37792198/55625622-9d338680-57a9-11e9-9161-263b2ea4664c.PNG)

**Comment by a17andby** [comment]
Since we can access the profile page on the current master branch (picture). Can we close this issue even though it does not work on the live version (dugga.webug.his.se) @HGustavs ?
  
![Screenshot from 2019-04-11 15-03-28](https://user-images.githubusercontent.com/49235724/55959410-006e5e80-5c6b-11e9-8ce2-5fc7c3071b16.png)
