### ISSUE TITLE
Change comments to the right standard

### ISSUE THREAD

**Issue by a17celal** [HGustavs/LenaSYS#5708]
Some comments in the digram files does not follow the code standard. Should be changed to the right format.

![Capture4](https://user-images.githubusercontent.com/37792271/55723867-63ad8600-5a0a-11e9-81e8-138a869e589a.PNG)

**Comment by HGustavs** [comment]
Yes this is worthwhile since it makes the code more readable for all.

Also, when making screenshots of code, use moustaches (~ <- three of those) and then the code pasted into the document and then three new moustaches.

Screenshots are for user interface stuff, for quoting code github and mardown has helped us...

~~~
Then it looks like this
~~~

**Comment by a17johpe** [comment]
I've come across php files containing html code and as such only html comments work .
How should comment standard look for html comments? Always single line, or should a comment such as 
~~~
<!-- The Appearance menu. Default state is display: none; -->
~~~
before a large portion of nested divs be changed into, e.g.:
~~~
<!---------------------------------------------------------
    The Appearance menu. Default state is display: none; 
---------------------------------------------------------->
~~~
