### ISSUE TITLE
The first column in result table shrinks when horizontally scrolling

### ISSUE THREAD

**Issue by a17poner** [HGustavs/LenaSYS#5713]
![image](https://user-images.githubusercontent.com/49194938/55724228-3e6d4780-5a0b-11e9-9515-e51780de4fb3.png)
The numbers from the first column are frozen but they shrink and lose value when scrolling horizontally.
Happens in resulted.php
Might be worth checking if the shared/sortableTableLibrary as well

**Comment by HGustavs** [comment]
There is an issue for this already, including screenshot. #5632 

Since magic headings is enabled the number and name columns should keep the same size and shape as the corresponding columns in the view.

It is unclear why this is a problem. 

I am thinking that the code uses getBoundingClientRect().top, bottom, left, right  but does not get a correct result when updating the "magic" column.

Additionally the top header should also be "magic"

**Comment by c17julka** [comment]
Issue #5632 has specified this problem, which has been commented on, and that issue has been fixed and pulled to the GruppB2019 branch, so this issue will be closed.
