### ISSUE TITLE
accessed.php FAB (Yellow button with + sign) Doesnt fit the others

### ISSUE THREAD

**Issue by a17fellu** [HGustavs/LenaSYS#5728]
The FAB isnt placed where the other FABs usually are placed and the shadow should be updated to match the one on courseed.php

**Comment by HGustavs** [comment]
![Screenshot 2019-04-09 08 46 13](https://user-images.githubusercontent.com/6978801/55778733-f3ebd980-5aa3-11e9-8804-712f427a41ec.png)

In the section editor, the fab is placed on top of the icons ... which makes it very complicated to edit the last two items in a list when the last of the items reach the fab button.

I suggest moving it slightly to the left so that the icons are press-able. It is less  of a problem if the deadline date is covered by the fab.

**Comment by a17joaap** [comment]
Seems like there are two different implementations for FAB's currently. The one on courseed.php is the outlier, using the class 'fab', while all others I can find (including on accessed.php) are using the 'fixed-action-button' class.

We should make this uniform, I suggest changing the FAB on courseed to match the rest.

**Comment by HGustavs** [comment]
Yes I would agree with this assessment. We should change the one in courseed to the more prevalent one.

**Comment by a17maxsj** [comment]
merged... closing
