### ISSUE TITLE
can not sort tests from "top - down" only "down - top" 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#5745]
When pressing the sort button on the test page it is only possible to sort them by "down - top" and not  from "top - down". If you are pressing the sort button two times it should flip the table and it should appear from the top down. (starting from A - Ö). 

![image](https://user-images.githubusercontent.com/49194898/55796141-8eaadf00-5ac9-11e9-9703-cff7c980fd80.png)

![image](https://user-images.githubusercontent.com/49194898/55796192-a5513600-5ac9-11e9-870e-2b255b5d73bf.png)

**Comment by HGustavs** [comment]
This seems like a general bug in how sorting works in all of lena ...

this used to work splendidly ...

Either the sort criteria for up/down is not changed correctly or ...
The sorting is not sign-flipping based on the sort criteria

test if it works correctly in sortabletable examples, if so this is a local problem ... otherwise problem of sortabletable ...

**Comment by a16joare** [comment]
Here is a pull request that solves the problem: #5944
