### ISSUE TITLE
The diagramservice.php file could use better documentation to clarify what it is about

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5818]
There are comments in the code but it lacks documentation in the top of the file. This makes it harder to understand what it really is about.

**Comment by HGustavs** [comment]
I agree.

Currently, this is very unclear, since the rest of the system has one php for static content, one php for database services and one js file.....

the diagram service is not following this rule in several different ways...

this may be one of theses ways... the documentation can tell us if it works as intended or if something needs to be fixed.
