### ISSUE TITLE
Problem with aligning objects when lines are marked

### ISSUE THREAD

**Issue by a17alfcl** [HGustavs/LenaSYS#5886]
Lines should probably not be included when determining distance between objects when aligning.
One solution would be to check for symbolKind when checking for overlap, and treating lines differently.

Related to issue #5686

**Comment by a17jonro** [comment]
This is a logical change since lines might not need to be considered when aligning. However this doesn't seem to change anything since alignment is based on the top or bottom most coordinates which will always be of one of the objects that is not a line, since lines are always between two objects. There is a possibility though that this change affects the secondary part of the align functions which is adding spacing when objects overlap, since the lines are not considered. Not sure about this though since without the changes the overlap doesn't seem to work correctly for lines anyway.
