### ISSUE TITLE
profile microservice - verify if it is used at all

### ISSUE THREAD

**Issue by a17pongo** [HGustavs/LenaSYS#5911]
Verify if the profile microservice is even used.
Has not been touched in two years and might be ok to remove.

**Comment by HGustavs** [comment]
Check if it is possible to navigate to the profile page and if it is really possible to change the password? 

If so, test it and see to what extent it works and then we can go from there reporting new issues.

**Comment by b17timjo** [comment]
On the production instance the profile page is a 404.
In the test environment a user can navigate to the profile page and change their password.

**Comment by b17timjo** [comment]
@HGustavs any thoughts on this? Did the profile page never make it into production; are there issues preventing integration?
The password (reset?) challenges have not been tested.

**Comment by HGustavs** [comment]
Security review

It should not require any input from teachers to change password....
and
It should never be possible to change the password of someone else...

if these conditions are met, we can try to run this on the system....
but since this is security related we have so far not dared to do this.

**Comment by a17alian** [comment]
After some testing I've concluded that profile.php seems to be close to useable,

1. _"It should not require any input from teachers to change password...."_
* Students CAN **change** password by themselves from profile.php without any input from teachers
* Student CAN'T  **reset** password by clicking "Forgot password?" in the login box
- The security questions does not seem to check the answer properly
* Students CAN **change** "Challenge question" (security question) from profile.php 
- The change of question is registered and can be seen when trying to reset password, but the answer is still not working

2. _"It should never be possible to change the password of someone else..."_
* Students **cant** change or reset the password of someone else
- Only admin and teachers can reset passwords from accessed page 
(**teacher** can't change their own sq or password from profile.php, but that seems intentional?)

Does everything (except reset password) seems to be working as intended? Should a separate issue  be created for getting the function of resetting password working? @HGustavs

**Comment by HGustavs** [comment]
We cant place this in production until we are REALLY sure what it does.

Feature-wise this seems reasonable.

What if there is no challenge question?

Can it be possible for someone else to set the challenge question of someone else and then log in as that person after changing password?

**Comment by HGustavs** [comment]
Combine with a message, someone has changed your challenge question.... at least add an issue for this.

**Comment by a17alian** [comment]
In order to change password or challenge question, the user needs to be logged in. So it's not possible to change someone elses question either. But an issue for adding a message when the challenge question is changed is a good idea

Removing the challenge question would make it possible for anyone to request a reset of the password. The first step when reseting a password is to enter the username in question
![image](https://user-images.githubusercontent.com/37792256/57514663-43c2f800-7311-11e9-8dff-6028c3c4c9e5.png)
Then anwser the current challenge question
![image](https://user-images.githubusercontent.com/37792256/57514851-9ef4ea80-7311-11e9-9f86-c2c0e820dba5.png)

Since then you only need to know the username anyone can reset the pasword. Assuming an e-mail with the new password will still be sent to the correct persons student email, the removal of the challenge question will only be an annoyance.

**Comment by b17timjo** [comment]
@HGustavs As I understand it, the worry lies in a person leaving their computer momentarily, whilst still logged in, which would allow someone to use their session to change the challenge question without the owner knowing.
This should still only be an inconvenience, as the "attacker" would need access to the target email account to actually use the reset password (and besides, they must have already stolen an active session).

Suggestion: It would be more secure if the user is required to re-enter their current password when they change anything in their profile page, including the challenge question/answer.

**Comment by b17timjo** [comment]
A better solution would be to do away with the challenge question completely.

If the issue here is that anyone can know a username, and therefore request a new password for any user:
When someone requests a password reset, a unique single-use link should be sent to the email of that account, and clicking that link within X hours should reset the password and send another email with the new password.

That initial reset email should contain something like "if you did not request this reset [...]"

**Comment by HGustavs** [comment]
I have lost interest.

**Comment by a18kaswi** [comment]
HGustavs commented on 23 May 2019
I have lost interest.


Customer lost interest? CLOSE
