### ISSUE TITLE
Save functionality not yet implemented

### ISSUE THREAD

**Issue by b17robev** [HGustavs/LenaSYS#5914]
Save functionality is not yet implemented in diagram, however the UI allows us to to click on the menu-item. Fix a form of save functionality?

<img width="197" alt="save" src="https://user-images.githubusercontent.com/37845511/56117935-85a68b80-5f69-11e9-9ae1-9783c4088d71.png">

**Comment by a17drama** [comment]
After a meeting with @HGustavs a decision has been made about the Save function in the menu. Save should not save to files. It should be connected to a database that is shared by several users that are working on the same diagram at the same time. Similar to the google docs where more than one user can make changes to a document. Saving to a file would be redundant due to the export function that already covers this. Syncing should be done automatically just as google docs. This makes the saving functionality obsolete? Load should still be able to load diagrams from files that are exported. This should be made into several smaller issues that can help this mechanics work.

**Comment by a17robhe** [comment]
https://github.com/HGustavs/LenaSYS/issues/2926 Would cover this issue, i dont feel the need to have both of this issues. Especially when the functionality has been clarified in such a way that https://github.com/HGustavs/LenaSYS/issues/2926 is more representative
