### ISSUE TITLE
Suggestion: Bulk delete/delete multiple duggas or allow enter key for deleting a dugga

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6053]
It's very tedious when you want to delete multiple duggas since you have to press the delete button for each dugga and then press yes on the dialog which pops up every time.

My suggestion would be to either allow selection of multiple duggas for deletion at once, or allowing the enter key to be pressed on the delete dialog to make the process faster.

**Comment by a17poner** [comment]
Thinkin that having both might be useful, having some sort of a cog wheel next to the upper plus (in the header) that allows the superuser to select multiple options and once at least one is selected a delete(trashcan) button could appear maybe as a FAB. allowing ctrl + click to select mutliple instead of having to use cogwheel would also be a way of selecting a bulk of "duggas". Would probably also be a good idea to have a confirm button that requires user input before deleting a bulk.

**Comment by a17poner** [comment]
Found that there are a somewhat existing onclick already in sectioned.js so just going to see if I can make that work again, however it is currently throwing an error on a missing reference for isTypeValid() which was removed by @HGustavs in [this](https://github.com/HGustavs/LenaSYS/commit/cdde4e215840dc33011b8142cc2b15bea5b163b2#diff-d962552fcc22e779f7743b7a148e27f5) commit. But the usage of isTypeValid() wasn't changed (and still isn't). Any reason why this function was removed and a new way of handling the onkeyPresses should be done or should the code be restored?

**Comment by a17poner** [comment]
Found a workaround way to make it work for this issue, altough there are still 2 references to functions that have been removed if enter key were to be used elsewhere on sectioned.php. They probably qualify for other issues though.

**Comment by a17andby** [comment]
Fixed and merged. Closing.
