### ISSUE TITLE
Resulted.php - nan is showed when changing a grade from U to G for a student

### ISSUE THREAD

**Issue by a17pongo** [HGustavs/LenaSYS#6154]
![Screenshot from 2019-04-23 11-22-45](https://user-images.githubusercontent.com/37792222/56569967-4eb02580-65ba-11e9-95f2-30689788ec97.png)
![Screenshot from 2019-04-23 11-23-01](https://user-images.githubusercontent.com/37792222/56569968-4eb02580-65ba-11e9-99b9-2a1eb8eb5959.png)

This number should probably be updated or not shown to prevent (nan)?

**Comment by HGustavs** [comment]
This should show the number of times this grade has been set.

It would seem logical to update this count accordingly.

It should be (4) in this case?

Perhaps this is not possible due to information missing from database or does it have some other cause?

**Comment by b17timjo** [comment]
There is a field in the database which appears to be updated: `timesGraded=timesGraded + 1`
As can be seen in e.g.:
https://github.com/HGustavs/LenaSYS/blob/29be894dd6ecd105e4259b7c93dba1133a95d698/DuggaSys/resultedservice.php#L115

**Comment by a17amama** [comment]
The issue appears not only when you change the grade from U to G, but also when you simply change a grade or remove it completely. It seems as if the grade is empty, it will get the value of (NaN), no matter how many times you change it.

**Comment by a17pongo** [comment]
but the value is updated and exists in the database? 
so I think you just need to fix so it gets this value and updates it on the website everytime you change grade.

**Comment by a17amama** [comment]
The data (Times Graded) is updated correctly in the database whenever you grade however unless you refresh the page, it will display (NaN) whenever you change it. From what I have observed, the issue seems to be that the data is not fetched from the database correctly. It fetches it correctly the first time you enter the page, and then it does not and the only way to get around it right now is to refresh the page, which could be done in the code but does not seem optimal. A solution is still not found for this issue.
