### ISSUE TITLE
"Reset toolbar position" should reset to default position

### ISSUE THREAD

**Issue by a17johpe** [HGustavs/LenaSYS#6212]
![åwaoåogjeåojrg](https://user-images.githubusercontent.com/37792313/56656127-f4d05e00-6694-11e9-8ab2-82f094101fe1.png)
The option to "reset toolbar position" resets the toolbar to the topleft corner, but this is not the default position any more and should be fixed.

**Comment by a17drama** [comment]
Doesn't it do this already or am I missing something?

**Comment by a17johpe** [comment]
The default position was changed as a solution to a previous issue solved by @a17vikab . Because of some implementation of the camera functionality this default position has been changed again to the top left corner and doesn't _seem_ to be an issue. Another issue and fix will be created before this issue is relevant again.

**Comment by a17drama** [comment]
The default position was changed as a workaround for another issue that is now solved and that is the reason that the tool bar is now moved to the original position. The argument of what the "default" position should be can be solved by a vote. Suggest we make a poll to pick a position or let @HGustavs pick the position. If that is considered a issue make a new one for that purpose. This one is getting closed because it's solved.
