### ISSUE TITLE
Functionality to drag middle line in UML boxes

### ISSUE THREAD

**Issue by a17alfcl** [HGustavs/LenaSYS#6261]
![umlline](https://user-images.githubusercontent.com/49202727/56717860-e12d0200-673d-11e9-8be7-f5948ad45711.png)

The line in the circle should be draggable, either all the time or only in developer mode.

**Comment by a16tobfr** [comment]
Right now, this line is drawn as a simple .ctx object in diagram_objects.js
One approach would be to change these type of lines into symbols so that they actually have some properties that we can manipulate.

Then I suppose that it would be rather easy to follow the instructions made by markE in the link below:
https://stackoverflow.com/questions/18034637/how-to-make-html5-draggable-objects-over-canvas

**Comment by a18andtu** [comment]
As said above the lines are drawn as .ctx lines and in order to manipulate these, the way uml entities are drawn needs to be changed.
