### ISSUE TITLE
Search window in Access does not work with swedish letters.

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#6292]
The search window in access does not handle swedish letter, for e.g. when searching for "Åsa" it will not filter the table.

**Comment by a17alevu** [comment]
This is also a issue as long as a person has a swedish letter (Å Ä Ö) in their first name or last name, which means the name does not have to **start** with a swedish letter, but only has to **contain** a swedish letter (Hällsjö, Jönsson etc.)

**Comment by HGustavs** [comment]
Is there a good generic way to fix this?

**Comment by a16joare** [comment]
The problem is that the database do not handle swedish characters like ÅÄÖ..  The search window is using the database to search for the values in the table. This means when you type in "Åsa" the name do not exist in the database because the value looks like this "&Aring;sa". If you however search on "&" in the search window åsa will show up.  I have made an issue on this (#6330). If issue #6330 is fixed, I think this issue will be fixed aswell.

**Comment by b16johso** [comment]
Possible solution: Create function that converts the html coded format to ÅÄÖ

**Comment by a17joaap** [comment]
Same as #6225?

**Comment by a16joare** [comment]
@a17joaap Yes it is the same. The search function however is a problem for group B.

**Comment by a17pongo** [comment]
don't know if this issue is related to only group B since the accessed page is not part of our scope. 
But this seems like something that needs to be implemented in a generic way for every page anyway.

**Comment by a17alevu** [comment]
Closing this since it is the same as #6225
