### ISSUE TITLE
Deselection of draw line

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#6354]
After the line is drawn the tool for drawing line should be deselected. This is irritating when the user is trying to move an object after the line is drawn and it starts drawing a new line.

**Comment by a17jonro** [comment]
Are we sure about this? You might want to be able to draw multiple lines without having to click the button multiple times. At the moment it is irritating if you want to move an object after drawing a line but if we change how it works then it will become irritating the other way around. And since all of the other create/draw works this way it would be weird to only change this one.

**Comment by a17drama** [comment]
I fully agree but our customer (@HGustavs ) has a wish to have it this way and the customer is always right. For the future to work around this problem we could implement hotkeys for tool bar to chose the different tools. This will remove the need for moving and clicking but the user will still have to do something to chose drawing lines. If there is a better suggestion it would be appreciated if this came up as an issue.
