### ISSUE TITLE
Investigate/remove migration.php

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#6359]
This might be unused:
![image](https://user-images.githubusercontent.com/49199993/56806049-1a8f6b80-682b-11e9-80c6-9ecf5c8b4e30.png)
Please investigate functionality and remove if possible

**Comment by a17alevu** [comment]
Very big file, not sure what i am supposed to investigate or remove.

**Comment by a17adajo** [comment]
Looks like some kind of weird way of handling database version upgrades. A better alternative would be to use something like: https://flywaydb.org/

**Comment by HGustavs** [comment]
Since we only do additive changes, one way is to always add an alter table / create table to another file, which the user can choose depending on what we are running.

Remember, we are not migrating the complete database, we are migrating parts of the database depending on what we are running at the moment, we may be running some tables as "new" and other tables as "old" or "old old" versions.... 

I think this cannot be resolved by automatic means.... at least it is very complicated.

**Comment by HGustavs** [comment]
I would suggest removing since it does not use the current database definition anyhow.

**Comment by HGustavs** [comment]
so my suggestion, which is by hand..

if we add a column to a table... we have an init_db.sql which is run when we want to run something from scratch, but if we want to migrate something we want to know firstly which table we are migrating and then which alter table to run.

so lets say this file is called alter_db.sql ... this should contain 

~~~
a comment about what service and what table and what alteration was made
alter table add column name datatype;
~~~

etc

If this is kept in step with init_db it is possible to manually migrate andy specific service when we install it...

**Comment by a17alevu** [comment]
Not quite sure, you suggest me to remove the whole migration.php ? @HGustavs

**Comment by a17adajo** [comment]
For this issue I Think @HGustavs means he is ok with removing the file. But he is also suggesting a new way for handling database schema migrations

**Comment by a17poner** [comment]
merged, closing this.
