### ISSUE TITLE
Move cursor displayed when it shouldn't be

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#6377]
Move cursor is displayed when hovering a line and lines shouldn't be able to move. They are "static" between entities. It also displays when a draw tool for line is chosen and this is very confusing. Is the user drawing a line or moving the entity?

**Comment by a16jenja** [comment]
![image](https://user-images.githubusercontent.com/49199287/56888264-da6ef980-6a73-11e9-9ed0-6e502fc73b5b.png)
I might be misunderstanding the issue, but when I hover over a line it does not show a move cursor. And I can't move the lines either. @a17drama 

Although when the draw tool for line is chosen it does show a move cursor, so that I could try and fix.

**Comment by a17drama** [comment]
Might have been an issue that got resolved by something else. First time I tested I got a move cursor hovering the line. Focus the line drawing then and check if there is something else being wrong with the move cursor. Remember the UML line.

**Comment by a16jenja** [comment]
You are right, I forgot to test the UML line, there is a move cursor and you can move that one. So I'll get right on that.

**Comment by a17drama** [comment]
A part of this issue is written as a separate issue #6507 . When this is done tag both issues in the pull request so both get closed.
