### ISSUE TITLE
Cursor change to indicate objects are movable in 'MoveAround' mode

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6465]
The cursor is not shown in the print screen, but when you are in 'moveAround' mode and hovering over an ER entity for example, the cursor change to indicate that the object is movable. This is not true when in the 'moveAround' mode, and the cursor should not change when hovering objects here
<img width="287" alt="hoverCursor" src="https://user-images.githubusercontent.com/49199690/56959388-8cc6bf80-6b4d-11e9-9a98-76550fb61ef8.png">

**Comment by a17jonro** [comment]
Exactly this issue doesn't seem to exist in the current branch. However this issue with the cursor changing is present when hovering over the points even when they're not visible. So I'll fix that and after disscussing it with a16tobfr, I'll also remove that you can hover symbols when in "movearound" mode since that is slightly related to this issue. Instead of creating a new issue for it.
