### ISSUE TITLE
Global appearance menu should be updated with current line thickness

### ISSUE THREAD

**Issue by a17alfcl** [HGustavs/LenaSYS#6521]
![linethickness](https://user-images.githubusercontent.com/49202727/57071692-8d8d5c00-6cdb-11e9-8e46-8e00e846f19c.png)

**Comment by a17jacsv** [comment]
How do you mean? In my view is a non-issue and works without any problem?

<img width="945" alt="Skärmavbild 2019-05-03 kl  12 57 48" src="https://user-images.githubusercontent.com/37792795/57133463-220ec180-6da3-11e9-9bb2-005eba7b0d0a.png">

**Comment by a17jacsv** [comment]
@a17alfcl ?

**Comment by a17alfcl** [comment]
> @a17alfcl ?

If you close the appearance menu with a line thickness that is not at minimum value, the menu is still set to min value on this when reopened. It should check currently set global line thickness when reopened.

**Comment by a17jacsv** [comment]
Oh, now I understand. I will get into it!

**Comment by a17jacsv** [comment]
It seems like none of the changes made in the "global appearance menu" is saved when creating new objects. This is obviously a problem and not only the line-thickness that is affected. The whole menu should be fixed with another larger issue.

![Skärmavbild 2019-05-07 kl  12 42 12](https://user-images.githubusercontent.com/37792795/57293698-c35c8700-70c5-11e9-8751-c6f3a0e641c1.png)
