### ISSUE TITLE
Sorting arrows in access doesn't work

### ISSUE THREAD

**Issue by a17poner** [HGustavs/LenaSYS#6602]
This is split off from #6238, the sorting arrows don't work and maybe they aren't even needed. So waiting for response from @HGustavs before merging any commits from this issue.

**Comment by HGustavs** [comment]
Unclear what the issue is... exactly so I give a generic answer... specifically applicable to accessed view.

Column filter should control which columns to show and in this case there is no point in  this table that has very few columns....

The sorting one is a shorthand for selecting which column / data the sorting is based on... and this is much more useful in this case.

Sorting on study programme or on student name for example.

**Comment by a17poner** [comment]
The funnel is fixed with filtering in a different issue, we  split them up. So this one is supposed to be that the sorting arrows have no functionality on the current version. But they're from my understanding supposed to do exactly what you can already do with column headers using the sortableTable hence it would be redundant funcitonality.

**Comment by HGustavs** [comment]
Yes, same functionality should be called that is called by clicking headers.. so it should work more or less automatically. Unclear what the reason is for this not working at the moment...

I cannot remember if the sorting change caused by header clicks calls a function or updates a variable....

Irrespective of this it should do the same thing.

What function is called by the arrow list item?

**Comment by a17poner** [comment]
I think it uses myTable.toggleSortStatus from looking at what the renderSortOptions sets as its onclick.
