### ISSUE TITLE
Invert login/logout button colors

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6619]
At the moment it looks like you're logged out when you're logged in:
![image](https://user-images.githubusercontent.com/37834592/57215057-24179100-6fec-11e9-93d4-2f94df572f7a.png)

Using a green color when you're logged in and a red color when logged out would look better in my opinion.

**Comment by a17alevu** [comment]
I dont really agree. I would say that green indicates to login and that red indicates to logout, but maybe i am wrong with this.

**Comment by a17andby** [comment]
Don't agree as well.

**Comment by b17albbe** [comment]
I would say that I agree that the color needs to be changed. In fact I would prefer if the previous login visuals were still used too (the user icon). I don't think anybody is arguing whether or not green indicates login, or if red indicates logout. The problem is how those colors are used in this case. And I think it would work better if those colors were used when you are actually trying to login or logout, when hovering over the button.

**Comment by b17carma** [comment]
I'll close the pull request for this issue since people have different opinions about it 😛

**Comment by b17annni** [comment]
This seems sorted by other issues now. @a17alevu ?
