### ISSUE TITLE
AccessED sorting passwords and ssn

### ISSUE THREAD

**Issue by b17annni** [HGustavs/LenaSYS#6671]
This should not be a feature for privacy purpose.

**Comment by a17alevu** [comment]
You can only access these futures as long as you are a admin? Or am I wrong?

**Comment by HGustavs** [comment]
Sorting on the recently added button is a good idea, but we do not need to show or sort the password hashes.... however, we need the password for generating the email?

**Comment by a17poner** [comment]
This isn't the first time someone has made an issue regarding sorting by password, it was dealt with in a pr #5905 even when it was made so that sorting by password showed people who had requested password changes at the top. Regarding privacy, we don't actually sort by the users password, only by the button value currently and at one point before the compare in sortableTable was refactored it would sort by their requestpasswordchange status but never a users actual password (it isn't stored in the sortableTable at all).

**Comment by a17alevu** [comment]
We will remove SSN from the table. So this issue will be closed.
