### ISSUE TITLE
Double-click on symbols creates more symbols as well as opens appearance

### ISSUE THREAD

**Issue by a14oscna** [HGustavs/LenaSYS#6712]
There is an issue when you try to open the appearance tab on a symbol by double-clicking it. If you have a symbol currently selected in the toolbar you also create duplicates of that symbol on top of the symbol you attempted to click. The appearance window that opens is also connected to the last created duplicate, which is not the symbol that was initially double-clicked. 

This requires some sort of check which prevent additional symbols from being created if the user is clicking on a symbol.

**Comment by HGustavs** [comment]
And also, clicks that are too close (temporally) should not trigger new creation of symbols either.

**Comment by a16jenja** [comment]
This issue only seems to happen when I create a new object and without moving the mouse at all, then I try to bring up the appearance menu for the first object and a new object will be created on top of the other object. But if I move the mouse slightly before double-clicking it will bring up the appearance menu like it should, very weird.

But it seems to work when doing it on exisiting objects while having a symbol selected in the toolbar.

**Comment by a14oscna** [comment]
Yeah, I believe it happened at all time when i initially tested it, but the problem still exists as you described it a16jenja. It is still a issue we want fixed since if you press on the canvas every 2 seconds to create a new object (without moving the cursor) you can create infinite amount of objects on top of each other.

**Comment by a16jenja** [comment]
What we want to change is that when you create a new object another object can't be created at the same place. What we noticed is that when you create a new object the hover effect is not used until you actually move the mouse, which probably means that it only updates when you actually do a mouse move event. We are not sure how the hover effect are functioning, it seems to only work when doing a mouse move event, which makes this issue happen.

We know what we want to change but we don't really know where to do the changes, after a lot of trying and testing we feel like we are not able to solve the issue. I've had this issue for a long time now and I think it would be nice to get some new fresh thoughts on the issue. Therefore it would be nice if someone else could take care of this issue, because we are kinda stuck. Hopefully, the next person can solve this.

@a17vikab

**Comment by a17vikab** [comment]
> What we want to change is that when you create a new object another object can't be created at the same place. What we noticed is that when you create a new object the hover effect is not used until you actually move the mouse, which probably means that it only updates when you actually do a mouse move event. We are not sure how the hover effect are functioning, it seems to only work when doing a mouse move event, which makes this issue happen.
> 
> We know what we want to change but we don't really know where to do the changes, after a lot of trying and testing we feel like we are not able to solve the issue. I've had this issue for a long time now and I think it would be nice to get some new fresh thoughts on the issue. Therefore it would be nice if someone else could take care of this issue, because we are kinda stuck. Hopefully, the next person can solve this.
> 
> @a17vikab

Okay, I reassign this issue.
