### ISSUE TITLE
AccessED: Select/Unselect all option?

### ISSUE THREAD

**Issue by a16lisri** [HGustavs/LenaSYS#6769]
Suggestion: Maybe we could add a "Select all" or unselect all in the filtering (or something similar)? Maybe you just want to see first names, then it would get tedious having to unselect every other filtering option.

![filter](https://user-images.githubusercontent.com/37792690/57379183-b1064a00-71a6-11e9-9a13-b89d1c1c6f26.png)

**Comment by a17fellu** [comment]
fixed in Pull Request: #6817

**Comment by a17fellu** [comment]
There are issues to implement this. The way the table gets created it doesn't let you only add new items to the checkbox list without also them getting added to the actual table. So at the moment my fix in: #6817 works but it isn't a good solution but the only solution at the moment. There isn't really a standard on how these tables should be implemented. fileed, accessed and tested are completely different in the way they are built. So this function could probably be implemented in another of those tables but at the moment this doesn't really work for accessed. 

**Feel free to try and fix my implementation on branch:**  #GruppC2019W20_6769

But from my understanding this issue should be closed since there isn't really a good way to implement this.

**Comment by a17joaap** [comment]
This commit: https://github.com/HGustavs/LenaSYS/commit/4ce780b60d3ea5fa44cd9a82fabc5d0725611095

Adds an easy way of adding the toggle all button to the dropdown list

**Comment by a17fellu** [comment]
Edited the styling of the newly added toggle button in commit: 8308a70

Made it fit the other buttons. Also changed the cursor for when hovering over the drop-down menu

**Comment by a17fellu** [comment]
This is now ready for a Pull Request. Will create one for it

**Comment by a17fellu** [comment]
Pull Request with the fix: #6850

**Comment by a17fellu** [comment]
Merged, Closing
