### ISSUE TITLE
Dugga with text upload throws console error (generic_file_receive.js)

### ISSUE THREAD

**Issue by a17poner** [HGustavs/LenaSYS#6796]
Uncaught TypeError: Cannot set property 'innerHTML' of null
    at Object.returnedDugga [as success] (generic_dugga_file_receive.js:79)
    at j (jquery-1.11.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.min.js:2)
    at x (jquery-1.11.0.min.js:4)
    at XMLHttpRequest.b (jquery-1.11.0.min.js:4)

is thrown when entering a dugga that has a text upload.

**Comment by a17joaap** [comment]
This error occurs when an enabled variant does not exist, or when the enabled variant does not have a 'fieldname' value.

**Comment by a17poner** [comment]
aa okey, might've tested it in an unlucky way then when i tried to reproduce it :) Think there's a good solution to get rid of this? either by giving it a placeholder when submitting a variant or making a empty file link value get something that doesn't produce an error in generic_file_receive?

**Comment by a17joaap** [comment]
Yeah I see a weird thing in the code, row 78 on generic_dugga_file_receive.js:
`if (duggaParams['uploadInstruction'] !== null){`

The problem is that the variant parameters does not contain that key, and is such set to 'undefined'. Which is not null so the conditional is set to true..

Probably a remnant from a previous version, but I'm pushing an update that will resolve this issue.

**Comment by a17poner** [comment]
Great! 🎆
