### ISSUE TITLE
Accessed: Hovering on the "funnel"-icon menu for filtering is unreliable

### ISSUE THREAD

**Issue by a17robda** [HGustavs/LenaSYS#6920]
WEBM of issue:
https://imgur.com/a/rpyGf5b

Seems unreliable to have the window for filtering disappear when moving the mouse on it.

**Comment by a17andby** [comment]
@a17anter Haven't you worked on a solution for this in resulted?

**Comment by a17andby** [comment]
Found it, https://github.com/HGustavs/LenaSYS/issues/6520 

I will check if their solution (https://github.com/HGustavs/LenaSYS/pull/6816) also fix our issue

**Comment by a17anter** [comment]
Yes I believe that solution also works for your issue.

**Comment by a17andby** [comment]
I don't think that we need to solve this issue since @a17anter have done a solution that will also affect Accessed when we merge our groups together.

I have checked and tested @a17anter solution on Accessed and it will fix this issue as well. 

What do you say @a17poner ? Should we just close this issue, since it will be fixed in the weekly merge with groupB? So we don't get any unnecessary merge conflicts

**Comment by a17poner** [comment]
We'll leave this issue as is and hopefully and likely it will get fixed by @a17anter in the weekly merge
