### ISSUE TITLE
Text documents in codeviewer cannot handle bold text. 

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#6926]
![image](https://user-images.githubusercontent.com/49199285/57605177-5da94880-7566-11e9-9bf2-ffc448599c9f.png)

As seen on the picture, no bold text, instead it outputs stars that hightlights the boldness.

**Comment by a17fellu** [comment]
The question is, do we want it to be able to do that. Since it is a codeviewer and not a text editor?

**Comment by a17alevu** [comment]
I do not know. But I feel like if you want to highlight some important in text this tool is relevant. Not sure tho.

**Comment by a17fellu** [comment]
Lets try to get others opinions

**Comment by b16johso** [comment]
Bold would probably be useful. The text viewer is meant for instructions and information for the students and it would be nice to be able to set headers to bold for example.

**Comment by a17fellu** [comment]
Ok then i will start working on this

**Comment by a17andby** [comment]
I share @b16johso 's opinion

**Comment by a17fellu** [comment]
Maybe we should add all markdown functionality to it then?

**Comment by HGustavs** [comment]
If we are talking about the markdown view it should handle this but possibly with three stars instead of two.... I am not sure how this should work for txt files... they should probably display directly, but .md files should display using markdown, check the markdown description file in the root for exact syntax, I do think it is three stars not two in that case.

In short
* .txt should display as text
* .md should display using markdown in that case it may be three stars and not two.

**Comment by a17fellu** [comment]
Just tested it out and markdown works fine. This should probably get closed then
