### ISSUE TITLE
Short command for "Clear Diagram"

### ISSUE THREAD

**Issue by a17okaoz** [HGustavs/LenaSYS#6963]
Implement a short command for the button "Clear Diagram". This will make the process easier. 

@HGustavs Do you have any preference for this command?

**Comment by a14oscna** [comment]
The short command technically already exists as: Ctrl+A followed by Delete, since doing this selects all objects and deletes them. This works exactly as the "Clear diagram" option in the menu, therefore we do not need to implement any additional short command. 

Simply add the tool tip into the menu option.
