### ISSUE TITLE
Contribution: Dugga elements on the contribution page. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#7018]
Find some strange Dugga elements on the contribution page. It seems like elements from the showdugga appears in the background of the contribution page.. 

![image](https://user-images.githubusercontent.com/49194898/57688589-18584a00-763e-11e9-916d-8e92a8f7887a.png)

When inspecting the site it seems like many elements from Showdugga is appearing outside of the frameContainer.. 
![image](https://user-images.githubusercontent.com/49194898/57689396-bc8ec080-763f-11e9-858e-a811dae4358f.png)

Maybe someone can investigate if this elements can be removed or how we can solve this so the showdugga elements want appear?

**Comment by HGustavs** [comment]
Is it that I used copy from dugga for seeding the code or is it some other bug?

**Comment by a17joaap** [comment]
This is because all 'Test' duggas get the submit button table, should be easy enough to remove if the template is contribution.

**Comment by a17poner** [comment]
A semi related note on this is that because of contribution being an iframe, all its php code gets run so we get a new navheader but also include basic and session.php again and a side effect of this is we get two alerts saying our session is about to expire. Should probably be made into an issue of its own but contribution.php should probably get a lot of that php removed from it since it will get them from showdugga anyways or changed to normal template file like all the other duggas.

**Comment by a17joaap** [comment]
I'll add (remove) that to the PR
