### ISSUE TITLE
UMLlines are selectable when mouse cursor is not hovering the line

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7036]
In the image below, I am hovering the uml object named New1. The line gets highlighted and the line gets selected on mouse down.
The line should only be selected when pressing the line.
<img width="268" alt="umlLine" src="https://user-images.githubusercontent.com/49199690/57695725-4abe7300-764f-11e9-8fd3-fd8142cde5a3.png">

**Comment by HGustavs** [comment]
Seems like we are checking for diagonals? 

The code should use the same code as for diagonals but with three straight lines. Not a specific function for "lines with kinks". If this code uses the general "close to line" code, it should not be able to mis-identify clicks.

**Comment by a16tobfr** [comment]
I realize that my first picture was not fully illustrating where the line was given priority when selecting over other objects in the same area.
This probably gives a better idea of the area where the line is selected.
![umlLines](https://user-images.githubusercontent.com/49199690/57795610-b3d4e200-7746-11e9-9c2e-c2bf5ca19b8a.JPG)

**Comment by a17johpe** [comment]
The pull request that solved this issue has not been merged due to too many major issues with UML line anchors. 

The code that solves it can be found here: https://github.com/HGustavs/LenaSYS/pull/7652/files
the two important functions _should_ be "checkForHover" and "UMLLineHover" in the file diagram_objects.js.

However, this solution only works if anchors are in place as well (which was what the pull request mainly set out to solve). See https://github.com/HGustavs/LenaSYS/issues/6577 for further documentation on that.

**Comment by b18mikfr** [comment]
This issue is was popping up due to lack of functionality of the UMLLine symbol. It was treated like a regular UML symbol and thus i implemented functionality that followed what is drawn on the diagram. Took forever to implement but it is done and ready to review. Every case for each UML Line realtionship is supported. The issue of UML Lines being selectable over other symbols is present and would suggest another issue to solve that particular problem.
