### ISSUE TITLE
motd overlapping text

### ISSUE THREAD

**Issue by b17annni** [HGustavs/LenaSYS#7073]
![image](https://user-images.githubusercontent.com/37792766/57771460-101e0e80-7713-11e9-998f-12164ff53d82.png)

**Comment by c17julka** [comment]
This is actually a part of Grupp B's segments, since it is on courseed. As a result of this, 2 issues now exist (#7106) and are being worked on at the same time.

Please refer to this when labeling issues :) 

![Screenshot 2019-04-03 09 33 36](https://user-images.githubusercontent.com/37792321/57841168-5aae9200-77ca-11e9-9709-3e7cf9cc7b73.png)

**Comment by a17poner** [comment]
Yep, to avoid conflict this won't be merged and you could drop this and stop working on it, any thing related to courseed or sectioned which includes motd and hamburgers should belong to group B and we should refer to them first.
