### ISSUE TITLE
Modify the HTML code for the menu

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#708]
The menu consists current of a table. We consider this as a bad solution to a menu.
We would rather use div tags and float-left, for example.

**Comment by HGustavs** [comment]
The problem is the following
* A width-adaptive design with only css if page is narrow we do not want the icons one below another. It should adapt and reduce until the menu items no longer fit, at which point scroll bars should appear.
* Simple html layout readable directly in the file, without changes
* When page is resized, no javascript should be needed to compensate

If the css/code could be reduced without bad effect (errors with reduced size or failure to adapt to web page width) I do not personally mind. But if it does not reduce the html/or css or breaks the page there is no point to this change.

**Comment by c13caral** [comment]
Could you be more specific? The first point is understandable, but the other two is more on the lost phase. If I understand correctly, you want us to create/test if we can create a simple html layout, but do you want us to implement the image with <img src>? And the last point, what does the javascript have to do with resizeable the page, isn't that why we have CSS in the firstplace?

**Comment by HGustavs** [comment]
The problem is that it is quite complex to make a width-adaptable layout using pure css.
We want a menu on the right, and a layout that adapts when the page is resized.

This tends to often result in very complex layouts with deeply nested divs and spans and lots of css to account for the adaptation to the screen width, whereas a table layout "just works"....

Float-left and float-right are difficult to get "right" such layouts often use absolute sizes in pixels to work properly. If the screen layout changes or the size of a text field or image changes, these "absolutes" need to be updated in the css or updated live using javascript.

One common failure of floating layouts is that in HTML elements "want" to stack vertically, not horizontally, if you want 5 buttons with unknown width, then to the right, a button of unknown width and between them space to fill out the rest.... this may or may not be easy to do. And it may result in the page "breaking", at a certain width of screen or size of button... the buttonst will start to stack vertically rather than horizontally.... whereas when using a table this is automatic, nearly no css and only basic html in the static file.

**Comment by HGustavs** [comment]
If you feel up to the task I am not against it, but to me, it is better to focus on some issue that is "broken" or "missing" rather than spending time on repairing something that is not exactly broken.

Having said that, if you can produce a demo/test page that works and it is better than the existing one I dont mind having a standardized html layout.
