### ISSUE TITLE
Login/logout button only works as long as you have the console open. 

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#7135]
The login/logout button only works when you have "inspektera" open. 

![image](https://user-images.githubusercontent.com/49199285/57778335-1ff21e80-7724-11e9-8591-f9de5b523f56.png)

NOTE: This is only a issue when you want to logout, logging in is not an issue what i can tell.

**Comment by a17joaap** [comment]
This is a weird one, the logout button does not work in sectioned for me even with inspect open. It does work everywhere else, with inspect closed/open.

**Comment by a17joaap** [comment]
Looking closer, I believe this to be because of a double navheader:
![doublenavheader](https://user-images.githubusercontent.com/37792198/57782348-5469d880-772c-11e9-86ad-9a86e6af2961.PNG)

A less than optimal situation, I'll try to implement the menu options to the standard navbar instead of adding another navbar over the other navbar
