### ISSUE TITLE
[SectionEd] Cannot set deadline in Edit Item dialog

### ISSUE THREAD

**Issue by b17nicsv** [HGustavs/LenaSYS#7191]
Cannot set deadline in Edit Item dialog on items except tests. The deadline shouldn't show if the type doesn't allow for deadlines.

@HGustavs Should you be able to set deadlines on anything else than tests? If not, then I propose we hide the set deadline from the view to avoid confusion.

**Comment by HGustavs** [comment]
We want the dialog to be complete, if we change between types, it is very counter-intuitive if items appear and re-appear or enable / disable when we change types.

Therefore we want all items to work at all times, cince we in the next workflow step will change from for example a heading to a test, and we want the items to remain in the dialog.

**Comment by a17anter** [comment]
@HGustavs 
But if the dialog always should be complete it means that we can see rows that makes absolutly no sense to the specific type.
For example if the item has type "header" we can still see "deadline" and "highscore" which makes no sense?

The reason why I'm asking is because in the beginning of this course I worked on an issue that removed the visibility of "Grade system" if the item doesn't have type "Test" or "Moment". https://github.com/HGustavs/LenaSYS/issues/5606

**Comment by b17nicsv** [comment]
@HGustavs Bump

**Comment by b17nicsv** [comment]
Closing this because it should always be complete. Hiding rows shouldn't be implemented on any type.
