### ISSUE TITLE
Missing chart in 'Charts' view

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#7307]
This chart:
![missingchart](https://user-images.githubusercontent.com/37792198/58074301-3e816b00-7ba5-11e9-8aa7-eecfb4948768.PNG)

Would be expected in the 'Charts' view of contribution, instead we get a table:
![missingcharttable](https://user-images.githubusercontent.com/37792198/58074364-65d83800-7ba5-11e9-99cc-dd289b259446.PNG)

**Comment by HGustavs** [comment]
This is a bug?

The table is for teachers only, not for students and the svg view is for the current selected user if teacher or the current user if student.

**Comment by a17poner** [comment]
Yea this is a bug, after changing all the tables in contribution to sortableTables the groupings that had been made got leftout and a lot of the tables are in the wrong places compared to how it used to be. We will make a seperate issue to deal with the layout of contribution and groupings but waited with creating it since there was still big changes to one of the tables currently waiting approval and I wanted to avoid as many conflicts as possible 😄
