### ISSUE TITLE
Arrows are broken in Codeviewer

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#7313]
https://gyazo.com/b1644c479fb2664cb61b5ddb7d3af5cc 

As seen on the gif, when you press the arrows (which are supposed shift between different code examples) you cannot use them again to go back to the previous code example. I feel like this is not right.

**Comment by a17robes** [comment]
https://gyazo.com/1fa20eeb1b8b5c65c8a8c8c92f335e1d

As demonstrated in the gif, you have to choose "before:" and "after:" on each "Example". When doing this, you can use the arrows for switching between the chosen "before:" and "after" examples.  You probably forgot to choose values for these two, and therefor it did'nt work.

Maybe we should close this issue since the "before" and "after" buttons are working? @a17alevu

**Comment by a17alevu** [comment]
Closing this issue.
