### ISSUE TITLE
Cookie message overlapping MOTD

### ISSUE THREAD

**Issue by a17alian** [HGustavs/LenaSYS#7329]
The cookie message is overlapping the MOTD when on a big screen. 
![bild](https://user-images.githubusercontent.com/37792256/58085665-7399b780-7bbd-11e9-8b09-67fb1bab1d5c.png)

But when resizing the screen to a smaller size it jumps down to it's proper position
![bild](https://user-images.githubusercontent.com/37792256/58085691-83190080-7bbd-11e9-900b-c917ed5778f2.png)

**Comment by a17anter** [comment]
This is due to the fact that someone commented out the "default" position of the cookie-msg and added code for if the window is a certain size as can be seen below. Is the cookiemsg supposed to move depending on the size of the screen or what is supposed to happend? 

"Default" position
![image](https://user-images.githubusercontent.com/49204317/58177198-35c38e80-7ca4-11e9-893d-c9886c29ba78.png)

Restriction 1
![image](https://user-images.githubusercontent.com/49204317/58177247-4ecc3f80-7ca4-11e9-8a3f-8bc30b9d171c.png)

Restriction 2
![image](https://user-images.githubusercontent.com/49204317/58177272-5c81c500-7ca4-11e9-8f95-5fc37d58e0b4.png)

**Comment by b17nicsv** [comment]
We want the cookie to always be at the bottom of the screen when appearing regardless of screen size. I think removing the comments around `.alertmsg#cookiemsg { bottom: 0px; } ` would fix the problem.
