### ISSUE TITLE
Cardinality attribute for a symbol should hold an id

### ISSUE THREAD

**Issue by b17robev** [HGustavs/LenaSYS#7391]
In its current implementation the caridinality attribute holds an object, which gives an circular structure error when converting JSON to a string (probably related to localStorage). It should instead hold an unique identifier for each symbol. This should probably not be implemented until #7181 is done.

![ugly](https://user-images.githubusercontent.com/37845511/58171297-f68e4100-7c95-11e9-8ab1-6132bcdac719.png)

**Comment by HGustavs** [comment]
What object does it contain?

**Comment by b17robev** [comment]
It contains the line's parentObject which should be it´s entity. This is used to find out which direction to move the cardinality.

**Comment by a17alfcl** [comment]
This should also solve issue #7361, one of the issues should perhaps be closed.

**Comment by a18petha** [comment]
This error cannot be reproduced. seems as GruppA already implemented a fix for this issue, which did not include the need for an ID. There is no need to add IDs if there not gonna be use for anything, for issue 7361 there is smarter way of fix this issue instead of trying to order the elements by id

**Comment by a18petha** [comment]
Seems as this issue has re emerged with W-16 weekly branch. re opening this issue

**Comment by a18petha** [comment]
I found the issue that causes this error and it relates to following code

`cardinality.parentBox = diagram[i];`

the issue here is that cardinality.parentBox is an element within diagram, linking like this causes infinite loop which results in a crash. Removing this one line of code seems to solve the problem,  although I don't know how desirable of a solution this is, it might cause issue at other places of the software.

here is screenshot of console printing out the loop
![Capture JPG5](https://user-images.githubusercontent.com/49141878/79246065-457a3180-7e79-11ea-9bd3-00aadb01a6b1.JPG)
@HGustavs @mbrohede 
have any recommendation for how to go forward with this issue?

**Comment by a18petha** [comment]
Seems as this solution might be more fit

```
cardinality.parentBox = diagram[i];
delete cardinality.parentBox.cardinality[0].parentBox;
```

With this solution we keep the old code structure but remove the infinite loop logic from it.
