### ISSUE TITLE
code viewer button minimize

### ISSUE THREAD

**Issue by b17annni** [HGustavs/LenaSYS#7401]
Perhaps a minimize to go with the maximize.
![image](https://user-images.githubusercontent.com/37792766/58173379-808cd880-7c9b-11e9-9cc5-a5f3fed9d849.png)

**Comment by a17maxsj** [comment]
+1

**Comment by a17alevu** [comment]
I agree! =)

**Comment by a17maxsj** [comment]
However the button does not really minimize the section, it reverts to its prior state

**Comment by a17maxsj** [comment]
Adding another button minimizing would probably be a better idea

**Comment by b17annni** [comment]
Adding a minimize button was what I intended with issue.

**Comment by HGustavs** [comment]
Good idea.

**Comment by a17fellu** [comment]
Just keep in mind that when you would try to minimize a box that is maximized you need to hard code the size of every box for every template (-template9 and template10). Since we need to minimize that specific box all other boxes widths and heights needs to be recalculated. At least from my understanding.
