### ISSUE TITLE
Error message on contribution page

### ISSUE THREAD

**Issue by a16lisri** [HGustavs/LenaSYS#7460]
If you are logged out, you can't see the contribution page. There is an error message that states you can't see it but it only appears for a split second. Either we could have it stay there or we could remove it completely. What do you think? Made a gif to demonstrate this: https://gyazo.com/94967ebe4ab81976a5e952ff03c1be7b

**Comment by b16johso** [comment]
Maybe have the contribution page display a text saying something like "You must be signed in to use this feature"?

**Comment by adajoh** [comment]
I agree with b16johso, even if you are not supposed to see or do anything when not logged in, the system should provide relavant information about what the problem is so the user can make the right choice

**Comment by a17adajo** [comment]
I agree with b16johso, even if you are not supposed to see or do anything when not logged in, the system should provide relavant information about what the problem is so the user can make the right choice

**Comment by a16joare** [comment]
This issue is still active from 2019. 
I think that the problem is that showdugga is loaded before the contribution file. This means that the content from contribution ends up on top and blocking the error message. 
![image](https://user-images.githubusercontent.com/49194898/58462557-7141db00-8132-11e9-8d2b-2fda89ca57f5.png)

**Comment by a20behta** [comment]
This issue is not relevant as error will be replaced with login page
