### ISSUE TITLE
Global Appearance menu doesn't affect UML objects anymore

### ISSUE THREAD

**Issue by c17matjo** [HGustavs/LenaSYS#7483]
Changing settings in the global appearance menu doesn't affect UML objects anymore after #7417. Changing e.g. stroke color updates the stroke color for all objects when in the global appearance menu but is not saved(?) when you click "OK". 
![bild](https://user-images.githubusercontent.com/49195031/58312185-0c714280-7e0b-11e9-9b1b-52cae629b611.png)
Screenshot was taken after setting stroke color to purple in global appearance window. Only ER objects received the new stroke color.

**Comment by a16tobfr** [comment]
I just want to add that global appearance has not affected the UML objects before, so this is nothing new. Do we want colorful UML diagrams and UML classes with large text sizes?

**Comment by c17matjo** [comment]
From my testing they did seem to work up until merge commit 2e64aea3. The following screenshot was made on commit 728cf96cc, the one just before PR #7417 was merged. 

![bild](https://user-images.githubusercontent.com/49195031/58423952-9e40b000-8096-11e9-9843-c5cba92df2bb.png)

**Comment by a16tobfr** [comment]
I see, then it worked like you are describing at one point. Though I know it did not work from the start and that it has not worked like this for the last few days (before we started meddling with the global appearance changes that are now merged), hence my comment.

However, the global appearance should not change attributes for objects in both modes at the same time. Maybe in dev mode where 'display all tools' is selected, but not when you are in the ER, ER + dev or UML, UML + dev modes, then it should be exclusive to the mode you are in.

**Comment by c17matjo** [comment]
If the global appearance menu should be mode specific then that should get it's own issue.

**Comment by a18antsv** [comment]
Issue #7645 is related here.

**Comment by a18antsv** [comment]
As of right now there is no way of knowing what will be affected without trial and error. You could also question if UML should even be affected at all by any changes for global appearance. There is no options for changing appearance except for name, operations and attributes for individual UML appearance. If it should be possible to change UML apperance from global apperance there should also be options in the individual appearance form to make it possible to change one uml class apperance more. Otherwise UML classes should not be affected by global apperance. Same for all other types of symbols.

**Comment by a18antsv** [comment]
I have reworked the whole structure of apperance menus which should make it much easier to add or remove functionality.

**Comment by g18marma** [comment]
What is the actual goal of this issue? Because it seems like there are a bunch of different opinions on what should be done.

**Comment by a18kaswi** [comment]
Closing this because of reasons, check #7645
