### ISSUE TITLE
Points stay, even after UMLLine gets deleted

### ISSUE THREAD

**Issue by b17albbe** [HGustavs/LenaSYS#7491]
When you delete the UMLLine, the point doesn't get removed with it. This leads to the starting point of the line being pushed further and further away from the center, like this screenshot shows:
![7e3cae8f4f2b25701d5ab59c2ff83e87](https://user-images.githubusercontent.com/38030926/58315171-48a7a180-7e11-11e9-958d-b4e5249ccbfa.png)

**Comment by a14oscna** [comment]
I believe that after recent updates, this issue is no longer present. I tried: deleting with backspace, delete and undo in both Dev mode and standard UML mode. I will close this issue until further notice.

**Comment by a14oscna** [comment]
After further discussion with b17albbe he clarified that the issue still exists although the points (as shown in his first image) are not visible.
![yallah](https://user-images.githubusercontent.com/37793141/58474746-4fede880-814c-11e9-8886-c384d83d1014.PNG)
This image shows that when drawing multiple lines AFTER having deleted a line, there is a weird spacing between them as if the deleted line still occupies the space. I will open this issue again due to this.

**Comment by b18phibe** [comment]
The erases object function starts on line 1800 in diagram.js and the same code are to remove both er and uml lines(as well as all other objects) but the problem does not occur in er. 

To see the  x's explained in the first post you need to reference the page in developer mode after delinting the lines.

**Comment by a18antsv** [comment]
The points are visible again after page refresh it seems but invisible directly after deletion.

**Comment by a18kaswi** [comment]
Possible connected:
#5057
#6491
#7491
#7673

**Comment by o18marka** [comment]
#7673 definitely seems to be connected after working towards a solution.
