### ISSUE TITLE
Sortabletabel set decimals and title for sum

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#7497]
you should be able to set the number of decimals for the sum and also set a title in the far left field natively. 
![image](https://user-images.githubusercontent.com/49199993/58316943-0c764000-7e15-11e9-9af6-526a9207e215.png)

**Comment by b18veran** [comment]
Is this issue relevant now? Is this page still on LenaSys?

**Comment by c14jonfr** [comment]
I believe the screenshot is from the contribution-page (the URL says showDugga though). Maybe this should belong to group 1 instead?

**Comment by a20behta** [comment]
Issue remains, need to limit the decimals. 
2 decimal points seems like a good point unless @HGustavs has a different opinion.

**Comment by a20caros** [comment]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/81676918/165468569-fbbbf95f-8f09-40c7-aafa-7862c01c2fc9.png">
The table ranking and group ranking have only two decimal places now instead of before when there were several. The table number is not a decimal number. To solve this, an if statement is used that checks if the line is called number and does not add two decimal places.
A title has also been added to make the table clearer.

To solve the problem, help and discussion were taken by @a20willa  and @a20novra  to find where the tofixed() method would be placed so that the correct result would be executed

**Comment by a20behta** [comment]
merged into master 
branch closing issue
