### ISSUE TITLE
Columns with long names should be shortened in resulted

### ISSUE THREAD

**Issue by c17julka** [HGustavs/LenaSYS#7518]
![image](https://user-images.githubusercontent.com/37792321/58325823-47836e00-7e2b-11e9-818b-4cb7b2ebc0fd.png)
Tests with long names resutls in very wide columns in the resulted view. Perhaps they should have some sort of max width.

It seems like it has been the intended behavior at some point, since the th spans have an ellipsis on overflow text.

**Comment by a17alian** [comment]
Yes, the columns should definitely have some kind of max width. Maybe using some sort of text wrap instead of ellipsis since duggor can have similar names. Ex Biträkningsdugga 1  and  Biträkningsdugga 2 etc

**Comment by a18viksa** [comment]
@a18marax and I have this issue. The problem with ellipsis is that the text disappears and makes it impossible to know if it's for example "Biträkningsdugga 1" or ""Biträkningsdugga 2". But if you use a text-wrap or overflow-wrap the th-elements height varies in size. I don't know if that's a real issue since no dugga example name is too large to make that a serious problem.

**Comment by a18viksa** [comment]
One solution to the problem can be to implement an ellipsis to the text and on top of that a hover-effect that displays the full name of the dugga. Working on different solutions with @a18marax.

**Comment by a18viksa** [comment]
Can't really understand the tables syntax since there's a div and span inside the table head. Would be easier to work with if resulted was actually working... Waiting for fix. 

Trying to implement styling to span, div and th but without results.

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
