### ISSUE TITLE
Better explanations in options for UML line 

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#7560]
![Edited](https://user-images.githubusercontent.com/46029340/58410960-8efc3b00-8073-11e9-91d8-03199c73ee50.png)
First and Second object is a bit unclear in this menu. Should show the names of the objects instead. (New 0 and New 1)

**Comment by a17jonro** [comment]
The line direction is basically just a visible thing and the direction is determined depending on the start and end points for the line, which in turn depends on in what order the line is drawn between objects. So in order to implement this behavior the text "First object" and "Second object" should change depending on which objects the line is connected to when the apperance dialog is opened.

**Comment by a17drama** [comment]
Exactly. That way it's easy to make a choice. Knowing which object is which when they are called first and second is a bit throwing a dice. It works but there is a 50% chance of making the wrong choice. With the names of the connected objects there it's much easier.
