### ISSUE TITLE
AccessEd: Group(s) dropdown list buggy

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#7566]
The dropdown lists in the Group(s) column are buggy. After opening one and then closing it, they all become impossible to use as they will just automatically close themselves immediately after opening. Refreshing the page makes them usable again. Also, they have no highlighting effects like the other dropdowns do.

**Comment by a17robes** [comment]
in accessed, should there be possible to choose more than one option in "Group(s)", could I for example be a member of multiple group(s)? 

![image](https://user-images.githubusercontent.com/38004435/58421661-ccbb8c80-8090-11e9-8ca6-398e9ac5b401.png)
@HGustavs

**Comment by a17robes** [comment]
Found an ugly solution for this by creating a new variable instead of the "expanded"-variable ( is declared as a global variable in accessed.js) in ` Function showCheckboxes(element)`.  I think I wont commit this because of the risk of it affecting other stuff on the page, with the small amount of time we have left. For the next assignee, the following code is a possible solution for this issue. 

`var test = expanded;
function showCheckboxes(element) {
	activeElement = element;
	var checkboxes = $(element).find(".checkboxes");
	checkboxes = element.parentElement.lastChild;
	if (test) {
		checkboxes.style.display = "block";
	} else {
		checkboxes.style.display = "none";
	}
	test = !test;
}`
