### ISSUE TITLE
Fix text and styling in import-dialog

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#7618]
The button "Välj fil" should have the same styling as all the other buttons. Also, all the text in the dialog should be changed to English (if possible...) and not Swedish to make it more user-friendly.

![Skärmavbild 2019-05-28 kl  11 04 54](https://user-images.githubusercontent.com/37792795/58465714-8faad500-8138-11e9-8633-173c17410016.png)

**Comment by a17okaoz** [comment]
The button "Välj fil" should have the same styling as the "Upload diagram". Just insert the class that the "Upload diagram" button to "Välj fil". And change the name so it is in English.

**Comment by g18marma** [comment]
This issue is not solved by adding the same styling as other buttons, as most browsers will not change the appearance of input type="file" from either CSS or javascript. An approach is to have a custom label element with a for attribute attached to the file input element, and then hide the actual input element.

Something like the following illustration.

![Screenshot_3](https://user-images.githubusercontent.com/49142301/79215449-d508eb80-7e4b-11ea-96fa-982967b73d1e.png)
