### ISSUE TITLE
Resulted Search bar Å doesn't work

### ISSUE THREAD

**Issue by ghost** [HGustavs/LenaSYS#7620]
Able to search for Lind
![image](https://user-images.githubusercontent.com/49199825/58465894-e57f7d00-8138-11e9-884e-45229bf2aae2.png)

Unable to search for Å
![image](https://user-images.githubusercontent.com/49199825/58465965-0a73f000-8139-11e9-9777-fef4ee610a66.png)

PS. ä,ö is working

**Comment by c17johha** [comment]
![image](https://user-images.githubusercontent.com/49199825/58466066-3becbb80-8139-11e9-9445-9d8018ff8e36.png)

**Comment by a17oscno** [comment]
@c17johha It seems to work on lastnames though.

![image](https://user-images.githubusercontent.com/49207814/58467053-35f7da00-813b-11e9-9acb-1d187d6b5720.png)

**Comment by a17oscno** [comment]
@c17johha Or is it only a problem with "Å" and not with "Ä" and "Ö"?

**Comment by a17ludca** [comment]
Seems like it only has trouble with "Å" 🤔

**Comment by a17oscno** [comment]
The problem either exists in the Resulted.js file or the Resultedservice.php file because it can either (or both) be that the letters are changed to "wierd letters" (like Å being aur; because the english language do not have that) or it might be that the firstname in the SQL query in Resultedservice.php dont do the conversion from "wierd letters" to the normal Å, Ä and Ö

**Comment by a18sebka** [comment]
The problem does not seem to exist on my end, Å, Ä and Ö works for me. Would be good if someone else tested it as well.

**Comment by a18sebka** [comment]
Already works.
