### ISSUE TITLE
Unable to search in mobile view (fileed.php)

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7640]
On desktop you can see the search bar in the header:
![image](https://user-images.githubusercontent.com/37834592/58473279-7c076a80-8148-11e9-8064-3b7355d39283.png)

But on mobile there's no searchbar:
![image](https://user-images.githubusercontent.com/37834592/58473292-845fa580-8148-11e9-876c-547b1845ea90.png)

**Comment by c17julka** [comment]
There was an issue at some point to implement a searchbar below the header when on smaller screens. I guess that issue was never solved?

**Comment by a17poner** [comment]
This somehow dissapeared during the last merge, not enough time for us to fix it again since there are other things with higher priority than setting up mobile view for admin only pages. The code used to fix this the first time around is available in the files changed in the pr linked above if henrik wants this done next year, glhf!

**Comment by a17poner** [comment]
nvm this seems to have been fixed when we did the merge a second time closing again!
