### ISSUE TITLE
Global Appearance should be mode specific

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7645]
The global appearance should be mode-specific, meaning that when the user is in ER mode, the global appearance should only change the settings for the ER objects, and when in UML mode the settings should only change for the UML objects.

The same approach is also relevant for the three dev modes.

DEV + Display All Tools -> Global Appearance -> affect ER and UML

DEV + ER -> Global Appearance -> affect ER ONLY
DEV + UML -> Global Appearnace -> affect UML ONLY

MODE: ER -> Global Appearance -> affect ER ONLY
MODE: UML -> Global Appearance -> affect UML ONLY

This means that the DEV + ER and ER modes belong to the same category, and the same is true for the DEV + UML and UML modes.

**Comment by a18antsv** [comment]
This is necessary. As of right now there is no way of knowing what will be affected without trial and error. You could also question if UML should even be affected at all by any changes for global appearance. There is no options for changing appearance except for name, operations and attributes for individual UML appearance. If it should be possible to change UML apperance from global apperance there should also be options in the individual appearance form to make it possible to change one uml class apperance more. Otherwise UML classes should not be affected by  global apperance. Same for all other types of symbols.

**Comment by a18antsv** [comment]
I have reworked the whole apperance menu which should make this easier to implement because of the logic is being built by.

**Comment by a18kaswi** [comment]
appearanceDiagram
#7677
#7928
#7645
#8067
#6888

**Comment by a18antsv** [comment]
I have fixed this now. There is just one problem; all objects use the same base settings when being created. So when changing global appearance settings in UML mode, only objects active in the toolbar will be changed. But when creating a new object that is not in the UML toolbar, they will still have the new settings that were set for UML. Or when opening the global appearance menu for a new mode, the settings that were set while in UML mode will be used as presets.

**Comment by a18antsv** [comment]
It could be solved by having a different settings object for each mode.
