### ISSUE TITLE
Disable drawing multiple lines between same objects

### ISSUE THREAD

**Issue by a17alfcl** [HGustavs/LenaSYS#7647]
As of now, several lines can be drawn between the same two objects.

![ugly](https://user-images.githubusercontent.com/49202727/58475070-3d27e380-814d-11e9-819c-de850db1c09a.png)

**Comment by g18marma** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/49142301/78642025-58599880-78b2-11ea-8548-03454e4624cb.png)

Right now there are if-statements that check if entities are connected to the same attribute multiple times and if that is the case the user wont be able to draw more lines between them. The solution to this issue is to do the same but with attributes to relation and vice versa.
