### ISSUE TITLE
Problem with UML lines and Free draw

### ISSUE THREAD

**Issue by a17alfcl** [HGustavs/LenaSYS#7673]
When removing an UML line and one of the objects connected to it, and then drawing a free draw object, the free draw object gets connected to the UML object. 

![ugly](https://user-images.githubusercontent.com/49202727/58545318-4d9a9580-8203-11e9-8dae-7d3cee56f783.png)

**Comment by a17alfcl** [comment]
Interleaved with issue #7491

**Comment by b17albbe** [comment]
I don't think the issue is just related to the free draw tool, but all kinds of objects. For example, if i delete a line between two UML classes, and then create a new object, the new object will snap to the previous line points as this picture shows:
![3c921468eb88c5596ad6d6f49025f3d7](https://user-images.githubusercontent.com/38030926/58546990-cfd88900-8206-11e9-9cd3-ec6768e95c4c.png)

**Comment by a18kaswi** [comment]
Possible connected:
#5057
#6491
#7491
#7673

**Comment by o18marka** [comment]
> When removing an UML line and one of the objects connected to it, and then drawing a free draw object, the free draw object gets connected to the UML object.
> 
> ![ugly](https://user-images.githubusercontent.com/49202727/58545318-4d9a9580-8203-11e9-8dae-7d3cee56f783.png)

This problem seems to apply to all objects, not just free draw objects!
