### ISSUE TITLE
Line can be changed to forced in some cases.

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7676]
Line changes to forced

This only happens in situations where a line has been drawn directly from a relation to an attribute.

Seems to happen when we have a weak entity which is moved over a normal line.
<a href="https://gyazo.com/a196e32a14142b2a6f436a9a55a81202"><img src="https://i.gyazo.com/a196e32a14142b2a6f436a9a55a81202.gif" alt="Image from Gyazo" width="1199.9999999999995"/></a>

**Comment by a17alfcl** [comment]
Should be solved by adding a reference on the line for the ID:s of the objects connected to it. Currently this issue is caused by calculating the correct object. An ID would remove the need for these calculations. Similar solution to that of cardinality, which is also calculated rather than retrieved from ID.

**Comment by a16tobfr** [comment]
Since we now use ID's, the logic for making this work should probably be refactored.

**Comment by g18marma** [comment]
This issue is resolved from previous merges. Issue closed
