### ISSUE TITLE
SortableTable/Resulted: supplied csv delimiter is discarded, instead ";" is used

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#7687]
The delimiter set in:
https://github.com/HGustavs/LenaSYS/blob/ccd052de3394630af07b584ab2fc3e223ead8557/Shared/SortableTableLibrary/sortableTable.js#L686-L688

Is not used for export, see examples:
https://github.com/HGustavs/LenaSYS/blob/ccd052de3394630af07b584ab2fc3e223ead8557/DuggaSys/resulted.js#L1318
https://github.com/HGustavs/LenaSYS/blob/ccd052de3394630af07b584ab2fc3e223ead8557/DuggaSys/resulted.js#L1363

**Comment by b18fella** [comment]
I issue #7687, vad är det exakt som söks/vad som ska stå? Svårt att se hur resultatet ska vara utan ett exempel på det.

**Comment by HGustavs** [comment]
I believe that this has to do with the export of results 
and/or
the emailng of users in access editor

dont remember if any other tables can be exported?

Try to export some results by pressing the button... what comes out?

Feel free to paste excerpt here.

**Comment by b18fella** [comment]
![exportResult](https://user-images.githubusercontent.com/49142651/78342299-584b5700-7599-11ea-8b66-1a6a4d455aff.png)

This is what comes up when you click the button.

**Comment by HGustavs** [comment]
Probably due to no results or no students?

Seems like completely empty?

You must test this type of functionality on a course with results/students/course modules/submodules/tests

**Comment by HGustavs** [comment]
Seems like the delimiter is ; though...

please test on a course that has students and results to confirm that not only header has ; as the delimiter

**Comment by a18ismca** [comment]
Maybe you that have had this assignment before to check again if this works as there is enough of data right now? with @a17pioja to @b18fella @b18alegu @a18oscte @b18alegu

**Comment by a17pioja** [comment]
@HGustavs Me and @a18ismca are not sure what the problem is, should the delimiter not be ";" (semi-colon)? The software seems to be using the supplied delimiter contrary to what the issue states.
We are able to change the delimiter succesfully.
![image](https://user-images.githubusercontent.com/49141519/79212473-fc5db980-7e47-11ea-9d1b-1913729bdeca.png)

**Comment by a18ismca** [comment]
![image](https://user-images.githubusercontent.com/62876523/79734719-759d5680-82f7-11ea-9f82-c36f0e4d92a5.png)

We have succeded to separate the unique value "ssn" from the other values by using "," instead of ";". The only thing we wonder is if this is the solution to the issue? As we have read this issue, we can tell that this issue lacks enough data to figure the objective of this issue. For example, it would have been good by screenshoting an example of the fault of ladExport window.

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
