### ISSUE TITLE
Contribution: Only half of the tooltip is visible

### ISSUE THREAD

**Issue by a16lisri** [HGustavs/LenaSYS#7712]
When hovering over contribution buttons, you can only see half of the tooltip that shows up. Demonstrated in gif below:
https://i.gyazo.com/87837dd38b24eba03e585816b8ceb787.mp4

**Comment by HGustavs** [comment]
This is linked directly, since it is only valid for software engineering courses, we link contribution.php

**Comment by a18eliek** [comment]
> This is linked directly, since it is only valid for software engineering courses, we link contribution.php

Linking directly only seems to work on the live version of LenaSYS. Ex: [https://dugga.iit.his.se/DuggaSys/contribution.php](url)

However, on a local installation the user is redirected upon visiting the following example URL: [http://lenasys/DuggaSys/contribution.php](url) to this [http://lenasys/DuggaSys/sectioned.php?courseid=UNK&coursevers=UNK](url)

It appears like the live version differs a lot from the master branch, at least in this matter.

**Comment by a20caros** [comment]
![image](https://user-images.githubusercontent.com/81676918/162159581-860c0249-fe96-4fc4-93d7-512d2d07c505.png)
Now when you hovering over contribution buttons the issue that you only can see half of the tooltip is fixed. But the contribution button still have a problem, the problem is that the tooltip is in front of the buttons and hide the buttons. 

One solution is to remove the tooltip in that reason that the tooltip have no reason to exist because the tooltip says the same that the button.

**Comment by a20caros** [comment]
![image](https://user-images.githubusercontent.com/81676918/162169429-70d22e43-aa2b-445c-ac40-34f19cb721ea.png)
Now the contribution buttons only have a lighter colour effekt when you hovering over the buttons.

**Comment by a20behta** [comment]
merge into main branch issue solved.
