### ISSUE TITLE
Accessed: Change "Reset PW"-button from purple 

### ISSUE THREAD

**Issue by a16lisri** [HGustavs/LenaSYS#7722]
Related to https://github.com/HGustavs/LenaSYS/issues/7569. The latest added users' "Reset PW" button appear different than the other ones. The current background colour is purple, but this doesn't really indicate that the user is new. I suggest to change the colour to something else, to maybe make it more obvious what it means.

![58417091-08038e80-8084-11e9-82a9-962c0c43cafe](https://user-images.githubusercontent.com/37792690/59781687-98687400-92bc-11e9-9dcd-bff0e8a5c7ca.png)

**Comment by a18eripi** [comment]
Confusing issue. Me and @a18matna are investigating, however the installed local version of lenasys contains no entrys for this database, and the database is missing in SQL entirely. This makes testing very frustrating, since we are changing colors we can not see.

The logic in the code seems to suggest newer accounts should be purple - but investigating the CSS  code & accessed.js logic shows that old accounts should use the purple colour, and new accounts the yellow. Very confusing.

**Comment by b18alegu** [comment]
@a18eripi and @a18matna, there are two pull requests linked to this issue. Which one do you propose to be merged with our groups branch?

**Comment by a18matna** [comment]
@b18alegu the one made yesterday and commited by @a18eripi and Me. not "komplettering by ..."

**Comment by b18alegu** [comment]
Issue solved last week (W15 2020). I'm now closing this issue.
