### ISSUE TITLE
SectionED: Unclear icons

### ISSUE THREAD

**Issue by b17annni** [HGustavs/LenaSYS#7724]
All the new icons in navbar is somewhat unclear. However the test one is the worst offender. Should be changed.
![image](https://user-images.githubusercontent.com/37792766/59827998-4bc37e00-933a-11e9-910d-ca825955acae.png)

**Comment by b17annni** [comment]
![image](https://user-images.githubusercontent.com/37792766/59830086-2f761000-933f-11e9-908a-fca21b44603c.png)

**Comment by a17towan** [comment]
Suggestions:

### 1.  ![image](https://user-images.githubusercontent.com/49142028/78651176-43840180-78c0-11ea-8863-9a46cd1a8a63.png)
With an 'A'

### 2. ![image](https://user-images.githubusercontent.com/49142028/78652110-927e6680-78c1-11ea-837a-7563e96ef899.png)
Same as 1 but bigger 'A'


### 3.  ![image](https://user-images.githubusercontent.com/49142028/78651287-6b736500-78c0-11ea-9585-5dab291a2a55.png)
With check boxes instead of an 'A'

@HGustavs @a97marbr

**Comment by HGustavs** [comment]
Last one is the best. Most similar to pen icon.
