### ISSUE TITLE
css / js refresh issues

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#7760]
Some times the css or js has changed but the browser thinks ... [computer says noooo](https://youtu.be/AJQ3TM-p2QI)

I think something like this solution from php.org might work

~~~
This is a very handy function for dealing with browser caching. For example, say you have a stylesheet and you want to make sure everyone has the most recent version. You could rename it every time you edit it, but that would be a pain in the ass. Instead, you can do this:

<?php
echo '<link rel="stylesheet" type="text/css" href="style.css?' . filemtime('style.css') . '" />';
?>
~~~

**Comment by a18filkr** [comment]
Because of the structure of how js files are located, the solution for this is very bad compared to css which are all in the Shared folder. Will make a quick solution för the js files but that should be looked into. Having an array go through all the files would be much easier to implement on every .php document.
