### ISSUE TITLE
Inline file editor in code viewer.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#7770]
In code viewer it would be nice to have a pencil icon (if administrator/teacher) that would open the current view (for example lower left in 1+(1/1) view) to an iframe of the editor in fileed.

Somehow a the iframe to the fileeditor (same as pen in fileeed) will do exactly the same as editing in file editor. (we dont want to duplicate code but use the same editor in both cases).

**Comment by HGustavs** [comment]
This way in-line editing is possible directly in code viewer

**Comment by a18jonsj** [comment]
![exempel](https://user-images.githubusercontent.com/49142617/78229359-2fab5a80-74d0-11ea-890c-6438a57e8032.png)
Henrik, tänker du att du vill ha en ikon för pennan i varje ruta som skapats, eller bara en ikon längst ner till vänster för alla rutor, eller vill du ha ikonen för pennan som en extra knapp, där det i denna bild just nu står edit?

**Comment by a18jonsj** [comment]
@HGustavs

**Comment by a18jimol** [comment]
Du säger att du vill vi ska använda samma editor på båda ställena men problemet vi har då är att vi inte kan komma åt funktionerna i fileed.js som används i file-edit från codeviewer.js som vi lagt den nya knappen i.

När man väljer att editera innehållet i textruta vill du att ett fönster ska öppnas på sidan där man kan editera text( som i file-editer ) eller vill du att man ska länka till file-editor och editera där?

**Comment by a18jimol** [comment]
@HGustavs

**Comment by a97marbr** [comment]
Having a one-click option to get directly to file edit would be a great improvement **and** we still only have editing code in one place. I would vote for that.

**Comment by a18jimol** [comment]
We found out the solution to this issue didn't work well and created other issues like #8008 . We tried to access fileed.js from codeviewer.php because we wanted to use the code for editing and saving files from codeviewer but it does not work well becuase fileed.js have so many other variables and function we don't need in codeviewer.

So we have two possible solutions.
First one is to only access fileed.js when it is need with JQuerry like this:
	```
$.getScript("fileed.js", function() {
		newUpdateFile(fileUrl, fileName, fileKind);
	 });
```
Then fileed.js is only used when the function is in use and seems to not trigger any other issues after the functions use because when the user saves the edit the page reloads and loses the access to fileed.js

The other solution is to maybe make a new file that only contains the functions for editing and saving files so that one easy can be used both by fileed and codeviewer and the function only for fileed is kept in fileed.js
@HGustavs @a97marbr

**Comment by a18jimol** [comment]
We tried a new way accessing fileed from codeviewer with opening an iframe from codeviewer. To be able to access the functions of fileed.js directly when the iframe open the only solution we found was to use postMessage and send the varibles to fileed.js and then call the function to open the window to edit that specific code-exemple.

We wonder if this i good or bad solution because we don't know how safe this is and effective, it works well on localhost but we don't know if this is first safe to use postMessage and if it will work well on LenaSYS online

**Comment by HGustavs** [comment]
I am thinking that an iframe solution would be possible with only minor changes to fileed?

I would have passed the information about the file using the iframe url and then just made a pop-over window or just the actual file area for the iframe.

Some minor changes to fileed.php are probably necessary for the in-line editing.
