### ISSUE TITLE
Accessed table - Back-end table does not reorder after a cell update

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#7859]
Steps to reproduce:
1. edit a cell, press enter
2. sort table in another order
3. edit new cell

1.<img width="445" alt="Screenshot 2020-04-06 at 10 43 16 AM" src="https://user-images.githubusercontent.com/62876553/78540079-de62da00-77f3-11ea-98ad-e5c99d297dd3.png">
2.<img width="454" alt="Screenshot 2020-04-06 at 10 43 27 AM" src="https://user-images.githubusercontent.com/62876553/78540083-e0c53400-77f3-11ea-9bd5-0b36a3d4aec2.png">
3.<img width="464" alt="Screenshot 2020-04-06 at 10 43 32 AM" src="https://user-images.githubusercontent.com/62876553/78540087-e28ef780-77f3-11ea-89b4-f0f4dcc22182.png">

**Comment by c14jonfr** [comment]
There is already an issue for this (#6068). The issue is presented a little differently but I believe the issue is the same (after editing and sorting the next edit will not be for the person clicked, but rather the person who was in that position before sorting). I'm pretty sure the root cause is the same - the table renders as sorted but has not been properly sorted somewhere else, until the "new" edit is made (by pressing the check mark or enter) which fixes the sorting.

This is being looked into but at this point I am not sure we will be able to come up with a solution.
