### ISSUE TITLE
Bug when clicking on edit file icon

### ISSUE THREAD

**Issue by a18mahkh** [HGustavs/LenaSYS#7883]
Inputs system code (HTML code) in textarea
![Anteckning 2020-04-06 143337](https://user-images.githubusercontent.com/49142349/78558941-c8fda800-7813-11ea-92d2-d4024902c92a.png)

**Comment by HGustavs** [comment]
some context: This may happen if the installer does not create the file but creates database entries that say that the file exists.

Before checking bugs, try to see if this is the case first.

Navigate to the file area and see if the file is there, if not, that is the culprit.

Then the fix is, write a sane error message for "file does not exist plz upload again" ... if that is not the reason, more testing is needed.

...

**Comment by a18mahkh** [comment]
It's not a bug! HTML file has been mistaken for normal text file.
