### ISSUE TITLE
Ability to subscribe to deadlines via WebCal/iCal

### ISSUE THREAD

**Issue by a18eliek** [HGustavs/LenaSYS#7892]
An option to get a webcal link that the user can add to their phone or their calendar software with the deadlines of each coursemoment. 

An example of links that we could use to return the WebCal/iCal data from: https://dugga.iit.his.se/DuggaSys/calendar.php?courseid=17&coursevers=92474&type=ical
https://dugga.iit.his.se/DuggaSys/calendar.php?courseid=17&coursevers=92474&type=webcal

It seems like there is no standard between IOS and Android Users, so an implementation of either both of iCal and WebCal probably needs to be implemented, if there's no other format.

Some more information regarding the format: https://en.wikipedia.org/wiki/Webcal
Also see this: https://en.wikipedia.org/wiki/ICalendar

The main goal of this feature is the ability for the users to see when there's an deadline coming up, so that they will either get an notification on their phone or just get an overview of their whole schedule.

**Comment by HGustavs** [comment]
Also good for teachers.

I think this would be a good feature for the sectioned.

It is not terribly difficult. I would say that getting basic support would not take much more than a few days.

I would add this as an option to the sectioneditor service, so that one can link to sectioned_service to get a ical/webcal link.

I would start with ical as one issue and then adding webcal as a separate issue if the ical version works well.
