### ISSUE TITLE
Calling of file-ed

### ISSUE THREAD

**Issue by a18mahkh** [HGustavs/LenaSYS#7919]
Make sure that we are calling the service for creating files in fileed, so that we are not writing new code for the same task.
This issue is related to:  https://github.com/HGustavs/LenaSYS/issues/7766 and https://github.com/HGustavs/LenaSYS/issues/7917 and https://github.com/HGustavs/LenaSYS/issues/7918

**Comment by HGustavs** [comment]
Either by calling service directly or by a conveniently placed iframe to fileed.

**Comment by a18jimol** [comment]
Now we have the button and dialog to write the name of the file from #7917 , #7918 . Do you want us to use the service of fileed.js and filereceive.php as we are in fileed.php when writing the dummy-file so don't see the reason to use an iframe as we already are in fileed.php.

When tryint to call the service filerecive.php it seems the code don't accept the string of text of the name of the file, we get no errors but it just sends us back to fileed.php without a new file saved. Should we make new functions that sends the data in another way than uploadfile() from fileed.js or can the string be converted to a "file". We also have a problem finding where filereceive.php actuelly get the filename from.

**Comment by a18mahkh** [comment]
@HGustavs @mbrohede

**Comment by a18jonsj** [comment]
We are not sure about this issue, we have gotten to the point where we can convert a text-string in filerecieve.php, but we havent figured out a way that will use $_FILES array for taking the file uploaded by a user, and using the values from the array during the actuall upload.
What we can do is to use all the code that checks if the file is valid, the code that puts the file in a folder and uploads it to a server, and put it all in place made for the dummyfiles only, because there seems to be no way of creating a file in fileed and sending that file with "input type=file".

Do you think that putting all of the code for uploading into two places is a bad idea, or is it an acceptable soloution? Right now this is the only way we are able to make it work, the problem being that the same code exists in several places.
@HGustavs @mbrohede

**Comment by a18jimol** [comment]
We can create a file and save it in the right directory and upload it to the database(on localhost) but we don't know if this really is agood solution. Because we can't use $_FILES and the varibles that you use when creating and uploading files we have a seperate if-statement that handles "dummy-files". This means that we have two places in filerecieve.php that have the same functions and that might not be that good but we don't see another solution.
On top of that we could not use "move_uploaded_file" as that one only handles files that get uploaded by the user and the only check to see the file is allowed is to see if the extension is allowed.
@HGustavs @a97marbr

**Comment by a97marbr** [comment]
Not sure I follow.

If you can create a new file in the correct directory I would think this is good.

When uploading a new file, we first receive the file into a temporary place. Check if conditions are meet (ok size, file type, etc) then we move to correct place in our file structure.

I'm thinking that the temporary-file-move-after-check is not the case for creating a new file. Since you ask PHP to create a new file with a given file name. You could (should?) guard against unwanted file types.

Can I try the create new file feature some where?

**Comment by a18jonsj** [comment]
If you want to test it locally, check out this branch: G3-2020-ISSUE#7919. You can also try it out on the testserver: http://group3.webug.his.se:20001/G3-2020%237919/DuggaSys/courseed.php
To try it just:
1. log in as brom. 
2. go to a course, go to fileed.
3. choose the fab-button option create dummyfile and upload a dummyfile of your choice.

The way it is now, the dummyfile is added in the global directory and can be seen trough all courses.

**Comment by a97marbr** [comment]
Nice!

From the feature point of view I would say it works exactly as I would like.

The only thing I lack is the ability to select Global/Course/Course local in the create dummy file dialog.
