### ISSUE TITLE
Make content fit into a4-size

### ISSUE THREAD

**Issue by a18frior** [HGustavs/LenaSYS#7935]
Everything works well, but would it be possible to change the size of the content? The content gets cut to fit the a4-size?

Related issue: https://github.com/HGustavs/LenaSYS/issues/6129

**Comment by HGustavs** [comment]
No scaling to fit.

As many models are greater than a page.

BUT.

You would like have a visual cue as to where the a4 boundaries are to avoid placing e.g. an entity exactly on a border.

When printong/exporting to svg this gets important

**Comment by HGustavs** [comment]
Would be nice to be able to switch to e.g. A3 or A2 instead of only a4.

There is more than one size of paper in the "real world"... we dont want to support the abomination known as "Letter" though ...

**Comment by o18marka** [comment]
@HGustavs 

> No scaling to fit.
> 
> As many models are greater than a page.
> 
> BUT.
> 
> You would like have a visual cue as to where the a4 boundaries are to avoid placing e.g. an entity exactly on a border.
> 
> When printong/exporting to svg this gets important

There is already a feature to display virtual A4 in the diagram in the form of dashed-lines in the diagram if this is what your referencing. By using this feature you can make sure that enteties are not placed on the border.

**Comment by HGustavs** [comment]
We do not want the model to be changet for printouts/exports. Nor to limit the model.

If one uses a3 instead of a4 or any other size such borders are meaningless.

Perhaps some visual cue if something is placed on a border.... but in a large model for example 10.000 classes. the model would start to look weird if we had to automatically conform to a random paper format.

**Comment by b18phibe** [comment]
@HGustavs I'm sorry but i do not understand the requirements of this issue. do you wish to have a greater selections of paper sizes or a alert messages saying you put this class on a boarder between two pages?

**Comment by HGustavs** [comment]
Im saying unobtrusive.

Since most people will not bother about the lines we do not want it to disturb people that do not print on paper (which is a majority imho). So what I am saying is that we do not want it to bother people that do not print. So any action must be very "nice" we do not want alerts or other "loud" techniques or automatic changes of document.

For example color change to orange if crossing line when paper outlines are shown.

Custom paper sizes are equally important. From experience I know that landscape A3 printouts are more common than portrait A4...
