### ISSUE TITLE
Colorpicker in markdown

### ISSUE THREAD

**Issue by a18jakme** [HGustavs/LenaSYS#7956]
Be able to color text in markdown with a Colorpicker.
Screenshot example:
![image](https://user-images.githubusercontent.com/49142935/78763885-0aae6000-7986-11ea-83ef-f03853cb064c.png)

**Comment by b18gussv** [comment]
Due to the limitations that the Markdown language puts on this and the fact that it is designed to be lightweight we do not see a solution for the exact requirements without having to change how MarkdownPreview works completely. While it is possible to change the color in the preview (see picture 1) it will change back when something new is added (see picture 2) due to the reparsing that will happen through the UpdatePreview function. 
![bild](https://user-images.githubusercontent.com/49142342/78788939-c2eeff00-79ac-11ea-840c-a8629e2a7b67.png)
Picture 1

![bild](https://user-images.githubusercontent.com/49142342/78789132-0184b980-79ad-11ea-81b4-1d8b0911a967.png)
Picture 2

A description on what this should actually be used for or its usage is welcome.
If you have any pointers or more specific advice feel free to answer otherwise we do not see a solution or use for this.

**Comment by HGustavs** [comment]
Dont think coloring would work.

For example in dark mode what would dark red look like?

**Comment by a18jakme** [comment]
@HGustavs 
You're right, I forgot about dark/white theme.

**Comment by a18filkr** [comment]
Closing issue, seems like this is not wanted by customer and would be hard to implement with dark mode.
