### ISSUE TITLE
Important word highlighting work with more than one word as string

### ISSUE THREAD

**Issue by a18filkr** [HGustavs/LenaSYS#7959]
#7339 
Ref to earlier issue that was only fixed to work by highlighting one word as a string.
"Hello world", would not work to highlight but "Hello" "world" would.

Fixing this issue to fix 7669 as well.

**Comment by a18filkr** [comment]
Fixed words in strings to be highlighted, proceeding to new issue with strings within strings.
![Screenshot_2020-04-08 Validating form data](https://user-images.githubusercontent.com/49142751/78772178-abeee380-7991-11ea-954f-c32c52b8aeda.png)

**Comment by a18jakme** [comment]
Strings are now getting highlighted. "Hello world" is working fine as you can see in the screenshot below. @a18filkr Remove debug lines "console.log" in code. Otherwise issue solved!
![Skärmavbild 2020-04-08 kl  15 16 53](https://user-images.githubusercontent.com/49142935/78788736-799eaf80-79ac-11ea-8cb6-4f219d9240be.png)
