### ISSUE TITLE
CodeViewer: Editbox; save does nothing

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#796]
Edit content boxes does nothing when trying to click "Save"

**Comment by c12jenek** [comment]
![editboxes-issue](https://cloud.githubusercontent.com/assets/11715479/7068471/ff46f518-ded2-11e4-8209-765279a3a4aa.jpg)
Setting wheel of the code/comment boxes

**Comment by HGustavs** [comment]
I think this was mentioned in another commit / issue that this needs to be updated to comply with the workings of the editExample dialog. It is important that the box ID is supplied to the dialog as a hidden field when we click the cogwheel.

Otherwise both the service and the javascript code is very similar to the edit example dialog.

Furthermore a separate service ajax vall is needed to store the important rows. The important words part of the edit example dialog does not work either.

**Comment by b12alela** [comment]
Major updates to the edit box. This is solved.
