### ISSUE TITLE
popupDocumentation not working with HTML attributes after merge

### ISSUE THREAD

**Issue by a18geoge** [HGustavs/LenaSYS#8108]
After creating W17 branch the linking to documentation regarding HTML attributes no longer work unless you add them to the important words list.

Before:
https://i.gyazo.com/ee1f03867a7ad8d26003c0bda55334f7.mp4

After:
![HTMLattr](https://user-images.githubusercontent.com/62876595/79322619-5d9b9080-7f0d-11ea-839f-df60d86bb1c7.jpg)

**Comment by a18wilis** [comment]
Since the original issue #1789  specifically requested popup-documentation for **highlighted** words we will be dropping this issue, since the documentation for HTML attributes still work when they're added to the important word list. Attributes are not required to show it's documentation when not considered important.
