### ISSUE TITLE
CodeViewer: Templates aren't connected properly

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#817]
Choosing templates doesn't result into the correct template, the id possibly isn't equal to the icon of the template.

**Comment by HGustavs** [comment]
Is this after-the-fact selection of template or first-time template selection?

If first-time works and after-the-fact does not, it means that it is only the after the fact one that is broken.
Choosing a template must mean that we also create or update the corresponding box entries and so on so that everything matches.

**Comment by a13jorla** [comment]
Similar to #789 .
