### ISSUE TITLE
Dugga Stats shouldn´t be able to extend while dragging the heading. 

### ISSUE THREAD

**Issue by b18veran** [HGustavs/LenaSYS#8206]
By dragging the heading you can make the box as long as you like. Don't see the meaning of it. You can also move it vertically which is good if you want to be able to read the text behind. We need to fix it so it is not expendeble sideways.

<img width="725" alt="Screenshot 2020-04-17 at 09 37 35" src="https://user-images.githubusercontent.com/49142649/79544339-29e87400-808f-11ea-8128-9523212fce9e.png">
<img width="725" alt="Screenshot 2020-04-17 at 09 37 47" src="https://user-images.githubusercontent.com/49142649/79544342-2a810a80-808f-11ea-9cc6-0dad0863ff1a.png">

**Comment by HGustavs** [comment]
I think the draggability is a bug.

Most things used to be draggable but this caused more problems that it solved.

In reality we want a minimum of stuff to be draggable as it creates problems.

What if we drag something and then come back with a smaller monitor, where should the stuff appear?

Should it remain static on refresh using local storage?

so I think that the fix is removing the drag-ability altogether.

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
