### ISSUE TITLE
Functionality issue with 'New Item' button

### ISSUE THREAD

**Issue by a18mahkh** [HGustavs/LenaSYS#8271]
What should this 'New Item' button do? Does this button have different set of purposes or have the same functionality as the fab button?

![Anteckning 2020-04-20 104852](https://user-images.githubusercontent.com/49142349/79733733-dcba0b80-82f5-11ea-923a-451b26360dd5.png)

**Comment by a18mahkh** [comment]
@HGustavs @a97marbr

**Comment by a97marbr** [comment]
It should have the same functionality.

What we could perhaps argue is where the new sectionEd line appears ... now I believe it will enter the course at the bottom or at a specific line if there are many lines in the course.

I suggest that the button in your image should add items from the top?

The FAB i suggest would add new lines at the center of the screen. So if I scroll down a few pages and press the FAB the new line should appear in the center of my scroll position.

Perhaps the newly added line could have a visual animation to indicate that it is new? Something like a pulsing/blinking fade-in?

**Comment by a18jimol** [comment]
Our solution to this is to add the list from the FAB-button to the button on the top a18mahkh pointed out. This is the list:
![Skärmklipp2](https://user-images.githubusercontent.com/49142669/80215198-5a568200-863c-11ea-958b-626cf21dc4eb.PNG)

Also we will make the button on the top follow with when you scroll like the FAB-button.

We will try to make it possible so when adding from the button on the top it will add in the  top of the list instead of the botton and when use FAB-button it will be added in middle of the screen in the list.
Is this a good solution for it?
@HGustavs @a97marbr

**Comment by a18jimol** [comment]
Right now the FAB-button on the top have all the options as the button in the bottom and follows with as you scroll down. It looks like this: 
![fabtop1](https://user-images.githubusercontent.com/49142669/80492461-555b4080-8964-11ea-8122-94e8b7c304ae.PNG)

Added the functionality so when you click on the FAB-button on the top( the one on the picture) an new item is being added on the top of the list as you wanted. This is done by adding a comment that says "TOP" with the item and then giving it the position of -1 and then gets in the top. 
Our questions are, is this how you want the button on the top to behave and look like and is the solution to ading the item on the top reasonable?
Still working on adding them in the middle of the screen.
