### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by c13andka** [HGustavs/LenaSYS#830]
When you logout from the page and you are in a course or doing a dugga. I think you should get directed to the front page again after logout.

**Comment by b12erijo** [comment]
This issue also encompasses the fact that the loginbox shows up again if you log out without refreshing the page.

**Comment by HGustavs** [comment]
Have we progressed anywhere when it comes to this bug?

I see this "bug" as a quite an important issue to resolve.

It should not be possible to be confused as to whether or not you are logged in, especially when submitting dugga answers.

There was a bug last year that resulted in people seeing a "dugga" without being logged in and therefore submitting "blank" answers.

This happened after clicking the logout button but since the page was still visible it was possible to submit an answer without being logged in.

....Is this bug still repeatable? I though that it had been fixed.....
