### ISSUE TITLE
Inconsistent margin to the left on the "Download all contents in a ZIP file"-button

### ISSUE THREAD

**Issue by a18eliek** [HGustavs/LenaSYS#8359]
<img width="833" alt="Skärmavbild 2020-04-22 kl  09 08 41" src="https://user-images.githubusercontent.com/49141837/79951380-ddc77600-8478-11ea-8af8-992429d2992b.png">

**Comment by c14jonfr** [comment]
Pretty sure this is because of the access (padlock) td having the menuButton class which the other td's don't, see screenshot.

Removing the menuButton class from the access <td> seems to fix this issue (but this has only been briefly tested, so please make sure it doesn't break anything else if you use this fix).

![image](https://user-images.githubusercontent.com/49141758/79954325-79f37c00-847d-11ea-8bcb-31a69dc2b393.png)
