### ISSUE TITLE
Resizing issue on appearance change (UML-class)

### ISSUE THREAD

**Issue by o18marka** [HGustavs/LenaSYS#8556]
When appearance/content is changed in a UML-class it resizes. This is an issue when UML-classes have a custom size. See GIF:
![issue2](https://user-images.githubusercontent.com/49142263/80419938-45971a00-88da-11ea-9b68-a8ccabf7bb4d.gif)

**Comment by a18antsv** [comment]
Just as a comment for what I see you doing in the gif (unrelated to the acutal issue), the text does not change since you write it after the comma. Comma separation was introduced to make it possible to change text for multiple objects at the same time in the same textarea when many are selected. I will fix this in a new issue to prevent comma separation for the last selected object to make it easier.

**Comment by o18marka** [comment]
Was thinking about making this an issue actually, though had a hard time describing it and didn't know exactly how commas are supposed to be handled.

**Comment by a18antsv** [comment]
The rework I did in that one issue was already so big so I thought I split it up into another issue. I need an index for each type that comma separation should be used for to prevent it from appearing after the text the last selected object represents.

**Comment by a18antsv** [comment]
This affects only when the form is submitted. Any changes do not have to be made. When the form is submitted by enter click or button it will run submitAppearanceForm function where a function is used to resize it back to minimum.
