### ISSUE TITLE
Pen icon missing in files

### ISSUE THREAD

**Issue by a18jenro** [HGustavs/LenaSYS#8638]
See the image, it used to be a black pen:
![untitled](https://user-images.githubusercontent.com/62876507/80576812-22698900-8a06-11ea-9d73-9985a7679f98.PNG)

**Comment by c14jonfr** [comment]
The same icon is missing in the Dugga Editor. I believe another group replaced the old icon with a new, white icon for use in diagram.php. The new icon has a new name, breaking all links/references to the old one. 

I would argue we should bring the old icon back because the white icon will not be visible for the white rows in the File and Dugga Editor.

**Comment by a17towan** [comment]
The old icon seems to have been deleted upon the creation of a new one. I have the old icon saved, so I'll just put it back in.
