### ISSUE TITLE
Disallow non-whitelisted character input in text boxes

### ISSUE THREAD

**Issue by a13karsi** [HGustavs/LenaSYS#877]
With the new regex powered parsing that only allows white-listed characters to be accepted as input, see pull request #868 and issue #747 the problem that now arises is that a user may inadvertently input a course name such as "Toddler's epic course" only to find out that the ' character would be removed and the resulting name would be "Toddlers epic course". 

In order to improve the user interface and experience of the user, all user input should be parsed as well right away to indicate to the user that some characters are not allowed as input.

**Comment by HGustavs** [comment]
My suggestion is to do this at the service level so that you do not have to implement this code on every input box. I am hesitant on features that have to be added manually to input boxes since this often results in boxes that have not been fixed which in turn results in potential injections since the site owner thinks it has been fixed.

e.g. an alert that says "some characters have been removed from the input: xxxx".

**Comment by HGustavs** [comment]
Now if there are several boxes at once that have this issue perhaps writing an alert for each field is overkill... so if there is more than one a coalesced output is preferred to me at least.

**Comment by a13karsi** [comment]
I agree that it would be overkill, since it would require so many changes to so many files. Me and Johan were looking at the code and tried looking for if there was a common point of origin where text input was handled but it seems like the ajax service function is the only candidate. 

It is probably the best solution as you mentioned that we alert the user from the service level that some characters have been removed.

**Comment by a13karsi** [comment]
Merged #888
