### ISSUE TITLE
Only whitespace input shouldn't be possible 

### ISSUE THREAD

**Issue by a13karsi** [HGustavs/LenaSYS#881]
For example, creating a course that has nothing but whitespace as input creates a new course on the course list that has no name. Instead, the user should be informed that creating a new course requires a valid name and course code.

**Comment by HGustavs** [comment]
I think this is related to the regex issue.
Im thinking we may want to stop this on the service level and also give feedback on the service level.

I am against code that has to be written for every input box since there is a risk that you might miss some box..... which unknowingly passes bad stuff to the database.

However are there cases when we want white space only in an input?

**Comment by a13oscwe** [comment]
@HGustavs The code is "stopped" at the service level now and i guess that's fine but there should be some kind of frontend validation aswell letting the user know. https://github.com/HGustavs/LenaSYS/issues/747 https://github.com/HGustavs/LenaSYS/issues/877

**Comment by HGustavs** [comment]
Im thinking an alert box... suggestion in comments for issue #877.

**Comment by a13karsi** [comment]
That's the easiest solution for the time being. If it's okay with everyone I would like to have pull request #868 merged and we'll address this in a separate issue, that is, adding an alert box with a notification.

**Comment by a13karsi** [comment]
Merged #888
