### ISSUE TITLE
Generate UML- and Generate ER- diagram works slowly.

### ISSUE THREAD

**Issue by a18frior** [HGustavs/LenaSYS#8821]
When the user clicks on generate UML-diagram or Generate ER-diagram is either not working or it works very slowly. Maybe it's possible to make this work better.

**Comment by a18antsv** [comment]
Check how cardinality created as well. How this information is stored was changed to store less redundant information. UML-lines only store value and valueUML while ER-lines only store value and parentPointIndexes, where parentPointIndexes is an object with reference to index of point for the object's topLeft and bottomRight points. This is used instead of storing the whole object there.

**Comment by a18antsv** [comment]
Also do never create centerPoints for lines as this only causes dummy points to be created.

**Comment by a18antsv** [comment]
Why not create a diagram in the actual diagram, export a file and store this file on the server. Load this file instead for the example diagram. This would be much simpler than writing the code yourself. Everything will be handled the same way as you would import a diagram so you should not have any problems with connections and all example diagram code can be removed.
