### ISSUE TITLE
ER/UML diagrams for the database 

### ISSUE THREAD

**Issue by a18jenro** [HGustavs/LenaSYS#8822]
There should be ER/UML diagrams over how the database tables are connected such that new coders can more easily get an understanding of the database structure.

**Comment by a18jonkl** [comment]
I have created a schema for the LenaSYS database without relationships because there are too many connections to some attributes. But primary keys and foreign keys are displayed and how they are connected.

This picture will be placed in the ‘Wiki’ section and the .dia file somewhere for easy access so changes can easily be made.

<a href="https://gyazo.com/e302d390a742611455a03b8eaf00998e"><img src="https://i.gyazo.com/e302d390a742611455a03b8eaf00998e.png" alt="Image from Gyazo" width="1159"/></a>
