### ISSUE TITLE
Change let to var [Group 4: Diagram]

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#8835]
According to the `code_standard.md` document, `let` should not be used for variable declarations for browser compatibility reasons. Instead `var` should always be used.

For group 4 this concerns the following files:
- `courseed.js`
- `diagram.js`
- `diagram_objects.js`

**Comment by a18antsv** [comment]
I do not think this is relevant anymore, since the customer wrote that variables that clearly are constants could be changed to const, meaning they are okay with using the new ES6 let and const keywords. They are not interested in changing all var to let though since this would mean thousands of lines having to be changed and also change owner for no change of functionality.

**Comment by a18antsv** [comment]
In my opinion using const is the best habit and should be used as much as possible since it is good to know when a variable can never change. Const is making this strict, preventing errors in the system as errors will easily be seen when developing. Even arrays and objects can be const since this allows properties in an object or positions in an array to be modified. The good thing is that the array can never be cleared or change datatype. Develop to try to prevent changing variables as much as possible. Most variables can be const.

**Comment by a18antsv** [comment]
They didn't say exactly how to do with already existing let or what should be used from now on, which could be worth clarifying. There was nothing against let in the statement though so it seemed to be fine. I think let should be the new standard for variables that change due to being much clearer in scope and const should be used whenever a variable do not change.

**Comment by b18alegu** [comment]
This issue is no longer relevant and will now be closed.

`code_standard.md` will be updated in #9147 to clarify the future uses of variable declarations.
