### ISSUE TITLE
MOTD character limits and restrictions

### ISSUE THREAD

**Issue by a17towan** [HGustavs/LenaSYS#8979]
There are some things that needs to be fixed when you decide what to type in for a MOTD message.

For example, if you type in Swedish characters "åäö", click out of the MOTD edit box and then open it again, it looks like this:
![image](https://user-images.githubusercontent.com/49142028/81297975-66970200-9074-11ea-9614-a5e47a454590.png)

My suggestion: Disallow non-English characters. Maybe also disallow special characters ( "+§&%# ).

Problem no. 2: There is no character limit so you can type in however many characters you want. There should probably he a limit for that. Example:

![image](https://user-images.githubusercontent.com/49142028/81298111-9ba35480-9074-11ea-8f75-81fa240726d8.png)
![image](https://user-images.githubusercontent.com/49142028/81298139-a3fb8f80-9074-11ea-8efa-609009155a86.png)

**Comment by a18jonsj** [comment]
We are considering if the user should be able to use the letters "åäö", in some case it might be usefull because there are some duggas with those letters in it. In message of the day for the different  courses you are not allowed to use "åäö" and is this intended or is it suppose to be possible to use them?
@mbrohede @HGustavs
