### ISSUE TITLE
Logging - Submitted and marked Duggas during the day

### ISSUE THREAD

**Issue by a18wilis** [HGustavs/LenaSYS#9012]
Issue #1885 mentions that the wished-for Analysis page would have some sort of funcitonality that logs the amount of duggas that are submitted/marked in the system during the day. 

This will be used together with issue #9016 to display the logging results on the analytic page.

**Comment by a18jakme** [comment]
@a18wilis  Do you mean when a student submit/save a dugga and it turns "yellow" or do you mean when a teacher corrects a dugga and it turns "green" ?
Because there is already a log called duggafileupload which is implemented when a student upload a file or save a "linedugga". Is that something that solve this issue?

**Comment by a18wilis** [comment]
The logging functionality should log student submitted duggas (where they turn yellow) as well as when a teacher marks a dugga (where they turn either green or red). That's what I assume the original requester (#1885 ) wants, so what you wrote is exactly what I mean.
