### ISSUE TITLE
Update function "minimizeBoxes" to better fit the code standard

### ISSUE THREAD

**Issue by a18abuah** [HGustavs/LenaSYS#9091]
As a part of dividing issue #8232. This issue focuses on making the function "minimizeBoxes" within codeviewer.js (located on rows 2218-2494) to fit with the code-standard.

**Comment by a18geoge** [comment]
After trying to solve this I am unassigning myself since the only thing I can fix is the indentation and declaration of variables. I tried setting up a loop that would create thisBox1 through 5 in the beginning which not only turned out to be trickier than I first thought, the advice online (and when I checked, also the code standard) is to not do this dynamically. I have also tried to create a setWidth/setHeight method in native so that the code could be reused but have not been successful in getting it to work.
