### ISSUE TITLE
SQL-Migration: Change queries made through $pdo if needed.

### ISSUE THREAD

**Issue by a18kaswi** [HGustavs/LenaSYS#9506]
The $pdo socket are used in the system to work against the database. 

All queries made through this socket needs to be overlooked. 

If needed these queries needs to be changed to conform with PostgreSQL-syntax.

A complete list of all rows (as of branch G4-2020-W21) in codebase mentioning $pdo
http://group4.webug.his.se:20001/SQL-migration/grep_pdo-variabel.txt

As can be seen this is a pretty huge list, split into subissues if necessary.

Resource: https://en.wikibooks.org/wiki/Converting_MySQL_to_PostgreSQL

**Comment by a18kaswi** [comment]
@a18jonkl I think you are the one that made the most changes around the system. A summary?

**Comment by a18jonkl** [comment]
I didn't get to test out all of the different queries that you can see in the link. We got past the login function and for that to happen we had to change the syntax for all the queries calling “user”.

User is a reserved word in Postgres and needs to be in quotation marks and most queries in the code are written “ SELECT user.uid FROM user ”.This would not give an error because it will try the default table ‘user’ and complain about not finding the column uid. To bypass this start with single quotation marks and wrap user in double quotation marks:  ‘ SELECT “user”.uid FROM “user” ’. 

From what we read online it is not good practice to use reserved words as ‘user’ and ‘group’ and I suggest talking about changing this to something else.
