### ISSUE TITLE
When removing/resetting a grade for a group assignment in Result Editor group member submissions will be rendered differently

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9579]
After removing/resetting a grade (by clicking the "G" button again, if the previous grade was G), the issue mentioned in #9575 happens. After a refresh, the members in the group will be colored differently. The person you did the reset "on" will be marked with orange, the others will be marked with purple. See screenshot.

I'm not sure what causes this, to be frank I'm not sure what the purple color means when it comes to duggas (what it means for moments is explained in the Legend).

![image](https://user-images.githubusercontent.com/49141758/82654926-b69fc800-9c21-11ea-984f-a4f3fc3ee5cb.png)

**Comment by a19anjst** [comment]
Vi är lite osäkra på vad denna issuen innebär. Är det meningen att en grade för ett group assignment som tas bort ska bli en annan färg än de färger som redan existerar för andra grades?

**Comment by a19isada** [comment]
What seems to be the problem is that after you reset a grade and refresh the page, the different members of the group will have different colours on their assignments even though they are in a group and should have the same colour. This needs to be investigated and if it isn't a problem anymore, this issue can be closed.

**Comment by a19isada** [comment]
This issue is no longer relevant groups should not be a part of LenaSYS anymore.
