### ISSUE TITLE
Course/deadline-tab stuck in mobile version

### ISSUE THREAD

**Issue by a18jimol** [HGustavs/LenaSYS#9600]
The courseheader and deadline-tab gets stuck in mobile version if the "show statistic and deadline" button(the yellow triangle) is clicked.
If you click the button it will look like this:
![image](https://user-images.githubusercontent.com/49142669/82663446-f8d00600-9c2f-11ea-9c41-570968730d51.png)
When resizing the window to a width above 860px it should go back to the desktop-view but it doesn't and stay like this. 
![image](https://user-images.githubusercontent.com/49142669/82663471-07b6b880-9c30-11ea-8d16-294e8ee04ea2.png)
It is still stuck in mobile-version if you click it down
![image](https://user-images.githubusercontent.com/49142669/82663675-6d0aa980-9c30-11ea-8841-8897093125d2.png)
So you have to reload the page to get the original view
The transition between mobile-version and desktop-version works fine as long you don't click the "show statistic and deadline" button

**Comment by a18jonsj** [comment]
Me and @a18jimol have been working on this issue but cant seem to find a good fix, that wouldnt change the styling to much. Since the issue doesnt really give an error and all the needed information is still presented in the rare case that a user would encounter this bug, we tought we might leave it open for next years students.

**Comment by a19isada** [comment]
Since this has been moved, it's no longer an issue
