### ISSUE TITLE
hidden class exists in both style.css and codeviewer.css

### ISSUE THREAD

**Issue by a18geoge** [HGustavs/LenaSYS#9720]
Title description on the example boxes disappears in codeviewer when using mobile view because of using the style.css class. If using the codeviewer.css one there are problems with the style (borders, margins etc.).

**Comment by a20sarle** [comment]
Not solved but couldn't be replicated during testing. Keeping issue open.

**Comment by a20sarle** [comment]
@a20mtafa Could you please see if this issue can be replicated on the newest version of the webbserver just as you could replicate it previously? If it canät be replicated the issue is most likely fixed.
This is what I see
![image](https://user-images.githubusercontent.com/81631818/164446252-c6764526-9ab8-4c2b-879c-973fbd88c91b.png)

**Comment by a20willa** [comment]
The problem does not seems to exist in the new version of the server, and thus issue is no longer relevant.
