### ISSUE TITLE
Diagram lines extend to nearly the edge of the box

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9796]
We have a safety margin around each box so that we have ample space to draw the lines in the svg

Relationship lines are however drawn only to the edge of the box and not to the edge of the diagram symbol wihch is a few units further down the line.

<img width="380" alt="Screenshot 2021-03-29 at 15 34 56" src="https://user-images.githubusercontent.com/6978801/112844738-5c269200-90a4-11eb-8d70-1894e4f95ed1.png">

**Comment by HGustavs** [comment]
This is done by 
* dividing the line with the length of the line, this way we get a vector for the line
* we multiply this with the safety margin variable and ...
* subtract it from one end of the line and ...
* add it to the other end of the line

...thus extending the line in both directions with the safety margin value (strokewidth multiplied with the zoom factor).

**Comment by a19matma** [comment]
Since the lines are drawn "on-top" of the boxes, it's very difficult to get a satisfactory result when it comes to the relations with double-lines. This is due to how the program was written.
A small fix I did makes the other lines appear without the small whitespace, but without changing a lot more of the underlying draw functions for the lines this issue cannot be resolved. 

![image](https://user-images.githubusercontent.com/81557380/113298041-aeadbb80-92fb-11eb-9cec-1271307eefd2.png)

**Comment by HGustavs** [comment]
My suggestion is to also move the double line one line width towards the center of both ends of the line e.g. some 3 pixels to the left of the "owns" side and the same amount to the right towards the center of the car end.
