### ISSUE TITLE
Removing menu bar for linked page

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9799]
Currently this is what lenasys looks like when embedded into canvas

<img width="1440" alt="Screenshot 2021-03-29 at 17 06 48" src="https://user-images.githubusercontent.com/6978801/112857819-8894db00-90b1-11eb-94a9-e8ce67c6fcb8.png">

**Comment by HGustavs** [comment]
We still need the top menu bar for teachers but in this embedded view we do not need the top menu since it should not be possible to log in to lenasys when embedded into canvas.

The home button that navigates to the curse list can also be removed.

The move down in hierarchy button is however useful still, I suggest retaining it as an icon in the top left corner of the embedded view.

The rest of the menu can then be removed in the embedded view.

I suggest adding some parameter such as for example &embedded=true that is automatically added by the redirection code... this should make testing of the embedded variant easy since we do not need canvas to test this embedded version.

**Comment by a18danli** [comment]
Are we supposed to remove the top menu bar = navheader when embeded into canvas? Or do you want the navheader to be removed when or display:none; when every id except a teacher is loggedin?

If the first options, this means we can only test the version but not the code will not do anything in this version, because we dont have a embeded version yet.

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
