### ISSUE TITLE
Prepare webserver for canvas installation

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#9828]
Installing the canvas lms requires certain prerequisites to be installed on the webserver for example Ruby on Rails and the PostgreSQL db engine. 

I would hope that the "quick-start" version of canvas is enough for our purposes but further research on this may be necessary.

The open source code for Canvas is on their github [here](https://github.com/instructure/canvas-lms) which includes a rather robust wiki.

**Comment by a16erilj** [comment]
Canvas need several libraries to be installed on Ubuntu linux. Some are even not available any longer on the regular apt-get command. So custom libraries are needed to get them. The needed libraries to date (15/04-21) are the following ruby2.6, ruby2.6-dev, postgresql, zlib1g-dev, libxml2-dev, libsqlite3-dev, ibpq-dev, libxmlsec1-dev, curl and lastly build-essential. Of which all of them have been installed to the server in order to prepare for installation. 

It’s possible that the requirements may change in the near future as Ruby2.6 is on EOL. 

Link to Canvas wiki: https://github.com/instructure/canvas-lms/wiki/Quick-Start
